### ISSUE TITLE
DuckDB does not handle double inverted commas; errors integrating with Superset

### ISSUE THREAD

**Issue by rajivpatki** [duckdb/duckdb#10033]
### What happens?

This issue is specific to Superset: duckDB tableschemaviews do not work with SQL Lab on 3.0.0+

`select * from "database_name.schema_name".table_name` throws an errors asking if you meant `"database_name.table_name"` instead. This causes an error fetching table metadata in Superset. See issue https://github.com/apache/superset/issues/26286

### To Reproduce

In SQL Lab
`select * from "database_name".table_name` works fine
`select * from "database_name".main.table_name` works fine
`select * from "database_name"."main".table_name` works fine

`select * from "database_name.main".table_name` throws an error

### OS:

x86

### DuckDB Version:

0.9.2

### DuckDB Client:

Python (Superset 3.0.0 and 3.0.2 official docker image)

### Full Name:

Rajiv Patki

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by guenp** [comment]
Hey @rajivpatki , thanks for opening this issue! The superset issue you referred to should be fixed by #848. `duckdb` indeed does not support `select * from "database_name.main".table_name`. The correct syntax should be `select * from "database_name"."main".table_name`. After #848 is merged, however, superset should generate SQL code the correct syntax.
