### ISSUE TITLE
Slow python executemany for inserts

### ISSUE THREAD

**Issue by kmagusiak** [duckdb/duckdb#10106]
### What happens?

When trying to insert records using DBAPI, the insertion is very slow compared to other databases. When using some other libraries that use the DBAPI, the ingestion is very slow.

### To Reproduce

```python
import duckdb
import pandas as pd
ddb = duckdb.connect()
import sqlite3
sdb = sqlite3.connect(':memory:')

data = [['x', x] for x in range(50000)]
ddb.execute('create table atest (name varchar, n int)')
sdb.execute('create table atest (name varchar, n int)')

# CPU times: user 36.2 ms, sys: 643 µs, total: 36.8 ms (sqlite)
%time sdb.executemany('insert into atest values (?,?)', data)
# CPU times: user 12.5 s, sys: 3.72 s, total: 16.3 s
%time ddb.executemany('insert into atest values (?,?)', data)
# CPU times: user 22.2 ms, sys: 1.58 ms, total: 23.8 ms
%time ddb.from_df(pd.DataFrame(data)).query("source", "insert into atest select * from source")
```

### OS:

wsl

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

Krzysztof Magusiak

### Affiliation:

none

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment]
`executemany` isn't really intended for bulk insertion of data, have a look at the data ingestion docs for alternatives: https://duckdb.org/docs/archive/0.9.2/api/python/data_ingestion

**Comment by kmagusiak** [comment]
I have and that's why I go through a DataFrame to load the data (last timed execution in the description).
In my scenario, I have some data I fetch from an API and I wanted to insert it (a list of dicts). I had code to insert it into postgres and found out that in duckdb the performance was low in that use case.

**Comment by szarnyasg** [comment]
I ran this on an M1 Max MBP, here are the numbers:
```
%time sdb.executemany('insert into atest values (?,?)', data)
```
```
CPU times: user 19.3 ms, sys: 55 µs, total: 19.4 ms
Wall time: 19.4 ms
```
```
%time ddb.executemany('insert into atest values (?,?)', data)
CPU times: user 2.49 s, sys: 394 ms, total: 2.88 s
Wall time: 3.84 s
```
```
%time ddb.from_df(pd.DataFrame(data)).query("source", "insert into atest select * from source")
CPU times: user 16.7 ms, sys: 1.17 ms, total: 17.9 ms
Wall time: 28.1 ms
```

The differences are still significant but I'd say this is expected.

**Comment by kmagusiak** [comment]
Ok, if it's expected, do I close this issue?

**Comment by andreamoro** [comment]
## Still an issue in v1.4.2 — 8+ minutes vs 0.05s for 76K rows

I ran into this while building a personal NLP pipeline project. The pipeline persists term frequency data to DuckDB — 382 documents x ~200 terms each = ~76K rows. Using `executemany`, persistence took **over 8 minutes**. Switching to `read_csv()` brought it down to **under a second**.

Spent hours debugging, suspecting batch sizes, DELETE operations, table bloat, or Python loop overhead — none of which were the actual problem.

### Environment

- DuckDB: **1.4.2** (Python client)
- Python: **3.13.9**
- OS: **Ubuntu Linux 6.17.0-8-generic, x86_64**

### Reproducible benchmark

```python
import time, os, csv, tempfile, duckdb

# Generate 76,400 rows (382 docs x 200 terms)
rows = [
    (f'doc_{i}', f'term_{j}', j + 1, (j + 1) / 500.0)
    for i in range(382) for j in range(200)
]
cols = ['document_id', 'term', 'raw_count', 'tf_score']
print(f"Rows: {len(rows)}")

db = '/tmp/test_executemany.duckdb'
schema = 'CREATE TABLE test (document_id TEXT, term TEXT, raw_count INTEGER, tf_score DOUBLE)'

# --- Method 1: executemany ---
if os.path.exists(db): os.remove(db)
conn = duckdb.connect(db)
conn.execute(schema)
t0 = time.perf_counter()
conn.executemany('INSERT INTO test VALUES (?, ?, ?, ?)', rows)
print(f"executemany:      {time.perf_counter() - t0:.2f}s")
conn.close()

# --- Method 2: executemany in 382 batches of 200 ---
if os.path.exists(db): os.remove(db)
conn = duckdb.connect(db)
conn.execute(schema)
t0 = time.perf_counter()
for i in range(382):
    batch = rows[i * 200:(i + 1) * 200]
    conn.executemany('INSERT INTO test VALUES (?, ?, ?, ?)', batch)
print(f"executemany x382: {time.perf_counter() - t0:.2f}s")
conn.close()

# --- Method 3: CSV temp file + read_csv ---
if os.path.exists(db): os.remove(db)
conn = duckdb.connect(db)
conn.execute(schema)
t0 = time.perf_counter()
with tempfile.NamedTemporaryFile(mode='w', suffix='.csv', delete=False, newline='') as f:
    csv_path = f.name
    writer = csv.writer(f)
    writer.writerow(cols)
    writer.writerows(rows)
conn.execute(f"INSERT INTO test SELECT * FROM read_csv('{csv_path}', header=true)")
os.remove(csv_path)
print(f"CSV + read_csv:   {time.perf_counter() - t0:.2f}s")
conn.close()

os.remove(db)
```

### Results

| Method | Time | Factor |
|---|---|---|
| `executemany` (single call, 76K rows) | **16.08s** | 1x |
| `executemany` (382 calls x 200 rows) | **16.90s** | ~1x |
| CSV temp file + `read_csv()` | **0.05s** | **~320x faster** |

Batching doesn't help — `executemany` is equally slow whether called once with 76K rows or 382 times with 200 rows. The overhead is clearly per-row, not per-call.

### Real-world context

In my pipeline, the full persistence cycle (serialize + DELETE existing + `executemany` INSERT) for 382 documents took **8 minutes 37 seconds** wall clock. After switching to CSV-based insertion, the same operation completes in **~3 seconds** including serialization, DELETE, CSV write, and `read_csv` INSERT.

### Workaround

Write data to a temp CSV and use `read_csv()`. It uses DuckDB's native vectorized scanner instead of the row-by-row Python API path. No extra dependencies — just stdlib `csv` and `tempfile`.
