### ISSUE TITLE
read_json_auto should not convert String to BigInt

### ISSUE THREAD

**Issue by jochenchrist** [duckdb/duckdb#10218]
### What happens?

When reading JSON files with read_json_auto, columns that are defined a String in JSON are converted to BigInt if they only contain number values.

IMHO this should not happen, as JSON has numeric types.

### To Reproduce

```py
import duckdb
import tempfile


data = """{"name": "John Doe","order_id": "30"}"""

temp_file = tempfile.NamedTemporaryFile()
with open(temp_file.name, 'w') as file:
    file.write(data)

# con = duckdb.connect(database=":memory:")
duckdb.sql(f"""
CREATE TABLE orders AS SELECT * FROM read_json_auto('{temp_file.name}', format='newline_delimited');
""")
print(duckdb.sql("describe orders"))
```

`order_id` has the type `BIGINT`, but should be `VARCHAR`.

### OS:

macOS, arm64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Jochen Christ

### Affiliation:

INNOQ

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
Hi @jochenchrist, I'm the author of the JSON extension.

I've added this [because people use string values in JSON to encode numbers larger than 2^53 (something to do with JavaScript)](https://stackoverflow.com/a/34989371). I thought the auto-conversion would be convenient. I ran benchmarks on some [GH Archive data](https://www.gharchive.org), and found that the size of the data when inserted into DuckDB was many GB's smaller when converting the integers-encoded-as-strings in that data to `BIGINT` using auto-detection, e.g.:
```sql
create table tbl as select * from 'gharchive_data.json.gz';
```
This is because integers are much more space-efficient, and DuckDB can compress them better.

However, I don't have much experience with JSON in practice, so I'd like some input. Perhaps this is not desirable from a user's point of view. What do you think?

**Comment by jochenchrist** [comment]
Sure, here some use cases, they might feel odd:
- One might perform conversions in a query, and expect a string / varchar
- Many business numbers, such as order_ids or zip_codes simply are not integers, but strings
- The extension behaves differently with leading zeros (`0123` vs `123`)
- In data quality tests, like soda-core or great expectations schema checking on varchar fails

What do you think about a configuration option, such as:  `convert_strings_to_integers=false` (or similar)

**Comment by rsyring** [comment]
I've been looking for a tool to use to help process API responses.  Its not been uncommon for me to encounter APIs that store identity columns as strings, which might currently happen to be all numbers, but explicitly state that such values should always be treated as strings and never converted.  The latest of which is: https://developer.todoist.com/sync/v9/

I started to use DuckDB for the first time to help with that API  and was really excited to work with it initially as it seemed ideal in terms of schema generation, speed, and flexibility (good work).  But, once I realized the values were being stored as ints, I spent about a day trying to work around the issue.  I could have just specified the columns manually but part of this exercise was to find a tool that did the type/structure detection automatically.

IMO, since JSON is a typed format, auto-generating a schema type as 'bigint' instead of 'str' when the format is clearly using a string is buggy behavior.  I understand that the whole point of `read_json_auto()` is to do helpful guessing but IMO this is "wrong", not helpful.  Strings with only integer characters _are not integers_, no exceptions,  at least for the default behavior IMO.

I understand the use-case discussed above but I feel like that should be the opt-in special-case.  How many people using duckdb have integers that are that big encoded in strings compared to those who would want their strings to remain strings?  An option to opt into the int conversion, behavior when needed, maybe even just for for specific columns, seems better to me. 

Thanks for your effort and sharing the results.
