### ISSUE TITLE
Should a UNION with untyped NULL preserve the type?

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#1049]
Currently it doesn't for `BOOLEAN`, DBItest `"data_logical"` .

``` r
library(DBI)

drv1 <- duckdb::duckdb()
conn1 <- dbConnect(drv1, debug = TRUE)
dbDataType(conn1, logical(0))
#> [1] "BOOLEAN"
dbGetQuery(conn1, "SELECT CAST(1 AS BOOLEAN) as a, CAST(0 AS BOOLEAN) as b")
#> Q SELECT CAST(1 AS BOOLEAN) as a, CAST(0 AS BOOLEAN) as b
#>      a     b
#> 1 TRUE FALSE
dbGetQuery(conn1, "SELECT NULL as a, NULL as b, 1 as id UNION SELECT CAST(1 AS BOOLEAN) as a, CAST(0 AS BOOLEAN) as b, 2 as id")
#> Q SELECT NULL as a, NULL as b, 1 as id UNION SELECT CAST(1 AS BOOLEAN) as a, CAST(0 AS BOOLEAN) as b, 2 as id
#>    a  b id
#> 1 NA NA  1
#> 2  1  0  2
dbGetQuery(conn1, "SELECT CAST(1 AS BOOLEAN) as a, CAST(0 AS BOOLEAN) as b, 1 as id UNION SELECT NULL as a, NULL as b, 2 as id")
#> Q SELECT CAST(1 AS BOOLEAN) as a, CAST(0 AS BOOLEAN) as b, 1 as id UNION SELECT NULL as a, NULL as b, 2 as id
#>    a  b id
#> 1  1  0  1
#> 2 NA NA  2
```

<sup>Created on 2020-10-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hannesmuehleisen** [comment]
It should not lose the boolean type, for sure

**Comment by krlmlr** [comment]
The `duckdb` shell shows a similar result:

```
$ echo 'select TRUE AS a UNION select NULL;' | ./duckdb
┌───┐
│ a │
├───┤
│   │
│ 1 │
└───┘
```

**Comment by krlmlr** [comment]
This is relevant for DBItest.

**Comment by Mytherin** [comment]
I had a look at this and the problem here is that we don't allow the NULL type to exist outside of expressions. At the expression boundary the NULL type will instead be converted to an INTEGER type, which then leads to the union being (BOOL, INT) which gets promoted to (INT). The fix here is to allow the NULL type to exist outside of the expression binder, but this is a slightly more involved fix. I can have a go at this next week.

**Comment by krlmlr** [comment]
This still seems to be an issue with f2d7702421c151e9acd840d52ed1f46a5b8174f1.

**Comment by krlmlr** [comment]
Thanks, this fixes the DBItest problems.
