### ISSUE TITLE
Macro defined with one default parameter does not accept parameter

### ISSUE THREAD

**Issue by arjenpdevries** [duckdb/duckdb#10539]
### What happens?

After:

```
D create or replace macro test(a := 'auto') AS a;
```

Doing `SELECT test();` works as expected.
But...

```
D select test('fiets');
```
throws an error:
```
Error: Binder Error: Macro function 'test()' requires 0 positional arguments, but a single positional argument was provided.
```

### To Reproduce

Do as above.

### OS:

Linux

### DuckDB Version:

v0.9.3-dev3269 8de2d291d8

### DuckDB Client:

CLI

### Full Name:

Arjen P. de Vries

### Affiliation:

Radboud University

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment]
Hi @arjenpdevries, thanks for the bug report!

This is currently expected behavior. We make a distinction between positional and named parameters. Positional parameters can only be used positionally, and named parameters can only be used by supplying their name.

This will work:
```sql
D create or replace macro test(a := 'auto') AS a;
D select test(a:='fiets');
┌────────────────────┐
│ test(a := 'fiets') │
│      varchar       │
├────────────────────┤
│ fiets              │
└────────────────────┘
```
Or this will work:
```sql
D create or replace macro test(a) AS a;
D select test('fiets');
┌───────────────┐
│ test('fiets') │
│    varchar    │
├───────────────┤
│ fiets         │
└───────────────┘
```
And this will also work:
```sql
D create or replace macro test(a, b := 'fiets') AS (a, b);
D select test('auto');
┌────────────────────────────┐
│        test('auto')        │
│ struct( varchar,  varchar) │
├────────────────────────────┤
│ {'': auto, '': fiets}      │
└────────────────────────────┘
```
But this won't:
```sql
D select test('fiets', 'auto');
Error: Binder Error: Macro function 'test(a)' requires a single positional argument, but 2 positional arguments were provided.
LINE 1: select test('fiets', 'auto');
               ^
```
Named parameters always come after positional parameters (like in Python).

However, I realise that Python accepts positional parameters even when they have a default:
```py
>>> def test(a='auto'):
...   return a
... 
>>> test('fiets')
'fiets'
```
Perhaps we can add this functionality as well.

**Comment by arjenpdevries** [comment]
Ah thanks for the clear explanation! I see now how this is expected.
