### ISSUE TITLE
Property names not populated with column names in C++API

### ISSUE THREAD

**Issue by lkordos** [duckdb/duckdb#10778]
### What happens?

After retrieving the data from a table, the property 'names' is empty. It seems that the values are not propagated from the base class in the C++ API (see attached screenshot). This was working in previous versions of duckdb.

### To Reproduce

```
std::unique_ptr<duckdb::MaterializedQueryResult> test = con->Query("select * from myTable");
auto data = test->names;
```
As a result, the data collection will be empty. The attached screenshot shows, there is 16 columns, however.
![Screenshot 2024-02-20 144308](https://github.com/duckdb/duckdb/assets/53355767/21a4ff72-736e-42f0-af38-01b44e2cf6d2)

### OS:

Windows 11

### DuckDB Version:

v0.10.0

### DuckDB Client:

C++

### Full Name:

Lubomir Kordos

### Affiliation:

Lukosoft Canada

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @lkordos, unfortunately, the C++ API falls outside [the scope of our community support policy](https://duckdblabs.com/news/2023/10/02/support-policy#extensions-and-apis). We are happy to review PRs resolving the issue but are unable to guarantee that it will be fixed in the near future. For guaranteed fixes, please consider our [support options](https://duckdblabs.com/support/).
