### ISSUE TITLE
.NET/C# bindings

### ISSUE THREAD

**Issue by x2bool** [duckdb/duckdb#1084]
Are there known ADO.NET implementations for DuckDB? What would be the best way to contribute .NET bindings if there are none right now?

(Edit: https://github.com/x2bool/duckdb-net, https://www.nuget.org/packages/DuckDb)

**Comment by Giorgi** [comment]
I'm working on it. Feel free to email me at giorgi at giorgi.dev

**Comment by x2bool** [comment]
We decided to start implementing .NET drivers: https://github.com/x2bool/duckdb-net

This is work in progress. So far we got connections and simple queries working. There is still plenty of room for improvement, but hopefully soon we gonna have the minimum viable version working. Contributions are welcome.

**Comment by Giorgi** [comment]
Here is my library: [DuckDB.NET](https://github.com/Giorgi/DuckDB.NET) It supports only Windows at the moment but I plan to add support for other platforms soon.

It supports creating tables, inserting/updating data and querying the data.

**Comment by hannes** [comment]
Since there is DuckDB.NET and it seems alive and kicking we are closing this here.

**Comment by sgf** [comment]
> 

hello, since the duckdb-net you developed has been archived, I have to find an Issue of another project to communicate with you.
If you want, why not continue the development of duckdb-net.

https://github.com/Giorgi/DuckDB.NET
Giorgi's development does not hinder your development plan.
The .net community shouldn't have just one choice.
If you have time and are willing to do something you like to do, I believe no one will object.
As an ordinary rookie developer, I would like to thank you for your contribution to the .net community.

**Comment by sgf** [comment]
> Since there is DuckDB.NET and it seems alive and kicking we are closing this here.

DuckDB.NET Although alive, but a few years have passed, the development progress of the project is slow, and there is no much development. I suggest that if the duckdb official has knowledge of .net developers, whether it can launch a more complete version.

**Comment by Giorgi** [comment]
@sgf You are probably looking at the wrong repository. [DuckDB.NET](https://github.com/Giorgi/DuckDB.NET/) had [lots of commits](https://github.com/Giorgi/DuckDB.NET/commits/main) this year. Is there a specific feature you need that isn't supported by the library?

**Comment by sgf** [comment]
> @sgf You are probably looking at the wrong repository. [DuckDB.NET](https://github.com/Giorgi/DuckDB.NET/) had [lots of commits](https://github.com/Giorgi/DuckDB.NET/commits/main) this year. Is there a specific feature you need that isn't supported by the library?

Don't get me wrong, just because the author wasn't actually involved in your project after closing his own repo, so I think if, he's interested in maintaining his own project, he can do as he wants, without forcing him to have to maintain someone else s project.

Your project is actually very good, but there are still some deficiencies in the implementation of some features of ado.net. For example, if use Orm to connect to your driver, some key implementations are missing. 

Of course, this is not your responsibility. The features of duckdb itself have not yet been perfected. What I want to emphasize is that a person's time and energy are limited after all. If other people are willing to devote themselves to this, if they want to maintain their own projects, why not .
