### ISSUE TITLE
Python: eager execution / results sets / relations

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10954]
### What happens?

I'm trying to pass around the eager "result sets" of duckdb queries between functions without converting back and forth to and from polars/pandas/python-object-representation. I don't seem to be able to achieve this in a sensible manner and I believe the (documentation of?) the Python API is at least be partly to blame since one of the results I'm getting below is just plain wrong.
(Sort of a follow up on https://github.com/duckdb/duckdb/discussions/10193 since I embarassingly still just don't get it.)

The snippet below shows that, in order,

- `duckdb.execute()` contrary to what the documentation says doesn't "Execute the given SQL query" since the output is an empty table (with the correct schema) without referenced variables present in Python's `locals()`
- `duckdb.sql()` is lazy as expected
- `duckdb.sql().execute()` contrary to what the documentation says doesn't "Transform the relation into a result set" since the output can't be used without referenced variables present in Python's `locals()`
- `duckdb.execute()` behaves somewhat surprisingly in that if you call `.df()` on it twice, the second call always returns `None` (this is unrelated to the `df` presence question)
- `duckdb.sql()` behaves surprisingly in that if you call `str` on it it will change behavior and return correct results on successive `str` calls even if referenced dataframes are not available in the Python `locals()` anymore
- `duckdb.sql().execute()` behaves the same as `duckdb.sql()` -- not sure if that's expected

### To Reproduce

```python
import pandas as pd
import duckdb

df = pd.DataFrame({'a': [0]})
attempts = dict(
    b = duckdb.execute("SELECT * FROM df"),
    c = duckdb.sql("SELECT * FROM df"),
    d = duckdb.sql("SELECT * FROM df").execute(),
    bp = duckdb.execute("SELECT * FROM df"),
    cp = duckdb.sql("SELECT * FROM df"),
    dp = duckdb.sql("SELECT * FROM df").execute(),
)
for v in ['bp', 'cp', 'dp']:
    str(attempts[v])

del df

for v, q in attempts.items():
    try:
        print(v)
        print(q if not v.startswith('b') else q.df())
    except Exception as e:
        print(f"Couldn't display {v} because {type(e)}")
```
```
b
Empty DataFrame
Columns: [a]
Index: []
c
Couldn't display c because <class 'duckdb.duckdb.InvalidInputException'>
d
Couldn't display d because <class 'duckdb.duckdb.InvalidInputException'>
bp
None
cp
┌───────┐
│   a   │
│ int64 │
├───────┤
│     0 │
└───────┘

dp
┌───────┐
│   a   │
│ int64 │
├───────┤
│     0 │
└───────┘
```

### OS:

Linux

### DuckDB Version:

'0.10.1-dev717'

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hey, thanks for the interest and the feedback 👍 

Regarding `b = duckdb.execute("SELECT * FROM df")`
`execute` returns the connection, the result is stored inside of it.
Meaning `b` is just the duckdb connection that's stored inside the `duckdb` module

Addressing your comments/questions around `duckdb.sql().execute()`
I'm not sure I follow what you said about referenced `locals()`
`duckdb.sql()` creates a Relation, this is lazily executed. with `.execute` the result gets executed and stored inside the relation object, ready to be retrieved with a result collecting operation (such as fetchall, df, fetchone, etc..)

This behaves as expected for me?
```
>>> rel = duckdb.sql("select * from df").execute()
>>> del df
>>> res = rel.df()
>>> print(res)
   a
0  1
1  2
2  3
```

`str` calls work because the result is cached, so nothing gets executed on subsequent calls

> `duckdb.execute()` behaves somewhat surprisingly in that if you call `.df()` on it twice, the second call always returns `None`

This is expected, because a result set is created, `df()` and other result collection methods consume this result set
`fetchone()` for example consumes a single row at a time, `fetchall` and `df()` are examples of fully consuming methods.
Once the result is fully consumed.

Some of this behavior is dictated by [DBAPI](https://peps.python.org/pep-0249/)
For example, this is sqlite3's dbapi compliant API behavior:
```py
>>> import sqlite3
>>> con = sqlite3.connect(':memory:')
>>> cursor = con.cursor()
>>> cursor.execute("select * from (VALUES (1), (2), (3))")
<sqlite3.Cursor object at 0x10331e940>
>>> res = cursor.fetchall()
>>> print(res)
[(1,), (2,), (3,)]
>>> res = cursor.fetchall()
>>> print(res)
[]
```

**Comment by soerenwolfers** [comment]
Thanks for the quick answer.

Let me split up my concerns a bit.

First, the thing that I still think is definitely a bug: 

```
df = pd.DataFrame({'a': [0]})
b = duckdb.execute("SELECT * FROM df")
cp = duckdb.sql("SELECT * FROM df")
str(cp)
b.df()
```
```
Empty DataFrame
Columns: [a]
Index: []
```

**Comment by soerenwolfers** [comment]
Thanks for the quick answer. 

The MWE for what I thought is definitely a bug is this:
```python
df = pd.DataFrame({'a': [0]})
b = duckdb.execute("SELECT * FROM df")
cp = duckdb.sql("SELECT * FROM df")
str(cp)
print(b.df())
```
```
Empty DataFrame
Columns: [a]
Index: []
```

**Comment by soerenwolfers** [comment]
@Tishj In case there is no bug here, I am happy to have this ticket closed. In the meantime I have created a Q&A  at https://github.com/duckdb/duckdb/discussions/10962 that focuses more on what I'm actually trying to do and less on the question whether there is a bug or not.
