### ISSUE TITLE
Cannot use overriding column alias for aggregate expression in HAVING clause

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10961]
### What happens?

DuckDB doesn't let me use aliases in the HAVING clause that I define in the SELECT clause and that override an existing column. (More precisely, it gives higher precedence to the original columns over  aliases in the SELECT when resolving column names in HAVING expressions, and then throws because the original column is not being aggregated over.)

DuckDB does let me use aliases in the HAVING clause that I define in the SELECT clause as long as they do not override an existing column. 

Prior art:
- MySQL lets me use all aliases in the HAVING clause, see https://www.db-fiddle.com/f/6CMxm3gtr2h7PWLXkJkax3/0
- SQLite allows aliases in the HAVING clause but in case of overrides gives precedence to original columns (and if those original columns are not GROUPED over, it'll filter the groups by checking the filter condition on a randomly selected row of each group, which seems insane to me)
- PostgreSQL and SQLServer don't let me use any alias in the HAVING clause.

This may as well be intentional, just opening in case there is interest in adopting MySQL behavior here, which I find more convenient, since duckdb is already deviating from PostgreSQL.

Personally, I find that:

- even in non-grouped by select statements, the aliases should take precedence over the original columns, see https://github.com/duckdb/duckdb/issues/13991
- even if not, typing the HAVING instead of the ubiquitous WHERE raises enough alerts in my brain that I'm now talking about groups, so I see even less danger of accidentally referring to the alias when the original column was meant. Also, MySQL here offers a precedent, the lack of which was given in #13991 as a reason not to make a general switch to alias precedence. 
 

### To Reproduce

```sql
SELECT b, sum(a) AS a
FROM (VALUES (1, 0), (1, 1)) t(a, b)
GROUP BY b
HAVING a > 0
```
```
Error: column t.a must appear in the GROUP BY clause or be used in an aggregate function
```

while
```sql
SELECT b, sum(a) AS c
FROM (VALUES (1, 0), (1, 1)) t(a, b)
GROUP BY b
HAVING c > 0
```
```
┌───────┬────────┐
│   b   │   c    │
│ int32 │ int128 │
├───────┼────────┤
│     1 │      1 │
│     0 │      1 │
└───────┴────────┘
```

### OS:

Linux

### DuckDB Version:

'0.10.1-dev717'

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by milancio42** [comment]
This is likely a standard behaviour. I checked it on teradata and it behaves the same.

That being said, it is unfortunate. If I wanted to filter the original column, I would do it in the `WHERE` clause, not in the `HAVING` clause. There I want to filter the result of the aggregation so the alias should be used.

It gets even worse if you use `GROUP BY ALL` - it will add the original column to the group list without warning, leading to a non-intuitive behaviour and ugly bugs. 

Consider this:
```
SELECT a, sum(b) AS b
  FROM (VALUES (1, -1), (1, 1)) t(a, b)
  GROUP BY ALL
  ;

┌───────┬────────┐
│   a   │   b    │
│ int32 │ int128 │
├───────┼────────┤
│     1 │      0 │
└───────┴────────┘
```

But putting there `HAVING` we get this without any warning:

```
SELECT a, sum(b) AS b
  FROM (VALUES (1, -1), (1, 1)) t(a, b)
  GROUP BY ALL
  HAVING b <> 0;
┌───────┬────────┐
│   a   │   b    │
│ int32 │ int128 │
├───────┼────────┤
│     1 │      1 │
│     1 │     -1 │
└───────┴────────┘
```

Instead of having no rows in the output, we see the two original rows.

Of course changing it is a breaking change but it would go in line with the DuckDB's pledge of having friendly SQL.

Thank you for your good work.

**Comment by soerenwolfers** [comment]
It's not standard behavior; the four major dialects all behave differently than duckdb and they behave differently in different ways (both of which are friendlier that duckdb's solution, IMO). 

I do agree with you that the behavior with GROUP BY ALL is an even clearer argument that the current behavior should be changed.

**Comment by soerenwolfers** [comment]
@szarnyasg This is still an issue. I cannot remove the stale label myself. Is it okay to tag you in each of these or is there an alternative solution? (For example, if the closing after 30 days happens non-automatically I guess I can just leave a comment under each ticket for the manual closer to read)

**Comment by Mytherin** [comment]
Thanks for the report!

I've looked into this - and I think the issue here is a bit more complex than just which order columns are resolved in. MySQL prefers the original columns over the aliases as well. Below are some queries that return the same result in all systems I've tested (DuckDB, MySQL, SQLite, Postgres) showing the original columns are filtered instead of the aliases:

```sql
create table t1(a int);
insert into t1 values (42), (84);
select a+1 as a from t1 group by a having a=42;
+------+
| a    |
+------+
|   43 |
+------+

create table t2(a int);
insert into t2 values (42), (84), (42);
select a as b, sum(a) as a from t2 group by b having a=42;
+------+------+
| b    | a    |
+------+------+
|   42 |   84 |
+------+------+
```

It seems to me that what MySQL/SQLite are doing is instead: filter on the original columns first, if filtering on the original column is not possible because it is part of an aggregate then we filter on an alias.

I think that's fair, and actually seems like a good solution to the issue here since the alternative is throwing an error. I would argue the `GROUP BY ALL` should adopt the same binding rule or throw an error in that scenario.

> @szarnyasg This is still an issue on 1.0.0. I cannot remove the stale label myself. Is it okay to tag you in each of these (i have O(10) affected tickets) or is there an alternative solution? (For example, if the closing after 30 days happens non-automatically I guess I can just leave a comment under each ticket for the manual closer to read)

The stalebot automatically removes the label if there's any activity in the issue.

**Comment by soerenwolfers** [comment]
As usual, you have a keener eye for these intricacies. lf the discussion in #13991 ever results in a way to explicitly refer to an alias, that can adopted here too, but until then your solution sounds great. 

> The stalebot automatically removes the label if there's any activity in the issue.

Good bot.

**Comment by Mytherin** [comment]
I've pushed a fix for this in https://github.com/duckdb/duckdb/pull/14023
