### ISSUE TITLE
Unexpected Binder Error with 0.10.0

### ISSUE THREAD

**Issue by schu** [duckdb/duckdb#11013]
### What happens?

I have a `case` statement similar to the following example:

```
case
when
  ...
then
  date_trunc('day', date1) - date_trunc('day', date2)
when
  ...
then
  date_trunc('day', date1) - (date_trunc('day', date2) + interval 1 day)
when
  ...
  ...
end
```

With version 0.9.2 both then statements produce a `BIGINT`, with version 0.10.0 the first then statement is a `BIGINT` and the second an `INTERVAL`, i.e. 0.10.0 returns an error:

```
Binder Error: Cannot mix values of type INTERVAL and BIGINT in CASE expression
```

The following select statements show the difference:

```
select date_trunc('day', '2024-01-03 12:00:00'::DATETIME) - (date_trunc('day', '2024-01-01 12:00:00'::DATETIME));
select date_trunc('day', '2024-01-03 12:00:00'::DATETIME) - (date_trunc('day', '2024-01-01 12:00:00'::DATETIME) + INTERVAL 1 DAY);
```

(Note the `...(CAST(trunc(...` in the output of the second select with 0.10.0.)

Is this intended? From reading https://duckdb.org/2024/02/13/announcing-duckdb-0100.html I didn't expect the breaking change, but maybe I have missed something?

### To Reproduce

See the select statements above.

### OS:

Linux

### DuckDB Version:

0.10.0, 0.9.2

### DuckDB Client:

CLI

### Full Name:

Michael Schubert

### Affiliation:

none

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
This is due to the fix for #10272 that changed `DATE + INTERVAL` to return `TIMESTAMP` for Postgres compatibility. 

Sorry for the surprise - it didn't make the release notes because it was a small change, but of course you were relying on that functionality! I think you can just add a cast to fix it:

case
when
  ...
then
  date_trunc('day', date1) - date_trunc('day', date2)
when
  ...
then
  date_trunc('day', date1) - (date_trunc('day', date2) + interval 1 day)::DATE
when
  ...
  ...
end
