### ISSUE TITLE
DuckDB benchmark with 1.1B Taxi Data?

### ISSUE THREAD

**Issue by cavanaug** [duckdb/duckdb#1121]
It might be useful to add a DuckDB benchmark for the 1.1 Billion Taxi Rides datasets that Mark Litwintschik has done for a number of databases/warehouses.   It is not a formal benchmark, but it is a fairly well known dataset with a collection of queries for analytics that has been used to compare and contrast various systems.

A DuckDB analysis/blog post might go a long way to get people excited in comparison to sqlite or even real db systems such as Postgres.

https://tech.marksblogg.com/billion-nyc-taxi-rides-sqlite-parquet-hdfs.html

**Comment by hannesmuehleisen** [comment]
Yeah I tried to reproduce that dataset at some point did not work out so well...

**Comment by wallflower** [comment]
As a starting point, I remember Uwe did a run through of the taxi data (although I don't think it was the entire dataset) comparing it against sqlite.

Taking DuckDB for a spin | Uwe’s Blog 
https://uwekorn.com/2019/10/19/taking-duckdb-for-a-spin.html

**Comment by wallflower** [comment]
Looking more closely at the Uwe's blog post, I see he only did 2016-01 data.  In doing some other searches, I found that a new version of the embedded MonetDB (now named MonetDBe) was released (nice!), and I see that there is a blog post doing the same 2016-01 dataset... 

Taking MonetDB/e for a taxi ride | MonetDB 
https://www.monetdb.org/blog/taking-MonetDBe-for-a-taxi-ride

I might dig into this a little deeper and do some testing on my own.  If I do, I will be sure to post back some results...

**Comment by hannesmuehleisen** [comment]
I'm trying to create the dataset again right now. Will post for download somewhere so this has an end.

**Comment by tobymao** [comment]
has there been any update on this? curious to see if duckdb will scale to this dataset with multiple threads

**Comment by hannesmuehleisen** [comment]
@tobymao I am happy to confirm that DuckDB has no issues running queries on this dataset with multiple threads etc. We were waiting for a hosting agreement so we can make the dataset available with benchmark results as well.

**Comment by jtommaney** [comment]
I did a simplified version of what Mark Litwintschik did here: https://tech.marksblogg.com/benchmarks.html

Key differences:  loaded 72 months of data from yellow cab only (Mark includes Uber, Green, etc), and did not transform to include weather, borough, cab_type columns within the fact table.
- 18 columns instead of 45
- 1.03 billion instead of 1.1 billion
- 3 of the 4 queries Mark uses still apply to this simplified data load.
- 1 query against cab type changed to look at a vendor_name (and vendor_id)

-Used AWS 5d.8xlarge instance 16 cores (32 HT), 256GB memory.

```
'Taxi_Q1_variant'|1|"select vendor_name, count(*) from trip group by 1 "
'Taxi_Q2'|2|"select passenger_count, avg(total_amt) from trip group by 1 "
'Taxi_Q3'|3|"SELECT passenger_count, EXTRACT(year from trip_pickup_datetime), count(*) FROM trip GROUP BY 1,2"
'Taxi_Q4'|4|"SELECT passenger_count, EXTRACT(year from trip_pickup_datetime) as year, round(trip_distance), count(*) trips FROM trip GROUP BY 1,2,3 order by year, trips desc;"

'Taxi_Q1_variant2'|5|"select vendor_id, count(*) from trip group by 1 "
```

wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2009-{01..12}.csv
...
wget https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2014-{01..12}.csv

cleaned up a few rows with extra columns in 2 months of 2010 per Mark's suggestions.

- Run as in-memory through python. 
- let read_csv_auto determine structure:
create table trip as select * from read_csv_auto('/data1/yellow_tripdata_2009-01.csv',header=true)


Raw timings with 1 through 32 threads (pragma threads=N)
```
                         |    1    |    2    |    3    |    4    |    6    |    8    |   12    |   16    |   24    |   32
Taxi_Q1_variant 1'       | 33.181 | 16.628 | 11.075 | 8.308 | 5.544 | 4.156 | 2.774 | 2.084 | 1.801 | 1.585
'Taxi_Q2'                | 6.506 | 3.297 | 2.2 | 1.652 | 1.105 | 0.828 | 0.556 | 0.419 | 0.349 | 0.299
'Taxi_Q3'                | 12.318 | 6.233 | 4.14 | 3.103 | 2.075 | 1.557 | 1.04 | 0.782 | 0.688 | 0.617
'Taxi_Q4'                | 44.666 | 21.517 | 14.559 | 11.073 | 7.445 | 5.905 | 4.055 | 3.604 | 3.397 | 4.103
Taxi_Q1_variant 2'       | 4.492 | 2.366 | 1.559 | 1.169 | 0.775 | 0.586 | 0.391 | 0.293 | 0.253 | 0.225
```
![Duckdb_1 03_trended](https://user-images.githubusercontent.com/8917575/108901205-706ffe80-75cf-11eb-8a0d-cdc944baecae.png)

### **Key Learning:**
1)  **Extremely strong linear scaling**: -a validation of their vector-volcano model for these use cases.
    Example:  Q3 is 0.78 seconds at 16 threads.  Perfect linear scaling extrapolated from 1 thread is 0.77 seconds.   (beyond 16 threads linear scaling is not expected )

Additional Learnings:
1)  Group by vendor_name (string) is about 7x slower than group by vendor_id (integer) (2.084 vs 0.293 seconds at 16 threads).  There is a future optimization Mark and Hannes have planned around dictionary handling that should allow string performance here to approach integer (with few distinct strings yielding a tight dictionary). 
2)  Q4 is about 6x slower than Q3, likely because it <may> use a less optimized hash aggregate strategy due to higher number of group by items (doesn't use perfect hash afaik).  
3) Decrease "perfect linear scaling" beyond 16 threads is a by-product of ht architecture.  Vectorization and streaming data input minimize L1 data and L1 instruction cache misses to the point where the CPU is productive "most" of the time, leaving fewer opportunities to run a second thread transparently.  There could be artifacts from a virtual environment at play as well.  
4)  It took about 3 minutes to add the vendor_id column and populate 1.03 billion rows via a case statement.  I don't have a direct comparison, but was both fast and easy to do this.

**Comment by tobymao** [comment]
Wow awesome stuff. Are operations on floats (total_amt) parallel? I read in #854 that floating point summation was not parallel https://github.com/cwida/duckdb/issues/854#issuecomment-677455468.

Looks like duckdb can stand up to these other db's without having to install anything external!

**Comment by Alex-Monahan** [comment]
Great benchmark! Fantastic to see DuckDB compete with these other DBs.
How long did the data import step take?
Thanks!

**Comment by jtommaney** [comment]
Something like 3 hours to load 72 months, I didn't get the exact timings.

**Comment by jtommaney** [comment]
> Wow awesome stuff. Are operations on floats (total_amt) parallel? I read in #854 that floating point summation was not parallel [#854 (comment)](https://github.com/cwida/duckdb/issues/854#issuecomment-677455468).
> 
Be default, the read_csv_auto defined fare_amount as a double which scales nicely.
