### ISSUE TITLE
read_csv treats leading zeros as VARCHAR during type auto-detection

### ISSUE THREAD

**Issue by tboddyspargo** [duckdb/duckdb#11411]
### What happens?

When reading a CSV file that has values like `01` and `12`, the auto-detected type for the column ends up being `VARCHAR`, when I expected it to ignore leading zeros and detect `Integer` instead.

Example:
The `fips` column in the NYTimes US COVID data repository contains these identifiers with leading zeros.
- https://github.com/nytimes/covid-19-data/blob/master/us-states.csv

Do you think it's reasonable to detect an `Integer` type in cases like this?

### To Reproduce

_Using a downloaded copy of this file:_
<https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv>

```python
import duckdb
conn = duckdb.connect()
rel = conn.read_csv("us-states.csv")
rel.show()
```

### OS:

Darwin, macOS 14.4, aarch64 (arm64)

### DuckDB Version:

v0.9.2

### DuckDB Client:

Python

### Full Name:

Tyler BoddySpargo

### Affiliation:

DataChat

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by tboddyspargo** [comment]
I'm not sure what's best or standard practice here, but I'm coming from a custom implementation that ignored leading zeros and detected a type of `Integer`.

`pandas` seems to take that approach, too:

```python
>>> df.dtypes
date      object
state     object
fips       int64
cases      int64
deaths     int64
dtype: object
```

I am, admittedly, a bit torn about what's appropriate here, because in some cases (perhaps [including this `fips` example](https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt)), maintaining a consistent number of digits/characters may be desired.

**Comment by cmdlineluser** [comment]
I was just curious about this: it seems DuckDB used to default to parsing this as numeric.

That behaviour was reported as a bug and https://github.com/duckdb/duckdb/pull/5850 fixed it to match `readr` which parses it as a string:

```R
date       state      fips  cases deaths
<date>     <chr>      <chr> <dbl>  <dbl>
```

pandas, Polars, and PyArrow all parse it as numeric.

I'm not sure if it would be feasible to have an parameter that controls this? `strip_leading_zero = false` or something?

None of the other parsers seem to have any way of controlling this behaviour other than specifying the column type by name.

**Comment by pdet** [comment]
> I'm not sure what's best or standard practice here, but I'm coming from a custom implementation that ignored leading zeros and detected a type of `Integer`.
> 
> `pandas` seems to take that approach, too:
> 
> ```python
> >>> df.dtypes
> date      object
> state     object
> fips       int64
> cases      int64
> deaths     int64
> dtype: object
> ```
> 
> I am, admittedly, a bit torn about what's appropriate here, because in some cases (perhaps [including this `fips` example](https://transition.fcc.gov/oet/info/maps/census/fips/fips.txt)), maintaining a consistent number of digits/characters may be desired.

Yes, this appears somewhat ambiguous. On one hand, one could argue that treating these as numbers will lead to a loss of information. On the other hand, if that's the default behavior of other tools, I think it provides a compelling enough argument.

**Comment by pdet** [comment]
Hi @tboddyspargo 

I've given more thought to this topic and believe it's best not to lose information by default.

The original issue that triggered this change, https://github.com/duckdb/duckdb/issues/5782, includes an example of zip codes that would be incorrectly converted if changed to numeric values.

I'm also not very keen on adding an option since column types can still be manually defined. However, if adopting such a feature is common practice in other systems, we might consider implementing it eventually.
I gave more thought to this topic, and I think it's best not to lose information by default.

The original issue https://github.com/duckdb/duckdb/issues/5782 that triggered this change in the first place has an example of zipcodes that would be incorrectly converted if done to numeric values.

I'm also not very keen on adding an option since column types can still be manually defined, but if that's something other systems do, we could eventually adopt it.

**Comment by pdet** [comment]
Hi @tboddyspargo

I've given more thought to this topic and believe it's best not to lose information by default.

The original issue that triggered this change, https://github.com/duckdb/duckdb/issues/5782, includes an example of zip codes that would be incorrectly converted if changed to numeric values.

I'm also not keen on adding an option since column types can still be manually defined, but if that's something other systems do, we could eventually adopt it.

**Comment by pdet** [comment]
> > I've given more thought to this topic and believe it's best not to lose information by default.
> > The original issue that triggered this change, #5782, includes an example of zip codes that would be incorrectly converted if changed to numeric values.
> > I'm also not keen on adding an option since column types can still be manually defined, but if that's something other systems do, we could eventually adopt it.
> 
> That seems quite reasonable. I, similarly, would be hesitant to incorporate such a specific auto-detect option. An additional type casting step or specifying ones prefered type for the column seems to provide well enough (and for a far more broad set of use-cases).
> 
> Thanks for the discussion and consideration!

My pleasure! :-)
