### ISSUE TITLE
Lambda functions like `list_transform` work only for the first row?

### ISSUE THREAD

**Issue by manticore-projects** [duckdb/duckdb#11434]
### What happens?

When applying a Lambda function on a set of rows, only the first row is considered.

### To Reproduce

```sql

SELECT split(word, '') 
      FROM (
        select * 
        FROM ( select UNNEST(['foo', 'bar', 'baz', 'giraffe', 'llama']) word)
        )

/* returns as expected
┌───────────────────────┐
│ split(word, '')       │
├───────────────────────┤
│ [f, o, o]             │
├───────────────────────┤
│ [b, a, r]             │
├───────────────────────┤
│ [b, a, z]             │
├───────────────────────┤
│ [g, i, r, a, f, f, e] │
├───────────────────────┤
│ [l, l, a, m, a]       │
└───────────────────────┘
*/

-- but LIST_TRANSFORM considers only the first row:
select list_transform( 
    ( SELECT split(word, '') 
      FROM (
        select * 
        FROM ( select UNNEST(['foo', 'bar', 'baz', 'giraffe', 'llama']) word)
        )
    )
    , x -> unicode(x) 
) as code_points ;

-- expected result
/*---------+------------------------------------*
 | word    | code_points                        |
 +---------+------------------------------------+
 | foo     | [102, 111, 111]                    |
 | bar     | [98, 97, 114]                      |
 | baz     | [98, 97, 122]                      |
 | giraffe | [103, 105, 114, 97, 102, 102, 101] |
 | llama   | [108, 108, 97, 109, 97]            |
 *---------+------------------------------------*/

-- actual result is only the first row
/*---------+------------------------------------*
 | word    | code_points                        |
 +---------+------------------------------------+
 | foo     | [102, 111, 111]                    |
 *---------+------------------------------------*/
```

### OS:

Linux

### DuckDB Version:

10.0.1

### DuckDB Client:

Java

### Full Name:

Andreas Reichel

### Affiliation:

manticore-projects.com

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by manticore-projects** [comment]
Interestingly, using a `WITH` clause helps:

```sql
with t
as (SELECT word, split(word, '') split
      FROM (
        select * 
        FROM ( select UNNEST(['foo', 'bar', 'baz', 'giraffe', 'llama']) word)
        )
    )
select word, list_transform( split , x -> unicode(x)) as code_points from t;

/* output
┌─────────┬────────────────────────────────────┐
│ word    │ code_points                        │
├─────────┼────────────────────────────────────┤
│ foo     │ [102, 111, 111]                    │
├─────────┼────────────────────────────────────┤
│ bar     │ [98, 97, 114]                      │
├─────────┼────────────────────────────────────┤
│ baz     │ [98, 97, 122]                      │
├─────────┼────────────────────────────────────┤
│ giraffe │ [103, 105, 114, 97, 102, 102, 101] │
├─────────┼────────────────────────────────────┤
│ llama   │ [108, 108, 97, 109, 97]            │
└─────────┴────────────────────────────────────┘
*/

```

**Comment by manticore-projects** [comment]
Better pronounced:

```sql
-- 1 record only, why?!
select list_transform( 
    ( SELECT split(word, '') split
      FROM (
        select * 
        FROM ( select UNNEST(['foo', 'bar', 'baz', 'giraffe', 'llama']) word)
        )
    )
    , x -> unicode(x) 
) as code_points;


-- 5 records as expected
with t 
as ( SELECT split(word, '') split
      FROM (
        select * 
        FROM ( select UNNEST(['foo', 'bar', 'baz', 'giraffe', 'llama']) word)
        )
    )
select list_transform( split , x -> unicode(x)) as code_points from t ;
```

In my opinion, both queries mean the same and should produce exactly the same result set.

**Comment by cmdlineluser** [comment]
Is it a case that it is parsed as a [Scalar Subquery](https://duckdb.org/docs/sql/expressions/subqueries.html#scalar-subquery)?

```python
duckdb.sql("""
select unnest(['foo', 'bar', 'baz']).split('')
""")
# ┌─────────────────────────────────────────────────────────┐
# │ split(unnest(main.list_value('foo', 'bar', 'baz')), '') │
# │                        varchar[]                        │
# ├─────────────────────────────────────────────────────────┤
# │ [f, o, o]                                               │
# │ [b, a, r]                                               │
# │ [b, a, z]                                               │
# └─────────────────────────────────────────────────────────┘
```

Which essentially has an implicit `LIMIT 1`?

```python
duckdb.sql("""
select (select unnest(['foo', 'bar', 'baz']).split(''))
""")
# ┌──────────────────────────────────────────────────────────────────┐
# │ (SELECT split(unnest(main.list_value('foo', 'bar', 'baz')), '')) │
# │                            varchar[]                             │
# ├──────────────────────────────────────────────────────────────────┤
# │ [f, o, o]                                                        │
# └──────────────────────────────────────────────────────────────────┘
```

**Comment by soerenwolfers** [comment]
In general, you'd make the developer's life easier by writing truly MWE. This can almost always be achieved by iteratively removing bits from your examples that are unlikely to be part of the problem. 

In your example, you almost surely don't need five records instead of two, the `split` is almost surely not needed, the `unnest` is unlikely to be needed`, the `unicode` is almost surely not needed, the multiple layers of `selects` are likely not needed, the renames are likely not needed, the `list_transform` is likely not different from any more simple function, and indeed if you try all these simplifications you end up with a much more concise example of what you are surprised by:
```sql
select 0 + (select 0 union select 1)
```
```
-- Actual result
┌─────────────────────────────────────┐
│ (0 + ((SELECT 0) UNION (SELECT 1))) │
│                int32                │
├─────────────────────────────────────┤
│                                   0 │
└─────────────────────────────────────┘
```
```
-- Expected result
┌─────────────────────────────────────┐
│ (1 + ((SELECT 0) UNION (SELECT 1))) │
│                int32                │
├─────────────────────────────────────┤
│                                   0 │
├─────────────────────────────────────┤
│                                   1 │
└─────────────────────────────────────┘
```

Now that you have a truly MWE, you can try it at https://www.db-fiddle.com/ with PostgreSQL to see what a very related dialect does and it will tell you
```
Query Error: error: more than one row returned by a subquery used as an expression
```

FWIW, I think duckdb should also throw this error.

**Comment by soerenwolfers** [comment]
After all the lecturing, here is a solution to your problem:

```sql
select 
    list_transform( 
        split(word, '') 
        , x -> unicode(x) 
    ) as code_points 
FROM (
    select UNNEST(['foo', 'bar', 'baz', 'giraffe', 'llama']) word
)
```

**Comment by manticore-projects** [comment]
Thank you for the lecturing and for the work around. I found a similar work around too, using a `WITH` clause.
However, I am lost WHY this makes any difference.

To me the hint regarding Scalar Subqueries was most useful, however I still don't see the difference and I think it should be somehow predictable when this "scalar subquery" applies.

Last but not least, keep in mind that not everyone is an experienced C developer.  There are people, how are just simple accountants, engineers, risk managers or plumbers.

**Comment by soerenwolfers** [comment]
In Python pseudocode, your goal was to do
```
[do_something_to_a_foo(single_foo) for single_foo in multiple_foos]
```
but instead your original attempt was 
```
do_something_to_a_foo(multiple_foos)
```
What you should have been surprised by was that this didn't just throw, since you're passing a parameter of the wrong type: a list of foos is not a foo!

The reason it didn't throw is that SQL has the concept of "scalar subqueries" which allow you to use a "inner query"/subquery anywhere a single value is expected. For this to make sense, duckdb expects the subquery to return a single row with a single column (and confusingly, it throws if your subquery returns multiple columns, but it silently discards multiple rows). Hence, subqueries cannot possibly solve your conundrum. 

Your and my solution (they are really the same, I just wanted to point out that it's not the CTE/`WITH` clause that makes the differences) solve this by actually passing single foos:
```
SELECT do_something_to_a_foo(single_foo) FROM something_that_produces_multiple_lists
```

PS: I'm not a duckdb dev and have never written a serious line of C or C++. I'm just lurking around here in attempt to lessen their support burden so they can focus on making this great library even greater, and I'm happy for everyone that shares my fandom, accountant, engineer, risk manager, or plumber.

**Comment by manticore-projects** [comment]
Thank you very much for this good explanation. I actually do understand your example:

```
do_something_to_a_foo(multiple_foos)
```

The surprise is, that `do_something_to_a_foo(multiple_foos)` expects/works with `single_foo` only and so just *makes* my `multiple_foos` a `single_foo` by trimming *silently*.

**Comment by soerenwolfers** [comment]
You're not alone! As I have stated repeatedely, I find it confusing and dangerous too (note that it will randomly print 1 or 2 or 3) and would prefer that it throws the same error that PostgreSQL throws. If you have open a new issue, that just makes that single request, I'll keep out of it and let the devs weigh in.

**Comment by manticore-projects** [comment]
Ok, thanks again for explanation and patience! I do appreciate.
I am closing this and reopen with a shortened version. (I really though at start it was related to the Lambda function, sorry!).
