### ISSUE TITLE
BigInt mod Double returns wrong result in case of a large BigInt

### ISSUE THREAD

**Issue by tolmalev** [duckdb/duckdb#11480]
### What happens?

Mod operation returns invalid result when left side is a large BigInt

### To Reproduce

```sql
SELECT 12345678901111111 % 2.0;
```
returns `0.0`

```sql
SELECT 12345678901111111 % 2;
```
returns `1`

### OS:

Windows

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Lev Tolmachev

### Affiliation:

N/A

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mytherin** [comment]
Thanks for reporting! Using a modulo with a double uses a floating point modulo ([`fmod`](https://cplusplus.com/reference/cmath/fmod/)), as also indicated by the return value. This allows you to do modulo of decimal values, e.g.:

```sql
D select 10 % 2.4 AS result;
┌─────────────────────┐
│       result        │
│       double        │
├─────────────────────┤
│ 0.40000000000000036 │
└─────────────────────┘

```

 Floating points are not always accurate, and especially with larger values this can lead to inaccuracies in the result, as experienced in this example. As such - this is expected behavior. Perhaps this should be mentioned in the documentation.

**Comment by tolmalev** [comment]
Thanks for the explanation.

I understand why it happens but it's just weird to see that changing second argument from 2.0 to 2 significantly changes the result.

**Comment by Mytherin** [comment]
Unfortunately that's the nature of floating point numbers. This seems to be consistent with fmod in other libraries, e.g. in numpy:

```py
>>> numpy.fmod(numpy.array([12345678901111111], dtype=numpy.int64), numpy.array([2.0], dtype=numpy.float64))
array([0.])
```

**Comment by Mytherin** [comment]
We might be able to make a decimal implementation of modulo that would address this in this scenario - it seems to be that Postgres supports that:

```sql
postgres=# select 10 % 2.4;
 ?column? 
----------
      0.4
(1 row)
```
