### ISSUE TITLE
Add column computed from existing column(s)

### ISSUE THREAD

**Issue by willium** [duckdb/duckdb#1187]
SQLServer has [this neat feature](https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver15#to-add-a-new-computed-column-to-an-existing-table) that allows for adding computed columns. It would be really cool to have that in DuckDB as well.

Perhaps a similar syntax to **ALTER TYPE** with `USING`:

<details>
 <summary>Add a column computed by adding two existing columns</summary>
<pre class="highlight highlight-source-sql">
ALTER TABLE integers ADD COLUMN z INTEGER USING x + y;
</pre>
</details>

<details>
 <summary>Add a column computed by casting an existing column to a different type</summary>
<pre class="highlight highlight-source-sql">
ALTER TABLE foo ADD COLUMN bar_dbl DOUBLE USING CAST(bar_int::DOUBLE);
</pre>
</details>

**Comment by Alex-Monahan** [comment]
Postgres also has generated columns. I think DuckDB might need an updated parser to get Postgres version 12 syntax though? 

https://pgdash.io/blog/postgres-12-generated-columns.html

**Comment by willium** [comment]
does the current alter table implementation in DuckDB make a new table? I know with SQLite altering a table to add new columns is not possible. It seems like Postrgres may only allow for generated columns to be done at table creation time?

**Comment by Alex-Monahan** [comment]
Postgres 12+ allows generated columns to be added with ALTER TABLE statements.

**Comment by willium** [comment]
Postrgres's `AS` syntax seems (with a `STORED` flag) to be pretty nice as well!

**Comment by Mytherin** [comment]
This is a feature that we are definitely interested in adding. The way I see it is that there are two orthogonal parts (although they seem very similar): stored and non-stored generated columns.

Stored generated columns are akin to default expressions, where the column value is computed when data is inserted into the table, with two differences. (1) unlike default expressions, stored generated columns can refer to *other* columns, (2) the default value is not merely inserted once and forgotten about, rather the value is recomputed also when other columns are updated.

Non-stored generated columns are computed whenever a column is used, essentially expanding the expression in any query, which can be achieved by simply pushing a projection over the table when it is generated.

Non-stored generated columns seem rather easy to implement, they only introduce an extra node during binding. Stored generated columns are more involved. As far as I can tell most other systems implement them using triggers, however, we don't have triggers (and likely won't for the foreseeable future). We could special-case generated columns rather than implementing triggers, of course, but that seems less clean to me.

I would propose to start of with implementing regular (non-stored) generated columns and implementing stored generated columns later on. 

> does the current alter table implementation in DuckDB make a new table? I know with SQLite altering a table to add new columns is not possible. It seems like Postrgres may only allow for generated columns to be done at table creation time?

No, it will only append the new column to the table. It won't touch the existing columns. Especially non-stored generated columns should be trivial to add, since they don't require changing the storage at all (besides meta data).

**Comment by willium** [comment]
That sounds terrific—a few follow up questions to make sure I understand.

In what way are the non stored columns different than just using an expression directly inline? Is it only ergonomic or is there the implication that we’re essentially materializing a view (albeit temporary)?

Would non-stored work within other clauses than SELECT (eg WHERE, GROUP BY)?

I wonder if there is a stop-gap solution where non-stored columns could be stored “post-rasterization” as it were, and to recompute it, you’d either need to manually update the value by applying the same expression, or need to drop the column and recalculate it. Not very elegant, but would allow people who need that functionality to have it.

**Comment by Mytherin** [comment]
> In what way are the non stored columns different than just using an expression directly inline? Is it only ergonomic or is there the implication that we’re essentially materializing a view (albeit temporary)?

In no way, they would essentially be materialized views.

> Would non-stored work within other clauses than SELECT (eg WHERE, GROUP BY)?

They would work in all clauses except for `UPDATE` (as you can't change the value of a stored column using update).

> I wonder if there is a stop-gap solution where non-stored columns could be stored “post-rasterization” as it were, and to recompute it, you’d either need to manually update the value by applying the same expression, or need to drop the column and recalculate it. Not very elegant, but would allow people who need that functionality to have it.

Perhaps one solution would be to allow `DEFAULT` columns to use other columns from the table, as long as there are no circular references (i.e. `x DEFAULT y, y DEFAULT x` is not allowed). Then on an insert the value of the default columns can be computed using the other values. That would allow "sort of" this functionality, as long as there are no updates to the other columns.

**Comment by willium** [comment]
> In no way, it's mostly syntactic sugar.
If this is the case (same as inline expressions), perhaps it's not a huge priority and we're better off focusing on the STORED version?

**Comment by jtommaney** [comment]
Yes, non-stored computed columns are syntactic sugar.  However, they do add a layer of abstraction that can be valued in production environments.  
- Allows writing a complex transform 1 time, used consistently for all queries.
- Potential use for data obfuscation.  (last 4 digits of an identifier).
- Some BI tools may prefer column references rather than generating functions. 

These are view-like behaviors, but some prefer using views to hide join abstraction and want to minimize view nesting. 

The highest value of stored computed columns when 1) significant work can be avoided and 2) the dbms ensures consistency for you.

For DuckDB, the cost of  "work to be avoided" may be smaller than expected.
Without the dbms ensuring consistency there are other ways to achieve similar results.  The admin can manually add real columns, and update on desired frequency.   Theoretically possible to hide the column from DDL with a view <maybe>.

**Comment by willium** [comment]
> Perhaps one solution would be to allow DEFAULT columns to use other columns from the table, as long as there are no circular references (i.e. x DEFAULT y, y DEFAULT x is not allowed)

Would love to see this half measure and possibly some way to allow for “caching” the non stored column to avoid expensive computation when we know the data is stable?

**Comment by willium** [comment]
reactive cells would be nice (stored calculated columns), but as a half measure, could something be added that lets you in one step map over all rows and add a new column to each row?
1. Alter myTable to add a new Column _B_
2. Select A from myTable
3. For Each A, B = Expr(A)
?
It doesn't need to be reactive to updates (we can fix B values manually on updates) or inserts (sure the default thing would be nice, but not required)

**Comment by Mytherin** [comment]
That sounds like the default expression solution that I described above:

> Perhaps one solution would be to allow DEFAULT columns to use other columns from the table, as long as there are no circular references (i.e. x DEFAULT y, y DEFAULT x is not allowed). Then on an insert the value of the default columns can be computed using the other values. That would allow "sort of" this functionality, as long as there are no updates to the other columns.

Currently you can already do this:

```sql
ALTER TABLE test ADD COLUMN new_col INTEGER DEFAULT 3
```

Which creates a column and fills it with the value "3" (instead of NULL - the "default default"). But you cannot yet use other columns in the default expression. Making this change would allow you to do e.g. this:

```sql
ALTER TABLE test ADD COLUMN new_col INTEGER DEFAULT old_col1 * old_col2;
```

Which would create a new column filled with the result of the expression.

I will work on adding this later, but not until after the holidays.

**Comment by krlmlr** [comment]
Are you also considering support for updating a table with data from a different table? See `rows_update()` in https://dplyr.tidyverse.org/reference/rows.html and https://krlmlr.github.io/dm/reference/rows-dm.html .

**Comment by Mytherin** [comment]
You can do this using the UPDATE...FROM syntax. See [here](https://github.com/duckdb/duckdb/blob/master/test/sql/update/test_update_from.test) for some examples.

**Comment by Mytherin** [comment]
CC @Tishj

**Comment by Alex-Monahan** [comment]
In case it's easier this way, it looks like SQLAlchemy primary keys could be supported using a `GENERATED BY DEFAULT AS IDENTITY` syntax instead of the SERIAL column type. Maybe this could be a two-birds-one-stone situation!
https://docs.sqlalchemy.org/en/14/dialects/postgresql.html#postgresql-10-and-above-identity-columns

**Comment by Tishj** [comment]
I believe `GENERATED BY DEFAULT AS IDENTITY` differs from generated columns in that it uses physical storage, it uses a `SEQUENCE` internally, and it allows supplying a value through an `INSERT` or `UPDATE` to override this generated value.

Whereas a (generated column)`GENERATED ALWAYS AS (<expression>) VIRTUAL` doesn't use physical storage, doesn't allow supplying a value directly through `INSERT` or `UPDATE` and runs this stored expression whenever the column is referenced in a query.

**Comment by mzy2240** [comment]
> ```sql
> ALTER TABLE test ADD COLUMN new_col INTEGER DEFAULT old_col1 * old_col2;
> ```

I know I should not add any comments to a closed issue, but just wondering has the above syntax been implemented? Try to do the same thing but saw this error `Binder Error: DEFAULT value cannot contain column names`

**Comment by adrianog** [comment]
> > ALTER TABLE test ADD COLUMN new_col INTEGER DEFAULT old_col1 * old_col2;
> 
> I know I should not add any comments to a closed issue, but just wondering has the above syntax been implemented? Tried to follow the same syntax but encountered this error `Binder Error: DEFAULT value cannot contain column names`

Did you ever find out?
