### ISSUE TITLE
Joining 3 arrow tables

### ISSUE THREAD

**Issue by joetl** [duckdb/duckdb#1189]
If I have 3 pandas dataframes I can register 3 dataframes and can write execute sql to join all 3 tables and thinking of how to do the same with arrow table.
Example for pandas
db= duckdb.connect(database=":memory:")
db.register("a",dataframe_a)
db.register("b",dataframe_b)
db.register("c",dataframe_c)
db.execute("select * from a inner join b on a.col1=b.col1 inner join c on b.col2=c.col1").arrow()

I see duckdb.from_arrow_table but it seems Ilike standalone table unlike  pandas dataframe

**Comment by Mytherin** [comment]
The function `duckdb.from_arrow_table` returns a relation. Any relation can be turned into a view by using the `create_view` method. The Pandas `register` method is only shorthand for `db.from_df(df).create_view('a')`. For an arrow table you can use the following syntax to create a view:

```python
db.from_arrow_table(tbl).create_view('a')
```

You can then use the view in any queries.

The arrow support is still somewhat new so let us know if you run into any issues.

**Comment by akokkonidis** [comment]
Hi, many thanks for the very nice project!
Related to the above issue

df_new is an arrow table
`con.from_arrow_table(df_new).create_view('df_duckview2')`
returns -Expression Tree-, -Result Columns- -Result Preview- all good!

```
con.execute("PRAGMA show_tables")
```
Returns RuntimeError: Not implemented Error: Cannot convert VIEW to SQL because it was not created with a SQL statement

```
con.execute("SELECT count(*) FROM df_duckview2")
print(con.fetchall())
```

returns 0 even though the df2 contains data
Also the next time I try to re-run I get:
RuntimeError: Invalid Input Error: arrow_scan: get_schema failed(): stream was released

```
con.execute("PRAGMA table_info('df_duckview2')")
print(con.fetchall())

```
returns the correct schema

_____________________________________________
pyarrow = 3.0.0
duckdb = 0.2.4

Let me know if you need any further info.
Many thanks again!
