### ISSUE TITLE
Convert Column Type Failed

### ISSUE THREAD

**Issue by coloraven** [duckdb/duckdb#11939]
### What happens?

The `phone` column in the `test` table contains the following data: ["123949", "sdkkd", "ppd23f", "56565652"]. I'm trying to delete the records that are not purely numeric and then convert the column to the `BIGINT` type. Here are the steps I followed:

1.  First, I used `DELETE FROM test WHERE NOT regexp_matches(phone, '^\d{1,}$');` to delete the non-numeric records.
2.  Then I used `SELECT * FROM test;` to check the results after the deletion, and I can only see only the numbers remaining.
3.  Finally, I used `ALTER TABLE test ALTER phone TYPE BIGINT;` try to convert the column type to `BIGINT`. However, I received an error message: `Conversion Error: Could not convert string 'sdkkd' to INT64.`

At first, I thought the DELETE operation didn't fully take effect, but even after disconnecting and reconnecting the data, the same error still occurred.

I'm not sure what the problem is.

### To Reproduce

```sql
CREATE TABLE test (
  phone VARCHAR(10)
);

INSERT INTO test (phone) VALUES
  ('123949'),
  ('sdkkd'),
  ('ppd23f'),
  ('56565652');

-- To delete the non-numeric records
DELETE FROM test WHERE NOT regexp_matches(phone, '^\d{1,}$');

-- To check the results
SELECT * FROM test;

-- Try to convert the column type to `BIGINT`
ALTER TABLE test ALTER phone TYPE BIGINT;
-- SQL error: Conversion Error: Could not convert string 'sdkkd' to INT64
```

### OS:

WIN_x64

### DuckDB Version:

v0.10.2

### DuckDB Client:

DBEAVER

### Full Name:

john

### Affiliation:

ignore

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by cmdlineluser** [comment]
I am not sure what the problem is - but I did notice that this avoids the error:

```sql
ALTER TABLE test ALTER phone TYPE BIGINT USING try_cast(phone as BIGINT)
```

**Comment by Tishj** [comment]
I suspect running a CHECKPOINT after the delete, before the alter, fixes the issue (as a temporary workaround)

**Comment by rommelDB** [comment]
Hi,

As is usual in some database systems, the DELETE statement doesn't remove the rows [immediately](https://duckdb.org/docs/sql/statements/delete). You may try to force the removing of the rows with commands like CHECKPOINT, but, in DuckDB, that command does not work for [in-memory](https://duckdb.org/docs/sql/statements/checkpoint.html) databases.

The reason why the query from @cmdlineluser works seems to be that the expression `USING try_cast(phone as BIGINT)` creates [another object column](https://github.com/duckdb/duckdb/blob/main/src/catalog/catalog_entry/duck_table_entry.cpp#L698) with the BIGINT datatype omitting the non-deleted non-number strings (no-throw effect from try_cast).

I don't know another way to force the removing of the deleted elements for in-memory databases, but I found that in order to cast the column without any error, we might wrap at least the INSERT and the DELETE up in a transaction:
``` sql
CREATE TABLE test ( phone VARCHAR(10) );

BEGIN TRANSACTION;
INSERT INTO test (phone) VALUES   ('123949'),   ('sdkkd'),   ('ppd23f'),   ('56565652');
DELETE FROM test WHERE NOT regexp_matches(phone, '^\d{1,}$');
COMMIT;

ALTER TABLE test ALTER phone TYPE BIGINT;
SELECT * FROM test;
```

**Comment by blacelle** [comment]
An alternative is to write some marker compatible with the target type before the removal:

```
DROP TABLE int_as_varchar;
CREATE TABLE int_as_varchar (v VARCHAR);
DESCRIBE TABLE int_as_varchar;
INSERT INTO int_as_varchar (v) values ('123');
INSERT INTO int_as_varchar (v) values ('456a');
UPDATE int_as_varchar SET v = '-1' WHERE  NOT regexp_full_match(v, '\d+');
DELETE FROM int_as_varchar  WHERE  NOT regexp_full_match(v, '\d+') OR v = -1 ;
ALTER TABLE int_as_varchar ALTER v TYPE int;
DESCRIBE TABLE int_as_varchar;
select * from int_as_varchar;
```
