### ISSUE TITLE
Spill files to disk works?

### ISSUE THREAD

**Issue by akkishore** [duckdb/duckdb#1218]
I have been trying run a large join of two parquet files of around 20 GB each. The RAM starts filling up and after a long time the following error shows: `Error: Not enough memory to complete operation!`. All this time I dont see any usage of db.tmp files.

Are only RAM sized operations supported or duckdb support operations spilling to disk?

**Comment by Mytherin** [comment]
DuckDB in general supports spilling to disk, but we don't support spilling joins yet, which means at least the smallest side of the join has to fit in memory for the join to work properly. If you are joining two tables that are larger than memory, the system will build a hash table on one of the sides, which will not fit in memory anymore and lead to the following error.

As a work-around you can raise the memory limit of the system (e.g. `PRAGMA memory_limit='100GB'`) which will allow the system to allocate beyond your RAM. You can then enable RAM spilling on your system which should allow the join to spill to disk.

Note that this will not be fast, since hash joins are optimized for RAM. They involve a lot of random access, which will be extremely slow if the random access means reading random pages on disk. To properly solve this we need to implement a disk-spilled merge join and fallback to that implementation when the HT fits in memory.

**Comment by hannes** [comment]
This is more of a question than an issue, we are also actively working on making operators capable of spilling to disk.

**Comment by BsoBird** [comment]
@Mytherin 
Sir, does the COPY TO... Option support SPILL?
