### ISSUE TITLE
Entry type not supported in PhysicalCopyDatabase

### ISSUE THREAD

**Issue by exolab** [duckdb/duckdb#12329]
### What happens?

When copying from a Posgres DB to DuckDB, I get an internal error.

```sql
ATTACH 'dbname=foo_bar user=foo password=bar host=foo.bar.io' AS db (TYPE POSTGRES, READ_ONLY);
ATTACH 'duck.db' AS duck;   
COPY FROM DATABASE db TO duck;
INTERNAL Error: Entry type not supported in PhysicalCopyDatabase
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
```

Since I have no idea where that error is happening, it is hard for me to provide more information.

### To Reproduce

Attach a Postgres DB.
Attach a DuckDB DB.
Copy from Postgres to Duck.

### OS:

Ubuntu 22.04 LTS on x64

### DuckDB Version:

v0.10.3

### DuckDB Client:

CLI

### Full Name:

Toby

### Affiliation:

MMT

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
This is likely solved by latest nightly, could you try that?

See the instructions here: https://duckdb.org/docs/installation/index?version=main&environment=cli&platform=linux&download_method=package_manager

**Comment by carlopi** [comment]
Actually, the relevant PR is here: https://github.com/duckdb/duckdb/pull/12264, that moves this from a crash to a NotImplementedException (given the operation can safely error out, and internal logic is not broken).

The problem is possibly connected to indexes that are currently not handle by COPY FROM DATABASES.

**Comment by exolab** [comment]
I can confirm that the nightly build returns ```Not implemented Error: Entry type Index not supported in PhysicalCopyDatabase```.

**Comment by Flogex** [comment]
In DuckDB v0.10.2, indexes were silently skipped when a database was copied, but this changed to an internal error being thrown in v0.10.3. I must say I like the old behavior better because now it is not possible at all to copy a database that contains an index. Or am I missing something and there is a trick to do this?

**Comment by carlopi** [comment]
@Flogex: if you were to be an evil duck you could do something like:

```
carlo@ScroogeMcDuck duckdb % duckdb with_index.db           
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
D BEGIN;
D DROP INDEX idx;
D EXPORT DATABASE 'some_folder';
D 
carlo@ScroogeMcDuck duckdb % duckdb no_indexes.db
v1.0.0 1f98600c2c
Enter ".help" for usage hints.
D IMPORT DATABASE 'some_folder';
D 
```
(do NOT commit that transaction!)

**Comment by serdardidan** [comment]
The same problem occurs when copying the SQLite database containing a index to DuckDB. DuckDB version v1.0.0
