### ISSUE TITLE
`SET home_directory` doesn't do anything 

### ISSUE THREAD

**Issue by rebasedming** [duckdb/duckdb#12837]
### What happens?

Setting the `home_directory` config when no `HOME` env variable is set doesn't do anything.

### To Reproduce

Using the duckDB CLI on macOS:

1. Unset the HOME env var
```bash
unset HOME
```

2. Start the DuckDB CLI and try querying an S3 Parquet file. (The following Parquet file is public and should work).
```sql
SELECT * FROM read_parquet('s3://paradedb-benchmarks/yellow_tripdata_2024-01.parquet') LIMIT 1;
```
```
Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'httpfs':
Can't find the home directory at ''
Specify a home directory using the SET home_directory='/path/to/dir' option.
```

3. Try setting `home_directory` and run the same command, you'll get the same error.
```sql
SET home_directory = '/tmp';
SELECT * FROM read_parquet('s3://paradedb-benchmarks/yellow_tripdata_2024-01.parquet') limit 1;
```
```
Extension Autoloading Error: An error occurred while trying to automatically install the required extension 'httpfs':
Can't find the home directory at ''
Specify a home directory using the SET home_directory='/path/to/dir' option.
```

### OS:

macOS M2

### DuckDB Version:

1.0.0

### DuckDB Client:

CLI

### Full Name:

Ming Ying

### Affiliation:

ParadeDB

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment]
Thanks for raising this. We will take a look at the logic here.

For now I can offer a workaround that I would suggest for this case:

```sql
SET secret_directory='path/to/my_secrets_dir';
SET extension_directory='path/to/my_extension_dir';
```
Those can be set either to relative or absolute path, folders will be created if not existing.
I do recommend pointing those to `absolute` paths, since paths are saved as-is, and changing the current directory (e.g.: via the `.cd subfolder` CLI command) will change meaning of those relative paths.

Once those are SET, both extension load/install and secret creation/querying will happens from the pointed folders.

Setting those might make sense even in cases where HOME is well defined, to allow more control over where duckdb files are created.

---

There might be other cases where a missing HOME directory will cause problems, we will need to do a review and probably add a CI run with those disabled to caught them in the future.

**Comment by szarnyasg** [comment]
This was clarified in the docs via https://github.com/duckdb/duckdb-web/pull/3462
