### ISSUE TITLE
Bulk insertion happy path

### ISSUE THREAD

**Issue by willium** [duckdb/duckdb#1293]
Insertion has become an extreme bottleneck for us, despite buffering and wrapping insertions in a transaction. I understand bulk insertion with `INSERT` statements is heavily discouraged, but it's not abundantly clear what the best alternative is for loading data into DuckDB from non-CSV, non-Parquet sources—short of using C++ Appender directly. Have any alternatives been explored? Does it make sense to prioritize more file reader types into those provided by DuckDB (e.g. a `read_arrow` or `arrow_scan`, and a `read_json`)? Or am I missing a happy path that hasn't been documented yet?

**Comment by willium** [comment]
Does it make sense to convert other datatypes (e.g. JSON array of objects) to a CSV or Parquet file as an intermediate step? It seems like it'd be better to natively support reading other types or provide an alternative API rather than make more IO round-trips

**Comment by Mytherin** [comment]
It would help if you could be more specific on which API specifically you are targeting, and what format your is data stored in. If it is stored in simple in-memory structures, perhaps exposing the Appender to that API would solve the problem (there is no logistic reason that this is limited to the C++ API, after all).

If it is stored in another file format, note that anything that DuckDB can scan can be inserted efficiently into a table using an insert statement (e.g. `INSERT INTO tbl SELECT * FROM arrow_scan(...)`). If it is stored in json files, for example, you could convert that data to another format that is supported by DuckDB natively as an additional "hop", e.g. `json -> arrow -> DuckDB`, or `json -> in-memory -> DuckDB appender`.

We will add a `read_json` at some point for sure, but we prefer to do this right rather than fast (including supporting e.g. nested types and optional fields), so this will not be there for some time at least.

**Comment by willium** [comment]
Ah! Is arrow_scan documented somewhere? Hadn't realized it exists at all. A little unclear on the syntactical difference between read_* and *_scan as well-I'll dig into the cpp, but if you have a recommendation of where to look, that would be great

**Comment by willium** [comment]
We're trying to allow our users to import a range of file types including JSON and even Excel. It's sensible to load them into memory using JavaScript, but then the write cost into DuckDb is massively slow (begin; insert a chunk; commit). We're considering the "hop" you mentioned using parquet (or I suppose arrow) as an intermediate filetype, but it's surprising to me that insertion performance is slow enough that doing an extra disk write for conversion would end up being faster.

**Comment by willium** [comment]
It seems the DuckDb appender is ultimately the best solution, but accessing it via C++ is ergonomically tedious given write locks and juggling multiple connections to a single database. Is there any path towards exposing the appender beyond C++?

**Comment by Mytherin** [comment]
> Ah! Is arrow_scan documented somewhere? Hadn't realized it exists at all. A little unclear on the syntactical difference between read_* and *_scan as well-I'll dig into the cpp, but if you have a recommendation of where to look, that would be great

There is no difference besides name, scan and read are the same (they are aliases). Not sure about documentation; afaik it is only exposed in the Python API currently.

> We're trying to allow our users to import a range of file types including JSON and even Excel. It's sensible to load them into memory using JavaScript, but then the write cost into DuckDb is massively slow (begin; insert a chunk; commit). We're considering the "hop" you mentioned using parquet (or I suppose arrow) as an intermediate filetype, but it's surprising to me that insertion performance is slow enough that doing an extra disk write for conversion would end up being faster.

You can try using prepared statements, that should speed it up somewhat, but in general this path is not optimized and should be avoided if you want fast performance, as you have noticed as well :)

> It seems the DuckDb appender is ultimately the best solution, but accessing it via C++ in a non C++ application is ergonomically tedious given write locks the need to juggle multiple connections to a single database. Is there any path towards exposing the appender beyond C++?

Indeed that seems to be the best solution. I think wrapping the Appender in a different API is fairly straightforward, it just a matter of actually implementing it and doing any appropriate conversions that need to be performed.

**Comment by willium** [comment]
> > Ah! Is arrow_scan documented somewhere? Hadn't realized it exists at all. A little unclear on the syntactical difference between read_* and *_scan as well-I'll dig into the cpp, but if you have a recommendation of where to look, that would be great
> 
> There is no difference besides name, scan and read are the same (they are aliases). Not sure about documentation; afaik it is only exposed in the Python API currently.
> 
> > We're trying to allow our users to import a range of file types including JSON and even Excel. It's sensible to load them into memory using JavaScript, but then the write cost into DuckDb is massively slow (begin; insert a chunk; commit). We're considering the "hop" you mentioned using parquet (or I suppose arrow) as an intermediate filetype, but it's surprising to me that insertion performance is slow enough that doing an extra disk write for conversion would end up being faster.
> 
> You can try using prepared statements, that should speed it up somewhat, but in general this path is not optimized and should be avoided if you want fast performance, as you have noticed as well :)
> 
> > It seems the DuckDb appender is ultimately the best solution, but accessing it via C++ in a non C++ application is ergonomically tedious given write locks the need to juggle multiple connections to a single database. Is there any path towards exposing the appender beyond C++?
> 
> Indeed that seems to be the best solution. I think wrapping the Appender in a different API is fairly straightforward, it just a matter of actually implementing it and doing any appropriate conversions that need to be performed.

**Comment by willium** [comment]
> If it is stored in another file format, note that anything that DuckDB can scan can be inserted efficiently into a table using an insert statement (e.g. `INSERT INTO tbl SELECT * FROM arrow_scan(...)`). If it is stored in json files, for example, you could convert that data to another format that is supported by DuckDB natively as an additional "hop", e.g. `json -> arrow -> DuckDB`, or `json -> in-memory -> DuckDB appender`.

Gave `arrow_scan` a try:
```sql
CREATE TABLE flights200 AS SELECT * FROM arrow_scan('./flights-200k.arrow');

Error: Binder Error: No function matches the given name and argument types 'arrow_scan(VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	arrow_scan(POINTER)

LINE 1: ...EATE TABLE flights200 AS SELECT * FROM arrow_scan('./flights-200k.arrow');
```

**Comment by Baoqi** [comment]
Just want to share our usage, this may related with your usage case. We also have lots of different datasources (files, jdbc, web services) to process, and then do some processing on those raw data, finally, the formatted data will write to data warehouse. we selected "parquet" file & duckdb for this work. 

1. The "Source" Stages: for different input data sources, we make each generate a parquet file for its result (so that we can stream the data into file, to avoid out of memory), and we can also use Plugin System to make them isolate with core tool. 

2. The "Transform" Stages: Then, since we have different parquet files, we register views for each parquet file, like " create view view_name as scan_parquet('your_parquet')",   Then, we can do lots of processing by use duckdb's  sql.    Since currently duckdb don't support JSON well, no problem, we can use "jq" tool to define some rules to generate new columns in duckdb. Also, Python pandas has several good libraries to process data, we also support user to write custom Python script to do processing, just when python script finish, we first register the generated df into duckdb, then create a physical table to save those data into duckdb.  

3. Finally "Sink" Stages, that can read the duckdb's resultset line by line, and then write those records to different warehouse 

Then, we just write some config files (like yaml), to describe the steps by combining those stages, and the command tool will execute them one stage by one stage.

So, I think picking Parquet as a common file format may be a good solution (we also tried avro, or arrow, but seems parquet file size is the smallest, and parquet column name can contains most special characters) (CSV is not good choice, because it lost the data type information).

**Comment by Mytherin** [comment]
> > If it is stored in another file format, note that anything that DuckDB can scan can be inserted efficiently into a table using an insert statement (e.g. `INSERT INTO tbl SELECT * FROM arrow_scan(...)`). If it is stored in json files, for example, you could convert that data to another format that is supported by DuckDB natively as an additional "hop", e.g. `json -> arrow -> DuckDB`, or `json -> in-memory -> DuckDB appender`.
> 
> Gave `arrow_scan` a try:
> 
> ```sql
> CREATE TABLE flights200 AS SELECT * FROM arrow_scan('./flights-200k.arrow');
> 
> Error: Binder Error: No function matches the given name and argument types 'arrow_scan(VARCHAR)'. You might need to add explicit type casts.
> 	Candidate functions:
> 	arrow_scan(POINTER)
> 
> LINE 1: ...EATE TABLE flights200 AS SELECT * FROM arrow_scan('./flights-200k.arrow');
> ```
> 
> How do I go about covering the file into a pointer without using Python?

The arrow scan doesn't read files from disk, but rather in-memory arrow arrays. The pointer is an in-memory pointer to an existing arrow array. The arrow_scan function cannot be used from SQL directly for this reason, but only from within an API that supports it (which currently is only the Python API).

**Comment by willium** [comment]
In the meantime, we found that doing all the insertions in one statement was orders of magnitude faster, which hadn't occurred to us as being supported by DuckDB :)
