### ISSUE TITLE
Arrow_scan: Support of Dictionary Vectors

### ISSUE THREAD

**Issue by akokkonidis** [duckdb/duckdb#1375]
A table with dictionary-encoded columns  from pyarrow seems not to be supported at the moment. 
Reading directly from parquet works fine. A user could cast to primitive types in pyarrow before registering the the pyarrow Table in duckdb.

`rel2=duckdb.from_arrow_table(df)`
RuntimeError: Not implemented Error: arrow_scan: dictionary vectors not supported yet

python 3.7
duckdb=0.2.4
pyarrow=3.0.0

I fully understand the message that this is not supported yet, just opening the issue for tractability/user interest.

Many thanks!

**Comment by pdet** [comment]
One problem with integrating the dictionary vectors, is that both indexes and the dictionary data can be null.
The dictionary data being null is fine, but what is the desired effect when an index is null? (We ignore the existence of the data or is the data point then null?)

If the data point is then null, this will be quite messy to implement, because then I must insert a new null element, go over the selection vector of the indexes, and if null then actually point to the null element I've inserted.

Right now, I'm checking if this index vector has nulls and if yes just throwing an implementation error, but I'm happy to hear what @hannesmuehleisen thinks of this.

@akokkonidis is this also something that exists in your use case?

**Comment by akokkonidis** [comment]
Hi, 

usually my dictionary encoded columns stem form Parquet files were the column has the type: 

variable_id: dictionary<values=string, indices=int32, ordered=0>
  -- field metadata --
  PARQUET:field_id: '4'

typically columns containing strings with low cardinality.

my naive understanding is that when the index is null the datapoint is null. Not sure how you can create a null value in the dictionary.
 
See for example my naive example:

`df=pyarrow.Table.from_pydict({'Name':['Alex','David', 'Mario'],'Age':[40,40,None]})`
`df['Age']`
`df['Age'].dictionary_encode()`
```
<pyarrow.lib.ChunkedArray object at 0x00000285618695E8>
[

  -- dictionary:
    [
      40
    ]
  -- indices:
    [
      0,
      0,
      null
    ]
]
```
https://arrow.apache.org/docs/cpp/api/array.html?highlight=dictionaryarray#_CPPv4N5arrow15DictionaryArrayE

Does this help at all?

**Comment by pdet** [comment]
@akokkonidis this was helpful!

I just merged an implementation for that, let me know if you face any issues!
