### ISSUE TITLE
Boolean implicitly cast to integer in list literal

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#13847]
### What happens?

```sql
SELECT [0, true]
```
works and creates `[0, 1]` but should fail according to the casting matrix in the documentation.

Probably related to https://github.com/duckdb/duckdb/issues/11958 but creating new issue since that one has been open for a while and maybe the list behavior is considered more severe. 

### To Reproduce

-

### OS:

x64

### DuckDB Version:

1.1

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Maxxen** [comment]
I think this might be intended. Since the `[x,y,z]` syntax is actually just sugar or `list_value` which is a generic variadic function, all the input argument types are compared in the bind phase and if they differ, the list element type is inferred as the "maximum logical type" of each argument type, and casts are inserted accordingly. Now I agree that this is inconsistent with the cast matrix, and maybe our type inference should be stricter, but Im pretty sure there are a lot of other functions with more than 1 generic parameter that currently work the same way by coalescing different types into their closest common ancestor in the cast hierarchy, so to speak.

**Comment by soerenwolfers** [comment]
Isn't all of that just the point of "implicit cast"?
Are you arguing that there are (and should be) really three levels of cast: explicit, implicit, rare-implicit?

**Comment by Mytherin** [comment]
There's indeed two sets of implicit cast rules - those used by function overloads, and those used by comparisons, set operations and operations like `list_value` where types are "combined". The combining rules are more lenient than the function overloads - partially because we don't necessarily need to go to one of the two types. For example, we can combine/compare an `INT64` and a `UINT64`, despite neither of these being implicitly castable to one another, and they combine into an `INT128` instead:

```sql
D select [1::bigint, 1::ubigint] AS result;
┌──────────┐
│  result  │
│ int128[] │
├──────────┤
│ [1, 1]   │
└──────────┘
```

Similarly, boolean types can be combined/compared with integer types which is what you are seeing here.

The difference between combining types and what happens with function overloads is that we don't necessarily need to end up with either of the two input types.

**Comment by soerenwolfers** [comment]
Actually, unless I don't get it yet, even if you think this is expected behavior, it's sufficiently "surprising" that I think there should be a setting to opt out. I wouldn't want an implicit BOOL to INT cast anymore than an implicit TIMESTAMP to DATE cast, even in things like `list_value`.
