### ISSUE TITLE
FTS ignore regex to include single quote

### ISSUE THREAD

**Issue by brandantck** [duckdb/duckdb#13866]
### What happens?

When trying to create a duckdb FTS index with single quotes included in the search regex, the following error occurs
```
con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore='(\\.|[^a-z0-9'])+')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "]"
```

### To Reproduce

```
import duckdb
con = duckdb.connect("tester.db")
con.execute("CREATE TABLE my_table AS SELECT 1 AS CustomerId, 'hans' as CustomerName")

# FTS Index creation to include search for lowercase alphanumeric characters and single quotes
con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore='(\\.|[^a-z0-9'])+')")

# Trying to escape the single quotes as well does not seem to work with PRAGMA
# Escape with single `\`
con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore='(\\.|[^a-z0-9\'])+')")
# Escape with double `\`
con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore='(\\.|[^a-z0-9\\'])+')")
```

### OS:

Ubuntu 24.04.1 LTS

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Brandan

### Affiliation:

NIL

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment]
`'` -> `''`

You have to escape the single quote, and to do that in SQL you need to double the single quote

**Comment by lnkuiper** [comment]
Indeed, as @Tishj says, in SQL, the way we escape single quotes is by doing a double single quote:
```sql
D select '''';
┌─────────┐
│  ''''   │
│ varchar │
├─────────┤
│ '       │
└─────────┘
```
You can also use the double-dollar quotes to avoid the single quote issue:
```sql
D select $$'$$;
┌─────────┐
│  ''''   │
│ varchar │
├─────────┤
│ '       │
└─────────┘
```

**Comment by brandantck** [comment]
I think in this case the create_fts_index PRAGMA's `ignore` parameter takes in the regex as a string wrapped in single quotes. So any single quotes in the regex itself will in a way prematurely end the input regex string. As i tried your suggestions.

Doubling up single quote
```
con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore='(\\.|[^a-z0-9''])+')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.ParserException: Parser Error: syntax error at or near "]"
```

Adding double-dollar
```
con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore='(\\.|[^a-z0-9$$'$$])+')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.ParserException: Parser Error: unterminated dollar-quoted string at or near "$$])+')"
```

**Comment by arjenpdevries** [comment]
When I try something very similar in the DuckDB CLI, there are no problems:

```~SQL
D create or replace macro s(t := 'hoi') as t;
D select s(t:='(\\.|[^a-z0-9''])+');
┌──────────────────────────────┐
│ s(t := '(\\.|[^a-z0-9''])+') │
│           varchar            │
├──────────────────────────────┤
│ (\\.|[^a-z0-9'])+            │
└──────────────────────────────┘
```

I was curious if the problem was perhaps caused by macro parameter processing, but no, fortunately.
Then I thought it must be the Python API.
However:

```~python
>>> con = duckdb.connect("tester.db")
>>> con.sql("create or replace macro s(t := 'hoi') as t;")
>>> con.sql("select s();")
┌─────────┐
│   s()   │
│ varchar │
├─────────┤
│ hoi     │
└─────────┘

>>> con.sql("select s(t:='(\\.|[^a-z0-9''])+');")
┌─────────────────────────────┐
│ s(t := '(\.|[^a-z0-9''])+') │
│           varchar           │
├─────────────────────────────┤
│ (\.|[^a-z0-9'])+            │
└─────────────────────────────┘
```

And, no difference for using `.execute().fetchone()` instead of `.sql()`, all works well.

I did however get the same error as reported by @brandantck for his example.
But...

If I adapt the most recent example to read:

```~python
>>> con.execute("PRAGMA create_fts_index(my_table, 'CustomerId', 'CustomerName', ignore = '(\\.|[^a-z0-9''''])+', overwrite = 1)");
<duckdb.duckdb.DuckDBPyConnection object at 0x7ffb173b5570>
```

I think it is the interaction between Python parsing and SQL parsing, but did not look into it in great detail.
Can you maybe just check if this version would deliver the result you expected, @brandantck ?

(I have been using versions 0.10.0 or 1.1.0.)

**Comment by lnkuiper** [comment]
In the initial issue, the problem was not doubling up the quotes, which caused a `ParserException` on the initial `PRAGMA` statement. However, once the quotes were doubled, a `ParserException` was triggered later on, when the index was actually being built (which is built fully using SQL statements, where the quote needed to be escaped _again_). I've opened a PR that fixes this.
