### ISSUE TITLE
asof join's result is incorrect in v1.1.0  when add filter for right table on join condition

### ISSUE THREAD

**Issue by de1tran** [duckdb/duckdb#13899]
### What happens?

asof join's result is incorrect in v1.1.0  when add filter for right table on join condition

### To Reproduce

data prepare
```sql
create table t1(seq_no int,amount decimal(10,2));
insert into t1
values
(1,1.00),(2,null),(3,null),(4,null),(5,2.00),
(6,null),(7,null),(8,3.00),(9,null),(10,null),(11,5.00);
```

diff results between v1.1.0 and v1.0.0 when query as below
```sql
select * from t1;
select a.seq_no,a.amount,b.amount
  from t1 as a 
  asof join t1 as b
    on a.seq_no>=b.seq_no
   and b.amount is not null;
```
expect result:
|seq_no|amount|amount|
|---|---|---|
|1|1.00|1.00|
|2||1.00|
|3||1.00|
|4||1.00|
|5|2.00|2.00|
|6||2.00|
|7||2.00|
|8|3.00|3.00|
|9||3.00|
|10||3.00|
|11|5.00|5.00|

result in v1.1.0
|seq_no|amount|amount|
|---|---|---|
|1|1.00|1.00|
|5|2.00|2.00|
|8|3.00|3.00|
|11|5.00|5.00|

change right table with filter to sub-query.results between v1.1.0 and v1.0.0 are the same.

```sql
select a.seq_no,a.amount,b.amount
  from t1 as a
  asof join (select seq_no,amount
               from t1
              where amount is not null
            ) as b
    on a.seq_no>=b.seq_no;
```
result:
|seq_no|amount|amount|
|---|---|---|
|1|1.00|1.00|
|2||1.00|
|3||1.00|
|4||1.00|
|5|2|2.00|
|6||2.00|
|7||2.00|
|8|3|3.00|
|9||3.00|
|10||3.00|
|11|5|5.00|

v1.0.0 screenshot
![17261262705990](https://github.com/user-attachments/assets/7e6d4921-ed2e-4a2a-8a4e-27f290332383)
v1.1.0 screenshot
![17261261624687](https://github.com/user-attachments/assets/5fee500e-068d-4ebc-816a-a17a79c88b54)

### OS:

windows10 x86_64

### DuckDB Version:

1.1.0

### DuckDB Client:

cli

### Full Name:

detran

### Affiliation:

sunline

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by hawkfish** [comment]
Thanks for the report.  I have a "fix" but I am no longer convinced the behaviour is incorrect. 

The change was introduced because of #12412 where a predicate was incorrectly pushed into the RHS. My feeling then was that since `ASOF` is more a table lookup than a join, users should be explicit about constructing that table and not rely on the optimiser to accidentally fix it for them.  We even have tests like the sub-query variant you provide showing how this should be done.

I have compared with another system and their result has all the LHS rows (like we used to), but fills in `0` for the `NULL`s, which seems incorrect to me. Since this is not standard SQL, I think this may end up as "not a bug". But I will check with the rest of the team tomorrow.

**Comment by hawkfish** [comment]
(BTW, if you use `.mode markdown` in the CLI, you can just paste the output directly into the report as text instead of having to create a screen shot.)

**Comment by soerenwolfers** [comment]
If it's decided that users should only stick equality comparisons (or any expression that involve both tables?) into ASOF JOINS,  could that be enforced by an error, please?

---

FWIW, I'm firmly in the "1.1 has a bug" camp, unless I misunderstood something: 

In 1.0, the SQL

```sql
SELECT X, Y FROM X ASOF JOIN Y ON Y.a <= Y.a AND f(X, Y)
```
was interpreted in mathematical language very straightforwardly as
```
{(x, y): x in X AND y in Y AND y = argmax_{y' in Y : y'.a <= x.a AND f(x, y')} y'.a}
```
(up to bags vs sets) regardless of what type of expression `f` was. 

In 1.1, I couldn't come up with a set notation that covers both `X.b = Y.b` and `Y.b is not NULL` without explicitly casing on the type of `f`.

If a filter on the result of the JOIN was desired, that could just be achieved with a regular subsequent WHERE clause instead of an AND in the ON clause. 

I think this should therefore be celebrated as an opportunity where the ON preferred by modern SQL JOINS actually is required because it applies more directly to the join than a subsequent WHERE.

**Comment by hawkfish** [comment]
We are considering another approach. But it may take longer.
