### ISSUE TITLE
POSITIONAL JOIN failure

### ISSUE THREAD

**Issue by pkoppstein** [duckdb/duckdb#13945]
### What happens?

Consider the following setup:
```sql
CREATE TABLE aa AS VALUES ({'a':1});
```
According to the docs, 'SELECT * from t1 POSITIONAL JOIN t2;' is valid.
It seems to follow that the following should be valid:
```sql
SELECT row_number() OVER () FROM aa POSITIONAL JOIN aa;
```
But it gives an error:

Binder Error: Duplicate alias "aa" in query!

~~Just as mysterious is that the query:~~

For comparison, note that
```sql
SELECT row_number() OVER () FROM aa POSITIONAL JOIN (FROM aa);
```

```
┌──────────────────────┐
│ row_number() OVER () │
│        int64         │
├──────────────────────┤
│                    1 │
└──────────────────────┘
```

~~So it would seem there are two separate errors here....~~

### To Reproduce

```sql
CREATE TABLE aa AS VALUES ({'a':1});
SELECT row_number() OVER () FROM aa POSITIONAL JOIN aa;
SELECT row_number() OVER () FROM aa POSITIONAL JOIN (FROM aa);
```

### OS:

MacOS

### DuckDB Version:

v1.0.0 v1.1.0 fa5c2fe

### DuckDB Client:

CLI

### Full Name:

Peter Koppstein

### Affiliation:

Princeton University

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment]
The first problem has nothing to do with window functions or positional joins. You need to give an alias to one side, e.g., `SELECT * FROM df JOIN df df2`.

The second problem is also expected behavior: You're asking for a single column and getting a single column.

**Comment by pkoppstein** [comment]
So  does the first problem amount to a documentation issue?

A positional join is supposed to add columns. Is there a documentation issue here too?

**Comment by soerenwolfers** [comment]
For the first problem, I'm not sure what you'd do with a self join like that. Maybe write down the full problem and solution that you're after and then we can think about whether the documentation could be improved. As it stands it seems sufficiently clear to me from the error message that you need to rename one of the `aa`s.

For the second problem, a join doesn't "add columns" unless you tell it to, which the asterisk does but which your original window function doesn't.

**Comment by pkoppstein** [comment]
@szarnyasg @soerenwolfers - Thanks for your patience.

The second issue arises because of my misunderstanding of the associativity rules.  I thought that

SELECT row_number() OVER () FROM aa POSITIONAL JOIN (FROM aa);

would be understood based on something like:

FROM (SELECT row_number() OVER () FROM aa) POSITIONAL JOIN (FROM aa));

So my mistake on that one.

But I'd like to try to explain to you why I still think DuckDB ought to be able to handle:
```
FROM aa POSITIONAL JOIN aa;
```
without throwing any error.

(1) DuckDB generally claims to offer a "friendly" take on SQL, and I believe there is no other plausible interpretation than `FROM aa POSITIONAL JOIN aa a2;`

(2) The documentation  for POSITIONAL JOIN gives the example:

SELECT * FROM t1 POSITIONAL JOIN t2;

without any indication that there are additional restrictions.

(3) The principle of referential transparency should apply.  In algebra, the expression `x * y` means `the value of the variable x multiplied by the value of y`; it would come as a surprise if `x * x` were deemed to be erroneous.  I realize that SQL is not itself an algebraic language, but in SQL generally, I believe it's generally understood that where the syntax allows, the principle should apply.  Just imagine if `SELECT a,b ...` was valid, but `SELECT a,a ...` was erroneous.

**Comment by soerenwolfers** [comment]
> (1) DuckDB generally claims to offer a "friendly" take on SQL, and I believe there is no other plausible interpretation than FROM aa POSITIONAL JOIN aa a2;

I don't consider "do whatever if the user asks for something unusual" friendly, because usually an error would help me realize that I actually wrote the wrong thing.

> Just imagine if SELECT a,b ... was valid, but SELECT a,a ... was erroneous.

I happen to think that `SELECT a, a ...` should indeed throw an error for two reasons:

(a) as above: almost everytime I use the same column name twice, I do so unintentionally and later get confused when I use the column name again but don't get what I expected. This is especially true for `SELECT *, 3 AS a` type statements, where the `3 AS a` is hidden by DuckDb behind a supposedly friendly `a_1` rename

 (b) because everything else always just leads to an inconsistent mess, as evidenced by the status quo: 

In MySQL & SQLite, `SELECT a, a ...` produces a single column but in PostgreSQL & DuckDB it produces two equally named columns. Wrapping it in a further `SELECT * FROM (...)` produces an error in MySQL, produces auto-deduplicated columns in SQLite & DuckDB, and produces two equally named columns in PostgreSQL. Creating a table from it throws an error in PostgreSQL & MySQL but produces auto-deduplicated columns in SQLite & DuckDB.

**Comment by soerenwolfers** [comment]
Here is a fun little trap duckdb currently sets for you in an attempt to be friendly around column identifiers:
```sql
SELECT 
a
FROM
(
    SELECT 1, 2
) _(A, a)
```
returns `1` because duckdb identifiers are case insensitive, so even though the original casing is preserved in output displays ("friendly"!), what matters is the lower-case version so the duplicated column specification (`a`, `a`) is  auto-deduplicated (friendly!) to (`a`, `a_1`).

Wouldn't it be nice if duckdb just told you

```
Binder Error: Duplicate column name "a"!
```
?

**Comment by soerenwolfers** [comment]
More examples of unnececessary pain that happen because of laissez-faire identifiers:

1: 
```sql
SELECT a FROM (SELECT *, random() AS a FROM df)
```

I mentioned this above: If `df` has a column named `a`, then this will show you that column and throw away the expression you clearly actually want

2: 

```sql
SELECT random() * 100 AS a, random() AS a FROM range(3) ORDER BY a
```

Which column would you expect this query order by? No clear preference, so duckdb just defaults to the second `a` . You couldn't have guessed it and none of your readers could have guessed it, so what's the use of this over just throwing an error? Furthermore, good luck figuring out that in the "obviously equal"

```sql
SELECT * FROM (SELECT random() * 100 AS a, random() AS a FROM range(3)) ORDER BY a
```
 the subquery necessitates column name deduplication, so the ordering now picks the other column!

**Comment by pkoppstein** [comment]
@soerenwolfers wrote:
> In ... SQLite, SELECT a, a ... produces a single column 

I have a very high regard for SQLite so I was very surprised by this claim about SQLite, so I checked, and fortunately for my sanity:
```
sqlite> select a,a from (select 1 as a);
1|1
sqlite>
```

I also checked that SQLite properly understands the JOIN in question without any fuss:
```
sqlite> create table t (i integer);
sqlite> insert into t values (1);
sqlite> select * from t positional join (select * from t);
1|1
sqlite> 
```

Indeed, the fact that SQLite gets it right is, for me, tangible evidence that DuckDB simply gets it wrong in this very unfortunate case.

More generally, I think the main argument from the existence of "traps and pitfalls" that arise because of commitment to fundamental principles is usually better documentation, not abandonment of such principles.  Indeed, I will study your examples more closely in relation to the existing documentation.  In the meantime, forgive me for saying that it seems to me that your general line of reasoning based on protecting users from themselves (or you from yourself?) seems to allow you to make any claim you like.

**Comment by pkoppstein** [comment]
@soerenwolfers wrote:

> Here is a fun little trap duckdb currently sets for you in an attempt to be friendly around column identifiers:
> SELECT a FROM (SELECT 1, 2) _(A, a)

If there is an issue here, it's whether the renaming of columns in expressions like the following is properly documented:
```
FROM (SELECT 1, 2) t(A, a);
┌───────┬───────┐
│   A   │  a_1  │
│ int32 │ int32 │
├───────┼───────┤
│     1 │     2 │
└───────┴───────┘
```
Is it?

**Comment by soerenwolfers** [comment]
SQLite claims were based on https://www.db-fiddle.com/f/bCj7FVgLXcgRzZ46t1rC7F/0 -- no idea what's going on there. Anyway: there is still s discrepancy between SQLite and PostgreSQL wrt reduplication in regards to subqueries.

**Comment by soerenwolfers** [comment]
you say 

>SQLite properly understands the JOIN in question without any fuss

yet you write 

```sql
select * from t positional join (select * from t);
```

which is exactly not the join in question because it uses a subquery, which also works in duckdb. The join in question is 

```sql
FROM aa POSITIONAL JOIN aa
```

**Comment by pkoppstein** [comment]
@soerenwolfers wrote:
> yet you write ...

My apologies, I should have copy-pasted the following two lines:
```
sqlite> select * from t positional join t;
1|1
```

(I've added these two lines to the post in question, as it is what I'd intended, and makes the point there more clearly.)

**Comment by Mytherin** [comment]
Thanks for the report!

Both of these are intended behaviors.

In the first case, DuckDB does not allow duplicate table identifiers, and an explicit alias is required. This follows the same behavior as other systems like e.g. Postgres. SQLite is more permissive in what they accept - and in the past we have often followed SQLite, but being more accepting is not necessarily being more friendly in all scenarios - often throwing an error is more user-friendly since that allows errors to be fixed at an earlier stage (rather than incorrect numbers/graphs being reported). 

That being said, the error message could be expanded and e.g. point to where the identifier comes from in the query, as well as suggest a solution (providing an explicit alias using the `AS` clause).

In the second case, a `SELECT` statement only emits what is present in the `SELECT` clause. The join is executed, but the output columns of the other table are explicitly thrown away by the user in that scenario. This is standard SQL behavior that all systems follow.

**Comment by pkoppstein** [comment]
@Mytherin - Thanks for your considered response.  Since the central issue here was muddied by my own failure to understand the heart of the matter initially, I'm wondering whether it wouldn't be better to "close" this issue in favor of a more focused one, along the lines of the following:

Title: DuckDB's documentation and handling of POSITIONAL JOIN

DuckDB's documenation and handling of 
```
SELECT * FROM t1 POSITIONAL JOIN t2;
```
is problematic.

As far as I've been able to discern, the official documentation does not specify that `t2` cannot be `t1`,
and indeed it seems rather bizarre that this should be disallowed, notably because it seems to violate the principle of referential transparency.  Who would have thought that:

SELECT * FROM t POSITIONAL JOIN t; 

is not equivalent to:

SELECT * FROM t POSITIONAL JOIN (SELECT * FROM t);

Certainly, they are the same in SQLite, which in cases like this I think can be taken as a "gold standard".

**Comment by Mytherin** [comment]
I think there are still a lot of misunderstandings here.


First, this is unrelated to the `POSITIONAL JOIN`, this applies to *everything* in the from clause, from cross products to any joins. For example:

```sql
D create table t(c int);
D select * from t, t;
-- Binder Error: Duplicate alias "t" in query!
D select * from t join t using (c);
-- Binder Error: Duplicate alias "t" in query!
```

Second, this is unrelated to `t` and t` being *identical*. This is about the **alias** being identical. The alias is just set, *if none is provided by the user*, to the name of the table. The alias can be set manually using the `AS` clause, which makes the query work as intended:

```sql
D SELECT * FROM t POSITIONAL JOIN t AS t2;
┌───────┬───────┐
│   c   │   c   │
│ int32 │ int32 │
├───────┴───────┤
│    0 rows     │
└───────────────┘
```

The subquery works because the alias is set to `__unnamed_subquery` by default, which resolves the duplicate alias.

> Certainly, they are the same in SQLite, which in cases like this I think can be taken as a "gold standard".

I think you are also misunderstanding what SQLite does. SQLite **does not** support the positional join at all. Positional joins are non-standard, and as far as I know only supported in DuckDB. In your SQLite example, you are *aliasing* the first table to the name `positional` instead - as in SQL you can alias tables **without** `AS` in some cases. Further, in an attempt to be friendly, SQLite supports joins without an `ON` clause resulting in a cross product. These two queries are equivalent in SQLite:

```sql
select * from t positional join t; -- alias "t" to "positional", perform a join without conditions (cross product)
select * from t AS positional, t; -- explicitly alias "t" to "positional", perform a cross product with itself
```

This becomes clear when we actually run the join:

```sql
create table t(c int);
insert into t values (1), (2), (3);
select * from t positional join t;
┌───┬───┐
│ c │ c │
├───┼───┤
│ 1 │ 1 │
│ 1 │ 2 │
│ 1 │ 3 │
│ 2 │ 1 │
│ 2 │ 2 │
│ 2 │ 3 │
│ 3 │ 1 │
│ 3 │ 2 │
│ 3 │ 3 │
└───┴───┘
```

When we omit the explicit alias that was accidentally provided, SQLite also produces an error, albeit when binding the column instead of a duplicate table alias error:

```sql
sqlite> create table t(c int);
sqlite> select * from t join t;
-- Parse error: ambiguous column name: main.t.c
--   select * from t join t;
--          ^--- error here
```

Regardless, I do think we can at the very least provide a better/more descriptive error message in this scenario.

**Comment by pkoppstein** [comment]
@Mytherin - Thanks again for taking the time to explain things, and in particular for the explanation of how SQLite interpreted the "positional join".

Please note that the reason I highlighted the case of "POSITIONAL JOIN" is that I was focused on the existing DuckDB documentation about "POSITIONAL JOIN".   From my perspective, there would not have been a problem if that documentation had mentioned something about "t POSITIONAL JOIN t;" being a special case, or if there were a pointer there to generic documentation about table aliases.

Thank you!

**Comment by szarnyasg** [comment]
> From my perspective, there would not have been a problem if that documentation had mentioned something about "t POSITIONAL JOIN t;" being a special case, or if there were a pointer there to generic documentation about table aliases.

I added a note on self-joins being a special case that required aliasing in https://github.com/duckdb/duckdb-web/pull/3964
