### ISSUE TITLE
If one of row is malformed in csv , all data is loaded to a single column 

### ISSUE THREAD

**Issue by sbbhardwa** [duckdb/duckdb#14117]
### What happens?

Sample csv 

id,name,age
2,"Alice,Doe",30
1,"John, Doe,25
3,"Bob",35
4,"John","45

Loaded using 

SELECT * FROM read_csv_auto("C:/rs/malformed.csv") ; 

![image](https://github.com/user-attachments/assets/ef3e335e-4009-4f52-97ce-496185392130)

Here the data is loaded to a single column 

one of the row is malformed that is noticeable here 

**1,"John, Doe,25**

### To Reproduce

If one of row is malformed in csv , all data is loaded to a single column 

### OS:

Windows 

### DuckDB Version:

1.1.0

### DuckDB Client:

jdbc:duckdb

### Hardware:

12th Gen Intel(R) Core(TM) i5-1250P   1.70 GHz

### Full Name:

Sandeep Bhardwaj

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @sbbhardwa, thanks for reporting this. First, please do not duplicate issues – this post describes the same issue as your comment in https://github.com/duckdb/duckdb/issues/14115#issuecomment-2373701575.

The reason why this issues is happening because the test this file is too small for the CSV sniffer to correctly identify the delimiter and quote characters. If a sufficiently large sample is available, the CSV reader will detect the correct settings.

**Comment by sbbhardwa** [comment]
I did tried with more number of rows and results is same 
[test2.csv](https://github.com/user-attachments/files/17129557/test2.csv)

It has now 117 rows 

![image](https://github.com/user-attachments/assets/29e269fa-7259-47fe-9293-fbf82ce77440)
