### ISSUE TITLE
Rejected Rows should at least display an error or warning once csv loaded 

### ISSUE THREAD

**Issue by sbbhardwa** [duckdb/duckdb#14114]
### What happens?

I added a 'I' intentionally in the input file to determine whether the data is loaded incorrectly or rejected 
![image](https://github.com/user-attachments/assets/e3ff819b-ebcf-48fc-ae17-6e101266cde2)

It seems after selecting the data using the Query below - 

![image](https://github.com/user-attachments/assets/8435537e-6f50-4c42-92ef-d6ea45fbef46)

There was no Warning or error , the row was rejected 

I do understand as per the documentation under https://duckdb.org/docs/data/csv/reading_faulty_csv_files

![image](https://github.com/user-attachments/assets/6a852c43-e35a-439d-a438-2815c72c168b)

The errors can be retrieved or stored but it would be great if there is at least a warning or informational message generated after the select is performed , showing that there were rows rejected , if there are thousands of rows , it could be a scenario where the data is missed 

### To Reproduce

The errors can be retrieved or stored but it would be great if there is at least a warning or informational message generated after the select is performed , showing that there were rows rejected , if there are thousands of rows , it could be a scenario where the data is missed 

### OS:

Windows 

### DuckDB Version:

1.1.0

### DuckDB Client:

jdbc:duckdb

### Hardware:

12th Gen Intel(R) Core(TM) i5-1250P   1.70 GHz

### Full Name:

Sandeep Bhardwaj

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pdet** [comment]
Hi @sbbhardwa,

In your example, the CSV will still be parsed because the sniffer attempts to determine the "best" set of options to read the file without errors.

I believe that, in your case, the sniffer assumes there are two varchar columns and uses the `,` delimiter. Because of this, it skips the actual header, treating it as garbage, and instead uses the first row as the header (since the types are varchar).

The more unconventional a CSV file is, the more options you will need to configure manually.

Regarding error warnings: warnings are not currently supported for SQL queries. While there might be a logger in the future, that is still uncertain. For now, the only way to investigate errors is to inspect the reject tables.
