### ISSUE TITLE
User-Defined Functions powered by AssemblyScript

### ISSUE THREAD

**Issue by ghalimi** [duckdb/duckdb#1442]
IDEA: Now that DuckDB is adding support for WASM deployment, it would be really interesting to see if user-defined functions could be added at runtime using [AssemblyScript](https://www.assemblyscript.org/). It would be slowish on WASM runtimes that do not yet support [module linking](https://github.com/WebAssembly/module-linking/blob/master/proposals/module-linking/Explainer.md), but [Wasmtime](https://github.com/bytecodealliance/wasmtime) does already, and we hope that some browsers will follow suit soon. AssemblyScript is very fast (_e.g._ exp is 2.5x faster than JS-native Math.exp), and we are porting the amazing [stdlib](https://github.com/stdlib-js/stdlib) to it. This would dramatically expand the scope of functions available in DuckDB, while allowing users to add their own from userland at runtime.

**Comment by ankoh** [comment]
Exciting idea! We thought about this as well already and you wouldn't necessarily even need module linking in browsers for this. You can just jit-compile your assemblyscript functions today and register them as udfs dynamically. The overhead of calling the functions is amortized enough through the vectorized processing.

**Comment by ghalimi** [comment]
> Exciting idea! We thought about this as well already and you wouldn't necessarily even need module linking in browsers for this. You can just jit-compile your assemblyscript functions today and register them as vectorized udfs dynamically. The overhead of calling the functions is amortized enough through the vectorized processing.

That's awesome! How much work do you think that would entail? Is that something that we could contribute, or is it better than you take a first crack at it?

**Comment by ankoh** [comment]
I'm not in the CWI group, I guess you can totally go for it. :)
We JIT-compiled vectorized UDFs with LLVM before and that is fairly straight forward.
In the web-world the only real challenge will be the data format for the JS interop which was briefly discussed [here](https://github.com/cwida/duckdb/issues/310) already.

We're actively working on an open-source browser-based analytics tool at the moment that talks to a DuckDB webworker though flatbuffer vectors.
That works quite nicely and if [this](https://github.com/google/flatbuffers/issues/6409) turns out to be working it might be a good path for you as well.
I'm open to discuss this more in-depth but we're still 1-2 months away from sharing this openly, I think.

**Comment by ghalimi** [comment]
> I'm not in the CWI group, I guess you can totally go for it. :)
> We JIT-compiled vectorized DuckDB UDFs with LLVM before and that is fairly straight forward.
> In the web-world the only real challenge will be the data format for the JS interop which was briefly discussed [here](https://github.com/cwida/duckdb/issues/310) already.
> 
> We're actively working on a browser-based analytics tool at the moment that talks to a DuckDB webworker though flatbuffer vectors.
> That works quite nicely and if [this](https://github.com/google/flatbuffers/issues/6409) turns out to be working it might be a good path for you as well.
> I'm interested to discuss this more in-depth but we're still 1-2 months away from sharing this openly, I think.

Great! Very much looking forward to hearing more about your project.

**Comment by hustnn** [comment]
> I'm not in the CWI group, I guess you can totally go for it. :)
> We JIT-compiled vectorized DuckDB UDFs with LLVM before and that is fairly straight forward.
> In the web-world the only real challenge will be the data format for the JS interop which was briefly discussed [here](https://github.com/cwida/duckdb/issues/310) already.
> 
> We're actively working on a browser-based analytics tool at the moment that talks to a DuckDB webworker though flatbuffer vectors.
> That works quite nicely and if [this](https://github.com/google/flatbuffers/issues/6409) turns out to be working it might be a good path for you as well.
> I'm interested to discuss this more in-depth but we're still 1-2 months away from sharing this openly, I think.

@ankoh Quite interesting. Can you introduce more on it? Thanks.

**Comment by ankoh** [comment]
The JIT compilation?
The starting point would be [this](https://github.com/cwida/duckdb/blob/34c7308bf08b507b6a1d2425ccde9ac3cadaa499/test/api/udf_function/test_templated_vec_udf.cpp#L235).

I'd begin with a simple JS-UDF.
Register a JS function in emscripten and add it as vectorized UDF first.
The only problem will be that you have to get the data chunk in and out of the linear memory of wasm.
If your target language can access the wasm heap, you could just [orrify](https://github.com/cwida/duckdb/blob/497c6deb6d499ee25bc13cab77114aee792bf904/src/include/duckdb/common/types/data_chunk.hpp#L86) the data chunk and pass refs to the data to your vectorized function.
With AssemblyScript this will be a bit more work since you'll probably have 2 distinct wasm heaps but its conceptually the same approach.

**Comment by ankoh** [comment]
The tool is not yet ready for prime time.
But take [this](https://observablehq.com/d/834cccf550a16c1e) as a teaser of how awesome DuckDB in the browser is going to be.

**Comment by hustnn** [comment]
Is the DuckDB fully hosted in the browser?

**Comment by domoritz** [comment]
Yes, running in WebAssembly. We support workers as well so the db runs in a different thread.

**Comment by hannes** [comment]
We have JS UDFs now in WASM and the Node.js APIs
