### ISSUE TITLE
parquet_scan not loaded in C API 

### ISSUE THREAD

**Issue by kosinsky** [duckdb/duckdb#1457]
Parquet extension not loaded in C API and as a result [C#](https://github.com/Giorgi/DuckDB.NET) and [Go](https://github.com/marcboeker/go-duckdb) clients both fails with "Table Function with name parquet_scan does not exist!"

Is it possible to load Parquet extension by default in C API or expose a function for loading extensions.

**Comment by hannesmuehleisen** [comment]
Yes this is possible and should be added.

**Comment by michaeldiscala** [comment]
Hi there!

I'm interested in being able to load the parquet extension from the C-API as well, so that I can use it from within Ruby. 


As a workaround, I was trying to compile an extension that I could use with `LOAD` that would just run the `ExtensionHelper::LoadAllExtenstions` method, but was running into an issue because `LoadAllExtensions` receives  `DuckDB` as an argument, but the dynamic `LOAD` infrastructure passes in a `DatabaseInstance` object. Is there any way to go from a `DatabaseInstance` to a `DuckDB` object to make this work?

If, not is there any other way to get access to extensions from the C-API?

Thank you!
--Mike

**Comment by michaeldiscala** [comment]
@hannesmuehleisen I was actually able to frankenstine together a loadable version of the parquet extension, which will at least get me started for testing!

Is using this extension loading framework the best approach for doing this with the C API? If so, would you be open to a PR that modifies the parquet extension code so that it outputs a `parquet.duckdb_extension` file that can be loaded in this way?

**Comment by SartorialOffense** [comment]
@michaeldiscala I am in almost the same boat as you (need to use DuckDB.NET and read Parquet files) and was able to munge something together that compiles and almost works.  I fixed a path separator issue in the `parquet-amalgamation.py` script, took the created duckdb and parquet-amalgamation files, rolled a cmake file, and added in my own dll endpoint to load the extension:

```
__declspec(dllexport) void load_parquet_ext(duckdb_database *database)
{
    auto wrapper = (DatabaseData *)database;
    DuckDB db = *wrapper->database;
    db.LoadExtension<ParquetExtension>();
}
```

More details in #2533.

Issue is that even if I don't call this endpoint, DuckDB.Net will crash in simple scenarios leading me to believe I have screwed something up. My next step is going to be trying to get it to work with the un-amalgamated files. I am not a C++ person so it is very slow going.

Do you mind sharing the details of what your solution was?

**Comment by blackrez** [comment]
Hello,

Same issue with the ruby client for duckdb https://github.com/suketa/ruby-duckdb/issues/225

**Comment by Mytherin** [comment]
This should be fixed in the master in #2563.

**Comment by Giorgi** [comment]
@Mytherin Does parquet_scan include support for `HTTPS` URLs by default or does it need another extension that is not included in the default build?

**Comment by Mytherin** [comment]
You need to enable the HTTPFS extension for that (`BUILD_HTTPFS_EXTENSION=1`). Note that this adds linking to OpenSSL. #2569 adds support for installing this extension using the `INSTALL` and `LOAD` commands, although that support is still very much in alpha state.

**Comment by Giorgi** [comment]
So HTTPFS is needed for plain HTTPS URLs right?

**Comment by Mytherin** [comment]
Yes
