### ISSUE TITLE
DuckDB C interface cannot correctly obtain the UUID result

### ISSUE THREAD

**Issue by BlackSakura3C** [duckdb/duckdb#14630]
### What happens?

In the duckdb.h provided by DuckDB, you can see that the UUID type is actually stored using duckdb_hugeint. However, when I tried to retrieve the content corresponding to the UUID using duckdb_value_hugeint, I encountered some issues with the internal implementation.
<img width="418" alt="image" src="https://github.com/user-attachments/assets/7db97f5c-02c2-4fc8-a556-6dee412fb1fc">

In DuckDB, when C is used, GetInternalCValue is employed, and its internal implementation does not account for scenarios where the type obtained is a UUID. As a result, it resorts to fetching the default value, ultimately leading to the return of an all-zero value.
<img width="570" alt="image" src="https://github.com/user-attachments/assets/0fa10cb9-7e9b-49b7-8474-cccd022d94ad">

<img width="649" alt="image" src="https://github.com/user-attachments/assets/4b3a60a1-8ac6-49a4-aaf4-cb5e69fe19cb">

It seems that a fix could be implemented by referencing the GetValuesInternal method.

### To Reproduce

You can directly look at the code analysis above

### OS:

x86_64

### DuckDB Version:

v1.1.1

### DuckDB Client:

C

### Full Name:

Amore

### Affiliation:

Software engineer

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by BlackSakura3C** [comment]
Just to add, I find that the C interface provided by DuckDB is not very user-friendly or comprehensive. For instance, there seems to be no way to retrieve data without losing precision for decimals, and I am unable to manipulate the content of duckdb_hugeint (since C doesn't have operator overloading like C++). Moreover, it appears that the C interface isn't updated with new versions. I wonder if there are any plans to enhance the C interface in future updates.

**Comment by Mytherin** [comment]
Thanks for the report!

The `duckdb_value_XXX` functions mimic the [`sqlite_value_XXX`](https://www.sqlite.org/c3ref/value_blob.html) functions. They are defined by *their return type*, not by the internal type of the type that you are querying. A hugeint is a 128-bit number, and a `UUID` cannot be converted to a number, so `0` is returned. In DuckDB itself, this cast returns an error:

```sql
D select uuid()::hugeint;
-- Conversion Error: Unimplemented type for cast (UUID -> HUGEINT)
```

This behavior is intentional.

Note also that these methods are actually deprecated and are mainly provided for backwards compatibility.

```cpp
/*!
**DEPRECATION NOTICE**: This method is scheduled for removal in a future release.

* @return The duckdb_hugeint value at the specified location, or 0 if the value cannot be converted.
*/
DUCKDB_API duckdb_hugeint duckdb_value_hugeint(duckdb_result *result, idx_t col, idx_t row);
```

They were part of DuckDB's original C interface, but have since been superseded by [the more efficient and comprehensive vector-based interface](https://duckdb.org/docs/api/c/vector) that support lossless conversion of all types.

>  For instance, there seems to be no way to retrieve data without losing precision for decimals, and I am unable to manipulate the content of duckdb_hugeint (since C doesn't have operator overloading like C++). 

The vector interface offers support for all types in DuckDB.

> Moreover, it appears that the C interface isn't updated with new versions. I wonder if there are any plans to enhance the C interface in future updates.

The C interface is worked on regularly and has new functionality and improvements/changes every release.

**Comment by BlackSakura3C** [comment]
Thank you for your response. These legacy interfaces have indeed caused quite a bit of confusion in their use. I will attempt to work with the vector-based interface.
