### ISSUE TITLE
Python appender and file locking

### ISSUE THREAD

**Issue by polyrand** [duckdb/duckdb#1526]
I've been looking into duckdb for some time and what you are doing is wonderful. I was thinking it could be useful as an append-only DB, where I can append logs and then use the full-text search functions to query them. I see there's an `Appender` api in C++, but for Python, I only see the standard SQL `INSERT INTO ...` or appending a pandas dataframe/CSV, but not a "raw" appender function. Or am I missing something?

I also wonder if having the DB as append-only (+ reading) would make it better for concurrent writes. I did some benchmarks, but I quickly hit `database locked` kind of errors (This is already explained in the official docs). In SQLite, I also end up hitting those errors, but SQLite guarantees thread safety by serializing concurrent access (you need to make sure you set the timeout high enough to avoid errors).

Those were a couple of random ideas that went through my mind. I was thinking that having a performant append-only OLAP embedded database would be really nice to implement some simple logging services, and I just wanted to share it.

Thanks again for the fantastic work!

**Comment by hannesmuehleisen** [comment]
Thanks for the praise! The reason there is no Python appender (yet) is that scalar code in Python is very slow and there is no real advantage between using a special appender and using an `INSERT` prepared statement. This only improves when appending in bulk, which is why we have the append for data frames. 

For the append-only mode, maybe @Mytherin is better positioned to answer this.

**Comment by Mytherin** [comment]
> I also wonder if having the DB as append-only (+ reading) would make it better for concurrent writes. I did some benchmarks, but I quickly hit database locked kind of errors (This is already explained in the official docs). In SQLite, I also end up hitting those errors, but SQLite guarantees thread safety by serializing concurrent access (you need to make sure you set the timeout high enough to avoid errors).

Append-only mode simplifies some things, but the single file storage format will still make it extremely difficult to sync between multiple processes concurrently. Even with append-only mode, there will be contention issues when merging changes back into the main file (i.e. running a checkpoint). There is more discussion on this [here](https://github.com/cwida/duckdb/pull/1448). For now this is not on our primary agenda for the primary storage format. It would complicate the design significantly and have many awkward restrictions, so much so that we prefer to keep this out of the main format.

As you have correctly noted yourself, SQLite actually has similar restrictions to DuckDB here. The difference is that SQLite does not keep a database connection open persistently, but rather does the locking on a transaction level (i.e. at the end of a transaction, the file lock is released again). This allows multiple processes to "more-or-less" use the same database file concurrently (with restrictions, of course). The downside here is that the database file continuously needs to be re-read and nothing can be cached in memory (since another process could very well have done anything to do the database file in the meantime).

You could achieve a similar behavior in DuckDB by opening and closing the database system for every transaction. However, unlike SQLite, DuckDB is not optimized for this. This is something that we want to work towards by (1) making opening a database as lazy as possible (i.e. only reading individual catalog and column data when actually required), and (2) adding support for `mmap` when opening files so that the database itself does not need to keep a lot cached in memory.

Those changes combined should make it much faster to open and close a database, which will make the SQLite-style multi-process concurrency work much better. Still, there is a fundamental difference between OLAP and OLTP style queries here. SQLite-style OLTP queries are expected to finish much faster, whereas OLAP style queries might hold locks for a long period of time.

For true concurrency, it is a better idea to use multiple files for storage. One of the changes we want to make in DuckDB as well is to add support for pluggable storage. Afterwards we could add support for e.g. a directory of Parquet (or even DuckDB) files as alternative storage format. Concurrent appends can be performed much easier in such a setup because adding a file to a directory is easily done concurrently.

If you really want to have a single file storage format, you could then periodically run a scan over the directory of files and append new data to the single file using a single process (this could still be parallelized within the process, of course).

**Comment by FrancoisLepoutre** [comment]
Hi Hannes, Mark... And Ricardo!

Thanks for this nice post and the related exchange. 

I have been thoroughly impressed by duckdb, right from the start. I appreciate Ricardo's question in this regard. We are a number of us looking for latency times to be as limited as possible between duckdb and, says, python. Yes I could have put is as well and I was quite interested by your feedback. 

Both of your answers bring a great clarification on the trade-off(s) involved. I really look forward to start using duckdb in a large python-based project:-)

Cheers, François

**Comment by polyrand** [comment]
Wow, thank you so much for such a detailed answer Mark! I definitely learned a few things I had no idea about.

I now understand better the upsides/downsides of each approach. The technique you mentioned of having a bunch of files and then loading those asynchronously into a DuckDB file is also something I thought about. Since DuckDB can load CSVs, I think I could get very fast appends to a plain csv file and then have another process loading them to DuckDB.

I'll also keep an eye on the discussion you linked to, thanks again!

**Comment by dforsber** [comment]
> For true concurrency, it is a better idea to use multiple files for storage. One of the changes we want to make in DuckDB as well is to add support for pluggable storage. Afterwards we could add support for e.g. a directory of Parquet (or even DuckDB) files as alternative storage format. Concurrent appends can be performed much easier in such a setup because adding a file to a directory is easily done concurrently.

This is a nice idea for that use case. I guess you can already now do the glob pattern matching with DuckDB, so that it would match new files on the folder.
