### ISSUE TITLE
M-f/M-b don't work in the DuckDB shell

### ISSUE THREAD

**Issue by nelhage** [duckdb/duckdb#1585]
I'm experimenting with using DuckDB to replace SQLite for [a personal project](https://buttondown.email/nelhage/archive/5e2a6c81-f873-484b-a640-fa464392750f), using the duckdb shell.

One minor annoyance I keep hitting is that the duckdb shell doesn't seem to respect the usual full set of readline cursor movement commands; in particular, M-f and M-b do not move forward/backwards a word as I expect. I'm not sure what you're using for shell input, but I'd love it for those and others to work so that my muscle memory continues to function.

**Comment by Mytherin** [comment]
Thanks for opening the issue!

By default the DuckDB shell uses a modified version of [linenoise](https://github.com/antirez/linenoise) rather than readline. It tries to support many of the readline escapes (we have added extra ones as well), but indeed some may be missing. I have added support for some extra escape sequences in this PR #1587. Could you check if that fixes the issue for you?

**Comment by nelhage** [comment]
Thanks for the fast turnaround! That seems to work as-expected in my testing.

**Comment by Mytherin** [comment]
Great! Closing this then.

**Comment by atombender** [comment]
I'm using 0.7.1, and I'm being hit by this on macOS; arrow-left/right inserts B and F respectively. Is this a regression, or a different problem?
