### ISSUE TITLE
Persistently cache Parquet metadata

### ISSUE THREAD

**Issue by hannes** [duckdb/duckdb#1622]
For wide and large Parquet files we spend most of our time reading the damn (Thrift-encoded) metadata. We can already cache this when setting `PRAGMA enable_object_cache`, but this cache will not survive DuckDB restarts. It probably should be possible to do this somehow....

**Comment by dforsber** [comment]
> For wide and large Parquet files we spend most of our time reading the damn (Thrift-encoded) metadata. We can already cache this when setting `PRAGMA enable_object_cache`, but this cache will not survive DuckDB restarts. It probably should be possible to do this somehow....

We are experiencing this heavy hit of "Parquet metadata reading" latency and it was a bit puzzling at first. However, even without the "PRAGMA enable_object_cache" the 2nd time we query the parquet files, they queries are like 10x faster. Furthermore, if we have the data set split to multiple Parquet files, the latency grows proportionally or even more (e.g. 2 parquets 25s vs 1 parquet 10s.. but that ofc depends on the parquet structure like row groups etc.).

It would be very nice to be able to "cache" the parquet metadata alongside the parquet files e.g. into a single continuous byte blob that is fast to read on when doing `parquet_scan()`. As now, the ad-hoc queries on large Parquet files take a hit of reading the Parquet metadata for almost every query and thus makes the engine feel very slow compared to subsequent queries.

Is there any way to speed up the initial metadata reading further on? Are multiple threads used to read metadata if there are multiple Parquet files? But yes, I think this feature would be re-enabler for us to use DuckDB on Lambda with Parquet files. It was a bit hard to figure out due to all OS caches etc. when running local testing :).

**Comment by dforsber** [comment]
> > For wide and large Parquet files we spend most of our time reading the damn (Thrift-encoded) metadata. We can already cache this when setting `PRAGMA enable_object_cache`, but this cache will not survive DuckDB restarts. It probably should be possible to do this somehow....
> 
> We are experiencing this heavy hit of "Parquet metadata reading" latency and it was a bit puzzling at first. However, even without the "PRAGMA enable_object_cache" the 2nd time we query the parquet files, they queries are like 10x faster. Furthermore, if we have the data set split to multiple Parquet files, the latency grows proportionally or even more (e.g. 2 parquets 25s vs 1 parquet 10s.. but that ofc depends on the parquet structure like row groups etc.).
> 
> It would be very nice to be able to "cache" the parquet metadata alongside the parquet files e.g. into a single continuous byte blob that is fast to read on when doing `parquet_scan()`. As now, the ad-hoc queries on large Parquet files take a hit of reading the Parquet metadata for almost every query and thus makes the engine feel very slow compared to subsequent queries.
> 
> Is there any way to speed up the initial metadata reading further on? Are multiple threads used to read metadata if there are multiple Parquet files? But yes, I think this feature would be re-enabler for us to use DuckDB on Lambda with Parquet files. It was a bit hard to figure out due to all OS caches etc. when running local testing :).

The speed differences are most probably due to hitting DuckDB and OS level caches?
Reading the metadata from the end of the Parquet file is probably tiny compared to tens of seconds we are talking here or does the metadata reading actually traverse all row groups (that would explain the slowness if jumping on disk to read tiny amounts of data)?

But still 25s is a long time (two snappy compressed Parquets) reading data from disk, or 10s still (ZSTD compressed single parquet file made with DuckDB by combining the two snappy parquet files). It sounds weird (total amount is about 5.7GB and 5m rows, <300 columns). In another test scenario the timings were 14s and 6s (local laptop with docker). So, the time difference between 1 and 2 parquets is ~2.4x. But it could also count towards zstd being that much faster than snappy (sounds a bit unbelievable)?

Any light to the confusion here?

**Comment by hannesmuehleisen** [comment]
The compression (snappy, zstd etc) in Parquet does not apply to the metadata, that's plain thrift. If you have more files, more metadata needs to be read, so that explains that. Thanks to thrift, there is no way to selectively read columns from the metadata, so its all-or-nothing. This becomes worst with many many columns and many many row groups. So what you can do to improve is having fewer columns (difficult) or larger row groups (not so difficult) at the cost of reduced in-column data skipping opportunities. There is nothing we can do with multiple threads here since this is likely blocked on the single-threaded bind on the query.  I invite you to use Arrow to read this file and see how long that takes, I suspect very similar. So indeed caching this metadata externally is a way around this.

**Comment by dforsber** [comment]
> The compression (snappy, zstd etc) in Parquet does not apply to the metadata, that's plain thrift. If you have more files, more metadata needs to be read, so that explains that. Thanks to thrift, there is no way to selectively read columns from the metadata, so its all-or-nothing. This becomes worst with many many columns and many many row groups. So what you can do to improve is having fewer columns (difficult) or larger row groups (not so difficult) at the cost of reduced in-column data skipping opportunities. There is nothing we can do with multiple threads here since this is likely blocked on the single-threaded bind on the query. I invite you to use Arrow to read this file and see how long that takes, I suspect very similar. So indeed caching this metadata externally is a way around this. Of course this opens a whole different cans of staleness/correctness issues with the cache.

How long does the Parquet metadata reading then take? I'm not sure how to divide the spent latency between:
- parquet metadata reading for 1 parquet file (5.7GB) with ~300 columns and num of rows groups as DuckDB creates them
- fetching data / scanning from disk
- executing the query

I'm assuming that while the initial query takes roughly 12s, the 2nd same query around 2.5s that most of that 10s is still data scanning and Parquet metadata reading could be around 1s. Am I on the right ballpark on this?

**Comment by dforsber** [comment]
FYI. 
I have a data source originally in 2 Parquet files. 
- I used parquet-tools to merge them into single Parquet. The result has 66 row groups and size of 5.5G and roughly 300 columns. The parquet-tools meta command outputs `21442  281611 3503379` for this file.
- I create a new Parquet file with DuckDB (and for ZSTD) compression. The resulting size is 5.3G. This file has 50 row groups. The parquet-tools meta command outputs `16322  192258 2072276` for this file.

==> Using these two different files for the same queries has latency 3s (merged) and 1.7s (duckdb created). The query is selecting first element from a single column.

**Comment by dforsber** [comment]
> FYI.
> I have a data source originally in 2 Parquet files.
> 
> * I used parquet-tools to merge them into single Parquet (snappy). The result has 66 row groups and size of 5.5G and roughly 300 columns. The "parquet-tools meta | wc" command outputs `21442  281611 3503379` for this file.
> * I create a new Parquet file with DuckDB (and for ZSTD) compression. The resulting size is 5.3G. This file has 50 row groups. The "parquet-tools meta | wc" command outputs `16322  192258 2072276` for this file.
> 
> ==> Using these two different files for the same queries has latency 3s (merged) and 1.7s (duckdb created). The query is selecting first element from a single column.

It seems that the difference is simply the performance between SNAPPY and ZSTD algorithm implementations on DuckDB, where in our tests, the ZSTD is at least 2x faster! 👍🏻 .

In my understanding the Object Cache stores the Parquet blobs, i.e. they need to be uncompressed when accessed (which is good as it saves memory). So, it pays off to use ZSTD.

(I didn't suspect this at all as they should be roughly on par on CPU and ZSTD winning clearly on storage size, but that's only based on what I've read, not tested before. In our tests the ZSTD compression is only little bit smaller.)

**Comment by hannesmuehleisen** [comment]
Again, the parquet metadata is never compressed. The object cache stores the decoded metadata. The speed diffs are on lambda? Maybe re-run locally which may be more insightful, without a network storage layer with caching in between.

**Comment by dforsber** [comment]
> Again, the parquet metadata is never compressed. The object cache stores the decoded metadata. The speed diffs are on lambda? Maybe re-run locally which may be more insightful, without a network storage layer with caching in between.

Yes, this "thread" went a bit sideways as I thought it was about Parquet metadata. But it is the same difference with local execution as well (i.e. Parquet performance with ZSTD and Snappy compressed).

Parquet metadata is certainly an issue with lots of files and partitions. Perhaps the [Apache Iceberg](https://github.com/duckdb/duckdb/discussions/1668) could help there, not sure.

**Comment by dforsber** [comment]
> > Again, the parquet metadata is never compressed. The object cache stores the decoded metadata. The speed diffs are on lambda? Maybe re-run locally which may be more insightful, without a network storage layer with caching in between.
> 
> Yes, this "thread" went a bit sideways as I thought it was about Parquet metadata. But it is the same difference with local execution as well (i.e. Parquet performance with ZSTD and Snappy compressed).
> 
> Parquet metadata is certainly an issue with lots of files and partitions. Perhaps the [Apache Iceberg](https://github.com/duckdb/duckdb/discussions/1668) could help there, not sure.

Just for the record. The difference was between GZIP and ZSTD compressed Parquet files, where zstd is obviously much faster to work with. No wonder, I was puzzled :D. 👍🏻

**Comment by hannes** [comment]
Not going to do this in the immediate future.
