### ISSUE TITLE
MODE aggregate function

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#1699]
Supported by [Oracle](https://docs.oracle.com/cd/B12037_01/olap.101/b10339/x_maxbytes008.htm) and [Postgres](https://www.postgresql.org/docs/12/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE). They define it as an ordered aggregate (window) function, but it is entirely possible to implement it as a regular aggregate using only an `O(1)` hash table in the state.

**Comment by hawkfish** [comment]
Ah, this was misfiled under distributive aggregates (it is holistic). It could do with a little TLC to support temporal types and reduce the number of physical implementations.

**Comment by tomthe** [comment]
Hi,

Mode works well and is tested well if there is a single mode (e.g.: mode([1,1,2,3])==1).
What happens if there is more than one mode (e.g.: mode([1,1,2,2,3]) == [1,2])?

The documentation doesn't specify this and the tests do not cover that case.

Pandas returns the list [1,2]. I don't know about Oracle, but Postgres "returns the most frequent input value (arbitrarily choosing the first one if there are multiple equally-frequent results)". I think DuckDB mode works like Postgres, but could you specify that in the documentation? Maybe a test case that covers this case would be a good idea? There is no test case for that in https://github.com/duckdb/duckdb/blob/8f44a3422a75cfc0d6af6a4ac2da4b63c6ff66c8/test/sql/aggregate/aggregates/test_mode.test

Maybe an option to work like Pandas would also be a good idea, but I don't know your philosophy about that.

**Comment by hawkfish** [comment]
DuckDB works like Postgres. The return type is a scalar, not a list.
