### ISSUE TITLE
Numeric Errors When Using REAL/FLOAT4

### ISSUE THREAD

**Issue by cyvb** [duckdb/duckdb#1811]
Hi everyone! Here I come again (with bugs hah hah)
<img src='https://preview.redd.it/0zf7y34xka801.jpg?width=640&crop=smart&auto=webp&s=4c724cc431fc06904df14fb740239af9ded5183a' height='300' />

**What does happen?**
There are errors between values between duckdb's REAL/FLOAT4 and python's float

**What should happen?**
What inserted into duckdb as REAL/FLOAT4 equals which in python

**To Reproduce**
```python
import duckdb
db = duckdb.connect()
db.execute('CREATE TABLE IF NOT EXISTS a(num REAL)')

db.execute('INSERT INTO a VALUES (0.1), (1.32)')

output = db.execute('SELECT * FROM a').fetchall()
# ouput is [(0.10000000149011612,), (1.3200000524520874,)]

output[0][0] == 0.1
# False
output[1][0] == 1.32
# False
```

**Environment (please complete the following information):**
 - OS: Windows 10, Python 3.9.5
 - DuckDB Version 0.2.6

**Comment by Mytherin** [comment]
Thanks for the report!

This is not a bug but rather a a side-effect of the imprecision of IEEE floating point numbers.

Note that while Python calls its float class `float`, it is really a C++-style `double` internally (i.e. 8-byte floating point number). `REAL` in DuckDB corresponds to 4-byte floating point number (or `float` in C++), see [here for an overview of DuckDB numerics](https://duckdb.org/docs/sql/data_types/overview).

Any library built on IEEE floating point numbers will have the same result, e.g. for NumPy:

```python
import numpy
numpy.array([0.1], dtype=numpy.single).astype(dtype=numpy.double)[0]
# 0.10000000149011612
```

Or Postgres:
```sql
select '0.1'::real::double precision;
--       float8        
---------------------
-- 0.10000000149011612
--(1 row)

```

I would recommend either using `DOUBLE`/`FLOAT8` instead of `REAL`, or to use a floating point comparison that compares values within a certain threshold rather than comparing for exact equality.

**Comment by cyvb** [comment]
Thanks a lot! I will use DOUBLE then.
