### ISSUE TITLE
Implement ENUM Types and Integrate with Categorical (Pandas) and Factors (R)

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#1879]
The basic idea is to implement a new type ENUM (i.e., basically just an unsigned integer internally, with the actual strings stored inside the type information) to use as R Factors and categorical from Pandas.
By using ENUM we would then get very fast joins, comparisons on these enums and groupings. With a  string conversion as a fallback.

The limit to enums should be 16-bits, otherwise fallback to a dictionary.

Currently Missing:

- [x] Table -> ENUM dependency (Only valid for ENUMs created via SQL
- [ ] Enum to Enum comparison (Right now this throws, we should do a string comparison)
- [ ] Updates (Alter type Add/Remove)

**Comment by Alex-Monahan** [comment]
Thank you for putting in a fallback beyond 16 bits - we automatically convert all strings to categories since it usually saves space. It means sometimes we have columns with as many categories as rows... If this could just automatically fall back to a different data type without throwing an error, that would be nice! 

Also, how would this be handled when registering a DataFrame and not inserting it?

**Comment by Mytherin** [comment]
Related to this is the [PostgreSQL Enum syntax](https://www.postgresql.org/docs/9.1/datatype-enum.html).

**Comment by pdet** [comment]
@Alex-Monahan To either scan DFs or create tables from the DFs is the same scan process, so it will be transformed to enums or dicts.

**Comment by Mytherin** [comment]
This has been implemented
