### ISSUE TITLE
`ConstructSemiOrAntiJoinResult` for `PhysicalBlockwiseNLJoin`

### ISSUE THREAD

**Issue by octaviansima** [duckdb/duckdb#1927]
Currently, only `PhysicalNestedLoopJoin` has a method `ConstructSemiOrAntiJoinResult`. Is there a reason why this is the case?

We are using DuckDB in a context where we need to get the result for semi/anti joins for a more general NL join that works on arbitrary expressions, and `PhysicalBlockwiseNLJoin::GetChunkInternal` seems to return intermediate results that still contain columns from the RHS table. I will open a PR if this is something that would be accepted -- plan is to just use the existing `ConstructSemiOrAntiJoinResult` but expose it in the header as well.

**Comment by Mytherin** [comment]
Sure, that seems fine to me. I don't believe the join is supported yet with the SEMI or ANTI join, since users cannot generate these types of joins themselves. We might want to add support for (explicit) semi or anti joins at some point though.

Is there a SQL query that results in this type of join, or are you generating the physical or logical operators yourself?

**Comment by octaviansima** [comment]
Hi @Mytherin, thanks for your quick response.

I figured that was the case -- the live demo seems to schedule a filter before a cross product for any non-comparison joins. We are generating the logical and physical operators ourselves. Do you have any recommendations on how to test this, given there is no possible SQL query to schedule this particular physical operator?
