### ISSUE TITLE
Expanded list/struct function support

### ISSUE THREAD

**Issue by erikcw** [duckdb/duckdb#1940]
Would love to see more array/list functions.  I'm currently porting some queries over from SparkSQL and Presto and am running into a brick wall with limited `list` functions.

```sql
-- Presto/Spark SQL
SELECT
array_join(array_distinct(array_sort(array_agg(a.segment) FILTER (WHERE a.segment is not null))), ',') as all_segments
FROM...

-- ClickHouse
SELECT
arrayStringConcat(arrayDistinct(arraySort(groupArray(a.segment))), ',') as all_segments
FROM....

-- DuckDB
SELECT
-- Lots of missing functionality.
list(a.segment) as all_segments
FROM ...
```

There doesn't appear to be functions in Duckdb for:
* `array_join(arr, sep)` (tried `concat_ws(",", arr)`, but it just produces a stringified list.
* `array_sort(arr)`
* `array_distinct(arr)`

To make matters worse in this case, the list and struct types aren't implemented in the pandas integration, so one can't just use pandas as a quick escape hatch to perform these transformations at the application level.

```python
In [28]: cursor.execute("SELECT list_value(1,2,3) as segment ").df()
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-7d6a1d36c1c1> in <module>
----> 1 cursor.execute("SELECT list_value(1,2,3) as segment ").df()

RuntimeError: Unsupported type LIST<INTEGER> for DuckDB -> NumPy conversion

```

**Comment by Mytherin** [comment]
List support is indeed still in its infancy in DuckDB and needs to be expanded. Perhaps for now a work-around using `UNNEST` would be possible?

Here is an initial list of array functions that should be implemented:

[ ] array_length
[ ] range/generate_series (scalar function returning a list of integers)
[ ] array_contains
[ ] hasAll/hasAny
[ ] indexOf
[ ] arrayCount
[ ] arrayPopBack/arrayPopFront/arrayPushBack/arrayPushFront
[ ] arrayResize
[ ] arraySort/arrayReverseSort
[ ] arrayUniq
[ ] arrayDistinct
[ ] arrayReduce
[ ] arrayIntersect
[ ] arrayFlatten
[ ] arrayCompact
[ ] arrayZip
[ ] arrayMap/arrayFilter
[ ] arraySplit
[ ] arraySum/arrayMax/arrayMin/arrayAvg/arrayCumSum/arrayProduct

[Clickhouse Functions](https://clickhouse.tech/docs/en/sql-reference/functions/array-functions/)

PRs more than welcome!

**Comment by hawkfish** [comment]
@Mytherin and I were discussing possibly combining lambdas and some basic functions (e.g., `array_map`, `array_reduce`) to provide a framework to implement most of these. So for example, `arraySum(list)` => `array_reduce(list, 'sum')`.

**Comment by erikcw** [comment]
@hawkfish Seems like the functional approach would unlock a ton of functionality.  I imagine `CREATE MACRO` could be used to port queries from other SQL dialects easily.

**Comment by Mytherin** [comment]
> @Mytherin and I were discussing possibly combining lambdas and some basic functions (e.g., array_map, array_reduce) to provide a framework to implement most of these. So for example, arraySum(list) => array_reduce(list, 'sum').

Presto offers the `reduce` function that generalizes this:

```sql
-- reduce(array(T), initialState S, inputFunction(S, T, S), outputFunction(S, R)) → R#
SELECT reduce(ARRAY [5, 20, 50], 0, (s, x) -> s + x, s -> s); -- 75
```

I'm not so sure how to implement that fast, though. Adding support for our own aggregate functions directly seems rather straightforward and could be implemented in a very efficient manner.

On that note, we also want to add support for lambda functions similar to Presto, e.g.:

```sql
SELECT filter([1, 2, 3], x -> x >= 2) -- [2, 3]
SELECT transform([1, 2, 3], x -> x + 1); -- [2, 3, 4]
```

Since this is a 1:1 transformation implementing this efficiently is much more straightforward .The support is already there in the parser, so it "only" needs to be implemented :)

**Comment by hawkfish** [comment]
> Since this is a 1:1 transformation implementing this efficiently is much more straightforward .The support is already there in the parser, so it "only" needs to be implemented :)

Or as a mathematician would say, "It is left as an exercise for the reader."

**Comment by buhrmann** [comment]
Unless I've missed something in the docs, could I add aggregate functions to the wish list? There doesn't seem to be any way to aggregate lists at the moment (such as simply concatenating them). Or is there a way to re-use the standard list functions with a group by somehow? I'm evaluating duckdb for replacing some of our data processing steps in Graphext, and see a nice 10x-20x speedup over pandas, which would be awesome if lists were supported (as well as basic arrow types such as dictionary, timestamp with timezone etc.).

**Comment by taniabogatsch** [comment]
Since I've been working on this, here is a small update on the list functions. So far, [these](https://duckdb.org/docs/sql/functions/nested) functions exist. 

I also finished `list_sort` (open PR, one bug left to fix) and `list_distinct`, `list_unique` (still on my fork, I'll open a PR once  #3345 is merged). These are still open:
- [ ] `list_hasAll(l1, l2)`, `list_hasAny(l1, l2)`
- [ ] `list_resize(l, size[, value])`
- [ ] `list_intersect(l1, l2)`
- [ ] `list_join(l, sep)`, this is an improvement on `list_string_agg`
- [ ] (`list_flatten(l)`, `list_compact`, `list_zip(l1, l2, ...)`), maybe

And then there are functions that require a lambda function as an argument, such as:
- [ ] `list_count(func)`, counts occurrences for which `func` evaluates to true
- [ ] `list_filter(l, func)`
- [ ] `list_transform(l, func)`

Optionally, I might have a look at a `list_reduce` after this.

**Comment by RobinL** [comment]
@erikcw  to note, for now it's possible to achieve `array_join` using `list_string_agg` : https://duckdb.org/docs/sql/functions/nested#list-aggregates

As far as I can tell, you can't change the delimiter at the moment

**Comment by taniabogatsch** [comment]
Hi @RobinL @erikcw there was a PR by Mytherin that should fix the issue and allow custom delimiters in the `list_aggr` function. :)

```sql
 SELECT list_aggr(list(i), 'string_agg', '|') FROM range(1, 4) tbl(i);
 ----
 1|2|3
```

**Comment by maiadegraaf** [comment]
I'm going to finish working on the last functions, starting with `list_hasAll(l1, l2)`,`list_hasAny(l1, l2)`, and `list_intersect(l1, l2)`.

**Comment by taniabogatsch** [comment]
I will close this issue since we implemented most of the list functions in it. Any further functions should be implemented through our extension ecosystem.

**Comment by wensle** [comment]
> hi just fyi you can use:
> 
> ```sql
> select array_to_string(['a','b'],'|')
> ```
> 
> [duckdb.org/docs/sql/functions/nested#array_to_string](https://duckdb.org/docs/sql/functions/nested#array_to_string)

Link does not link anymore to that function. I found another reference here [https://duckdb.org/docs/sql/functions/list.html#array_to_string](https://duckdb.org/docs/sql/functions/list.html#array_to_string)
