### ISSUE TITLE
R pkg duckdb() docs clarification

### ISSUE THREAD

**Issue by dselivanov** [duckdb/duckdb#1952]
Docs for 
```
duckdb(dbdir = DBDIR_MEMORY, read_only = FALSE, config = list())
```
say following:
- `dbdir` - Location for database files. Should be a path to an existing directory in the file system. With the default, all data is kept in RAM

while in fact `duckdb()` expects `dbdir` to be a file.

```
drv = duckdb::duckdb(dbdir=tempdir(), read_only=FALSE)
```
> Error in initialize(value, ...) : 
  duckdb_startup_R: Failed to open database: IO Error: Cannot open file "/var/folders/mw/ny_d_3j93134n9glqgq7t7l80000gn/T//RtmpWwaw19": Is a directory

**Comment by hannesmuehleisen** [comment]
Happy to review a PR!

**Comment by lpiep** [comment]
I'm happy to submit a PR for this. I'm kind of reluctant to simply change the description of the `dbdir` argument to specify that it only accepts files, since that doesn't address the root of the confusion here, unless @hannes thinks that's the best way to go. 

I can think of two other options:

1. The function be changed to accept a directory for `dbdir` with some default `.duckdb` file name. 
2. We could add an better-named argument, e.g. `dbfile`, and set its default value to that of `dbdir` if `dbdir` is a file (for backward compatibility).
