### ISSUE TITLE
There is a function "first", where is "last"? 

### ISSUE THREAD

**Issue by thetradingflow** [duckdb/duckdb#1954]
Hello,

Is there a function or a way to get the last value of a column in a group by statement? 

I see the function `first` but there is no equivalent function for `last`. May I ask why? 

Here's my working code, the only missing piece is the last. 

```python
import duckdb

filepath = "/home/user/data.parquet"

q = \
    f"""
    SELECT
        date_trunc('day', timestamp) AS date,
        first(open) AS open,
        max(high) AS high,
        min(low) AS low,
    FROM
        parquet_scan('{filepath}')
    GROUP BY
        date_trunc('day', timestamp);
    """

print(duckdb.query(q).to_df())
```

Thank you.

**Comment by Mytherin** [comment]
Thanks for opening the issue!

Indeed `LAST` is missing and should be added.

However, note that `FIRST` (and `LAST`, if we implement it) are not deterministic when multi-processing is enabled. Despite the name it is more akin to  `ANY`, since the order in which the tuples arrive determine the value which is not deterministic in the presence of multiple threads. As a result this might not actually be what you want to use.

Perhaps you want to use `MIN_BY` and `MAX_BY`?

```sql
SELECT MIN_BY(open, timestamp), MAX_BY(open, timestamp) FROM tbl
```

That basically means "retrieve the open value of the row with the minimum timestamp".

**Comment by hawkfish** [comment]
`FIRST` (and `LAST`) need to support the new `ORDER BY` syntax from #2117 to make them deterministic.

**Comment by hawkfish** [comment]
@thetradingflow Does this work for you?
