### ISSUE TITLE
Python Relational Api - Methods

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#2000]
I think we want 1-1 mapping with Pandas API (https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

**Reshaping  Functions**
- [ ] pivot()
- [ ] pivot_table()
- [ ] concat()
- [ ] melt()
- [ ] unpivot()

**Aggregation Functions**
- [x] sum()
Sum values of each object.
- [x] count()
Count non-NA/null values of each object.
- [x] median()
Median value of each object.
- [x] quantile([0.25,0.75])
Quantiles of each object.
- [x] apply(function)
Apply function to each object.
- [x] min()
Minimum value in each object.
- [x] max()
Maximum value in each object.
- [x] mean()
Mean value of each object.
- [x] var()
Variance of each object.
- [x] std()
Standard deviation
- [x] value_counts()
Count number of rows with each unique value of variable
- [x] len(rel)
 number of rows in relation.
- [x] rel.shape
Tuple of # of rows, # of columns in DataFrame.
- [x] unique()
 number of distinct values in a column.
- [x] describe()
Basic descriptive and statistics for each column.
- [x] mad()
Mean absolute deviation
- [x] mode()
Mode
- [x] abs()
 Absolute Value
- [ ] prod()
 Product of values
- [ ] sem()
Standard error of the mean
- [ ] skew()
Sample skewness (3rd moment)
- [ ] kurt()
Sample kurtosis (4th moment)
- [ ] cumsum()
Cumulative sum
- [ ] cumprod()
Cumulative product
- [ ] cummax()
Cumulative maximum
- [ ] cummin()
Cumulative minimum

**Subset Observations (Rows) Functions**
- [ ] df[df.Length > 7]
Extract rows that meet logical criteria.
- [ ] df.drop_duplicates()
Remove duplicate rows (only considers columns).
- [ ] df.head(n)
Select first n rows.
- [ ] df.tail(n)
Select last n rows.
- [ ] df.sample(frac=0.5)
Randomly select fraction of rows.
- [ ] df.sample(n=10)
Randomly select n rows.
- [ ] df.iloc[10:20]
Select rows by position.
- [ ] df.nlargest(n, 'value')
Select and order top n entries.
- [ ] df.nsmallest(n, 'value')
Select and order bottom n entries.

**Subset Variable (Columns) Functions**
- [ ] df['width'] or df.width
Select single column with specific name.
- [ ] df[['width','length','species']]
Select multiple columns with specific names.
- [ ] df.filter(regex='regex')
Select columns whose name matches regular expression regex

**Combine Data Sets**
- [ ] pd.merge(adf, bdf,how='left', on='x1')
Join matching rows from bdf to adf.
- [ ] pd.merge(adf, bdf,how='right', on='x1')
Join matching rows from adf to bdf.
- [ ] pd.merge(adf, bdf,how='inner', on='x1')
Join data. Retain only rows in both sets.
- [ ] pd.merge(adf, bdf, how='outer', on='x1')
Join data. Retain all values, all rows.

**Comment by Alex-Monahan** [comment]
Thank you for your work on this!

There are a few other projects in the Python ecosystem that do similar things that may help with this or provide inspiration!

Ibis is something Wes McKinney and others built that has non-pandas syntax, but generates SQL from DataFrame operations. It is not as heavily used as Pandas for sure, but might have solved some of the DF to SQL translations. I think it may serve more as an example than an API to follow. ([Ibis](https://ibis-project.org/) )

The other project is Modin. Modin follows the Pandas API directly, but has modular backends. One such backend is OmniSci DB, so they may have solved some of the Pandas to SQL translation there as well. Since Modin is aligned to Pandas, that may be the more useful code base to draw from. ([Modin](https://github.com/modin-project/modin) )

I talked about DuckDB with the creator of the Modin project already [here](https://github.com/modin-project/modin/issues/2589) . They were open to receiving PR's, so maybe the work you do in this relational API can feed forward to Modin as well!

**Comment by stefan-grafberger** [comment]
Thanks for your work; this would be great! Are you thinking about making the same ordering guarantees as pandas? 

Previously, I looked into replacing pandas function calls with duckdb operations, and order preservation was the main problem that I encountered. When using operations like `df.head`, users expect a specific dataframe order. In ML scenarios, order preservation is also important. There, model training methods assume that their inputs are ordered, by implicitly associating each featurized datapoint with its corresponding label. 

As far as I know, duckdb operators currently preserve order only in the single-threaded case, but not when multithreading is enabled. 

I'm also not sure how this relates to lazy evaluation. I'm not sure how the relational API is implemented, but if it uses CTEs, I'm unsure whether the query optimizer can interfere with the order. When you have an ordered CTE, then the query optimizer is usually allowed to optimize the `ORDER BY` of intermediate results away, isn't it? 
```sql
SELECT *
FROM (SELECT * FROM A ORDER BY col)
```

It's possible to overcome this by using artificial sort columns, but repeatedly sorting the data in data science scenarios would result in significant performance overhead.

**Comment by stefan-grafberger** [comment]
Another thing I was wondering related to pandas: pandas supports [sparse arrays](https://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html). As you move towards slowly offering everything pandas can do, is support for this also on your to-do list? I think with all of the recent work on structs and lists this shouldn't be impossible, but I imagine it might be a lot of work. Libraries like modin also do not support this currently.

Currently, duckdb cannot deal with these cases:
```python
from scipy.sparse import csr_matrix
import numpy as np
import pandas as pd
import duckdb
con = duckdb.connect(database=':memory:', read_only=False)

matrix = csr_matrix((3, 4), dtype=np.int8)
sparse_df = pd.DataFrame.sparse.from_spmatrix(matrix, columns=['A', 'B', 'C', 'D'])
#dense_df = sparse_df.sparse.to_dense()          

con.register('sparse_df', sparse_df)
#con.register('dense_df', dense_df)

sparse_result_df = con.execute("SELECT * FROM sparse_df").fetchdf()  # does not work currently
#sparse_result_df = con.execute("SELECT * FROM dense_df").fetchdf()  # does work
df
```

In any case, thanks for all your work on duckdb, the project is awesome!

**Comment by pdet** [comment]
Hey @stefan-grafberger, 

Thanks for the interest and questions! :-)

Regarding your first question, I think we have no plans on parallel order guarantees in the near future. 

And supporting the read of sparse arrays is something that is in the realm of possibilities, but is a bit unrelated to this issue, here I'm looking more for compatibility with the Pandas API when reading our tables, I'll create an issue to that based on your comment so we keep track of user interest!

**Comment by lsh** [comment]
Thank you for your work! In addition to pivot, [melt()](https://pandas.pydata.org/docs/reference/api/pandas.melt.html) or [unpivot](https://docs.microsoft.com/en-us/sql/t-sql/queries/from-using-pivot-and-unpivot?view=sql-server-ver15) would be a nice compliment.

**Comment by Alex-Monahan** [comment]
I was preparing for a 1 hour crash course on data analysis in Python and had one other thought on this!

Since the Pandas API is so huge, I've found Ted Petrou's Minimally Sufficient Pandas to be a big help. One extreme way to use his line of thinking would be to only add the core transformation functions he suggests (to avoid user confusion). However, that is in tension with the compatibility goal you are pursuing!

A middle ground may be that this article could help prioritize the order in which you add functionality. If you add these minimally sufficient methods first, there will be a way to achieve almost anything, even if not everyone's preferred syntax. For example, pivot_table can do everything that pivot can do, and more! As a strict superset, it may make sense to build that first. Also, Ted prefers methods that do not use Multiindexes, so they may be more compatible with SQL tables anyway!

https://medium.com/dunder-data/minimally-sufficient-pandas-a8e67f2a2428

**Comment by corneliusroemer** [comment]
It'd be great if GROUP BY'ed SAMPLE'ing was possible like this for example, see #2813 
```python
df.groupby('country').apply(
            lambda x: x.sample(
                n=df_weights.loc[x.name,'chosen'],
                replace=False
                )
            ).to_csv(output.metadata,sep="\t",index=False)
```

**Comment by hannesmuehleisen** [comment]
Ability to specify schema in table creation etc.

**Comment by hannes** [comment]
Moving #1026 here, I think it not yet possible to update or delete from a base table through the python API.
e.g.,
```python
rel = conn.get_table('table)
rel.delete('i=1')
```

**Comment by mauropagano** [comment]
I wonder if `df.ewm` is on the roadmap. 
I find that’s generally hard to express in SQL (recursive CTE helps but still…) but very common in pandas space / more scientific analysis

**Comment by earlev4** [comment]
Hi @pdet! A huge thanks to you and the DuckDB team for your work on Python Relational API. Greatly appreciate the efforts!  

Are there plans to add a functionality comparable to pandas `df.info()`?

[https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html)

Example:  
```python
df.info(verbose=True)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   int_col    5 non-null      int64
 1   text_col   5 non-null      object
 2   float_col  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 248.0+ bytes
```

Where the functionality would return column names, non-null counts, and data types of the Python relation.

I checked the following resources and did not see mention of it:
[https://duckdb.org/docs/api/python/overview.html](https://duckdb.org/docs/api/python/overview.html)
[https://duckdb.org/docs/api/python/reference/](https://duckdb.org/docs/api/python/reference/)
[https://github.com/duckdb/duckdb/blob/master/examples/python/duckdb-python.py](https://github.com/duckdb/duckdb/blob/master/examples/python/duckdb-python.py)

Thank you very much!

**Comment by pdet** [comment]
> Hi @pdet! A huge thanks to you and the DuckDB team for your work on Python Relational API. Greatly appreciate the efforts!
> 
> Are there plans to add a functionality comparable to pandas `df.info()`?
> 
> https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html
> 
> Example:
> 
> ```python
> df.info(verbose=True)
> <class 'pandas.core.frame.DataFrame'>
> RangeIndex: 5 entries, 0 to 4
> Data columns (total 3 columns):
>  #   Column     Non-Null Count  Dtype
> ---  ------     --------------  -----
>  0   int_col    5 non-null      int64
>  1   text_col   5 non-null      object
>  2   float_col  5 non-null      float64
> dtypes: float64(1), int64(1), object(1)
> memory usage: 248.0+ bytes
> ```
> 
> Where the functionality would return column names, non-null counts, and data types of the Python relation.
> 
> I checked the following resources and did not see mention of it: https://duckdb.org/docs/api/python/overview.html https://duckdb.org/docs/api/python/reference/ https://github.com/duckdb/duckdb/blob/master/examples/python/duckdb-python.py
> 
> Thank you very much!

Hi @earlev4, thank you for the kind words. Maybe the `describe()` function is the one you are looking for?

**Comment by earlev4** [comment]
Hi @pdet! Thanks so much for the prompt response and information. I sincerely appreciate it. The `describe()` function is very helpful. Using the `penguins` dataset from `seaborn` as an example with the `describe()` function, I incorporated the desired information:  

```python
counts = [rel.count(c).fetchall()[0][0] for c in rel.columns]
describe = rel.describe().fetchall()
total_qry = rel.query('penguins_rel', 'SELECT COUNT(*) FROM penguins_rel')
total = total_qry.fetchall()[0][0]
nulls = [total - x for x in counts]

for (col, typ, des, cnt, nul) in zip(rel.columns, rel.types, describe[0], counts, nulls):
    print(f"COLUMN: {col}, TYPE: {typ}, DESC: {des}, COUNT: {cnt}, NULL_COUNT: {nul}") 
```

Output:  
```python
COLUMN: species, TYPE: VARCHAR, DESC: [Min: Adelie, Max: Gentoo, Has Unicode: false, Max String Length: 9][Has Null: false, Has No Null: true][Approx Unique: 2], COUNT: 344, NULL_COUNT: 0
COLUMN: island, TYPE: VARCHAR, DESC: [Min: Biscoe, Max: Torgerse, Has Unicode: false, Max String Length: 9][Has Null: false, Has No Null: true][Approx Unique: 3], COUNT: 344, NULL_COUNT: 0
COLUMN: bill_length_mm, TYPE: DOUBLE, DESC: [Min: 32.1, Max: 59.6][Has Null: true, Has No Null: true][Approx Unique: 143], COUNT: 342, NULL_COUNT: 2
COLUMN: bill_depth_mm, TYPE: DOUBLE, DESC: [Min: 13.1, Max: 21.5][Has Null: true, Has No Null: true][Approx Unique: 54], COUNT: 342, NULL_COUNT: 2
COLUMN: flipper_length_mm, TYPE: DOUBLE, DESC: [Min: 172.0, Max: 231.0][Has Null: true, Has No Null: true][Approx Unique: 33], COUNT: 342, NULL_COUNT: 2
COLUMN: body_mass_g, TYPE: DOUBLE, DESC: [Min: 2700.0, Max: 6300.0][Has Null: true, Has No Null: true][Approx Unique: 65], COUNT: 342, NULL_COUNT: 2
COLUMN: sex, TYPE: VARCHAR, DESC: [Min: Female, Max: Male, Has Unicode: false, Max String Length: 6][Has Null: true, Has No Null: true][Approx Unique: 2], COUNT: 333, NULL_COUNT: 11
```

I am slightly confused by the columns that indicate:  `[Has Null: true, Has No Null: true]`, where both can be true.

I find my approach a bit cumbersome and would greatly welcome a simple function that could incorporate it.

Thank you very much for your time and feedback. I sincerely appreciate it.

**Comment by pdet** [comment]
The has no null name is indeed a bit confusing. Maybe we should rename it.
Has Null is in case the segment has null values, and has not null in the case the segment has values that are not null.
If both are true, the segment has null and non-null values.

I'm not opposed to printing the information in a more readable way. Do you have a format in mind?

**Comment by earlev4** [comment]
Hi @pdet. I appreciate the clarification. That makes sense.

I just performed a test and added two columns of all null values.
```python
con.execute("ALTER TABLE penguins ADD COLUMN test_int INTEGER DEFAULT NULL;")
con.execute("ALTER TABLE penguins ADD COLUMN test_var VARCHAR DEFAULT NULL;")
```

Both columns returned:  
`[Has Null: true, Has No Null: true]`  

I was expecting perhaps the following result, since the columns have all nulls:  

`[Has Null: true, Has No Null: false]`  

Perhaps, I am doing something wrong? I am still learning DuckDB.  

If not, one alternative could be:  

`[Has Null: true, Has Non-Null: true]` : The column has nulls and non-nulls (since nulls = true, non-nulls = true)  
`[Has Null: false, Has Non-Null: true]` : The column has no nulls (since nulls = false, and non-nulls = true)  
`[Has Null: true, Has Non-Null: false]` : The column has all nulls (since nulls = true, non-nulls = false)

I'm not sure if that makes sense. I might be confusing myself.

Or further simplified (although the other alternative provides more preferred detail):  

`[Has Null: true]` : The column has nulls (since null = true)  
`[Has Null: false]` : The column has no nulls (since null = false)  

However, I would defer to you and the DuckDB team.

Also, what are your thoughts on adding a column type, approximate count, and an approximate null count to the `describe()` results?

For example:  
```python
[Type: VARCHAR][Min: Female, Max: Male, Has Unicode: false, Max String Length: 6][Has Null: true, Has No Null: true][Approx Unique: 2][Approx Count: 333][Approx Null Count: 11]
```

I am very grateful for your help. Thanks so much!

**Comment by davetapley** [comment]
FYI https://github.com/duckdb/duckdb-web/pull/550/ just went in and [removes mention](https://github.com/duckdb/duckdb-web/pull/550/files#diff-b86b61172f73e2a73be980276f1f48cf4e8342eff781ad34bf0a6431980b7673L168-R102) of the examples in [`duckdb-python.py`](https://github.com/duckdb/duckdb/blob/8a8581e2e383326b67cd6a0d2d5bd2a650634839/examples/python/duckdb-python.py). 

I assume the plan is to to continue supporting these methods? Because:
I believe they are now not mentioned in the docs at all 😬

**Comment by Mytherin** [comment]
Yes, I am planning to document them separately

**Comment by ned2** [comment]
hey @pdet, is coverage over Pandas API still targeted?

I came looking to see if there was an existing issue about implementing a `head()` method, which would be a lovely quality of life improvement for the API. thought I'd chime in as the issue looks like it's gonna be closed soon.

**Comment by ned2** [comment]
perhaps a better question: are PRs for improving the coverage over the Pandas API welcome?

**Comment by szarnyasg** [comment]
> perhaps a better question: are PRs for improving the coverage over the Pandas API welcome?

@ned2 certainly!

**Comment by earlev4** [comment]
Hi @Mytherin and @pdet! Thank you very much for all the work on the Python Relational API methods! I sincerely appreciate the efforts! I see the issue will be closed in less than 30 days due to inactivity. Will work continue on this issue to develop the additional methods listed? Thanks again!

**Comment by earlev4** [comment]
Thanks for the clarification and update, @szarnyasg.
