### ISSUE TITLE
DeValue Window Calculations

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#2006]
As a follow on to work in #1756 we can remove the use of `Value` to transfer window calculation results.

**Comment by Mytherin** [comment]
On a related note in `ComputeWindowExpression` there are many switches happening on the window expression type/boundary for every row. For example, the `WindowNeedsRank` function is called once per row:

```cpp
static bool WindowNeedsRank(BoundWindowExpression *wexpr) {
	return wexpr->type == ExpressionType::WINDOW_PERCENT_RANK || wexpr->type == ExpressionType::WINDOW_RANK ||
	       wexpr->type == ExpressionType::WINDOW_RANK_DENSE || wexpr->type == ExpressionType::WINDOW_CUME_DIST;
}
```

The `UpdateWindowBoundaries` function contains switches on the start/end window boundaries, and there is a switch on `wexpr->type` again afterwards to compute the actual window aggregate for the row.

Since the window expression type and boundaries should not change between rows, it would be nice to switch to a vectorized model here. We could compute the window boundaries for a set of 1024 rows at the same time, and then compute the window function for that set of rows using the computed boundaries.

This likely won't matter too much for complex aggregates or large boundaries, but might significantly speed up simpler functions (e.g. row number or rank).

**Comment by hawkfish** [comment]
Yeah its ugly. I went for this first just to make it consistent, but that is a great idea. I also want to replace the `BitMask` object with `ValidityMask` simply to avoid code duplication.
