### ISSUE TITLE
SELECT DISTINCT ON does not return the right rows

### ISSUE THREAD

**Issue by Ziink** [duckdb/duckdb#2041]
DuckDB 0.2.7 on Windows 10

Based on [https://stackoverflow.com/a/46567397](https://stackoverflow.com/a/46567397)

The DISTINCT ON clause should be executed after the ORDER BY clause.

Sorry, I'm having trouble properly formatting the SQL from the StackOverflow page.

**Comment by kevinykuo** [comment]
just hit this too, workaround is to do the ordering in a subquery, note in my case the ordering column is double not int which might be relevant

**Comment by hannes** [comment]
Can you try to make a reproducible example following the issue template please?

**Comment by kevinykuo** [comment]
@hannes reprex below plz lmk if bug or expected behavior
```
create table foo(a real, b real);
insert into foo values (1, 69), (1, 420), (2, 69), (2, 420);
select distinct on(a) a, b from foo;
select distinct on(a) a, b from foo order by b desc; -- this gives the same result
```

**Comment by hannes** [comment]
I see. What makes you think the `DISTINCT ON` should be evaluated *after* the `ORDER BY`? Is this somewhere in the SQL standard? The link you sent appears to indicate Postgres does this, but the example you gave produces an error in Postgres: ` SELECT DISTINCT ON expressions must match initial ORDER BY expressions`

**Comment by kevinykuo** [comment]
re: the postgres error perhaps the correct syntax is
```
select distinct on(a) a, b from foo order by a, b desc;
```
which should yield the same result... but i don't have access to a shell right now

the reasoning for the proposed evaluation order is that currently `DISTINCT ON` yields random results, which renders it useless in many real life use cases -- the SO link provides one, another common scenario is selecting the desired row for each range in a range join

also since the behavior hasn't been deterministic up until this point, enforcing this evaluation order wouldn't be breaking

**Comment by kevinykuo** [comment]
from a bit of googling i can't find any other sql impl that has `DISTINCT ON`, so i'm guessing we got the inspiration from postgres and it would make sense to follow the behavior there... (documentation reproduced here https://www.postgresql.org/docs/9.0/sql-select.html#SQL-DISTINCT)

**Comment by kevinykuo** [comment]
@hannes checking in to see if any other info would help w/ further discussion here thanks

**Comment by dhirschfeld** [comment]
> What makes you think the `DISTINCT ON` should be evaluated _after_ the `ORDER BY`?

For me, the whole point of `distinct on` is syntatic sugar to filter a table for the max/min element of a group. Without `distinct on` you have to resort to joining on a subquery. The `distinct on` syntax is more concise, clearer, and IMHO more beautiful.

If `distinct on` simply returns a random value from the group it's not useful for this use-case. Maybe there other use-cases for it IDK, but by applying the `DISTINCT ON` *after* the `ORDER BY` it allows it to be used for filtering on the latest/max/min per group which makes it much more useful/powerful.

As @kevinykuo points out, the current implementation returns a random match (the first value in the set of matches) so changing it to return the first value after the `ORDER BY` clause has been applied is backward-compatible (modulo [`#1172`](https://xkcd.com/1172/))

----

Example showing that, as implemented, `DISTINCT ON` just returns the first value of a random set of matches rather than either the smallest or largest value (of `b`)

![image](https://user-images.githubusercontent.com/881019/216973928-8c87933c-fa06-41db-b009-602699410bf5.png)

**Comment by dhirschfeld** [comment]
What you have to do without `DISTINCT ON` to get the max/min `b` per group (`a`):

![image](https://user-images.githubusercontent.com/881019/216977015-8d4fbaf9-d213-452d-898d-09a7fa4ce5be.png)

**Comment by Mytherin** [comment]
I don't quite understand why the regular `min` and `max` aggregates would not work in your example? Finding the minimum value of `b` for a group `a` is exactly what `GROUP BY` does, no?

```sql
D select a, max(b) from foo group by a;
┌───────┬────────┐
│   a   │ max(b) │
│ float │ float  │
├───────┼────────┤
│   1.0 │  420.0 │
│   2.0 │  420.0 │
└───────┴────────┘
D select a, min(b) from foo group by a;
┌───────┬────────┐
│   a   │ min(b) │
│ float │ float  │
├───────┼────────┤
│   1.0 │   53.0 │
│   2.0 │   53.0 │
└───────┴────────┘
```

**Comment by dhirschfeld** [comment]
Sorry, bad example. I think you can't use `max` where you want to get the value of other columns, not in the `GROUP BY`? I think it might also not work for duplicate max values (neither does the join above). e.g.
```
create table foo(a real, b real, c real);
insert into foo values (1, 69, 1), (1, 53, 2), (1, 420, 3), (1, 420, 4), (2, 55, 1), (2, 69, 2), (2,53, 3), (2, 420, 4);
```
```
with T1 as (
    select *
    from foo
    order by b desc
)
select distinct on(a) a, b, c from T1
```

**Comment by Mytherin** [comment]
You can use `max_by` or `min_by` for that, e.g.:

```sql
select a, max(b), max_by(c, b), min_by(c, b) from foo group by a;
┌───────┬────────┬──────────────┬──────────────┐
│   a   │ max(b) │ max_by(c, b) │ min_by(c, b) │
│ float │ float  │    float     │    float     │
├───────┼────────┼──────────────┼──────────────┤
│   1.0 │  420.0 │          3.0 │          2.0 │
│   2.0 │  420.0 │          4.0 │          3.0 │
└───────┴────────┴──────────────┴──────────────┘
```

As a side-note, instead of using `.arrow().to_pandas()` it should be faster to use `.df()` directly.

**Comment by dhirschfeld** [comment]
Thanks, that's good to know! I'm just getting started out with `duckdb` so I'm still figuring things out.

That's in fact how I ended up here - I was looking to see if `duckdb` supported postgres' `DISTINCT ON` command. I'm glad I found this issue as if I had of used it as I would have in postgres I would have gotten silently incorrect results which might have been quite tricky to track down.

All other things being equal, I thing it would be good to align with the postgres implementation, if only to prevent users familiar with that from shooting themselves in the foot.
