### ISSUE TITLE
Question about ToArrowArray API

### ISSUE THREAD

**Issue by wangfenjin** [duckdb/duckdb#2056]
Not sure if I understand it right, current implementation of [ToArrowArray API](https://github.com/duckdb/duckdb/blob/3f0e699fa0762f3eff977dd53a8b1f13ec18b38a/src/common/types/data_chunk.cpp#L578) will copy the data when doing the convert.

For performance reason, not sure if we can support `move` the data into arrow format.

**Comment by Mytherin** [comment]
The data will only be copied if a conversion is required because there is a mismatch between the binary representation of the type in Arrow and in DuckDB. The byte-compatible types will not trigger any conversion. Specifically, the list of byte compatible types is [defined here](https://github.com/duckdb/duckdb/blob/3f0e699fa0762f3eff977dd53a8b1f13ec18b38a/src/common/types/data_chunk.cpp#L414).

The types that are not byte-compatible are `BOOLEAN`, `VARCHAR`, `BLOB`, `DECIMAL`, `LIST` and `MAP`. The cost of converting these types is not very large, but is still present.

If you require zero-copy conversion of these types, it would be better to extend and improve our C interface with efficient zero-copy integration of our own binary format.

**Comment by wangfenjin** [comment]
Thanks for your clarification!

Recently I migrate the rust client to use the arrow api because I think it might be useful if user can query the data by arrow format as they can use arrow-rs to do further processing. It may also enable other use cases.

After implemented I just thought of the data copy issue. Two further questions:
1. Do you think we can make these types also compatible with arrow?
2. For the type like `VARCHAR` or `BLOB`, do we also copy the content? if yes the memory cost should be large right?

**Comment by wangfenjin** [comment]
As @pdet is working on the arrow related feature, I would also like to hear your opinions on this.

**Comment by Mytherin** [comment]
> Do you think we can make these types also compatible with arrow?

Theoretically yes, but it would require modifying our execution engine to work with those Arrow types. This is not just an engineering effort but also a more complex trade-off. We would enable faster interchange between Arrow and DuckDB, but slow down interchange between Pandas/R DataFrames and DuckDB and slow down parts of our engine (e.g. CASE statements are inefficient on Arrow's string representation). It could definitely be done, but it is unlikely we will take this approach.

> For the type like VARCHAR or BLOB, do we also copy the content? if yes the memory cost should be large right?

Unfortunately the data must be copied. Arrow's VARCHAR and BLOB types require the strings to be laid out consecutively in memory, which requires us to copy the data. The memory cost can be large, but in general you would do this conversion on smaller chunks in a streaming manner, which makes it not very expensive (unless you have very large strings/blobs).

> Recently I migrate the rust client to use the arrow api because I think it might be useful if user can query the data by arrow format as they can use arrow-rs to do further processing. It may also enable other use cases.

Perhaps you could add an optional `to_arrow()` method, similar to how we have multiple result set export methods in the Python client (`fetchall()`, `todf`, `to_arrow`, etc). I am not sure if there is any standard for Rust's database connectors, but our experience is that users are generally interested in receiving native types (`[u8]`, etc). The `to_arrow()` method can be provided as an add-on for the people that are interested in e.g. using `arrow-rs` or other libraries that operate on arrow vectors.

**Comment by wangfenjin** [comment]
Very clear now! Thanks for your suggestion!

**Comment by pdet** [comment]
Hey @wangfenjin, exactly as Mark said, I think for nested types, the main extra cost we have is to transform the offsets, but for Varchars and BLOBs, there is some copying going around.

We had an idea of supporting both Arrow's and DuckDb's String representation, but as Mark pointed out, the extra copying cost is very small. The memory usage could be a potential reason to bring this idea back, though. As Mark said, this would only be a problem if you can't stream the query or have very large strings/blobs. Feel free to ping if you experience memory issues due to this copy.
