### ISSUE TITLE
Feature request - ORDER BY for list() and string_agg() aggregate functions

### ISSUE THREAD

**Issue by akdor1154** [duckdb/duckdb#2117]
Hey all,
Assuming I haven't misread doco, I don't think there is a way to specify internal ordering of of the list() and string_agg() aggregate functions.

Example:
```sql
with t as (
  values ('a',1), ('c',3), ('b',2)
)
select list(col0 order by col1) from t
```
`RuntimeError: Parser Error: ORDER BY is not implemented for aggregates`

In this example I nicked the syntax from Postgres as I thought maybe you'd have implemented it anyway and not told anybody :)

**Comment by hawkfish** [comment]
This would require something like the state model for `quantile`.

**Comment by Mytherin** [comment]
Perhaps one nice way of implementing this is to have a meta aggregate (`SortedAggregate`) that will materialize all intermediates passed to it (similar to `quantile`, but more complex since it needs to materialize multiple columns, hopefully using the RowData/sort infrastructure). In the `Finalize` phase the sorted aggregate can then sort the rows and call the child aggregate on the sorted input.

**Comment by hawkfish** [comment]
We should also add another flag to aggregate functions to say whether they are order sensitive (like `NULL` s). If it is not set, we can just optimise this away.

**Comment by hawkfish** [comment]
> hopefully using the RowData/sort infrastructure

I think this is worth doing with the old infrastructure as I expect the lists will be pretty short in most cases. Concatenating 1M strings in a specific order seems like using [the wrong tool](https://youtu.be/v79fYnuVzdI)...

**Comment by hawkfish** [comment]
This requires a file version bump because we have to serialise the `ORDER BY` clause as part of a `FunctionExpression`.

**Comment by hawkfish** [comment]
@akdor1154 This should be in the September release. Can we close it?
