### ISSUE TITLE
R: Timestamps are bound as strings

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2138]
**What does happen?**

Parameterized queries seem to bind timestamps as strings, not as timestamp values.

**What should happen?**

Timestamps should be bound (and returned) as timestamp values.

**To Reproduce**

``` r
library(DBI)

drv1 <- duckdb::duckdb()
conn1 <- dbConnect(drv1, debug = FALSE)

dput(dbGetQuery(conn1, "SELECT ? AS a", params = list(Sys.time())))
#> structure(list(a = "2021-08-12 03:57:58"), row.names = c(NA, 
#> -1L), class = "data.frame")
dput(dbGetQuery(conn1, "SELECT '2021-08-12 03:51:14'::timestamp AS a"))
#> structure(list(a = structure(1628740274, class = c("POSIXct", 
#> "POSIXt"), tzone = "UTC")), row.names = c(NA, -1L), class = "data.frame")

dbDisconnect(conn1)
```

<sup>Created on 2021-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Environment (please complete the following information):**
 - OS: macOS
 - DuckDB: Version 0.2.9

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment]
This looks like a direct consequence of #2128, no? The type is ambiguous, so the prepared statement parameter is defined as a `VARCHAR` as a fallback. In other systems (e.g. Postgres) this query would be incorrect and instead throw an error. The fix here is to add a cast to the prepared statement parameter so the type ambiguity is resolved, e.g.:

```sql
SELECT ?::TIMESTAMP as a
```

**Comment by Mytherin** [comment]
A potential solution would be to re-bind the prepared statement instead when a prepared statement parameter comes in with a different type. The problem is that we then do not know the result types of prepared statement objects anymore, since they depend on the input parameters. This breaks other APIs (e.g. the [JDBC API](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#getMetaData()) which wants to know the metadata of the prepared statement). In addition, this defeats part of the point of having prepared statements in the first place, since the prepared statement then needs to be re-bound whenever it is executed.

**Comment by krlmlr** [comment]
Thanks, got it. I think we can work around in `dbQuoteLiteral()`.
