### ISSUE TITLE
capi: behaviour not consistent

### ISSUE THREAD

**Issue by wangfenjin** [duckdb/duckdb#2170]
https://github.com/duckdb/duckdb/blob/0d2a2778ae50857bac3cb1788af5a2b66334f0e9/src/include/duckdb.h#L829
For appender_error, user need to free it

https://github.com/duckdb/duckdb/blob/0d2a2778ae50857bac3cb1788af5a2b66334f0e9/src/include/duckdb.h#L641
But for prepare_error, user shouldn't free it

I think we'd better make it consistent, and I prefer to let user free it

**Comment by Mytherin** [comment]
Yes, I agree it should be consistent. I almost modified it when I did the last patch but did not because it would break people's code.

I would instead prefer the change so that `duckdb_query_arrow_error` and `duckdb_appender_error` should not be freed. They are the most recent additions to the API, and hence changes to those will break the lowest amount of code. 

Why would you prefer to let the user free it? In all cases where error messages are used they are associated with a context that owns them and needs to be destroyed independently. What is the advantage to explicitly creating a copy just so the user has to free the message? If the user wants to keep around a copy they can just make a copy themselves, no? Perhaps we could add a `duckdb_strdup` method for this purpose?

**Comment by wangfenjin** [comment]
What I'm thinking is if the error string attach to the query context, then any operation on that context might invalid the error string, if user mistakenly hold and use the error again there might be problem

But what you said also reasonable. Would you like me to create a PR to make it consistent? Or we keep it for compatibility?

**Comment by Mytherin** [comment]
> What I'm thinking is if the error string attach to the query context, then any operation on that context might invalid the error string, if user mistakenly hold and use the error again there might be problem

That is fair, but as far as I can tell in all cases the error message is attached to an object that becomes invalid when an error happens (e.g. a query result that has an error cannot be re-used, or an appender that has an error cannot be re-used, etc). I don't think it will be a big problem in practice.

> But what you said also reasonable. Would you like me to create a PR to make it consistent? Or we keep it for compatibility?

Yes, please! That would be great. Thanks.
