### ISSUE TITLE
Size of duckdb file is huge

### ISSUE THREAD

**Issue by chilarai** [duckdb/duckdb#2179]
**What does happen?**
I am inserting a singular varchar value in a DuckDb table and saving it in a file on my hard disk.  The varchar is a very small string of 4-5 characters. However, the saved file on the disk is huge (around 1Mb). Approximately, 1 varchar insert is around an Mb increment on the size of the file. Does this also happen to in-memory storage as well?

**What should happen?**
Should have incremented a few bytes for a small varchar insert on the file
 
**To Reproduce**
Sample code
```
duckdb::DuckDB db("c://somepath//duckfile.db");
duckdb::DuckDB con(db);

auto createT = con.Query("CREATE TABLE x1 (a VARCHAR)");
if(!createT->success) cout << "ERROR CREATE TABLE";

duckdb::Appender appender(con, "x1");
appender.BeginRow();
appender.Append("xuv");
appender.EndRow();

appender.Close();
```

**Environment (please complete the following information):**
 - Windows 11
 - DuckDB Version  0.2.8

**Comment by Mytherin** [comment]
DuckDB stores data in fixed-size blocks of 256KB, and requires 3-4 blocks even for an empty database (containing metadata, free lists, etc). This means that a database with a single table and a single row will currently occupy around 1MB on disk. Work has been done on co-locating smaller tables on the same blocks (#2157), which will be extended to metadata, but even after that work is finished a database file will never be smaller than a single block (which is 256KB currently).  DuckDB files are not designed for efficiently storing tiny datasets (e.g. a single table with 2 rows) and will not be efficient for that. 

The second increment in size you see because you are performing a second checkpoint to disk. In order to provide ACID guarantees we cannot simply overwrite existing blocks (as this would cause data corruption when power is lost). Instead, DuckDB writes the blocks that are modified to a new location (so the 1MB database exists twice in the same file). This is generally unavoidable in a single-file ACID storage format, although we would like to provide a `COMPACT` command that erases all unused blocks (free blocks) that are no longer used and minimizes the database size. 

After you insert more strings the database size should not grow anymore until the blocks are actually filled, and for anything besides these tiny datasets this should not be as much of a problem.

**Comment by chilarai** [comment]
Understood. Thank you for explanation
