### ISSUE TITLE
Opening Multiple READ_ONLY and one READ_WRITE?

### ISSUE THREAD

**Issue by sdmcallister** [duckdb/duckdb#2192]
Probably not a bug but I see that you can open multiple READ_ONLY connections using the C API (Nim wrapper). I thought you might be able to open 1 READ_WRITE and multiple READ_ONLY but it appears that you cannot.  I have an application where I mostly need readonly connections but in the background I would periodically update data using one connection (probably just using the CLI tool or http route).  It would be nice to not have to shutdown the server to update data (it is true I am starting into the 'when not to use duckdb' terrain) .  

In case you are interested here is what I have in Nim which works nicely:

```
import jester
import duckdb_wrapper
import std/exitprocs

var dbconfig: duckdb_config
if (duckdb_create_config(dbconfig.addr) == DuckDBError):
    echo "Error: Couldn't create config"
    quit(1)

if (duckdb_set_config(dbconfig, "access_mode", "READ_ONLY") == DuckDBError):
    echo "Error: Couldn't set config read only"
    quit(1)

var db: duckdb_database
 
if (duckdb_open_ext("test.db", db.addr, dbconfig, nil) == DuckDBError):
    echo "Error: Couldn't Open with config"
    quit(1)
duckdb_destroy_config(dbconfig.addr)

proc atExit() {.noconv.} =
    duckdb_close(addr(db))
    echo "bye"
    quit(0)
exitprocs.addExitProc(atExit)

routes:
    get "/":
        var con: duckdb_connection
        if (duckdb_connect(db, con.addr) == DuckDBError):
            resp "Error: couldn't connect"

        var res: duckdb_result
        if duckdb_query(con, "SELECT * FROM integers", addr(res)) == DuckDBError:
            duckdb_disconnect(addr(con))
            resp "Error: Query failed"

        var qvals: seq[string]
        for row in 0..<res.row_count:
            for col in 0..<res.column_count:
                let val = duckdb_value_varchar(addr(res), col, row)
                qvals.add($val)
                duckdb_free(val)
        duckdb_destroy_result(addr(res))
        duckdb_disconnect(addr(con))
        resp $qvals # returns to the browser a slice/array from the table
```

**Comment by Mytherin** [comment]
> In the future, I could see myself using the SQLite reader (once it has been developed) to meet this use case. All the inserts could go into SQLite and then DuckDB could periodically read and process some bigger analytical queries from that SQLite DB!

Yes, that could certainly work. Although remember that SQLite's format is a row-store, not a column-store, so queries will likely be (somewhat) slower especially on wider tables.

**Comment by sdmcallister** [comment]
> Are your read-only connections short-lived, or do they keep the database open persistently?

They could be short lived. I could open and close read-only instances in each route. But I wonder about performance overhead. Is there much overhead for initializing a readonly or read-write instance?

At the same time I have realized that I was limiting myself to my current workflow which relies on a cli. I can also allow the application to take control using a persistent read-write instance and interact with the application using an http client as opposed to the cli, but I do like the duckdb/sqlite cli.

**Comment by Admolly** [comment]
Would it be possible to set some variable to indicate the last time at which the database file was updated, and only re-read it whenever that value changes?

**Comment by aaronsteers** [comment]
I wanted to propose an alternative implementation here and get thoughts around this.

Starting from [this](https://github.com/duckdb/duckdb/issues/2192#issuecomment-907387573) from above as a given:

> ...multi-process access to the same database file is currently limited to multiple read_only connections, i.e. you can either have multiple readers OR a single writer, not both at the same time.

## Prioritizing write over read

Focusing on this sample use case:

1. I want to have one or more read-only clients open lazily for data exploration and testing. For example, the CLI or the SQLTools client in VS Code, or DBeaver, or similar.
2. I _still_ want to be able to execute `dbt run` while those explorers are open.
3. It's acceptable if the readers have their connections broken when write operations invalidate their sessions. The client software (DBeaver, SQLTools. etc) will anyway try to reconnect when the user returns focus to their session.
4. As long as the expectations are made clear, it's okay if the readers are using stale data for a while, especially if prioritizing shortest disruption time (see below).

The above assumes that the multiple readers and the single writer are basically the same person. And by deciding to perform a write operation like `dbt run`, they knowingly accept that this may break other existing connections.

The above proposes we prioritize writers not being blocked by readers, perhaps as an opt-in behavior on behalf of the read-only client, and especially when the connection is open and no queries are active.

### Reducing downtime with read-replicas aka database snapshots

Now, with this approach, there's also a mitigation step we can perform to reduce disruption to the shortest possible window, which is periodic swapping/replication of the write-only database file to a read-replica or "snapshot db" file.

Rather than forcing readers offline for the duration of the `dbt run` operation, we could keep a copy of the prior data before the dbt run operation starts, and only bring readers down after (and if) `dbt run` completes successfully. Then, the outage or mandatory disconnect period for read-clients could be a few seconds long rather than for the duration of the entire write operation.

----

Is something like this possible today with existing functionality, or with some clever custom workarounds?

**Comment by blacelle** [comment]
> Is something like this possible today with existing functionality such as [EXPORT DATABASE](https://duckdb.org/docs/sql/statements/export) to a dedicated snapshot directory for readers, or with some other clever custom workarounds?

Could the CLI, instead of connecting as `-readonly`, trigger an `EXPORT DATABASE`-like (to be run by the READ_WRITE process? Not exporting in CSV|Parquet but with native DuckDB format?), hence enabling reading a safepoint without interrupting the read-write process?
