### ISSUE TITLE
Path issues when using CREATE VIEW for csv or parquet file and calling DuckDB from a different folder

### ISSUE THREAD

**Issue by sahuguet** [duckdb/duckdb#2342]
**What does happen?**
I am creating a database with a view for a file in the root directory.
I am using DuckDB+Python from a sub-directory.
When I run the query, DuckDB complains that the file does not exist.

**What should happen?**
The database should keep track of the absolute path of the file.

**To Reproduce**

```
% cat test.csv
id,name
1,duck

./duckdb test.db
CREATE view test AS SELECT * from 'test.csv';

% cd sub_folder
% cat test.py
import duckdb
import pandas as pd
con = duckdb.connect('../test.db', read_only=True)
data_df = con.execute('SELECT * FROM test').fetchdf()
print(data_df)

% python test.py
data_df = con.execute('SELECT * FROM test').fetchdf()
RuntimeError: IO Error: No files found that match the pattern "test.csv"

```

**Environment (please complete the following information):**
 - OSX 11.6
 - v0.2.9 1776611ab

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by nitinprakash96** [comment]
This issue persists even in duckdb `v0.8.1`.
Is this intentional @Mytherin

**Comment by Mytherin** [comment]
Yes, this is intentional. Views preserve the original query as submitted by the user and re-execute the query when referenced. If you change any external parameters that the view relies on (e.g. remove external files, change the working directory, or move the database file to a different computer) then the view might no longer work.

If you want to query an absolute path, you can manually specify the absolute path in the view definition.
