### ISSUE TITLE
Export Command creates wrong schema

### ISSUE THREAD

**Issue by Manerone** [duckdb/duckdb#2466]
#### What happens?

The command `EXPORT DATABASE` command creates a wrong schema when the data comes from a Pandas Dataframe.

#### To Reproduce

```Python3
import duckdb
import pandas as pd


# Create DataFrame with category attribute
df = pd.DataFrame({"id": [0, 1], "city": ["Amsterdam", "New York"]})
df["city"] = df["city"].astype("category")

# Copy Dataframe to DuckDB
con = duckdb.connect()
con.register("df", df)
con.execute(
    f"""
    CREATE TABLE t1 AS SELECT * FROM df
"""
)
con.unregister("df")

# Export the database
con.execute(
    f"""
    EXPORT DATABASE 'import_bug' (HEADER TRUE)
    """
)
con.close()


# Import database
con = duckdb.connect()
con.execute(
    f"""
    IMPORT DATABASE 'import_bug'
    """
)
```
I get the following error:
```
RuntimeError: Not implemented Error: DataType city not supported yet...
```

Which happens because the schema.sql looks like:
```SQL
CREATE TABLE t1(id BIGINT, city city);
```
#### Environment (please complete the following information):
 - OS: Mac BigSur 11.4
 - DuckDB Version: '0.3.1-dev287'
 - DuckDB Client: Python3

**Comment by pdet** [comment]
I guess that makes sense, when I added the enums for categoricals I did not intend to create them in the catalog since they seemed to be more transient.

But maybe they should be added there, otherwise is too much of a hippie-land, this will facilitate storage of these tables and allow for enum casting.

The downside I can think of is naming, right now I just use the name of the column as the type, which works out nicely even if the same table has two different enums with the same column name, on the other hand, this is again not sufficiently strict and confusing.

Any thoughts here @Mytherin ? I guess we should add these things in the catalog, if there is a catalog conflict check if they are the same, if not add a counter to distinguish it (e.g., _1)

**Comment by Manerone** [comment]
Yes, I want to :D
We can talk about it in a second.

**Comment by pdet** [comment]
New battle-plan to solve the Export on categorical/factor dependent ENUMs:

Right now we have this EXPORT problem for enums that come from Pandas. What if we can just define enums in-place as a type e.g. we could just do something like
```sql
SELECT 'sad'::ENUM(sad, happy, ...)
 ```
Then we wouldn't need a dependency on an external type for enums anymore.
