### ISSUE TITLE
I can't read from a parquet file with C API

### ISSUE THREAD

**Issue by kimmolinna** [duckdb/duckdb#2505]
I have csv-file and parquet-file in a same folder and I can SELECT count(*) FROM both with DuckDB client.
```
D select count(*) from 'file.parquet';
┌──────────────┐
│ count_star() │
├──────────────┤
│ 21754        │
└──────────────┘
D select count(*) from 'salary.csv';
┌──────────────┐
│ count_star() │
├──────────────┤
│ 65           │
└──────────────┘
```
But if I try to same selects via C API the csv-file works nicely but the parquet-file gives the following error message:
`Catalog Error: Table with name file.parquet does not exist!`

I'm using libduckdb which is built with the following commands from `https://github.com/duckdb/duckdb/archive/refs/tags/v0.3.0.tar.gz`
```
cd build
cmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DDISABLE_UNITY=TRUE -DENABLE_SANITIZER=FALSE -DBUILD_UNITTESTS=FALSE ..
make -j${nproc}
make install
```

What should I do to get a support for parquet-files for C API?

**Comment by SartorialOffense** [comment]
I am looking for the exact same thing and I am pretty desperate because this is going to save me so much time querying Parquet files.  

I am primarily a C# programmer and I don't have this working yet, so excuse anything I get terribly wrong.  You need to compile with the parquet extensions in there.  Normally you munge all the code into an "amalgamation file" before compilation using `scripts/amalgamation.py`.  This script works for me on my Windows machine. If you need the parquet extensions, there is a separate 'scripts/parquet_amalgamation.py' you need to run - this is failing for me.  Looks like the script is grabbing the needed files from the includes in `extension\parquet\parquetcli.cpp` but can't find `parquet-amalgamation.hpp`:

`Could not find include file "parquet-amalgamation.hpp", included from file "extension\parquet\parquetcli.cpp`

I can't find this file yet, but `parquetcli.cpp`  compiles for me so I assume it is pulling it out of a lib or something. I have to stop for the day...

Ref:
#1604 #2176

**Comment by SartorialOffense** [comment]
So the problem with the `parquet-amalgamation.hpp` error message above is that that the `need_to_write_file` method in `amalgamation.py` isn't filtering this out from the includes when run on a Windows box.  So:

`amalgamation.always_excluded += ['extension/parquet/parquetcli.cpp']`

Should likely be:

`amalgamation.always_excluded += [os.path.sep.join('extension/parquet/parquetcli.cpp'.split('/'))]`

**Comment by Mytherin** [comment]
I'm having a go at fixing this.

**Comment by SartorialOffense** [comment]
That would be fantastic.

**Comment by Mytherin** [comment]
This should be fixed in the master now, compiling with `-DBUILD_PARQUET_EXTENSION=1` should create a library that automatically links in the parquet extension.

**Comment by SartorialOffense** [comment]
@Mytherin Works great, thanks!

**Comment by kimmolinna** [comment]
@Mytherin I have used following code to build versions for different platforms and it's not working anymore with `-DBUILD_PARQUET_EXTENSION=1` for mingw32. Could you help with this?

```bash
# Bash recipe for building across all platforms
script = raw"""
cd $WORKSPACE/srcdir
cd duckdb*/
if [[ "${target}" == *-mingw32 ]]; then
    sed -i -E "/add_executable\(duckdb_rest_server server.cpp\)$/aif\(\$\{WIN32\}\)\n  set\(LINK_EXTRA -lwsock32 -lws2_32\)\nendif\(\)\n" tools/rest/CMakeLists.txt
fi
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DBUILD_PARQUET_EXTENSION=1 -DDISABLE_UNITY=TRUE -DENABLE_SANITIZER=FALSE -DBUILD_UNITTESTS=FALSE ..
make -j${nproc}
make install
if [[ "${target}" == *-mingw32 ]]; then
    mkdir -p ${libdir}
    cp src/libduckdb.${dlext} ${libdir}
fi
"""
```

**Comment by Mytherin** [comment]
You will likely need to link to the Parquet extension, which is a library that gets built in the `extension` folder. e.g. on linux:

```
build/debug/extension/parquet/libparquet_extension.a
```
