### ISSUE TITLE
Support for reading nested data with heterogeneous field types

### ISSUE THREAD

**Issue by gleec14** [duckdb/duckdb#2525]
#### What happens?
DuckDB is unable to read nested data in parquet files containing fields of different types.
```
java.sql.SQLException: Unsupported result column type STRUCT<timeVar: TIMESTAMP, timeVarTwo: TIMESTAMP, intVar: INTEGER, boolVar: BOOLEAN, boolVarTwo: BOOLEAN>
	at org.duckdb.DuckDBNative.duckdb_jdbc_fetch(Native Method)
	at org.duckdb.DuckDBResultSet.<init>(DuckDBResultSet.java:46)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:90)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:100)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:128)
```

#### Environment:
 - OS: Windows 10
 - DuckDB Version: 0.3.0
 - JDK Version: 11

**Comment by Mytherin** [comment]
The error seems to be in the JDBC client and not in the Parquet reader. The JDBC client doesn't support nested types yet. As a temporary work-around you could add a cast to string for this column, or extract individual columns from the struct in the SQL expression.

**Comment by Alex-Monahan** [comment]
I just ran into this as well in DBeaver. Using list_column[0] or cast(list_column as varchar) worked like you said!

**Comment by chrisfw** [comment]
Hello, I am trying to access values in a nested struct and I am not sure how/if this can be accomplished with Duckdb.  Given the nested struct below stored in a parquet column, how does one access the DetailBlock DetailAmt value using SQL?

Regards,
Chris Whelan

```
{
  "DetailLine": [
    {
      "element": {
        "DetailHeading": "CURRENT TRANS FEES",
        "DetailSubRecord": [
          {
            "element": {
              "DetailApplication": 3,
              "DetailBankedUsage": 0,
              "DetailBlocks": {
                "DetailBlock": [
                  {
                    "element": {
                      "DetailAmt": -10.5,
                      "DetailRate": 0,
                      "DetailTierNumber": 1,
                      "DetailTierType": 0,
                      "DetailTierUse": 0,
                      "DetailUsage": 0,
                      "DetailUsageXRate": 0
                    }
                  ...
```

**Comment by Alex-Monahan** [comment]
> Hello, I am trying to access values in a nested struct and I am not sure how/if this can be accomplished with Duckdb. Given the nested struct below stored in a parquet column, how does one access the DetailBlock DetailAmt value using SQL?
> 
> Regards, Chris Whelan
> 
> ```
> {
>   "DetailLine": [
>     {
>       "element": {
>         "DetailHeading": "CURRENT TRANS FEES",
>         "DetailSubRecord": [
>           {
>             "element": {
>               "DetailApplication": 3,
>               "DetailBankedUsage": 0,
>               "DetailBlocks": {
>                 "DetailBlock": [
>                   {
>                     "element": {
>                       "DetailAmt": -10.5,
>                       "DetailRate": 0,
>                       "DetailTierNumber": 1,
>                       "DetailTierType": 0,
>                       "DetailTierUse": 0,
>                       "DetailUsage": 0,
>                       "DetailUsageXRate": 0
>                     }
>                   ...
> ```

Hello!

Could you tell us which client you are using, send over the query you are trying and a small sample of your parquet file? You can likely use our new JSON extension to query it directly, or parse to DuckDB's native structs then query even more quickly!

**Comment by chrisfw** [comment]
Hi, thanks for your quick response.  That sounds promising!  I am using the CLI.  Yes, I can provide you with a sample file, but I need to scrub the PII first.  I will upload it as soon as I have done that.
Thanks,
Chris

```
D pragma version;
┌─────────────────┬───────────┐
│ library_version │ source_id │
├─────────────────┼───────────┤
│ v0.3.1          │ 88aa81c6b │
└─────────────────┴───────────┘
```

**Comment by chrisfw** [comment]
Hello, attached per your request is a sample parquet file with columns that contain complex nested structs.
Thanks for your assistance.

Regards
[sample.zip](https://github.com/duckdb/duckdb/files/8516151/sample.zip)
,
Chris Whelan

**Comment by Mytherin** [comment]
It looks like you are using an old version of DuckDB (0.3.1). I would recommend switching to the latest version, as this seems to work fine for me on the latest version:

```sql
D select AcctNum, DetailLines.DetailLine[1] from sample_view;
┌────────────┬────────────────────────────────────────────────────────────────────────────────────┐
│  AcctNum   │                           "DetailLines"."DetailLine"[1]                            │
├────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ 1433223000 │ {'DetailHeading': CURRENT CHARGES, 'DetailSubRecord': [{'DetailApplication': 3,... │
└────────────┴────────────────────────────────────────────────────────────────────────────────────┘
D select AcctNum, DetailLines.DetailLine[1].DetailHeading from sample_view;
┌────────────┬─────────────────────────────────────────────────┐
│  AcctNum   │ ("DetailLines"."DetailLine"[1])."DetailHeading" │
├────────────┼─────────────────────────────────────────────────┤
│ 1433223000 │ CURRENT CHARGES                                 │
└────────────┴─────────────────────────────────────────────────┘

```

**Comment by chrisfw** [comment]
Hi Mark,

Thanks for the information you provided, that worked.  However, is it
possible to extract the contents of the array as a table or view?   There
was mention of new json support and I am looking to be able to access all
of the content of these nested arrays rather than being limited to indexing
specific elements.  Is there a capability available or on the horizon
similar to Oracle's json_table approach?

By the way, I just want to say thank you to the team and contributors to
this project and that the work you have all been doing on duckdb is nothing
short of amazing!

Regards,
Chris

**Comment by Alex-Monahan** [comment]
I think the unnest table function will get you at least partway there! You can also convert JSON to DuckDB's native struct/list types for speed of access.
https://duckdb.org/docs/sql/query_syntax/unnest
https://duckdb.org/docs/extensions/json

Does that help?

**Comment by chrisfw** [comment]
Thanks Alex, that does help somewhat, but it appears depending on the depth
of the array I want to unnest, I still have to choose a specific index if
there is an array item higher up in the structure as in the example below
where DetailLine has to be indexed in order to unnest DetailSubRecord.

select AcctNum, unnest(DetailLines.DetailLine[1].DetailSubRecord)  from
sample_view;

I am not sure how to apply the json angle since I am trying to retrieve
nested parquet struct elements/arrays as tabular data.  In Oracle's case
they transform the nested parquet structs to json when exposing the parquet
file as an external table and then I can use the json_table function to
generate the tabular data.

Below is an example of how I can achieve this nested struct/array to
tabular data in Oracle

select b.detaillines, b.LastName,B.acctnum,B.InvoiceNum,
DetailSubRecord.DetailAmount, DetailSubRecord.DetailUsage from billing_ext2
b,json_table(b.DetailLines
    COLUMNS(NESTED
DetailLine[*].element.DetailSubRecord[*].element.DetailBlocks.DetailBlock[*]
       COLUMNS(DetailApplication NUMBER PATH '$.element.DetailApplication',
               DetailAmount NUMBER  PATH '$.element.DetailAmt',
               DetailUsage NUMBER  PATH '$.element.DetailUsage'
       ))) as DetailSubRecord
where b.filename = 'file:/home/spark/billing/bill.xml'
and DetailSubRecord.DetailAmount is not null
order by b.AcctNum;

Yielding:

"ACCTNUM","LASTNAME","TOTALDETAILAMOUNT","TOTALDETAILUSAGE"
751288300,"MINI GOLF
EMPOREUM",1615.799999999999952609,60848553.816000000000000204
251276300,"JONESVILLE MIDDLE
SCHOOL",780.910000000000021055,51129979.09999999999006006
382711300,"THE INN AT JONESVILLE",66837.60999999999966691,29901673717.86
266934300,"COMPUTER TECHNOLOGY CENTER",1274.76999999999997022,154.54

Regards,
Chris

**Comment by Alex-Monahan** [comment]
Ah, so that is a pivoting capability. Today we don't have a function for that, but it is on the roadmap for the Relational API. 

Today, I have to do my pivoting in 1 of 2 ways: pivot using an external library like Python's Pandas, or dynamically build a SQL query based on the "stacked" data, and then run that second query to pivot it out.

**Comment by chrisfw** [comment]
Ok, thank you for following up and the additional information.  Sounds good.  I look forward to that functionality and will keep my on the releases.

Regards,
Chris

**Comment by Mause** [comment]
Nested type support was added to the JDBC api in #7000, and PIVOT functionality has also been added, so I'm going to close this
