### ISSUE TITLE
Can we get pre-release versions for linux?

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#2541]
I noticed that the pre-release versions, specifically 0.3.1.dev*, are available for mac and windows, but not for linux. If possible can we get the linux versions released as well? I've been trying to test whether bugs are fixed, but I can't do it on my linux box.

**Comment by Mytherin** [comment]
Yes, this is not intentional but is temporarily broken because our Linux Python builds are not finishing. The problem we ran into is that several libraries we depend on removed wheel support for Python 3.6, which caused the build times of our Python 3.6 builds to go up from 5 minutes to ~1 hour. As we build [many Python 3.6 versions for Linux](https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip) this caused our Linux Python CI jobs to exceed the maximum 6 hour time slot, which results in the binaries not being uploaded. @pdet is working on a fix for this.

**Comment by carlopi** [comment]
I believe this has since been fixed, nightly builds artifacts can be found at the bottom of CI results like here: https://github.com/duckdb/duckdb/actions/runs/4333959853.
