### ISSUE TITLE
copy to parquet.zst and parquet file fail. copy to csv.zst is ok.

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2715]
#### What happens?
copy to parquet.zst and parquet file fail. copy to csv.zst is ok.

#### To Reproduce
copy to parquet.zst and parquet file fail. copy to csv.zst is ok.
v0.3.2-dev330 ae8562793
```
D create table t as(select i,i::varchar j from range(10000)t(i));
D copy t to 'd:/t.csv.zst';
D select count(*) from 'd:/t.csv.zst';
┌──────────────┐
│ count_star() │
├──────────────┤
│ 10000        │
└──────────────┘

D copy t to 'd:/t.parquet.zst';
D select count(*) from 'd:/t.parquet.zst';
Error: Catalog Error: Table with name d:/t.parquet.zst does not exist!
Did you mean "t"?
LINE 1: select count(*) from 'd:/t.parquet.zst';
                             ^

D copy t to 'd:/t.parquet';
D select count(*) from 'd:/t.parquet';
Error: Invalid Input Error: No magic bytes found at end of file 'd:/t.parquet'
```
#### Environment (please complete the following information):
 - OS: [e.g. iOS]windows7 x64
 - DuckDB Version: [e.g. 22]0.3.2dev
 - DuckDB Client: [e.g. Python]CLI

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
In order to copy to parquet files you need to specify `(FORMAT PARQUET)`, this is not yet inferred from the file extension, e.g.:

```sql
create table t as(select i,i::varchar j from range(10000)t(i));
copy t to 't.parquet' (FORMAT PARQUET);
select count(*) from 't.parquet';
```

We should probably infer this as well.

Copying to ZSTD compressed or GZIP compressed Parquet files where the entire file is compressed is not supported. Instead, the Parquet format has compression internally. You can specify which compression to use as a parameter to the COPY TO function:

```sql
create table t as(select i,i::varchar j from range(10000)t(i));
copy t to 't.parquet' (FORMAT PARQUET, COMPRESSION ZSTD);
select count(*) from 't.parquet';
```

Compressing the entire file (a) does not work because reading Parquet files requires jumping around to random locations, which is not possible in compressed files, and (b) has essentially no effect because the Parquet files are already compressed internally, and compressing the file twice will not accomplish much.

**Comment by l1t1** [comment]
thanks.
