### ISSUE TITLE
Parquet export alters table names

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb#2733]
#### What happens?
When exporting duckdb tables to parquet, the resulting parquet files are named based on sanitized versions of the table names: all uppercase are converted to lowercase (ok fine), and all digits are converted to underscores, and a number is prepended.  Luckily this can't create collisions of names, since at least all tables are then prefixed by a number, but I would still prefer the original table names.  
`duckdb` helpfully generates a `load.sql` file mapping the mangled file-names back to their original table-names, which is helpful.  However, because `duckdb` now has the *amazing* ability to read the parquet files directly, I really don't want to run `load.sql` at all, I just want to point duckdb at these nice portable parquet files it just made.  It would be wonderful if duckdb would generate a `parquet.sql` file in this case, or more simply, just not mangle the table names used for the parquet files?

No doubt there are good reasons I'm overlooking for doing this, maybe related to #2075 and backwards compatibility, but it seems unnecessary here?   

#### To Reproduce

https://duckdb.org/docs/sql/statements/export

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: current release
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
We could offer a `VIEW` option along with the EXPORT that would generate `CREATE VIEW` statements instead of `CREATE TABLE` statements. `IMPORT` will then just create a bunch of views over the Parquet files. Perhaps that would be useful?

The mangling of names is related to not wanting to deal with any issues arising from strange characters in table names or e.g. file insensitivity of file systems. Lowercasing only happens related to #2075 if the tables are created unquoted from the parser, the case of quoted table names are preserved. We couldadd a flag to disable this, but `EXPORT` is not really intended for creating "human-readable" files. It is mostly intended to create files that will be loaded with an `IMPORT` again. If you want parquet files with specific names can't you use [COPY](https://duckdb.org/docs/sql/statements/copy)?

**Comment by cboettig** [comment]
Thanks Mark, yeah, I could probably just auto-generate my COPY commands (even through the EXPORT 1-liner is nice).  The CREATE VIEW .sql file would be a nice addition on parquet export.
