### ISSUE TITLE
compile in gcc 11.1 Android version error

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2771]
an apk file or binary file. 
thanks.

**Comment by l1t1** [comment]
sth like https://clickhouse.com/blog/en/2020/pixel-benchmark/

**Comment by l1t1** [comment]
or sth like https://sqlite.org/2021/sqlite-android-3370000.aar
A precompiled Android library containing the core SQLite together with appropriate Java bindings, ready to drop into any Android Studio project.

**Comment by l1t1** [comment]
sqlite compile by source works on Android
gcc -DSQLITE_THREADSAFE=0 shell.c sqlite3.c -ldl -lm -o sqlite3

**Comment by l1t1** [comment]
duckdb compile is much slower than sqlite (10 s vs many min)

g++ appender.cpp duckdb.cpp -o b.out -ldl -lm -lpthread -std=c++11

**Comment by l1t1** [comment]
[error.txt](https://github.com/duckdb/duckdb/files/7698144/error.txt)
error msg of g++ 11.1 ofAndroid that comes from pydroid 3.

**Comment by l1t1** [comment]
Android version 11
mem 6GB
pydroid 3 5.0
[appender.cpp.txt](https://github.com/duckdb/duckdb/files/7698155/appender.cpp.txt)

**Comment by Mytherin** [comment]
> duckdb compile is much slower than sqlite (10 s vs many min)

That is completely expected, DuckDB has many more functions/aggregates/etc available than SQLite, and support for far more types in all layers of the system (storage, functionality, etc). Many of these functions are templated over the different types to allow for more efficient processing, at the cost of increased compilation time.

C++ also just takes much longer to compile in general than C since the many zero-cost abstractions used there are really only zero-cost at run-time. The compiler needs to perform optimizations to make these abstractions actually zero-cost, which again has a cost during compilation.

> error msg of g++ 11.1 ofAndroid that comes from pydroid 3.

The only error there is that you run out of memory:

> virtual memory exhausted: Out of memory

I recommend either using a system with more memory for compilation, or not using the amalgamation build. Compiling the entire system in a single file is the reason you are running out of memory.

Closing this, as there is no actual error here that we can act on or fix.

**Comment by l1t1** [comment]
thanks.
and how to remove the warning messages？

**Comment by l1t1** [comment]
https://github.com/termux/termux-packages/issues/8266#event-5821864811
