### ISSUE TITLE
RuntimeError: Not implemented Error: DataType year not supported yet...

### ISSUE THREAD

**Issue by benbensenton** [duckdb/duckdb#2976]
#### What happens?
using Data types YEAR, MONTH, DAY or SEQUENCE during table creation raises :

'RuntimeError: Not implemented Error: DataType year not supported yet...'

#### To Reproduce
conn.execute("CREATE TABLE calendar(date YEAR)")

#### Environment (please complete the following information):
 - OS: [Windows]
 - DuckDB Version: [0.3.1]
 - DuckDB Client: [Python]

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment]
@hawkfish I assume `YEAR` is not a type you like since its binning-related and there is no instant to bind this to? Any thoughts on this?

**Comment by Mytherin** [comment]
The error message "`DataType X is not supported yet...`" is the standard error message for any data type. We should remove the "yet..." to avoid confusion since that implies we are intending to add support for that data type in the future, when that might not be the case.

The discussion here is if we want to have these data types, and this is a feature request for adding these data types.

As far as I can tell, the [`YEAR` data type is supported in MySQL](https://dev.mysql.com/doc/refman/8.0/en/year.html). We might consider supporting this type for MySQL compatibility, although this type seems to be a bit evil, since it has these types of nasty pitfalls:

> As 1- or 2-digit strings in the range '0' to '99'. MySQL converts values in the ranges '0' to '69' and '70' to '99' to YEAR values in the ranges 2000 to 2069 and 1970 to 1999.

I can find no system that supports the `MONTH` or `DAY` data types. I also don't see a big reason not to use a regular numeric here, you will need to have a multi-column constraint to properly constrain these to valid values in the first place. And really, if you are storing a YEAR, MONTH and DAY you should really store these in a single date field in the first place. 

I can also not find any system that supports the `SEQUENCE` data type. Perhaps you meant to use the `SERIAL` type here (which DuckDB also does not yet support, but we actually do intend to support in the future).

**Comment by hawkfish** [comment]
I can see a value to validated user-defined types, but `YEAR` seems like a stretch. Also, I would not recommend emulating MySQL's temporal types - they allow dates to have months and days of zero to indicate indeterminate point in the period. I've never seen a situation where truncation didn't make more sense.
