### ISSUE TITLE
[node.js] Is `connection` doesn't need to close?

### ISSUE THREAD

**Issue by le0pard** [duckdb/duckdb#2977]
Hello.

Thanks for your work and this awesome db.

I am trying to do some tests with node.js client and in the doc, I see this option:

> However, these are all shorthands for something much more elegant. A database can have multiple Connections, those are created using db.connect().

 > var con = db.connect();

> You can create multiple connections, each with their own transaction context.

As I can see, for python client exists method `close` connection after it usage. But node.js client said:

```js
TypeError: connection.close is not a function
```

Does this mean, that node.js connections no need to close? Or does this method was just missed from node.js client API?

node.js client version: 0.3.1

**Comment by Alex-Monahan** [comment]
Hello and thanks for trying out DuckDB!

I believe the close function is on the database object itself rather than the individual connections. However, I don't know the way to close them one at a time.

[Here is an example of the db.close() approach](https://github.com/duckdb/duckdb/blob/6c7c9805fdf1604039ebed47d233ea55cabb4b2c/tools/nodejs/test/parallel_insert.test.js)

**Comment by le0pard** [comment]
@Alex-Monahan thanks. Does this mean, that no need to close connections and node.js process and in the end it will not have memory leak of not closed connections?
