### ISSUE TITLE
Bug in parse_profiling_output javascript ?

### ISSUE THREAD

**Issue by 9prady9** [duckdb/duckdb#3062]
#### What happens?
The python helper `duckdb_query_graph` seems to have a bug in the javascript file used from the generated html file. 

[This line](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/duckdb_query_graph/parse_profiling_output.js#L20) generates an error unless the variable `timing` is wrapped around in a `ParseFloat` call. This essentially renders the generated html non-viewable even though the data is all good.

#### To Reproduce
Steps from  https://duckdb.org/dev/profiling
```SQL
-- enable profiling in json format
PRAGMA enable_profiling='json';
-- write the profiling output to a specific file on disk
PRAGMA profile_output='/path/to/file.json';
```
```python
import duckdb_query_graph
duckdb_query_graph.generate('/path/to/file.json', '/path/to/out.html')
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.2, current master also doesn't have parseFloat call, so it must be also effected.
 - DuckDB Client: Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by NickCrews** [comment]
All of this code was removed in https://github.com/duckdb/duckdb/pull/6972.

Is there any planned workaround for this removed functionality? Since writing profiling to json seems to be supported still, I think there should be some officially supported way to visualize the output. Maybe just in a different repo under the duckdb org? If there is no officially supported parser, then we should remove `PRAGMA profiling_output`, since there is no way to deal with it.
