### ISSUE TITLE
Tests on the line after foreach are silently ignored

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#3078]
I ran into this while testing #2498:

```sql
foreach datatype <alltypes>
query I
SELECT HASH(NULL::${datatype})
----
<incorrect value>

endloop
```

was not failing because the test was not. being run.

**Comment by samansmink** [comment]
have ran into this as well, but with require:

fails:
```
require parquet
require tpch

statement ok
CALL DBGEN(sf=0.01)
```

works:
```
require parquet

require tpch

statement ok
CALL DBGEN(sf=0.01)
```

I believe the reason is that every test statement needs to be separated with a newline. For some types of statements like `query II` or `statement ok` this is intuitive, but for require and foreach is seems a little confusing. 

It appears to have to do with the lines 31-33 from test/sqlite/sqllogic_parser.cpp:
```
while (current_line < lines.size() && !EmptyOrComment(lines[current_line])) {
    current_line++;
}
```

A quick and dirty hack would be to run this after single line statements such as require and foreach:
```
parser.seen_statement = false;
parser.NextLine();
```

ill make it a bit nicer and submit a pr

**Comment by samansmink** [comment]
After quick discussion with mark we've reconsidered: a better solution would be to just throw a parser error when tests statements are not separated by newlines as this is more consistent.
