### ISSUE TITLE
FR: implement Arrow Flight SQL

### ISSUE THREAD

**Issue by domoritz** [duckdb/duckdb#3099]
https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/.

Flight SQL is a new client-server protocol developed by the Apache Arrow community for interacting with SQL databases that makes use of the Arrow in-memory columnar format and the Flight RPC framework.

It would make a lot of sense for DuckDB since flight SQL works best with columnar databases like DuckDB. 

Here is a client implementation for SQLite: https://github.com/apache/arrow/blob/release-7.0.0/cpp/src/arrow/flight/sql/example/sqlite_server.cc

**Comment by hamilton** [comment]
This would be fantastic, especially if it were at the engine / extension level & not solely for Python & R. I hope that in general the programmatic case w/ multiple clients can be supported. I know the arrow support in duckdb seems to be restricted to Python & R today and this is already kind of a bummer for data application development.

**Comment by domoritz** [comment]
https://github.com/duckdb/duckdb-wasm also uses Arrow to move data between the wasm and the js contexts.

**Comment by hamilton** [comment]
Great to hear. I would love something like this for the node module as well.

**Comment by wangfenjin** [comment]
Arrow is also supported in c-api, so any language that can interact with C API should be able to support arrow

**Comment by wangfenjin** [comment]
As duckdb tries to avoid external dependencies, not sure if it's easy to support flight sql in duckdb core. Maybe it's better to be support as an extension or a 3rd party component

**Comment by hannes** [comment]
I think it makes more sense for us to implement ADBC: https://docs.google.com/document/d/1t7NrC76SyxL_OffATmjzZs2xcj1owdUsIF2WKL_Zw1U/edit#heading=h.r6o6j2navi4c

**Comment by prmoore77** [comment]
Hi - we have implemented an example Flight SQL Server with DuckDB as a back-end here: https://github.com/voltrondata/flight-sql-server-example

Contributions are welcome!

**Comment by prmoore77** [comment]
@gizmodata maintains an open-source C++ Flight SQL Server with DuckDB (and SQLite) here: https://github.com/gizmodata/gizmosql

@tfmv maintains an open-source Go-based Flight SQL Server with DuckDB here: https://github.com/tfmv/porter

**Comment by domoritz** [comment]
Unfortunately I learned in the meantime that flight doesn't really work in browsers which would be my main use case. We're using a simple rest interface with sql queries and ipc responses instead.

**Comment by prmoore77** [comment]
> Unfortunately I learned in the meantime that flight doesn't really work in browsers which would be my main use case. We're using a simple rest interface with sql queries and ipc responses instead.

Ah - good point.  I had the same exact issue.  I wrote a web-socket proxy around Flight SQL to make it easy to use with javascript-based clients (web browsers):

https://pypi.org/project/flight-sql-websocket-proxy/

That's what powers my "try GizmoSQL" app: https://gizmosql.gizmodata.com

Your approach is more straightforward, however...

**Comment by prochac** [comment]
Do we speak here about DuckDB being the backend to FlightSQL interface, or DuckDB being a client?

DuckDB [can connect to Postgres](https://duckdb.org/docs/stable/core_extensions/postgres.html), but I haven't found a way to connect to the Flight SQL server.
Smth like this:
```
ATTACH 'flightsql://host:port' AS remote;
```

**Comment by prmoore77** [comment]
> Do we speak here about DuckDB being the backend to FlightSQL interface, or DuckDB being a client?
> 
> DuckDB [can connect to Postgres](https://duckdb.org/docs/stable/core_extensions/postgres.html), but I haven't found a way to connect to the Flight SQL server. Smth like this:
> 
> ```
> ATTACH 'flightsql://host:port' AS remote;
> ```

In the case of [GizmoSQL](https://github.com/gizmodata/gizmosql) - DuckDB is the back-end (not the client).  It would be cool to have DuckDB a client interface to Flight SQL though, as it would allow one to easily share data.

The [Airport extension](https://airport.query.farm) does allow DuckDB to be a Flight client, however - so that is somewhat close...

**Comment by prochac** [comment]
> > Do we speak here about DuckDB being the backend to FlightSQL interface, or DuckDB being a client?
> > DuckDB [can connect to Postgres](https://duckdb.org/docs/stable/core_extensions/postgres.html), but I haven't found a way to connect to the Flight SQL server. Smth like this:
> > ```
> > ATTACH 'flightsql://host:port' AS remote;
> > ```
> 
> In the case of [GizmoSQL](https://github.com/gizmodata/gizmosql) - DuckDB is the back-end (not the client). It would be cool to have DuckDB a client interface to Flight SQL though, as it would allow one to easily share data.
> 
> The [Airport extension](https://airport.query.farm) does allow DuckDB to be a Flight client, however - so that is somewhat close...

Thanks for the GizmoSQL, so far I just saw [sqlflite](https://github.com/voltrondata/sqlflite). I may use it as an inspiration too, now.
Because, I'm also reinventing the wheel, working on FlightSQL server, written in Go 😅 
When it comes to DuckDB FlightSQL backend, I kinda don't mind having some kind of wrapper. My goal is to load a proper DuckDB database based on credentials etc. And that's something that duckdb on its own can't handle with "duckdb -flightsql" (like `duckdb -ui`, but running FlightSQL)
Although, having an option to join DuckDB, Postgres, Clickhouse, GBQ, etc. in my local DuckDB, that would be nice. What's the alternative to this? I guess only running some Python script locally.

**Comment by prmoore77** [comment]
> > > Do we speak here about DuckDB being the backend to FlightSQL interface, or DuckDB being a client?
> > > DuckDB [can connect to Postgres](https://duckdb.org/docs/stable/core_extensions/postgres.html), but I haven't found a way to connect to the Flight SQL server. Smth like this:
> > > ```
> > > ATTACH 'flightsql://host:port' AS remote;
> > > ```
> > 
> > 
> > In the case of [GizmoSQL](https://github.com/gizmodata/gizmosql) - DuckDB is the back-end (not the client). It would be cool to have DuckDB a client interface to Flight SQL though, as it would allow one to easily share data.
> > The [Airport extension](https://airport.query.farm) does allow DuckDB to be a Flight client, however - so that is somewhat close...
> 
> Thanks for the GizmoSQL, so far I just saw [sqlflite](https://github.com/voltrondata/sqlflite). I may use it as an inspiration too, now. Because, I'm also reinventing the wheel, working on FlightSQL server, written in Go 😅 When it comes to DuckDB FlightSQL backend, I kinda don't mind having some kind of wrapper. My goal is to load a proper DuckDB database based on credentials etc. And that's something that duckdb on its own can't handle with "duckdb -flightsql" (like `duckdb -ui`, but running FlightSQL) Although, having an option to join DuckDB, Postgres, Clickhouse, GBQ, etc. in my local DuckDB, that would be nice. What's the alternative to this? I guess only running some Python script locally.

Yeah - I am interested in a Go-based Flight SQL Server as well.  I saw this project: https://github.com/TFMV/porter - which has the beginnings of it.  I had some trouble using it from JDBC, however.  The author of porter mentioned it (formerly named: "hatch") and GizmoSQL in a blog post: https://motherduck.com/blog/flight-sql-vs-rest-vs-jdbc/

I really like the idea of making a FlightSQL server extension for DuckDB - that would be pretty neat.

**Comment by staticlibs** [comment]
@prochac 

> DuckDB [can connect to Postgres](https://duckdb.org/docs/stable/core_extensions/postgres.html), but I haven't found a way to connect to the Flight SQL server.

This can be done using [odbc_scanner extension](https://github.com/duckdb/odbc-scanner) with [Dremio ODBC driver](https://docs.dremio.com/current/client-applications/drivers/arrow-flight-sql-odbc-driver/) (tested only with GizmoSQL so far).

**Comment by prochac** [comment]
> [@prochac](https://github.com/prochac)
> 
> > DuckDB [can connect to Postgres](https://duckdb.org/docs/stable/core_extensions/postgres.html), but I haven't found a way to connect to the Flight SQL server.
> 
> This can be done using [odbc_scanner extension](https://github.com/duckdb/odbc-scanner) with [Dremio ODBC driver](https://docs.dremio.com/current/client-applications/drivers/arrow-flight-sql-odbc-driver/) (tested only with GizmoSQL so far).

Cool. In a meanwhile, I was playing with Airport, just like I have half-baked Flight SQL server in Go.
But I was redirected to other tasks then. Hopefully, we will publish something.
I want to see ducks quacking everywhere :D

**Comment by wangfenjin** [comment]
For anyone interested, I’m working on a flight sql server based on duckdb, will be used internally in my company 

https://github.com/swanlake-io/swanlake

**Comment by TFMV** [comment]
If you're interested in a Go based Flight SQL server in Go, give mine (porter) a spin. It's more stable now and uses ADBC.

GitHub.com/TFMV/porter

I'd love any feedback. I'm still evolving it. If you need production grade, go with GizmoSQL. 

All the best,
Tom

**Comment by rabernat** [comment]
I have researched this situation a bit and have not found a satisfactory answer to my questions, so I'm posting a summary here.

The core problem: **this issue has been closed as completed, but DuckDB does not actually support Arrow Flight SQL.** The comment from @hannes (https://github.com/duckdb/duckdb/issues/3099#issuecomment-1123164933) conflates Flight SQL and ADBC. This confusion was noted already in https://github.com/duckdb/duckdb/issues/3099#issuecomment-3172551673. They are different things with different use cases.

* ✅  ADBC is a C API that applications code against to interact with a database. DuckDB supports the ADBC Client interface, allowing applications to query DuckDB using the ADBC API: https://duckdb.org/docs/current/clients/adbc. Similarly, DuckDB implements an ODBC client https://duckdb.org/docs/current/clients/odbc.
* ❌  Flight SQL is a gRPC-based client-server protocol, which allows a client to talk to a remote database. Its closest analog is the Postgres wire protocol. DuckDB has the [`postgres`](https://duckdb.org/docs/current/core_extensions/postgres) extension, which "allows DuckDB to directly read and write data from a running PostgreSQL database instance." **There is no comparable Flight SQL extension.** While it is relatively new, major databases like Dremio, InfluxDB, Apache Doris, and Apache Datafusion implement the server-side protocol. Its key selling point is the use of Arrow in the protocol, leading to more efficient transfer between client and server. This is highly aligned with DuckDB's columnar architecture. 

I believe that having a proper Flight SQL extension, allowing DuckDB to `attach` and query remote tables (as it already does with Postgres), would have great value for the ecosystem. For example, since DuckDB provides [SQL capabilities in Marimo](https://docs.marimo.io/guides/working_with_data/sql/#querying-files-databases-and-apis), supporting Flight SQL would open up more efficient interaction with the remote database listed above (plus other future ones that implement the protocol.)

 --- 

A note on the [Airport DuckDB Extension](https://query.farm/duckdb_extension_airport). This extension does use Arrow Flight SQL under the hood. However, it also requires the server to support a [long list of non-standard actions](https://github.com/hugr-lab/airport-go/blob/main/docs/protocol.md) which it calls the "Airport protocol". So it is a far cry from a standard-compliant Arrow Flight SQL extension.

**Comment by prmoore77** [comment]
Hi @rabernat - if you want to have a DuckDB Flight SQL Server - I would humbly recommend GizmoSQL, Porter, or SwanLake.  If you would like to connect (`ATTACH`) to a Flight SQL Server from DuckDB (or GizmoSQL) - you should check out the ADBC Scanner extension.  I have an example of usage here: https://docs.gizmosql.com/#/adbc_scanner_duckdb

One more thing - my company: GizmoData - just released GizmoSQL iOS edition - so you can run a DuckDB-powered Flight SQL Server from your iOS device: https://apps.apple.com/us/app/gizmosql/id6761951280
