### ISSUE TITLE
Compile to WebAssembly?

### ISSUE THREAD

**Issue by georgewfraser** [duckdb/duckdb#310]
Have you thought about the feasibility of compiling to .wasm so DuckDB can be embedded into a web page? It would make a killer demo. It has been done already with SQLite, you can see it [here](http://kripken.github.io/sql.js/examples/GUI/). 

If you think this is feasible, I'd be interested in giving it a shot, but I thought I'd check if you had any insight into how feasible it is first.

**Comment by hannesmuehleisen** [comment]
I believe someone has done this already. @ankoh ?

**Comment by ankoh** [comment]
@georgewfraser Yes, I did that already. Integrating duckdb via wasm is fairly straight-forward.
Having said that, it depends a bit on how much burden you want to put on the javascript user.

Exposing the raw C-api is IMO not ideal because manually freeing memory is something that is doomed to fail in js.
That, and the copies that come with js <> wasm calls led me to believe that you rather want to use zero-copy formats like Flatbuffers to expose some of the fundamental types like `duckdb::Vector` directly to js via views into the wasm memory.
That is more efficient but results in a slightly inconvenient api surface...

To get this discussion going, I can share a demo that makes use of the C-api until the end of the week.

**Comment by ankoh** [comment]
Ok, since it's Sunday now, I'll just share the proof-of-concept with you.
Even the C-API pushes you towards formats like Flatbuffers since you have no elegant way to encode the query results.

I haven't found a clean way yet how we can get the query results back to js.
For that reason, the demo does not yet print the query results to the web terminal but only logs to console.
Using the C++ API and encoding `duckdb::Vector` chunks manually is more elegant than the C-API but also much more invasive.

Repository: https://github.com/ankoh/duckdb.js
Demo: https://duckdbjs.kohn.io/

Comments are very welcome.
It should look like this:

![DuckDB](https://user-images.githubusercontent.com/3986510/67164705-e03bfc80-f37d-11e9-95c1-2c661c59ef61.png)

**Comment by Mytherin** [comment]
This is very cool! It even seems to work on my phone (although I can’t see the log messages there). Thanks for putting in the time to make this. I’m on holiday now so I can’t take a detailed look but I think this should definitely be integrated into the main repo and officially supported.

**Comment by domoritz** [comment]
I'd be super excited to use duckdb in the browser especially if there was a clean way to move memory from the wasm context to js. Maybe [arrow](https://github.com/cwida/duckdb/issues/151) could be the answer? Or some easy way to convert data to https://github.com/scijs/ndarray?

**Comment by ankoh** [comment]
@domoritz The problem with arrow is, that it buys yourself into quite a few more dependencies which is super nasty with wasm. I got duckdb with arrow working in wasm but ended up compiling boost_system, boost_regex, thrift, brotli and quite a few more using emscripten. Feasible but takes ages to build and I'm not quite sure whether you'd want all this in the duckdb repo.

**Comment by domoritz** [comment]
Thanks for the insight. Did you compile arrow from C++ or did you use the arrow js bindings? In https://github.com/cwida/duckdb/issues/151, the consensus was not to include arrow but only the header to produce compatible binary data.

**Comment by ankoh** [comment]
I compiled the C++ arrow runtime without arrow.js bindings since I needed to read Arrow on the C++ side anyway.
I agree that implementing https://github.com/apache/arrow/blob/master/docs/source/format/CDataInterface.rst for DuckDB result sets would be neat.
Although I'm not quite sure whether that would really eliminate glue code to somehow consume/provide that c data interface through js bindings.
The js library won't be able to consume/provide the c data interface after all.

**Comment by domoritz** [comment]
What I was thinking is that duckdb in wasm could produce an arrow result set, we then transfer it to js, and then we can read the data with the arrow js library.

**Comment by ankoh** [comment]
I totally agree, but how I understand the proposed [CDataInterface.rst](https://github.com/apache/arrow/blob/master/docs/source/format/CDataInterface.rst), the other party, in our case arrow.js, would also need to speak the C data interface through wasm, which is most certainly not the case today.
To quote their [example use-case section]:(https://github.com/apache/arrow/blob/master/docs/source/format/CDataInterface.rst#example-use-case), they write:
> A C++ database engine wants to provide the option to deliver results in Arrow format, but without imposing themselves a dependency on the Arrow software libraries. With the Arrow C data interface, the engine can let the caller pass a pointer to a ArrowArray structure, and fill it with the next chunk of results.

It would certainly be an interesting experiment but this sounds like you'd still have to write a fair amount of glue code on the C++ side to expose/bind the javascript library via the C interface.

**Comment by Alex-Monahan** [comment]
If you are headed down this path, we will definitely use it and can test things out!

**Comment by nmichaud** [comment]
> It would certainly be an interesting experiment but this sounds like you'd still have to write a fair amount of glue code on the wasm side to expose/bind the javascript library via the C interface.

If the CDataInterface will always generate/write the arrow data into a contiguous buffer per RecordBatch, then the JS arrow library can process the buffer using pure javascript/typed buffers, no bindings to any other implementation necessary. In this case a small shim would be needed to copy the arrow buffer from the Wasm heap to an independent buffer (or depending on the lifetime of the result set, ArrowJS could reference the buffer object directly in the wasm heap).

**Comment by Alex-Monahan** [comment]
A WASM DuckDB would be flat out amazing for our use case! If it is a smaller effort now that you guys have invested in Arrow compatibility, I think it would completely revolutionize the browser-based DB landscape. It's a slow life living in SQL.js land... I have some JS experience, but none with WASM, so I will help on the JS side if needed!

**Comment by hannesmuehleisen** [comment]
@ankoh now that we have basic arrow support would that address your previous issues?

**Comment by nmichaud** [comment]
> > It would certainly be an interesting experiment but this sounds like you'd still have to write a fair amount of glue code on the wasm side to expose/bind the javascript library via the C interface.
> 
> If the CDataInterface will always generate/write arrow data into a contiguous buffer for each RecordBatch, then ArrowJS can process the buffer using pure javascript/typed buffers, no bindings to any other implementation necessary. In this case a small bit of interface code would be needed to copy the arrow buffer from the Wasm heap to an independent TypedBuffer (using TypedBuffer.set), or depending on the lifetime of the result set, ArrowJS could use the block of memory corresponding to the RecordBatch directly from the wasm heap.

Actually I stand corrected. I read through the CDataInterface (https://github.com/apache/arrow/blob/master/docs/source/format/CDataInterface.rst#comparison-with-the-arrow-ipc-format), and it looks like it's meant to support intra-process communication. The current ArrowJS implementation is built on the IPC arrow interface, and so wouldn't be able to consume arrow data generated through the C data interface. However, to @ankoh's point above, it might be possible to expose the C data interface in the wasm bindings allowing javascript access to the underlying arrow data.

**Comment by ankoh** [comment]
@hannesmuehleisen I come to a similar conclusion as @nmichaud.
We're currently compiling the amalgamation version of 0.2.0 with Emscripten and we're wrapping the query results into a minimal protocol buffer.
That works pretty good.

```protobuf
// This looks worse than it actually is.
// Fields are optional (& absent in the encoding) in protobuf 3 and repeated fields of numeric types are packed by default.
// So the encoding is fairly compact.

message QueryResultColumn {
    repeated bool null_mask = 1;
    repeated int32 rows_bool = 2;
    repeated int32 rows_i32 = 3;
    repeated uint32 rows_u32 = 4;
    repeated int64 rows_i64 = 5;
    repeated uint64 rows_u64 = 6;
    repeated float rows_f32 = 7;
    repeated double rows_f64 = 8;
    repeated string rows_str = 9;
}

message QueryResultChunk {
    uint32 row_offset = 1;
    uint32 row_count = 2;
    repeated QueryResultColumn columns = 3;
}
```

This has the additional advantage that you can just stream the result chunks from the iterator back to javascript without materialising everything into a single result buffer on the wasm side.

I'm not really convinced that arrow is the right pick for the js-wasm interop.
Especially since you are forced to copy the wasm memory anyway if you don't want to expose the fact that subsequent wasm calls may just invalidate your previous UInt8Array.

**Comment by Alex-Monahan** [comment]
Hi @ankoh !
Would you be open to sharing your compiled WASM binary and any other JS wrapper that you are using? I am not a WASM expert, but would love to try out DuckDB in the browser! I checked your repo for DuckDB.js, but it looks like it hasn't been updated in a while.

Thanks!

**Comment by ankoh** [comment]
@Alex-Monahan I'll update the proof-of-concept at the weekend.

**Comment by Alex-Monahan** [comment]
Thank you! Ideally our hope is to stream an Arrow table from our server straight into a WASM DuckDB. So once the Arrow reader feature is out, that is something else I'd like to try! If it's easier on your side to just document how you are compiling it, I can recompile after the next release!

**Comment by nmichaud** [comment]
@Alex-Monahan I'm interested in that as well, but DuckDB's current arrow reader only works with the CDataInterface format, not the IPC based format (which is what you'd send over HTTP or websocket).

**Comment by Alex-Monahan** [comment]
Ah, thank you. I'm understanding now. I didn't realize there were multiple flavors of Arrow for different purposes.

Given that, what are the options for how to load data into a WASM DuckDB? Ideally we would want to do some bulk loading.

**Comment by ankoh** [comment]
You can implement bulk-loading fairly easily with the `Appender` as done, for example, in many of the [tests](https://github.com/cwida/duckdb/blob/e134825f4125a039d04c0aab19e5db3ee805b89f/benchmark/micro/rangequery.cpp#L18).
So the CDataInterface currently does not save us the heavyweight Arrow dependency on the C++ side unless we find a way to expose the CDataInterface using the Javascript Arrow library.
With protobuf, you canlink the wasm module to the 0 dependency protobuf-lite runtime and then use google-protobuf on the javascript side.
But you'd still have to encode your arrow buffer as protobuf in javascript then.

**Comment by hannesmuehleisen** [comment]
See #1424

**Comment by hannesmuehleisen** [comment]
There remains some API work to be done, but that's a separate issue.

**Comment by domoritz** [comment]
We have a release at https://github.com/duckdb/duckdb-wasm now.
