### ISSUE TITLE
JDBC: Querying with Timestamps

### ISSUE THREAD

**Issue by mbuechner** [duckdb/duckdb#3134]
#### What happens?
I'm trying to read data with WHERE \<timestamp> from DB, but it's not working. I'm getting empty results.

#### To Reproduce
Create table with...
```
CREATE TABLE IF NOT EXISTS main."data"(
   "timestamp" TIMESTAMP NOT NULL,
   id VARCHAR(32) NOT NULL);
```
Add some data and try to query like:
```
SELECT * FROM main."data" WHERE "timestamp" LIKE '2022-02-15 20:39:22.000'
```

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: JDBC 0.3.2
 - DuckDB Client: Java

**Comment by mbuechner** [comment]
I'm getting results with:
```
SELECT * FROM main."data" WHERE "timestamp">='2022-02-15 20:39:22.000'
```
So I tried to re-import the data with timezone set to UTC and - voilà! - it's working now!
Not sure if it is bug or not?

**Comment by Mytherin** [comment]
There is not enough information here to determine if there is a bug since no data or code related to a potential bug is provided. The only code here is the SQL query with the `WHERE` clause - which based on my understanding of the report was doing its job correctly and filtering out timestamps that did not match the condition. Perhaps you could expand and create a reproducible example that showcases what you think the bug would be in this scenario?

**Comment by mbuechner** [comment]
@Mytherin, I don't have time to figure it out in detail. I could send you my database, if you like to?

**Comment by mbuechner** [comment]
I'm getting closer to the problem:

- Importing timestamps from CSV like `2022-02-23 10:28:38.01598` with `COPY`
- `SELECT` timestamp with JDBC from DB: `2022-02-23 10:28:38.015`
- ...and the problem is: `2022-02-23 10:28:38.015` != `2022-02-23 10:28:38.01598`

**Comment by Mytherin** [comment]
Does Java support timestamps in microsecond precision? The truncation to milliseconds makes sense to me if that is the default timestamp format in Java.

**Comment by mbuechner** [comment]
Yes, it does! See https://docs.oracle.com/javase/6/docs/api/java/sql/Timestamp.html
...but it says: "This type is a composite of a java.util.Date and a separate nanoseconds value." Which is maybe the problem!?

**Comment by mbuechner** [comment]
I made a quick-hack: Just importing the timestamps w/o milli-/nanoseconds. :no_good:

**Comment by mbuechner** [comment]
@hawkfish, I think that's not the point. The problem is, that I store nano-precision in DB, but only get milli-precision when I query  via JDBC.

**Comment by hawkfish** [comment]
Got it - I just wanted to make sure there were no confounding variables. 

Even µs forces us to use 64 bit integers for `TIME` (10^5 * 10^6 = 10^11 ~= 2^34), so we could take another 10 bits to get to ns precision, and that would leave 20 bits for the `DATE` part in a 64 bit integer. Our current `DATE` range is 32 bits, giving us a rather absurdly large range, but dropping it to 20 bits would be problematic because it doesn't even cover the Julian Day range (today is JD 2,459,633, which uses 21 bits!) so our trade off is to get as much useful accuracy as we can in 64 bits.

You might try splitting off the fractional ns and using a struct like `{ts:TIMESTAMP, ns:SMALLINT}`? Then you could use date binning on the ts part and add the ns when dealing with low precision?

**Comment by hawkfish** [comment]
I should add that you can still sort and group by this struct - the semantics are left to right as you would need for this kind of precision.

**Comment by mbuechner** [comment]
I don't have the need to deal with nano-/milliseconds. My solution was to cut it off. I am also using Spring not to deal with the very basic details. Just run into this (at the beginning) confusing issue, and it took me a while to understand.

Thanks for your help, @hawkfish and @Mytherin. I really appreciate!
