### ISSUE TITLE
DUCKB aggregations over arrow table are slower than pandas dataframe

### ISSUE THREAD

**Issue by zacqed** [duckdb/duckdb#3138]
#### What happens?
DUCKB aggregations over arrow table are slower than pandas dataframe

#### To Reproduce
```
import pandas as pd
import duckdb

lineitem = duckdb.query("SELECT * FROM 'lineitemsf1.snappy.parquet'").to_arrow_table()
lineitem_df = duckdb.query("SELECT * FROM 'lineitemsf1.snappy.parquet'").to_df()
con = duckdb.connect()

con.execute('PRAGMA threads=4')
ungrouped_aggregate = '''SELECT SUM(l_extendedprice), MIN(l_extendedprice), MAX(l_extendedprice), AVG(l_extendedprice) FROM lineitem'''
ungrouped_aggregate_df = '''SELECT SUM(l_extendedprice), MIN(l_extendedprice), MAX(l_extendedprice), AVG(l_extendedprice) FROM lineitem_df'''


%timeit -n 20 -r 10 duckdb.query(ungrouped_aggregate).to_arrow_table()
549 ms ± 52.8 ms per loop (mean ± std. dev. of 10 runs, 20 loops each) with 1 thread

%timeit -n 20 -r 10 con.query(ungrouped_aggregate).to_arrow_table()
569 ms ± 81.2 ms per loop (mean ± std. dev. of 10 runs, 20 loops each) with 4 threads

%timeit -n 20 -r 10 duckdb.query(ungrouped_aggregate_df).to_df()
17.2 ms ± 2.34 ms per loop (mean ± std. dev. of 10 runs, 20 loops each) with 1 thread

%timeit -n 20 -r 10 con.query(ungrouped_aggregate_df).to_df()
20.5 ms ± 1.21 ms per loop (mean ± std. dev. of 10 runs, 20 loops each) with 4 threads
```

#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version: 0.3.1
 - DuckDB Client: Python

**Comment by hannesmuehleisen** [comment]
I don't see a join in those queries, did you mean aggregation?

**Comment by zacqed** [comment]
> I don't see a join in those queries, did you mean aggregation?

Yes, my apologies.

**Comment by Alex-Monahan** [comment]
Also, could you re run with a few more repetitions? The standard deviations are fairly high so the difference could be noise. Thanks!

**Comment by pdet** [comment]
I can confirm this is happening.

Two things to notice:
In our arrow integration, for doubles, we currently have to go over data once to transform NaNs into Nulls, so this will impact performance a bit, although not enough to justify the difference.

The arrow scans are only parallel for batched tables, so the table in your example won't be executed in parallel.

However, I'm not sure if these reasons are sufficient to explain the time difference there, so I will profile this later this week :-)

**Comment by pdet** [comment]
So I instrumented the code and found the issue here.
The problem is that when the arrow table is created from lineitem it actually creates a batched arrow table (with batch sizes of 1024 elements).
It looks like these are too small for arrow, which creates this huge additional cost to read them back.
So you can solve this difference by either reading the parquet file directly from arrow, or by calling the ```combine_chunks()``` method.

I think I'll add an optional parameter to the to_arrow_table(), where the user can state the number of vectors they want per batch. This is similar to what we have on ```fetch_arrow_chunk()```

Unless @Mytherin or @hannes has other thoughts?

**Comment by hannes** [comment]
We could indeed create bigger batches on our side

**Comment by zacqed** [comment]
I can verify using the performance using`combine_chunks()` or `fetch_arrow_chunk()`. Feel free to close this.

**Comment by hannes** [comment]
@nealrichardson @jonkeane is there a preferred batch size from your side?

**Comment by pdet** [comment]
I'm currently refactoring our DuckDb to Arrow Conversion, also to allow for a higher default chunk size.

I've noticed we have three main methods that return an Arrow Object,
FetchArrowTable -> Returns a fully materialized Table
FetchArrowChunk -> Returns part of the table
FetchRecordBatchReader -> Returns a Record Batch Reader.

If I remember correctly, the reason I've implemented this FetchArrowChunk, was because was not possible to create a record batch reader at the time. Hence I'm wondering if anyone opposes the removal of this function.

**Comment by jonkeane** [comment]
> @nealrichardson @jonkeane is there a preferred batch size from your side?

We haven't done a super exhaustive search for the optimal batch size (especially across the C-Data Stream interface). This is something we definitely should do (and I've made https://github.com/ursacomputing/arrowbench/issues/74 to look into some of that space). @westonpace did a bit of work looking at Arrow reading from parquet files and found that 1M rows was the minimum (though that minimum was guided by HDD scanning, which might not have the same bottleneck if DuckDB is doing the scan here. 100K rows as suggested by @Mytherin sounds like a good start until we have more detailed measures.


> If I remember correctly, the reason I've implemented this FetchArrowChunk, was because was not possible to create a record batch reader at the time. Hence I'm wondering if anyone opposes the removal of this function.

Agreed — I actually might even be inclined to say that the Record Batch Reader is the only way to go and if someone wants to materialize that into an Arrow table they can `.read_all()` to gather them into a table. Though I could see, especially for smaller tables, where just going directly to a table might be nicer.

**Comment by westonpace** [comment]
Hmm, the 1M rows suggestion was indeed calculated around working with files and row groups where we want to make sure that chunks of data on the disk are large enough to be efficiently read by HDD.  I agree that shouldn't be a factor here.  We do generally have some overhead issues with small batches but this seems rather extreme.  That being said, we are in the fairly early stages of optimizing a lot of this and I don't think we know all the details quite yet.

Semi-related, @wesm is investigating a lighterweight batch structure for processing inside of an Arrow exec plan (though I don't think we are using exec plans here?) and the current theory is that we want to aim for:

 * Create a thread task for a large chunk of rows (e.g. ~1 million)
 * Inside the task, process the large chunk in small batches (each batch being small enough to comfortably fit inside L2).

So I would be curious to know what precisely is happening here as anything we can learn might illuminate our work above.  I may try and dig around a bit with this example.

**Comment by westonpace** [comment]
Seems I was wrong on several counts :smile: 

 * We are using exec plans 
 * The culprit is indeed our small batch overhead

The extra work is (unfortunately) rather diffusely spread across a number of places.  We probably don't need to go into the details here, we can tackle these in Arrow.  Using larger batches is the best workaround.  Hopefully it won't be so necessary in the future once Arrow's had a few optimization passes.

**Comment by westonpace** [comment]
Actually, after staring at things on the Arrow side for a bit, I am ready to suggest an alternative workaround.

A big portion of the small batch overhead is in the scanner.  While we are investigating methods to reduce small batch overhead in the execution plans I don't know anyone that is looking into such a change on the scanner (when working with files we are rarely working with small batches).

My recommendation then would be to use a TableBatchReader but we don't currently have that exposed in pyarrow (I filed [ARROW-15823](https://issues.apache.org/jira/browse/ARROW-15823) to address this).  I'm not entirely sure how much C++ code is allowed in `arrow_array_stream.cpp` but if you can can use the C++ [`TableBatchReader`](https://arrow.apache.org/docs/cpp/api/table.html?highlight=tablebatchreader#_CPPv4N5arrow16TableBatchReaderE) then you should be able to do this today.

Otherwise you would need to wait for ARROW-15823 for a more python only solution.
