### ISSUE TITLE
timestamp field value out of range

### ISSUE THREAD

**Issue by alitrack** [duckdb/duckdb#3187]
#### What happens?
A short, clear and concise description of what the bug is.
```
RuntimeError: Conversion Error: timestamp field value out of range: "2022-03-05 17:59:17.877 CST", expected format is (YYYY-MM-DD HH:MM:SS[.MS])
```

#### To Reproduce
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
```sql
select '2022-03-05 17:59:17.877 CST'::timestamptz
```

tried the same query on Postgres, got,
<img width="444" alt="image" src="https://user-images.githubusercontent.com/20972179/156907529-b9f34f00-3441-446f-a757-627c439612ed.png">

#### Environment (please complete the following information):
 - OS: [e.g. iOS] macOS and Ubuntu
 - DuckDB Version: [e.g. 22] 0.3.2 and 0.3.3-dev585 
 - DuckDB Client: [e.g. Python] Python

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`  yes
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hawkfish** [comment]
Ah, sorry, the issue is that the time zone data is in the ICU extension, but there are currently architectural issues around adding casting operations to extensions. I presume this is a follow on to #3188?

You can use an offset instead of a time zone e.g., `select '2022-03-05 17:59:17.877-06:00'::timestamptz` if that will get you going?

If you need TZ name parsing, I think we could fairly easily add an `icu_to_timestamptz` function to the ICU extension where the format string was in ICU syntax?

**Comment by hawkfish** [comment]
@alitrack I've extended the `strptime` function to handle this situation. Will this help you?

**Comment by alitrack** [comment]
> @alitrack I've extended the `strptime` function to handle this situation. Will this help you?

Will let you know after test, thanks in advance.

**Comment by hawkfish** [comment]
Thanks to @Mytherin we can now implement casting functions in extensions, so I can revisit some of this!

**Comment by hawkfish** [comment]
@alitrack Can you try this on master to see if it solves your problem?

**Comment by alitrack** [comment]
> @alitrack Can you try this on master to see if it solves your problem?
just try this on master, and got the following error, 
```
Error: Conversion Error: timestamp field value out of range: "2022-03-05 17:59:17.877 CST", expected format is (YYYY-MM-DD HH:MM:SS[.US][±HH:MM| ZONE])
```
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/20972179/194685454-6c94a1d1-966a-40b3-9b04-45adeec657e3.png">

**Comment by hawkfish** [comment]
How very odd - I just tried it myself and it works fine.  Can we test whether you have ICU installed?  What happens with this query:

```sql
select '2022-03-05 17:59:17.877'::timestamptz + interval 1 day;
```

**Comment by hawkfish** [comment]
Another possibility is that you have the latest version of DuckDB (and the error message suggests that because I changed it) but an older version of the ICU extension. In that case you would not get an error from the second query, but it would display with the old format ("+00") instead of in your local time zone.

**Comment by alitrack** [comment]
works with icu loaded.
