### ISSUE TITLE
no function to_timestamp ( text, text ) → timestamp with time zone and to_char

### ISSUE THREAD

**Issue by alitrack** [duckdb/duckdb#3188]
Postgres has two functions that does not exist in DuckDB
to_timestamp ( text, text ) → timestamp

to_char

ref,
 [Data Type Formatting Functions](https://www.postgresql.org/docs/14/functions-formatting.html)

**Comment by hawkfish** [comment]
Yeah the problem is that there are so many different parsing and formatting syntaxes. PG has its own (which IIRC is copied from Oracle), C has a second and [ICU has a third](https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax). I once had to write a generic translator for date formats for a large number of database syntaxes and there were always gaps.

DuckDB does currently have [date parsing and formatting functions](https://duckdb.org/docs/sql/functions/dateformat), but they use the C conventions. Will they be sufficient?  And if you are looking for `to_char`, you might consider using your presentation layer to do the formatting. We have a `DATE_PART` variant that will very efficiently return any set of part codes as a `STRUCT` that you can then format as you see fit?

**Comment by hawkfish** [comment]
After looking at this in more depth, I think the simplest thing to do for this situation is to add new ICU functions  `strptime_icu` and `strftime_icu` that can handle time zone names for `TIMESTAMP_TZ`, but which use the C-style formatting codes.

We may be able to add full ICU syntax parsing at some point, but right now the subset we have extracted does not have the locale-specific date part names.  

I also looked at the PG/Oracle format syntax, and it is a real bear with pages of special cases. If someone wants to take the [PG formatting code](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/formatting.c;h=97a4544ffc630e1234dd387c9ebb0bcd58ec586b;hb=591e088dd5b357796e136c13dfcdb1f06fd7a3c2) and import it somehow, they are a better carbon-based life form than I...

**Comment by nicku33** [comment]
Just a note that we had a few users ask for this from MotherDuck, as they are trying to migrate ETL scripts from postgres and prefer not to alter them.

**Comment by hawkfish** [comment]
If they are not using anything too fancy in the PG date dialect, then they can probably translate the SQL using Python or something, but if they are relying on non-portable (to ICU) features then someone would need to import the PG code into an extension or something.

**Comment by ryguyrg** [comment]
Here's a thread asking for to_char in DuckDB on twitter: https://twitter.com/jaceksan/status/1690754399604285441.

DuckDB is quite compatible with Postgres already - would be good to add this in order to improve compatibility.

**Comment by hawkfish** [comment]
I don't do Twitter, but that is actually our default string format, so he doesn't need to do anything except cast to `DATE` and then `VARCHAR` (which I believe should work in PG too). Or use `strptime` just with different format codes (same as Python/C++).

I'm not opposed to someone doing this in an extension using the PG code, but my experience with these little languages is that they are not completely translatable. And chasing down the edge cases is a source of constant misery.
