### ISSUE TITLE
Rules for triggering a replacement scan (for parquet/csv files)?

### ISSUE THREAD

**Issue by rsund** [duckdb/duckdb#3260]
#### What happens?
Replacement scan is not triggering in some cases where it could be expected (gives Catalog Error instead).

#### To Reproduce

These two queries work as expected:
```sql
SELECT * FROM 'test.parquet'
SELECT * FROM "test.parquet"
```

This one gives **Catalog Error: Schema with name test does not exist!**. Understandable, as it is about missing schema, but maybe this one could also trigger the replacement scan?
```sql
SELECT * FROM test.parquet
```

The following gives **Catalog Error: Table with name ['test/*.parquet', 'old/*.parquet'] does not exist!** As it is clearly a missing table here, it could be expected that this triggers the replacement scan. This would also release (almost) the full potential of parquet reader as several files could be listed in wanted order.
```sql 
SELECT * FROM "['test/*.parquet', 'old/*.parquet']"
```

Of course it would be possible to use directly the following query with a parquet_scan function in this case, but that is not the point here.
```sql
SELECT * FROM parquet_scan(['test/*.parquet', 'old/*.parquet'])
```

But in fact, also the following gives an error **Catalog Error: Table with name parquet_scan(['test/*.parquet', 'old/*.parquet']) does not exist!** This is maybe a bit unexpected form of calling a table function, but could still be expected to trigger the replacement scan.
```sql
SELECT * FROM "parquet_scan(['test/*.parquet', 'old/*.parquet'])"
```
Indeed, there are use cases for these non-functioning forms: dbplyr-backend in the R client generates double quotation marks for "tables" while those are registered to be used with it, so the option to list several files in a list cannot be directly used.

It would be possible to fix that only in the R client, but maybe those small extensions of replacement scan rules for parquet (and csv) files would be useful also in more general sense?!

**Comment by Mytherin** [comment]
I quite like the idea of passing on `test.parquet` to the replacement scans as well in the case of a schema not existing, to make the quoting around the replacement scans for Parquet files and CSV files optional. I will have a go at implementing that.

Parsing complex lists as Parquet files does not look particularly nice and will not be very nice from an implementation perspective since that would mean duplicating the parsing logic of complex lists. At that point the amount of typing saved by adding a `parquet_scan` is also very small, so I would opt with fixing that on the R side rather than extending replacement scans for Parquet files with list support.

**Comment by rsund** [comment]
Excellent! I'll take a look for fixing the problem in the R client.
