### ISSUE TITLE
Pandas categoricals vs. R factors

### ISSUE THREAD

**Issue by sebffischer** [duckdb/duckdb#3309]
#### What happens?
When writing a pandas dataframe to parquet and loading it in R via duckDB, the information about whether a column is a factor or a string gets lost (everything is a string) 

#### To Reproduce
1. Create and write data in python 
```python
import pandas as pd
import pyarrow.parquet as pq
from pyarrow.parquet import write_table
import pyarrow as pa
import os

col1 = pd.Series(["a", "b", "c", "a"], dtype="category")
col2 = pd.Series(["a", "b", "c", "a"], dtype="string")
df = pd.DataFrame({"cat": col1, "str": col2})

path = os.path.expanduser("~/py.parquet")
table = pa.Table.from_pandas(df)
pq.write_table(table, path)
```

2. Load data in R

``` r
library(duckdb)
#> Loading required package: DBI
path = normalizePath("~/py.parquet")
db = dbConnect(duckdb::duckdb())
dbExecute(db, sprintf("CREATE TABLE t1 AS SELECT * FROM read_parquet(['%s']);", path))
#> [1] 4
data = dbGetQuery(db, sprintf("SELECT * FROM t1"))
Map(class, data)
#> $cat
#> [1] "character"
#> 
#> $str
#> [1] "character"

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
```

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04
 - DuckDB Version: [0.3.2]
 - DuckDB Client: [R]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by sebffischer** [comment]
```python
from pyarrow.parquet import read_table
table_read = read_table(path)
print(table_read)
```
gives the output: 

```python
pyarrow.Table
cat: dictionary<values=string, indices=int32, ordered=0>
str: string
----
cat: [  -- dictionary:
    [
      "a",
      "b",
      "c"
    ]  -- indices:
    [
      0,
      1,
      2,
      0
    ]]
str: [["a","b","c","a"]]
```

**Comment by Alex-Monahan** [comment]
I believe the Apache Arrow Feather file format retains its dictionary encoding. It was designed initially for data transfer between R and Python I believe!
[Arrow IPC format used in feather](https://arrow.apache.org/docs/format/Columnar.html)

**Comment by sebffischer** [comment]
Also the arrow R package keeps this property: 

``` r
path = normalizePath("~/py.parquet")
dat = arrow::read_parquet(path)
head(dat)
#> # A tibble: 4 × 2
#>   cat   str  
#>   <fct> <chr>
#> 1 a     a    
#> 2 b     b    
#> 3 c     c    
#> 4 a     a
```

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by sebffischer** [comment]
This would be quite convenient. We are currently working on using duckDB as a DataBackend for the mlr3 R package and for that it would be great fit it could handle factors

**Comment by eitsupi** [comment]
FYI, I believe this feature was added in this PR apache/arrow#5077.

**Comment by Mytherin** [comment]
Thanks, indeed this seems to directly serialize the Arrow schema into the Parquet file. It would be feasible for us to do this ourselves with our `ENUM` type to allow DuckDB to round-trip enums (and factors/categoricals), essentially copying what is done by Arrow here but by (de)serializing our own schema in the file metadata, into e.g. a `DUCKDB:schema` field.

Deserializing the Arrow schema in our Parquet reader is not on the roadmap, however, since that would require linking to Arrow which is something we have been trying to avoid for portability purposes.

If you wish to round-trip a file written by Arrow in such a manner I recommend using the Arrow Parquet reader directly, and using our Arrow integration to load the data back into DuckDB. DuckDB even supports reading from the Arrow Parquet reader in a streaming manner, so in principle this should not be very different performance-wise from reading a file using our built-in Parquet reader.

**Comment by sebffischer** [comment]
Maybe it is possible to talk to the Arrow developers to come up with a standard encoding of those data-types?
