### ISSUE TITLE
Bundle httpfs extension with DuckDB clients.

### ISSUE THREAD

**Issue by hokieg3n1us** [duckdb/duckdb#3315]
Currently, the parquet extension is bundled with DuckDB clients. However, support for S3 (or an API compatible file system) requires installing the httpfs extension. Accessing parquet through S3 seems like a common enough use case to warrant bundling the httpfs extension with DuckDB clients.

Since our team operates in a disconnected environment, they cannot install the extension from the externally hosted DuckDB extension repository, so they have to workaround by installing from a locally managed copy, which complicates deployment strategies.

 - OS: Windows/Linux
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python (though, we'd prefer like the feature for all DuckDB clients)

**Comment by arjenpdevries** [comment]
Just out of curiosity (an academic here): you are disconnected but can access S3? Is that a common setting in "the real world"?

**Comment by mskyttner** [comment]
@arjenpdevries sharing a few thoughts here regarding httpfs extension bundling. I would say from my perspective of the "real world", it is quite common to have setups with containers where S3 is provided by a FOSS component such as MinIO. It allows for "disconnected"/private cloud, hybrid cloud, private cloud, colo setups/deployments etc and can be a way of managing vendor lock-in for your data processing backend. 

You can try it out by running an S3 service locally (provided you have docker or podman on your machine) using a oneliner, quoting from the minio docs:

`docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  --name minio1 \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  -v /mnt/data:/data \
  quay.io/minio/minio server /data --console-address ":9001"
`

Such a setup BTW also allows for using [a gateway](https://docs.min.io/docs/minio-gateway-for-s3.html) against public cloud S3 storage, which can be used to dramatically lower network latency between data processing and object storage services, which can easily become a bottleneck. 

So for those kinds of setups, it would be quite convenient to have S3 connectivity "bundled" with duckdb (CLI, R, Python) from the get-go. Otherwise one would quite often need to repackage duckdb to have it included. 

As a side-note the same thing (in my opinion) goes for the FTS extension. This functionality comes with SQLite and can be used out of the box for example through RSQLite.

**Comment by hannes** [comment]
The reason those are not "baked in" right now is that for example httpfs needs OpenSSL which is a bit of a dependency nightmare. What we could consider is to bundle a bunch of extensions as separate files with the python package, with the search path rigged so it looks there first.

**Comment by hokieg3n1us** [comment]
@mskyttner Pretty accurately describes our operational environment. It's pretty common in industry to run in a private cloud. In our case, it's using MinIO with on-prem hardware. Even our dependency management (Maven/PyPi) are mirrors controlled by a security team.

**Comment by arjenpdevries** [comment]
Cool, thanks for these insights. Looks like I should include a `minio` based S3 object storage azsignment in our big data course exercises!

**Comment by mskyttner** [comment]
@arjenpdevries I just [tried](https://github.com/mskyttner/duckdbrest/blob/master/docker-compose.yml#L31-L41) using on-premise access (with parquet files on minio served within a software defined network of locally running containers) versus remote access against the same s3 object storage (also a minio server but on an external network). The same query against the same data was 70x faster when using on-premise s3 storage due to lower network latency in that (very specific) test.

**Comment by arjenpdevries** [comment]
Wow two orders of magnitude, clearly a benefit for on-premise S3. I appreciate these insights, many thanks!

**Comment by hannes** [comment]
Wer now support installation of extensions with e.g. `INSTALL 'httpfs';` once and then `LOAD 'httpfs';`.

**Comment by ruben-s** [comment]
Hi,

Question: Is there a way of installing extentions from local files (downloaded?).

The reason I ask is similar to the OP: our server is behind a firewall and has no outside access (except for certain repos via Artifactory, which is managed by another department).

So when I try ```con.execute("INSTALL` httpfs;")``` I get following error:

> duckdb.IOException: IO Error: Failed to download extension "httpfs" at URL "http://extensions.duckdb.org/v0.5.1/linux_amd64/httpfs.duckdb_extension.gz"

This error does not surprise me, the server isn't allowed to fetch this url by the firewall.

Is there a way of installing from a local file?
I can manually download this .gz (via a http-proxy which is virus checked/monitored) and then scp it to the server.

Thx for your feed-back.

br,
 Ruben

**Comment by Mytherin** [comment]
Yes, that is possible. You can pass a full file path to both `INSTALL` and `LOAD`.

**Comment by hokieg3n1us** [comment]
Yes. You can. You'll need to extract the files from within the gzip.

Then you can just do the following (example using Python):

```
import duckdb
db = duckdb.connect()
db.execute("INSTALL 'httpfs.duckdb_extension'")
```

I haven't tested it yet, but you could likely just create the expected
directory structure in your home directory, and just call LOAD httpfs
instead of running this step.

Barry

**Comment by ruben-s** [comment]
Hi Barry, Mytherin,

thanks for the quick response.

For reference purposes: indeed it works, some additional info:
The unzipping of the .gz resulted in only 1 single file, which intially confused me as a directory structure was mentioned.
As Mytherin mentioned the full path of the unzipped file needed to be passed to get it to work.

I did not try to directly use LOAD, but did the INSTALL step first.

Thx.

br,
 R.

**Comment by hokieg3n1us** [comment]
Ah. Sorry for the confusion about the directory structure.

To better explain what I was referencing, the INSTALL step creates a
directory structure in the home directory of your user.

For example: /home/bbragg/.duckdb/extensions/v0.5.1/linux_amd64/

The file, in this case httpfs.duckdb_extension, is placed under that
directory.

Thanks

Barry Bragg

**Comment by haj00007** [comment]
While invoking duckdb_jdbc-0.9.2 jar and connecting to adls gen2, behind proxy its gives 12002 error and connection timeout. Any help how to pass proxy to it?
