### ISSUE TITLE
dbWriteTable fails with std::bad_alloc when writing large dataframe on Windows

### ISSUE THREAD

**Issue by chrisknoll** [duckdb/duckdb#3429]
#### What happens?
When writing a large dataframe to a table via `dbWriteTable()`, the call fails with an error message:
```
Error: duckdb_execute_R: Failed to run query
Error: std::bad_alloc
```

#### To Reproduce
This is the R script that is being run to generate the test dataframe, and then the call to write table.

```
# Test large joins -----------------

n_covariates <- 1000
df1 <- as.data.frame(lapply(1:n_covariates, function(n) rbinom(1e6, 1, .2)))
names(df1) <- paste0("covariate", 1:n_covariates)
df1 <- cbind(data.frame(id = 1:1e6), df1)
df2 <- data.frame(id = sample(1:1e6, 10, replace = T))

### duckdb --------------------------
unlink(file.path("test.duckdb"))
con <- duckdb::dbConnect(duckdb::duckdb(), file.path("test.duckdb"))

duckdb::dbWriteTable(con, "df1", df1)
duckdb::dbWriteTable(con, "df2", df2)
```

#### Environment (please complete the following information):
 - OS: [Windows]
 - DuckDB Version: [0.3.2-2]
 - DuckDB Client: [R]
 - R version: 4.1.2
 - 
#### Before Submitting

I didn't complete any of the suggestions provided in the Before Submitting section, since the URL was invalid for downloading the package.  I did manage to find a 0.3.3 llink in the github releases and executed this:

```
install.packages("https://github.com/duckdb/duckdb/releases/download/v0.3.3/duckdb_r_src.tar.gz", repos = NULL)
```

The final lines of the failed build:
```
C:/Apps/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: duckdb/amalgamation-10.o:amalgamation-10.cpp:(.text$_ZN14duckdb_httplib10ClientImpl15process_requestERNS_6StreamERNS_7RequestERNS_8ResponseEbRNS_5ErrorE[__ZN14duckdb_httplib10ClientImpl15process_requestERNS_6StreamERNS_7RequestERNS_8ResponseEbRNS_5ErrorE]+0x158): undefined reference to `_imp__shutdown@8'
C:/Apps/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: duckdb/amalgamation-10.o:amalgamation-10.cpp:(.text$_ZN14duckdb_httplib10ClientImpl15process_requestERNS_6StreamERNS_7RequestERNS_8ResponseEbRNS_5ErrorE[__ZN14duckdb_httplib10ClientImpl15process_requestERNS_6StreamERNS_7RequestERNS_8ResponseEbRNS_5ErrorE]+0x16c): undefined reference to `_imp__closesocket@4'
C:/Apps/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: duckdb/amalgamation-10.o:amalgamation-10.cpp:(.text$_ZN14duckdb_httplib6Server24process_and_close_socketEj[__ZN14duckdb_httplib6Server24process_and_close_socketEj]+0xea): undefined reference to `_imp__select@20'
C:/Apps/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: duckdb/amalgamation-10.o:amalgamation-10.cpp:(.text$_ZN14duckdb_httplib6Server24process_and_close_socketEj[__ZN14duckdb_httplib6Server24process_and_close_socketEj]+0x110): undefined reference to `_imp__shutdown@8'
C:/Apps/rtools40/mingw32/bin/../lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld.exe: duckdb/amalgamation-10.o:amalgamation-10.cpp:(.text$_ZN14duckdb_httplib6Server24process_and_close_socketEj[__ZN14duckdb_httplib6Server24process_and_close_socketEj]+0x11f): undefined reference to `_imp__closesocket@4'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'duckdb'
```

**Comment by chrisknoll** [comment]
Playing around with the paramater `n_covariates`, as I narrowed down to a parameter that would be a 'breakpoint' of working (100, worked, 900 did not) I found that, in my enviornment, 549 (making 550 columns total) was a breakpoint (worked at 548, broke at 549).  

As it was running, I saw spikes in the reported memory consumption by RStudio going as high as 8GB.  The raw data in memory should not be this large, but possibly buffers are being allocated during `dbWriteTable` that is inefficient or some kind of memory leak.   This is the output of my gc() from R:

```
> gc()
            used   (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells    934718   50.0    1904365  101.8   1904365  101.8
Vcells 275954914 2105.4  728616966 5559.0 728593999 5558.8
```

If that helps show the memory usage.

So this issue could just be simply a limitation of my environment and not a bug, however it may be a bug that the operation doesn't handle the large-scale datafiles that you intend.

**Comment by rsund** [comment]
One option to install the latest development version is to get it from my r-universe -repo: [https://rsund.r-universe.dev/ui#builds](https://rsund.r-universe.dev/ui#builds).

One thing you could try is to set the memory limit explicitly (to be clearly smaller than your maximum memory):
`con <- duckdb::dbConnect(duckdb::duckdb(), file.path("test.duckdb"), config=list("memory_limit" = "4GB"))`

I understand that you want to write to create a "native" duckdb tables, but that may not be the best approach. Have you tried to use `duckdb::duckdb_register(con, "df1", df1)` instead of `DBI::dbWriteTable` as then you can make queries to data frames without copying those to duckdb database (e.g. `DBI::dbGetQuery(con,"SELECT COUNT(*) FROM df1;")` )? Hopefully the replacement scan for R data frames will be soon implemented and then there will be no more need even for separate registering of data frames.

You could also try to write tables to Parquet files e.g. `DBI::dbExecute("COPY df1 TO 'df1.parquet' (FORMAT PARQUET);")` and then and make queries directly from those: `DBI::dbGetQuery(con,"SELECT COUNT(*) FROM 'df1.parquet';")`

**Comment by chrisknoll** [comment]
Excellent thoughts, I'll take a look at those options.   At this point, we're evaluating replacing our current use of SQLite in place of duckdb as a persistence mechanism (normal dataframes proved to be not effective when the size of the dataframe exceeds the available, so the example I show you could be multiple dbWriteTable() calls to load several hundred gigs into the datastore for persistence).  So, while attaching a DF to duckdb is an itneresting option for certain usecases, ultimately we are going to want to persist a series of tables to the filesystem that will greatly exceed the ability to store all the contained tables in memory at once.

**Comment by rsund** [comment]
A native DuckDB filestorage may not be the best option to store large data as far as the storage format is not yet fixed but may change any time and has done that between releases so that it is not possible to read old storage file with a new version (and conversion to new format requires extra work). The native storage may also be problematic with several (simultaneous) users.

Therefore the Parquet files may currently be a better option for data storage. DuckDB supports querying direcly from those (has a native parquet reader).

If you plan to use dbWriteTable to write data into DuckDB, it is very likely that at least two times the size of dataframe of memory will be needed as you make a copy of data. With `duckdb_register()` you can avoid copying of data (DuckDB has native R data frame reader so no need to copy data first to DuckDB storage) and then write those to Parquet files with `COPY df TO 'df.Parquet' (FORMAT=PARQUET);`

It is also a good practise to define memory limit explicitely as otherwise (and occasionally even with the limit) extensive amounts of memory may be used.

You could also be interested in SQLite extension of DuckDB (https://github.com/duckdblabs/sqlitescanner) as with that you could make queries direcly from your existing SQLite database-files with DuckDB. However, so far the extension can be difficult to get working (at least with R-client).
