### ISSUE TITLE
0.3.3 R package

### ISSUE THREAD

**Issue by james-atkins** [duckdb/duckdb#3477]
The R package on CRAN is still v0.3.2 and the 0.3.3 release seems to be in the [waiting](https://r-hub.github.io/cransays/articles/dashboard.html) folder. Any update when the latest version is going to be published? Understand that dealing with CRAN is not always an easy process.

**Comment by rsund** [comment]
I'm also waiting for the new CRAN release as that is the easiest (and sometimes the only available) way to get packages into certain restricted environments.

It seems that DuckDB CIs for R show some NOTEs that probably cause delays in getting the release to CRAN: Some pragmas in a source file need to be removed and one third-party source is using stderr that is against the R package guidelines. Those should probably be quite easy to fix manually for the CRAN release, so hopefully there is nothing more serious behind the delay.

FYI, between the releases I have been using the unofficial R-universe build(s) for the latest DuckDB dev-version (including also all duckdb extensions that can be easily compiled with the R toolchain):  https://rsund.r-universe.dev/ui#builds

**Comment by krlmlr** [comment]
Should duckdb have its own r-universe? https://duckdb.r-universe.dev currently 404-s, I think organization owners/admins can setup here: https://github.com/apps/r-universe/installations/new .

**Comment by rsund** [comment]
FYI: Setting up the unofficial DuckDB build to the r-universe required some work as the rpkg-subdirectory as well as preparation of one source package that will build for all binaries supported by r-universe caused problems. I solved the problems by a scheduled CI that creates an r-universe compatible version of the repository: [https://github.com/rsund/duckdb-r/blob/main/.github/workflows/rpkg.yml](https://github.com/rsund/duckdb-r/blob/main/.github/workflows/rpkg.yml)

**Comment by krlmlr** [comment]
The NOTEs in question are:

```
* checking pragmas in C/C++ headers and code ... NOTE
Files which contain pragma(s) suppressing diagnostics:
  ‘src/duckdb/src/common/types/vector_constants.cpp’
  ‘src/duckdb/third_party/httplib/httplib.hpp’
* checking compilation flags used ... OK
* checking compiled code ... NOTE
File ‘duckdb/libs/duckdb.so’:
  Found ‘stderr’, possibly from ‘stderr’ (C)
    Object: ‘duckdb/third_party/libpg_query/src_backend_parser_scan.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.

```

See e.g. https://github.com/duckdb/duckdb/runs/6173550184?check_suite_focus=true#step:8:80 for a recent build on the main branch.

Do we need to clear the sources, or can we somehow `#define` away the offending parts?

**Comment by rsund** [comment]
@hannes mentioned in the [earlier discussion about the R NOTEs](https://github.com/duckdb/duckdb/pull/3180#issuecomment-1063897860) that he had manually removed the problematic pragmas from the earlier version, so those corrections could probably be easily checked from the old CRAN-release. I'm not sure, but the challenge for changing those in the DuckDB sources may be that some other supported clients/environments actually need those pragmas. 

I think that the stderr NOTE is relatively new and probably was not there at the time of older CRAN releases. I haven't checked that more closely, but usually those are relatively easy to patch by directing the stderr output to R console (by e.g. Rprintf) or maybe to silence it completely (by commenting those out), but in any case the calls to stderr need to be changed or overridden so that there are no more links to the "forbidden" keywords in the so/dll.

In general it seems that the CRAN release of DuckDB require also some other manual work for preparation of `Makevars` and `Makevars.win` to the same package, but probably those are clear steps so the manual work is tolerable to repeat for releases. But in any case, it would probably be a good idea to add checks for new/unexpected R NOTEs in the DuckDB CIs as those may be difficult to spot otherwise (see e.g. #3180, #3264, #3318, #3483).

Just guessing, but maybe the delay in getting 0.3.3 to CRAN is related to the bugfix release 0.3.4, i.e. corrections were not even planned to be submitted before 0.3.4 was released. In any case, in the [CRAN incomings](https://r-hub.github.io/cransays/articles/dashboard.html) DuckDB is still in the state "Waiting for the response from the developers".

**Comment by krlmlr** [comment]
Yeah, I think we might set `_R_CHECK_PKG_SIZES_` to `FALSE` and fail the check if a `NOTE` is found? I'll try this with another package first.

**Comment by hannes** [comment]
Yeah we failed a revdepcheck and then I was on vacation :/

**Comment by krlmlr** [comment]
I checked, `_R_CHECK_PKG_SIZES_=FALSE` gets rid of the NOTE related to the size of the binary, and we can change the check to also trigger in the presence of NOTEs. I'll take a look.
