### ISSUE TITLE
Wrong operator precedence for **

### ISSUE THREAD

**Issue by firerain42** [duckdb/duckdb#3561]
Executing 
```sql
SELECT 2**2 + 1;
```
returns the wrong value `8.0`, while executing
```sql
SELECT 2^2 + 1;
```
returns the correct result of `5.0`. The reason for this is most likely the different operator precedences.

**Comment by Tishj** [comment]
They're both handled by the same function
```
void PowFun::RegisterFunction(BuiltinFunctions &set) {
	ScalarFunction power_function("pow", {LogicalType::DOUBLE, LogicalType::DOUBLE}, LogicalType::DOUBLE,
	                              ScalarFunction::BinaryFunction<double, double, double, PowOperator>);
	set.AddFunction(power_function);
	power_function.name = "power";
	set.AddFunction(power_function);
	power_function.name = "**";
	set.AddFunction(power_function);
	power_function.name = "^";
	set.AddFunction(power_function);
}
```

But the first statement gets parsed into `2 ** (2 + 1)`

So I think this needs to be fixed in the grammar, as currently the `**` case is handled by this rule
```
			| a_expr qual_Op a_expr				%prec Op
				{ $$ = (PGNode *) makeAExpr(PG_AEXPR_OP, $2, $1, $3, @2); }
```
Whereas the `^` case is handled by this one
```
			| a_expr '^' a_expr
				{ $$ = (PGNode *) makeSimpleAExpr(PG_AEXPR_OP, "^", $1, $3, @2); }
```
Though I haven't yet identified why that causes this precedence issue, I figured it's best to note down some findings
