### ISSUE TITLE
ODBC data type error

### ISSUE THREAD

**Issue by sdmcallister** [duckdb/duckdb#3627]
#### What happens?

I try to load data in Power BI via odbc I see:

"This query does not have any columns with the supported data types. It will be disabled from being loaded to the model."

But I can preview the data prior to loading and transforming in Power BI which is odd.

#### To Reproduce
Successfully installed odbc on windows.
created a table and some test data using cli with something like this:
 `create table test (i int);` then `INSERT into test VALUES (42),(42);`

I tried the same thing with  a table with data type INT64 and got the same error.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: 0.3.4
 - DuckDB Client: ODBC/CLI

As an alternative I have successfully loaded duckdb data in power bi using a python to df script.

**Comment by tiagokepe** [comment]
Could you provide some prints with the steps to see how you are loading data into PowerBI (then I can try to reproduce)?

**Comment by sdmcallister** [comment]
Ok, it doesn't automatically detect data types and they have to be specified in Power BI.  Normally in csv or SQL Server it detects the type.

**Comment by tiagokepe** [comment]
I think this issue was already fixed since the latest DuckDB release. We have fixed some ODBC issues with PowerBI (#3439, #3478, and #3398) that will be available in the next release.

You can give it a try by grabbing the updated ODBC driver from the  [duckdb-binaries-windows](https://github.com/duckdb/duckdb/suites/6523720302/artifacts/243138718) generated in the action runs of the PR #3646.
