### ISSUE TITLE
Benchmark pages of website are broken

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#3709]
When you visit e.g., https://duckdb.org/benchmarks/append, the page attempts to make a request to `https://duckdbdemo.project.cwi.nl//query...`. In chrome, this errors with `net::ERR_CERT_COMMON_NAME_INVALID`. It looks like the site is serving a star cert for `*.cwi.nl`, but that doesn't work for the double-nested `duckdbdemo.project.cwi.nl`.

**Comment by Mytherin** [comment]
Thanks for the report! Indeed the benchmarks have been discontinued and have been replaced with our [Continuous Regression Tests](https://github.com/duckdb/duckdb/actions/workflows/Regression.yml). We want to bring back the benchmarks pages at some point with benchmarking info for every version rather than for every commit, but for now I have just removed the benchmarking pages from the website.

**Comment by zenazn** [comment]
Of course!
