### ISSUE TITLE
Adding N columns is slow, much slower than creating with N columns

### ISSUE THREAD

**Issue by haberman** [duckdb/duckdb#3780]
#### What happens?
When I use `ALTER TABLE` to add lots of columns, this is much slower than creating a table with the same number of columns.

#### To Reproduce
Repro:

```python
import duckdb
import timeit
import os

def create_db():
    filename = "test.duckdb"
    try:
        os.remove(filename)
    except OSError:
        pass
    return duckdb.connect(database=filename, read_only=False)


def create_with_many(n):
    con = create_db()
    cols = [f"val{i} INTEGER" for i in range(n)]
    query = "CREATE TABLE test(" + ", ".join(cols)+ ")"
    con.execute(query)


def alter_add_many(n):
    con = create_db()
    con.execute("CREATE TABLE test(val INTEGER)")
    con.begin()
    for i in range(n):
        con.execute(f"ALTER TABLE test ADD COLUMN val{i} INTEGER")
    con.commit()


def benchmark(func, n):
    time = timeit.timeit(lambda: func(n), number=1)
    print(f"{func.__name__}({n}) = {time:0.2f}s")


benchmark(create_with_many, 2000)
benchmark(alter_add_many, 2000)
```

Output:

```
create_with_many(2000) = 0.05s
alter_add_many(2000) = 14.21s
```

There doesn't seem to be any way to add more than one column with a single `ALTER TABLE` statement, and using repeated `ALTER TABLE` statements is very slow.

Two questions:
1. Is this expected?
2. Is this a reasonable use of DuckDB? If many of the columns are very sparse (ie. mostly `NULL`) can I expect reasonable performance? My hope is to get performance that is roughly linear in the number of non-NULL values.

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: duckdb-0.3.5.dev754
 - DuckDB Client: Python

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment]
Thanks for the report!

I have had a look at improving this in #3784, there was a regression caused by the newly added HyperLogLog statistics. Altering and adding many columns is still slower, but adding 2000 columns using alter statements completes in around ~0.7 seconds for me now on my machine.

The remaining costs here are related to creating `n` versions of the table, which each hold (amongst others) an `unordered_map` of the column names and a `vector` with the ColumnDefinitions. We create different versions rather than just modifying the table in place as part of the MVCC, so this is rather difficult to avoid. Allowing multiple columns to be added in a single `ALTER TABLE` statement will greatly improve performance here. 

> Is this a reasonable use of DuckDB? If many of the columns are very sparse (ie. mostly NULL) can I expect reasonable performance? My hope is to get performance that is roughly linear in the number of non-NULL values.

Yes, this should work reasonably well.

**Comment by haberman** [comment]
@Mytherin thank you for the info and the quick turnaround!

Re: many columns, one alternative I see would be using a `MAP`. But `MAP` doesn't seem to support aggregation. You could imagine a function `map_aggregate(map_col, aggregate_function)` that would return a map where all values with the same key are aggregated with the given function. Does that seem feasible, and how would it compare size/speed-wise to a large array of sparse columns?
