### ISSUE TITLE
Array_slice in macro type error

### ISSUE THREAD

**Issue by eaubin** [duckdb/duckdb#3822]
#### What happens?

A typing error `Binder Error: ARRAY_SLICE can only operate on LISTs and VARCHARs` is raised slicing into a macro parameter.

Mytherin confirmed this as a bug on discord and suggested casting x to a varchar as a work around.

#### To Reproduce

```sql
CREATE MACRO pyfloats_to_floats(x) AS (CAST(string_split(x[2:-1], ',') AS FLOAT4[]))
```
#### Environment (please complete the following information):
 - OS: Windows
 - DuckDB Version:  0.3.5.dev1091
 - DuckDB Client: Python

#### Before Submitting

- [X] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by lnkuiper** [comment]
@Mytherin This is due to `ArraySliceBind` checking for `LogicalTypeId::UNKNOWN`, but not for `LogicalTypeId::SQLNULL`, which is used by macro's. We can simply add the check for `SQLNULL` there, or we can change the type of macro parameters to `UNKNOWN`, which requires changing the `Bind` for a few functions here and there. I'm happy to do either

**Comment by lnkuiper** [comment]
Sounds good, I'll get on it!

**Comment by lnkuiper** [comment]
This is proving to be more difficult than I thought, as many things break when the expression is replaced with just `NULL`. Because the function is not bound, there is no `FunctionData`. Furthermore, prepared statements do not like it when we replace a function expression with a `NULL` parameter and a parameter expression, as the parameter expression gets lost this way.

**Comment by Mytherin** [comment]
That's a good point re: the parameter expressions. They will need to be removed from the `Binder::parameters` list.

Why is the missing `FunctionData` a problem?

**Comment by lnkuiper** [comment]
Thanks for the tip about the Parameters. The FunctionData ended up not being a problem.
