### ISSUE TITLE
Adding Custom Type Part 2

### ISSUE THREAD

**Issue by handstuyennn** [duckdb/duckdb#3827]
Hi @Mytherin 

Continuing from [this thread](https://github.com/duckdb/duckdb/pull/3490).
Part 1 ("Provide a way of creating a (named) alias to an existing type (e.g. a struct)") have been done.

I want to continue on Part 2: Provide a way of binding the type in functions, so functions can be created that take the type as input or output the type.

Could you tell me about which type will be provided a way to binding in functions?  An alias type in part 1?

I have investigated about binding type in functions. I found that when we create an alias type of `original type`, `alias type` could be an parameter of function which have parameter is `original type`
Eg, if we create alias type of `VARCHAR` with name `str_alias`, this type could be parameter of functions for `VARCHAR` like `concat`, `bit_length `, ...

Please give me advise for this.

Thanks

**Comment by handstuyennn** [comment]
Hi @mytherin,
Sorry to bug, just wanted to see if you could give me any feedback on the above before the weekend as I’d like to start on the next part of the task of implementing custom types.

**Comment by Mytherin** [comment]
> Could you tell me about which type will be provided a way to binding in functions? An alias type in part 1?

Yes, the idea here is that we add support for creating functions in the catalog and add support for binding them based on type-aliases. 

For example, let's say we have an alias `POINT` which is an alias for `STRUCT(x INT, y INT)`. We should be able to declare a function that takes as arguments that alias specifically (i.e. a `POINT` type), but that does NOT work if used with a `STRUCT(x  INT, y INT)`.

e.g. let's say I create a function, `add_point(POINT, POINT) -> POINT`. Then the following should happen:

```sql
CREATE TYPE POINT AS STRUCT(x INT, y INT);
CREATE TABLE my_table(my_point POINT, my_struct STRUCT(x INT, y INT));

-- this should work
SELECT add_point(my_point, my_point) FROM my_table;
-- this should give a binder error -> add_point only works on points
SELECT add_point(my_struct, my_struct) FROM my_table;

```

You would likely want to do this in a test extension (similar to e.g. `loadable_extension_demo`). 

I also noticed that this does not work yet, which should probably be fixed in the Parser:

```sql
CREATE TYPE POINT AS STRUCT(x INT, y INT);
```
