### ISSUE TITLE
R: RETURNING SQL clause not supported

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#3875]
#### What happens?

`INSERT INTO ... RETURNING ...` doesn't provide a result set, but it's available from the CLI.

#### To Reproduce

``` r
con <- DBI::dbConnect(duckdb::duckdb())

DBI::dbExecute(con, "CREATE TEMP TABLE x (a int, PRIMARY KEY (a))")
#> [1] 0
DBI::dbGetQuery(con, "INSERT INTO x VALUES (1) RETURNING (a)")
#> Warning in dbFetch(rs, n = n, ...): Should not call dbFetch() on results that do
#> not come from SELECT
#> data frame with 0 columns and 0 rows
```

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

```
➜  duckdb git:(d4c437597) ✗ echo "CREATE TEMP TABLE x (a int, PRIMARY KEY (a));
INSERT INTO x VALUES (1) RETURNING (a)
" | build/debug/duckdb
┌───┐
│ a │
├───┤
│ 1 │
└───┘
```

#### Environment (please complete the following information):

 - OS: macOS
 - DuckDB Version: d4c437597
 - DuckDB Client: R

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by krlmlr** [comment]
I'll take a look, the error comes from the R side.

**Comment by rsund** [comment]
It is easy to obtain the results in the following way (see [where the error is triggered here](https://github.com/duckdb/duckdb/pull/3876#issuecomment-1157563322)):

``` r
con <- DBI::dbConnect(duckdb::duckdb())

DBI::dbExecute(con, "CREATE TEMP TABLE x (a int, PRIMARY KEY (a))")
#> [1] 0
res <- DBI::dbSendQuery(con, "INSERT INTO x VALUES (1) RETURNING (a)")

res@env$resultset
#>   a
#> 1 1

DBI::dbDisconnect(con, shutdown=TRUE)
```

<sup>Created on 2022-06-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by rsund** [comment]
As pointed in #3876, also the R client should be updated to respect the query type as indicated by `GetStatementProperties().return_type`. Currently `dbFetch()` has too strict R-side condition to not allow fetching of any other than `SELECT` queries (or to be precise, `EXPLAIN` queries already have special handling).

In any case, as the example above shows, `dbSendQuery()` (that is not yet calling `dbFetch()`) is enough to get "access" to result set that contains the results of materialized query. I'm not quite sure whether these are always the full results (or only a first batch), but the point is that the data frame containing results has already been created there and the need for calling `dbFetch()` remains a bit unclear.

**Comment by krlmlr** [comment]
`dbSendQuery()` and `dbFetch()` are specified by DBI and tested by DBItest, for better or worse.

**Comment by rsund** [comment]
Yes, certainly the working and tested `DBI`-compatibility is the priority and no problems regarding that there, I think!

Maybe it would be a good idea to check (once more?) that the current code is not (unnecessarily) copying data to new data frame (resulting in the worst case to double memory requirement) but only referres to the "original" one. Also documentation for when fetching of the data in pieces is really necessary (i.e. is there cases in which the whole results are not mayerialized to the R res-object (obtained with e.g. `dbSendQuery()`). These things could be important especially with the larger-than-memory data. 

In any case, excellent to get a proper type information for the queries. Just wondering that maybe `dbGetQuery()` could be modified to return results for any query (data for actual queries or number of modified rows for others) instead of giving an error for "non-query cases"? Or is the error a requirement in the `DBI`-specification?

**Comment by krlmlr** [comment]
See also the new sections in https://dbi.r-dbi.org/reference/dbbind that describe the "data retrieval" and "command execution" flows.

Error/warning behavior is specified by DBI and subject to repeated discussion. We can do better with dbi3.

Where do you suspect that the current code wastes memory?

**Comment by rsund** [comment]
Many thanks for clarifications related to DBI! Interesting that DuckDB has results "available" already after the `dbSendQuery()`, i.e. even before `dbBind()`. In any case, very nice that DBI compatible interface is still the backbone for the R-client even though "simpler" one could have been used. I think a bit similar applies also for the driver and connection with DuckDB as it is not always easy (for me at least) to follow which tasks require driver and which connection. For instance, I would say that putting `shutdown=TRUE` as a default in `dbDisconnect()` is closer to the "expected" behaviour than the current default.

> Where do you suspect that the current code wastes memory?

In [`dbFetch()`](https://github.com/duckdb/duckdb/blob/8742b790923c2719430a6af778caa187a5a38c00/tools/rpkg/R/dbFetch__duckdb_result.R#L53-L78) the data frame is copied to another object before returning it. That should not generate a new copy, but the data frame is then possibly manipulated (timezones) that probably requires a new copy. Maybe the timezone manipulation could be done earlier and as an on place manipulation to avoid a second copy. With small results that doesn't matter, but with very large ones whole new copy of the whole set could be "fatal". As it also seems that the whole result set is already in a data frame after `dbSendQuery()`, fetching it (in chunks) feels a bit artificial thing to do. Especially if the results are not used for anything else than to return them, that "original" data frame could be directly constructed to correspond the needed one in order to restrict memory usage to minimum.

Despite these "ideas", I think that the most important thing is to have an R client that works in virtually all use cases (as currently). If it still could be improved would certainly be a plus, but maybe it is not a best investment to put too much effort in improvements without demostrated need. But I think that it is probably beneficial to have these kind of discussions if somebody someday could utilize the ideas or save some work in figuring out how the R client works "under the hood".
