### ISSUE TITLE
Mod operator applied to `UBIGINT, INTEGER` returns a `DOUBLE` type

### ISSUE THREAD

**Issue by jwills** [duckdb/duckdb#3931]
#### What happens?
The mod operator applied to a `UBIGINT, INTEGER` combination returns a `DOUBLE` instead of e.g. a `HUGEINT`, which surprised me; doing the mod of a `BIGINT` returns a `BIGINT` and the mod of a `HUGEINT` returns a `HUGEINT`. I'm not aware of any other cases where doing a mod of an integer type by another integer type returns a `DOUBLE` value.

I noticed this when I was testing the fix for #3920 and wasn't sure if it was a bug or if it was the intended behavior for that case.

#### To Reproduce
```SELECT typeof(1::ubigint % 2);```

#### Environment (please complete the following information):
 - OS: OS X
 - DuckDB Version: 0.4.0
 - DuckDB Client: CLI

#### Identity Disclosure:
 - Full Name: Josh Wills
 - Affiliation: WeaveGrid

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

No, but I'm pretty sure it's broken (?) there too.

- [] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yep, it's a straightforward one.

**Comment by Mytherin** [comment]
Thanks for the report!

The problem here seems to be that `2` is turned into an `INTEGER`, so the system tries to bind `mod(UBIGINT, INTEGER)`. `INTEGER` cannot be implicitly cast to `UBIGINT` since negative values might be out of range, while `UBIGINT` cannot be implicitly cast to `INTEGER` since large values might be out of range. The candidates are `mod(DOUBLE, DOUBLE)` and `mod(HUGEINT, HUGEINT)`, and the system prefers `DOUBLE` since it is faster performance wise.

In principle this makes sense to me, but perhaps it would make sense to turn constants into the smallest type that can represent them, so the constant `2` should instead be a `UTINYINT`.

**Comment by jwills** [comment]
Ah, gotcha-- so this would apply to essentially any arithmetic operations involving a mix of `UBIGINT` and `INTEGER`

**Comment by Mytherin** [comment]
Yes, perhaps changing the [implicit cast rules](https://github.com/duckdb/duckdb/blob/991d06596f4aa8b75c5e9c77642ce3bdcaccad0e/src/function/cast_rules.cpp#L13) to prefer `HUGEINT` over `DOUBLE` would be an improvement as well.
