### ISSUE TITLE
sql insert:  access last inserted id 

### ISSUE THREAD

**Issue by adamsch1** [duckdb/duckdb#3976]
I cannot find a way in the python API to acquire what sequence value was used for the most recent insert.  typically you can get this via last_insert_rowid, insert_id() depending on how you are talking to sqlite3, say, but I cannot find an equivelant in duckdb.  

Perhaps I missed something in the documentation but if so I cannot find it. 

Thank you!

**Comment by Mause** [comment]
The above is one solution, but a better one would probably be using the `RETURNING` keyword?

**Comment by Mytherin** [comment]
`RETURNING` seems like a better solution here:

```sql
D CREATE SEQUENCE seq;
D CREATE TABLE tbl(id INTEGER DEFAULT nextval('seq'), val INTEGER);
D INSERT INTO tbl (val) VALUES (10) RETURNING (id);
┌────┐
│ id │
├────┤
│ 1  │
└────┘
D INSERT INTO tbl (val) VALUES (10) RETURNING (id);
┌────┐
│ id │
├────┤
│ 2  │
└────┘
D INSERT INTO tbl (val) VALUES (10) RETURNING (id);
┌────┐
│ id │
├────┤
│ 3  │
└────┘

```

Although we should extend the client to allow for this information to be accessed without specifying the `RETURNING` clause.

**Comment by rsmckinney** [comment]
@Mause Looks like https://github.com/duckdb/duckdb/issues/3976 fell through the cracks as related to https://github.com/duckdb/duckdb/issues/1967. Fleshing out an entity with generated data after an insert/update is common practice, not having this capability readily available is concerning.  This is a bigger deal particularly for tooling using APIs such as JDBC. 

For instance, the `Connection#prepareStatement(sql, columnIndexes)` is not implemented in the duckdb driver. Usually, the next best option is to grab the generated keys, but that's not implemented either. Even Sqlite, which is pretty horrible as a JDBC driver, at least returns the `rowid` of the insert/update. Perhaps since duckdb similarly maintains a stable rowid, it can follow suit?

For duckdb I am currently appending a RETURNING clause to INSERT statements. This is hacky, I would expect the driver to handle that for me. Curiously, if I append a RETURNING clause to UPDATE statements, it results in a primary key collision error, which is a bug either in the driver or duckdb itself. As a consequence I am using the rowid to fetch the update results. Again, another hack.

I have a pile of issues mounting with the duckdb JDBC driver, there are so many holes it... My impression is that the driver should be qualified with "under construction" or "experimental" or similar to set expectations. Having a "1.0.0" designation is a bit misleading. Perhaps a roadmap describing unimplemented features, when/if they will be provided, and what the known workarounds are would help. _shrug_

**Comment by Mytherin** [comment]
DuckDB does not maintain stable row ids which is why this is tricky to implement. 

Could you file the other issues you mentioned in the [JDBC driver repository](https://github.com/duckdb/duckdb-java/issues) repository? They seem unrelated to this issue.

**Comment by rsmckinney** [comment]
@Mytherin The duckdb docs claim rowid is stable within a transaction. Isn’t that good enough?

**Comment by Mytherin** [comment]
It is stable within a transaction indeed, but when you `COMMIT` that stability is lost and rows are either (a) moved from transaction-local storage to the actual table storage, or (b) can be compacted/vacuumed, both of which alter row ids of previously written rows. Since `COMMIT` is often triggered implicitly (when connections are in auto-commit mode) that could cause confusion quite easily.

We could perhaps support this by making the function only work **within** a transaction, and having it return an error outside of a transaction - perhaps that is still useful. But unless I'm mistaken Postgres does not support row ids either and this is mostly a SQLite-only feature that is primarily useful within SQLite because it always maintains stable row-ids.

Reading your post it looks like you are primarily interested in using this as a work-around for features missing in the JDBC driver, I wonder if it would be more productive to work on implementing those features instead?
