### ISSUE TITLE
Question: Parquet requires much less space than DuckDB

### ISSUE THREAD

**Issue by FelixNeutatz** [duckdb/duckdb#4062]
Hi,

I am a  big fan of DuckDB :) but I am having memory issues. When I export my database to Paquet. The corresponding Parquet file requires 38.5 GB. However, when I load the table into DuckDB it takes more than 500GB. 

schema.sql
```
CREATE TABLE "AllTables"("CellValue" BIGINT, "TableId" BIGINT, "ColumnId" BIGINT, "RowId" BIGINT);
CREATE INDEX token_idx ON AllTables (CellValue);
```

So, now my question: Is there any way to reduce the memory space required? Are there any tricks to reduce the space?

Best regards,
Felix

**Comment by Mytherin** [comment]
Currently DuckDB first loads data into memory, and only then writes it to disk and compresses it. The reason for this is related to the transaction management - as this allows us to discard writes entirely in case of rollbacks. We will change this behavior in the future to start pre-emptively compressing and writing to disk during load - but loading a larger-than-memory Parquet file in one query will get you into trouble currently. I recommend splitting the Parquet file in multiple segments and loading it that way.

Alternatively you can also query the Parquet file directly using DuckDB instead of loading it into the system.

As a side note, are you sure you want to create an index? This will increase memory consumption, and is unlikely to help you (unless you are doing point selects on the `CellValue` column).

**Comment by FelixNeutatz** [comment]
Thank you for your answer. Yes, I need the index because I need an inverted index. I tried to save space by changing the data type. But unfortunately, the following does not work:

```
con.execute("CREATE TABLE AllTables(CellValue UINTEGER, TableId UINTEGER, ColumnId UINTEGER, RowId UINTEGER);")
con.execute("COPY AllTables FROM read_parquet('" + my_path + "/dresden/import/*.parquet');")
```

It throws the following exception:
```
RuntimeError: Parser Error: syntax error at or near "read_parquet"
```

**Comment by FelixNeutatz** [comment]
I found a hack around it

```
con.execute("CREATE TABLE AllTablesTemp(CellValue UINTEGER, TableId UINTEGER, ColumnId USMALLINT, RowId UINTEGER);")
con.execute("CREATE TABLE AllTables AS SELECT * FROM AllTablesTemp UNION SELECT * FROM read_parquet('" + my_path + "/dresden/import/*.parquet');")
```

**Comment by Mytherin** [comment]
It throws an exception because that SQL is not valid. You are mixing up two different syntaxes. The correct syntax is either:

```sql
COPY AllTables FROM 'test.parquet';
```

Or:

```sql
INSERT INTO AllTables SELECT * FROM read_parquet('test.parquet');
```
