### ISSUE TITLE
JDBC driver returns null for timestamp with time zone

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#4078]
#### What happens?
JDBC driver's `getTimestamp()` method works for timestamps without time zone information but returns null for timestamps with time zone information.

#### To Reproduce

* Clone this repository: https://github.com/szarnyasg/duckdb-jdbc-timestamps-test
* Run:
    ```bash
    mvn compile exec:java -Dexec.mainClass="my.Main"
    ```

The project contains two create-insert-retrieval operation sequences.

##### Without time zone

```java
stmt.executeUpdate("CREATE TABLE t1(ts timestamp without time zone);");
stmt.executeUpdate("INSERT INTO t1 VALUES (now());");

rs = stmt.executeQuery("SELECT ts FROM t1;");
while (rs.next()) {
    System.out.println(rs.getString(1));
    System.out.println(rs.getTimestamp(1));
}
```

This outputs:

```console
2022-07-09 19:19:49.824
2022-07-09 19:19:49.824
```

##### With time zone

```java
stmt.executeUpdate("CREATE TABLE t2(ts timestamp with time zone);");
stmt.executeUpdate("INSERT INTO t2 VALUES (now());");

rs = stmt.executeQuery("SELECT ts FROM t2;");
while (rs.next()) {
    System.out.println(rs.getString(1));
    System.out.println(rs.getTimestamp(1));
}
```

This outputs:

```
2022-07-09T19:19:49.831Z
null
```

So `getString()` works fine but [`getTimestamp()`](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#getTimestamp-int-) returns a `null`.

#### Environment (please complete the following information):
 - OS: Fedora 36
 - DuckDB Version: 0.4.0
 - DuckDB Client: Java

#### Identity Disclosure:
 - Full Name: Gabor Szarnyas
 - Affiliation: CWI

**Comment by Jens-H** [comment]
That looks wrong. The getTimestamp tries returns null if called and it is not a Timestamp column. The Integer for example tries to create the object via a round trip to string. Without success it would throw an error. The implementation should be changed to behave consistently.

```
if (isType(columnIndex, DuckDBColumnType.TIMESTAMP)) {
	return DuckDBTimestamp.toSqlTimestamp(getbuf(columnIndex, 8).getLong());
}
return null;
```

`return Integer.parseInt(o.toString());`

Anyway, calling getTimestamp will not return the result, because most probably the string cannot be parsed by Timestamp.valueOf(). 

The implementation follows the postresql way and returns an OffsetDateTime for TIMESTAMPTZ columns.

https://jdbc.postgresql.org/documentation/head/java8-date-time.html

You can see some examples in the tests:
[	public static void test_timestamp_tz() throws Exception {](https://github.com/duckdb/duckdb/blob/40e47cd36ba28a5970fbf8a91bee2858d6852086/tools/jdbc/src/test/java/org/duckdb/test/TestDuckDBJDBC.java#L332)

**Comment by szarnyasg** [comment]
Thanks for the fix. With DuckDB versions 0.5.0 and 0.5.1, the Java program now returns the following for timestamps with time zone:

```java
stmt.executeUpdate("CREATE TABLE t2(ts timestamp with time zone);");
stmt.executeUpdate("INSERT INTO t2 VALUES (now());");

rs = stmt.executeQuery("SELECT ts FROM t2;");
while (rs.next()) {
    System.out.println(rs.getString(1));
    System.out.println(rs.getTimestamp(1));
}
```
```console
2022-10-03T01:21:21.051Z
java.lang.IllegalArgumentException: Timestamp format must be yyyy-mm-dd hh:mm:ss[.fffffffff]
    at java.sql.Timestamp.valueOf (Timestamp.java:204)
    at org.duckdb.DuckDBResultSet.getTimestamp (DuckDBResultSet.java:499)
    at my.Main.main (Main.java:30)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
    at java.lang.Thread.run (Thread.java:748)
```

This seems to be in line with the expected behaviour.
