### ISSUE TITLE
Support ANY_VALUE aggregate function

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#4092]
Google BigQuery supports the [any_value](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#any_value) aggregate function which returns the first non-null value encountered. We have a similar function (`first`), but it returns the first value encountered. We would like to add support for the `ANY_VALUE` function as well.

**Comment by mauropagano** [comment]
I'd like to give it a shot, unless somebody picked it already.

I went through the code but I've a few questions:
1. I think this could be implemented either in `first.cpp` adding an extra template parameter and tweaking the logic or adding a new class altogether (e.g. `any_value.cpp`), what's the preferred approach?
2. When trying to run tests via `make unit` (from CONTRIBUTING) they take a lot longer than a minute, more around 15-20min, is that expected? I'm talking about running the tests, not building them. Am I doing something wrong?
3. When looking into the existing code I noticed `last()` always returns the value from the first query block in case of union all (e.g. `select last(n) from (select 0 n union all select 1)` (reproduces in shell.duckdb.org), is that expected behavior? If not maybe I could try to look into that too (unless you think it would get too hard as a first issue) 

Full disclosure: my C++ is very rusty so I may stumble on simple things, apologies in advance

**Comment by Tishj** [comment]
Hey, awesome to hear you wanna pick this up
1. I haven't looked into it too much, but it sounds like `first` could have an optional argument like `SKIP_NULLS`. Then `ANY_VALUE` could be a macro that calls `first` with SKIP_NULLS.
(have a look at `src/catalog/default/default_functions.cpp` to see what I mean by macro)
2. I believe `make unit` runs all unit tests, as that is the default behavior of `build/debug/test/unittest`.
But this same binary can also run a specific test file, for example:  
`./unittest test/sql/aggregate/aggregates/test_first_noninlined.test`

I can't really give you an answer on 3 though, hopefully Mytherin has an answer for you :)
