### ISSUE TITLE
Distinct stat is not written to parquet metadata

### ISSUE THREAD

**Issue by halvorlinder** [duckdb/duckdb#4182]
#### What happens?
When writing a table to a parquet file, the distinct stat is not set.

#### To Reproduce
```
CREATE TABLE TEST(A int);
INSERT INTO TEST VALUES(0);
COPY (SELECT * FROM TEST) TO 'test.parquet' (FORMAT 'parquet');
SELECT * FROM parquet_metadata('test.parquet');
```
Inspect the "stats_distinct_count" column.

#### Environment (please complete the following information):
 - OS: Ubuntu 20.04.4 LTS
 - DuckDB Version: v0.4.0 da9ee490d
 - DuckDB Client: CLI

#### Identity Disclosure:
 - Full Name: Halvor Linder Henriksen 
 - Affiliation: Huawei

**Comment by lnkuiper** [comment]
In order to write the exact distinct count to parquet files we would need to run a `count(distinct(col))` for every column, which is very expensive.

DuckDB only stores an approximate distinct count for base tables, which it potentially could write to the parquet metadata. However, this could have some bad consequences if the parquet file is then read by a parquet reader that assumes this distinct count to be accurate.

**Comment by Mytherin** [comment]
We could likely set it for dictionary-encoded string columns, since we know the distinct count from the dictionary.

**Comment by djouallah** [comment]
it will be nice to have it, it is better to pay a price for write then for read later:)
