### ISSUE TITLE
arrow dictionary types are converted to strings

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#4290]
### What happens?

Thanks for this great library. It was amazingly easy to get it set up and start using it on some parquet files.

Please excuse me if this isn't a bug, but I would think that arrow's dictionary dtype would be treated as duckdb's ENUM type, but instead it looks like it's converted to strings

### To Reproduce

Just tried with
```
duckdb==0.4.1.dev1225 (AKA main)
numpy==1.23.1
pyarrow==9.0.0
```

```python
import duckdb
import pyarrow as pa

dict_array = pa.DictionaryArray.from_arrays(
    pa.array([0, 1, 0, None]),
    pa.array(["a", "b"]),
)
before = pa.Table.from_pydict({"dicts": dict_array})
before
```
results in, as expected
```
pyarrow.Table
dicts: dictionary<values=string, indices=int64, ordered=0>
----
dicts: [  -- dictionary:
["a","b"]  -- indices:
[0,1,0,null]]
```
But if we put this into duckdb:
```python
con = duckdb.connect()
description = con.execute("DESCRIBE SELECT * FROM before").arrow()
description
```
We see that `column_type` is VARCHAR:
```
pyarrow.Table
column_name: string
column_type: string
null: string
key: string
default: string
extra: string
----
column_name: [["dicts"]]
column_type: [["VARCHAR"]]
null: [["YES"]]
key: [[null]]
default: [[null]]
extra: [[null]]
```
I'd like to be able to do round trips from parquet files -> duckdb -> back to parquet files, and for the schema to stay the same. But, because of that early conversion, all subsequent operations keep the VARCHAR type:
```python
after = con.execute("SELECT * FROM before").arrow()
after
```
gives
```
pyarrow.Table
dicts: string
----
dicts: [["a","b","a",null]]
```

### OS:

macOS 12.4

### DuckDB Version:

0.4.1.dev1225

### DuckDB Client:

Python

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pdet** [comment]
Hey, @NickCrews this issue is similar to #4268.

The reason why Arrow dictionaries are not exported to ENUMs is the following:

"The Arrow Dictionary is not the same as an Enum Type, but rather similar to an internal vector representation type of DuckDB.

The main difference is that the keys are local to batches and not global to the whole column. Hence when consumed, the dictionary type is consumed as a vector with a selection vector, and not as an Enum type.

On the other hand, ENUMs can be exported as dictionary vectors."

@hannes , since this issue keeps coming up, maybe we should add it into our documentation somewhere? not sure if you have a suggestion in mind.

**Comment by hannes** [comment]
Yes, lets document this.

**Comment by erinov1** [comment]
I was looking for workarounds for the roundtrip (e.g., querying the table and creating an enum type from the unique values), and noticed that arrow has a dictionary unifier method for unifying keys across chunks. The python bindings for Table are here: https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.unify_dictionaries. Could this maybe be used internally in duckdb?

**Comment by pdet** [comment]
I think that could be an option, although I'm not exactly sure how to integrate with that.
My guess is that the unification will have a considerable extra cost since it means not only unifying the dictionaries but also rewriting the existing column values, so I'm not sure if we should do it automatically.

Maybe a possibility would be to add one new parameter to the arrow scanners to treat dictionaries as enums, then call the unification function internally and then consume all the dictionaries of that table as enums. 
If we do this, then the question is how this would work with replacement scans.

Maybe @Mytherin has an opinion about this?

**Comment by hannes** [comment]
Problem with unification is of course also that it does not work on streams

**Comment by pdet** [comment]
Very true. This could only be added to table objects.

**Comment by NickCrews** [comment]
OK, it looks like there isn't any solution that I am looking for. I misunderstood the semantics of what a pyarrow dictionary array was. Perhaps if this gets added to the docs, a good way of explaining it is in terms of physical vs logical. I'm fine with closing this, it seems like there aren't any easy improvements, and this isn't a huge pain point.
