### ISSUE TITLE
using `UNION ALL` with a `LIMIT` expression causes a parser error

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#4325]
### What happens?

using `UNION ALL` when the first union query has a `LIMIT` expression causes a parser error. If I add parens around the query with `LIMIT`, the parser error goes away. If the `LIMIT` expression is on the last union query, there is no error.

### To Reproduce

This throws a parser error: 

```sql
WITH tbl AS (
  select 1 as num
  UNION ALL select 2 as num
)
-- relevant part
SELECT * from tbl LIMIT 1
UNION ALL SELECT * from tbl
```

This will work:

```sql
WITH tbl AS (
  select 1 as num
  UNION ALL select 2 as num
)
-- relevant part
(SELECT * from tbl LIMIT 1)
UNION ALL SELECT * from tbl
```

### OS:

Mac 12.1

### DuckDB Version:

0.4

### DuckDB Client:

node / CLI

### Full Name:

Hamilton Ulmer

### Affiliation:

Rill Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

That is required in order to avoid ambiguity in the parser - the `LIMIT` (and `ORDER`) applies to the entire set operation, and can only be placed at the end of the set operation, e.g.:

```sql
SELECT * FROM range(10) UNION ALL SELECT * FROM range(10) LIMIT 5;
┌───────┐
│ range │
├───────┤
│ 0     │
│ 1     │
│ 2     │
│ 3     │
│ 4     │
└───────┘
```

In order to apply `LIMIT` only to one of the internal elements of the set operation, brackets are required:

```sql
SELECT * FROM generate_series(0,10,1) UNION ALL (SELECT * FROM generate_series(0,10,1) LIMIT 5);
┌─────────────────┐
│ generate_series │
├─────────────────┤
│ 0               │
│ 1               │
│ 2               │
│ 3               │
│ 4               │
│ 5               │
│ 6               │
│ 7               │
│ 8               │
│ 9               │
│ 10              │
│ 0               │
│ 1               │
│ 2               │
│ 3               │
│ 4               │
└─────────────────┘

```

If we were to allow `LIMIT` without parenthesis within the set operation there would be ambiguity there, since the last limit could belong to either the entire set operation, or only the last query in the set operation. This follows the same behavior as Postgres in this situation.
