### ISSUE TITLE
ENUM data requires more space than VARCHAR

### ISSUE THREAD

**Issue by FelixNeutatz** [duckdb/duckdb#4393]
Hi everybody,

I wanted to make the following table use less space:
```
CREATE TABLE AllTables(CellValue VARCHAR, TableId UINTEGER, ColumnId USMALLINT, RowId UINTEGER);
>> 520,6 MB

SELECT count(*) FROM AllTables
>> 28.525.637

SELECT COUNT ( DISTINCT CellValue ) FROM AllTables
>> 4.709.270
```
So, my idea was to create an ENUM of all distinct values because there are 6 times more values than unique values.
```
all_vals = ''
for str_val in list(enum_dict.keys()):
    all_vals += "'" + str_val + "', "
all_vals = all_vals[:-2]

con.execute("CREATE TYPE str_value AS ENUM (" + all_vals + ");")

CREATE TABLE AllTables(CellValue str_value, TableId UINTEGER, ColumnId USMALLINT, RowId UINTEGER);
```
However, this database requires more than 1.5GB.

Did I do something wrong here?

Best regards,
Felix

**Comment by Mytherin** [comment]
Perhaps the enum type info is duplicated - since you have millions of values in your enum any duplication of the type becomes problematic.

However, I would not recommend using enums when you have millions of values in the first place. DuckDB already automatically does dictionary compression on a per-block level in the first place, so the gains with using enums are small to begin with. I would recommend using enums only if you have a very small set of unique values (<1000, but certainly <10000).

**Comment by FelixNeutatz** [comment]
Ok, thank you for your quick help :)
