### ISSUE TITLE
parquet_scan does not work on s3 if using s3_url_style=path

### ISSUE THREAD

**Issue by joshuarobinson** [duckdb/duckdb#4527]
### What happens?

An error message is returned. Here is an example
```
con.execute("SELECT * FROM parquet_scan('s3://joshuarobinson/tpcds_sf1000/web_sales/*.parquet') LIMIT 10")
...
RuntimeError: HTTP GET error on 'https://s3.amazonaws.com/joshuarobinson/?encoding-type=url&list-type=2&prefix=tpcds_sf1000%2Fweb_sales%2F' (Error code 1)
```

But if I switch to "vhost" then everything works.

If I try to use read_parquet with path-style addressing, everything works. So it seems to be something in the way that the LIST operation is constructed (where the normal GET works).

For context, I'm really trying to run against an external object store where I need path-style addressing. I have tried and reproduced same issue on a minio server.

I'm using duckdb 0.4.0 installed via pip (also tried duckdb-0.4.1.dev2348 numpy-1.23.2)

### To Reproduce

Try a parquet_scan on an S3 source with configuration s3_url_style=path

### OS:

ubuntu

### DuckDB Version:

0.4.0

### DuckDB Client:

python

### Full Name:

Joshua Robinson

### Affiliation:

Nvidia

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by samansmink** [comment]
Can reproduce this. The issue is that the default endpoint s3.amazonaws.com should be changed to `s3.<region>.amazonaws.com` for it to work. See aws docs [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html).

@joshuarobinson could you try setting the endpoint to an endpoint containing the region using: `set s3_endpoint='s3.eu-west-1.amazonaws.com'`? I will update our documentation on httpfs soon as it is not very complete atm.

Secondly, with Minio I would expect this to work, our CI runs the HTTPFS tests using Minio and all tests should use both url styles, see for example `test/sql/copy/s3/download_config.test`. Could you provide a reproducible example that shows it failing with Minio?

**Comment by joshuarobinson** [comment]
thanks Sam,
I took a quick look at those tests and didn't see one that uses parquet_scan() with the path style addressing, which is the only thing that was failing for me.  Are you able to get parquet_scan specifically working with minio?  (or is there a test that covers that which I missed)

I'll work on the repro with minio in the meantime...

**Comment by samansmink** [comment]
For example the test `test/sql/copy/parquet/parquet_glob_s3.test` covers this:

this snippet from line 45:
```
# Test variety of urls with both url styles
foreach urlstyle path vhost

statement ok
SET s3_url_style='${urlstyle}'
``` 
ensures everything in that loop is run in both path-style as vhost-style urls. These tests are run in CI using Minio.

Did you try switching the endpoint to one containing the region?

**Comment by samansmink** [comment]
Hi @joshuarobinson i'm not sure, i suspect this is an incompatibility between the way httplib encodes urls and Swift. [This](https://github.com/yhirose/cpp-httplib/blob/b57f79f43882bbc0268999647890bd621bd22c94/httplib.h#L2096) line in httplib seems to hint at a possible cause?
