### ISSUE TITLE
Address boundary error when using PARTITION BY

### ISSUE THREAD

**Issue by kmwang** [duckdb/duckdb#4625]
### What happens?

`PARTITION BY` a "TEXT" key might crash duckdb under certain conditions.

### To Reproduce

```sql
CREATE TABLE "crash"
("amount" "FLOAT", 
 "account" "TEXT");

INSERT INTO "crash"
VALUES
 (1000, '123456789012'),
 (1000, '1234567890123');

SELECT SUM("amount") OVER (PARTITION BY "account"
                           ORDER BY "account" ASC
                           ROWS CURRENT ROW)
FROM "crash";
```
However, duckdb runs just fine if we change `1234567890123` to `123456789012` (or a shorter value).

### OS:

MacOSX (M1)

### DuckDB Version:

0.5.0, v0.5.1-dev7

### DuckDB Client:

cli & jdbc

### Full Name:

Benjamin Wang

### Affiliation:

N/A

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
We're aware of this issue, it was brought up a few days ago by Pedro Tadim.
Any string larger than 12 characters causes this problem, it's probably a bug in constant handling. (12 is string_t::INLINE_LENGTH, exceeding that makes the size no longer constant)

**Comment by hawkfish** [comment]
The problem is that the partition and ordering layouts do not have matching constant states.

**Comment by lnkuiper** [comment]
I looked into this and it seems like the left and right `SortedBlock` have the same `SortLayout` when being compared, but a different `SortLayout` is being passed into the comparison function at `physical_window.cpp:80`, causing the crash.

I'll look into a fix today.

**Comment by lnkuiper** [comment]
I think I've found the problem. I have an optimization in `SortLayout`, that treats `VARCHAR` key columns as constant if we can derive from the statistics that their size is less or equal to 12 chars.

The problem here is that when we use a different `SortLayout` for the same data. For the partitions, we sort only by a single string, which has a max size of 13, and we get an entry size of 16 for the `SortLayout` (prefix 12 chars + 32bit int for row id, and it always rounds to multiples of 8). This makes the string just slightly too long to be compared with just the constant comparison.

When we sort by two strings, both 13 chars, we get 12 + 12 + 4 = 28 for our entry size. This is not a multiple of 8, we have 4 bytes to spare for 32 bytes. So, we encode the full 13 bytes of both strings, for 13 + 13 + 4 = 30, and 2 bytes of padding, making the comparison constant.

So, we have a non-constant `SortLayout` for the partitions, and a constant `SortLayout` for the partition + order. What we should do here is create a `GetPrefixComparisonLayout(idx_t num_cols)` to `SortLayout`, and use that for the partitions.
