### ISSUE TITLE
IGNORE_ERRORS on CSV import ignored

### ISSUE THREAD

**Issue by taniabogatsch** [duckdb/duckdb#5250]
### What happens?

I am trying to import a csv file with `read_csv_auto`. Even though I set `ignore_errors=True` it throws an error. I would have expected the csv parser to just skip all erroneous lines. If I set the quotes/escape to a string that does not occur in the data it runs smooth-ish (except it does not escape/quote anymore ofc).

### To Reproduce

Downloaded the data set from here: https://dumps.wikimedia.org/enwiki/latest/
Filename: enwiki-latest-all-titles.csv

```sql
# fails
CREATE TABLE titles AS SELECT * FROM read_csv_auto('enwiki-latest-all-titles.csv', ignore_errors=True);

# works
CREATE TABLE titles AS SELECT * FROM read_csv_auto('enwiki-latest-all-titles.csv', ignore_errors=True, quote='duckdbissupercool', escape='duckdbisacooldb');
```

### OS:

iOS

### DuckDB Version:

master

### DuckDB Client:

CLI

### Full Name:

Tania Bogatsch

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I think we want to fix this by adding a BOOL vector to the parse_chunk, where we register which tuples are ignored and which aren't
We already do something like that temporarily for the conversion error ignore, and since this needs similar treatment (one error on line results in stripping out the entire tuple) it's probably best to put it in one place

**Comment by taniabogatsch** [comment]
This was fixed here: https://github.com/duckdb/duckdb/pull/8253
