### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by ericman93** [duckdb/duckdb#5274]
### What happens?

Hey, I'm trying to run a very simple SQL over 20 million records and the RAM is going wild

When loading my DF to memory, I see (I'm running a Jupyter notebook on k8s) that 11GB is being used
After running the code below (register and return the table I just registered) I see that 53GB is being used
In 0.5.2 beta "only" 42GB ram was used

I tried adding `memory_limit='10GB'` but it didn't help and I tried to have a column with only unique values so it might be the PK (I didn't see any options to pass a PK column to `register` method)

### To Reproduce

this is the example file:
https://drive.google.com/file/d/1MgbQwZXy_QzIegkMAHEjTIR0_sQzZZED/view?usp=sharing

```
import pandas as pd
import duckdb

df = pd.read_csv(<attach file>)
con = duckdb.connect(database=":memory:")

try:
    con.register('mytable', df)

    con.execute("Install 'json'; Load 'json'")
    con.execute("SET enable_external_access=FALSE; SET memory_limit='10GB'; SET access_mode=READ_ONLY")

    result_rel = con.from_query('select * from mytable')

    output = result_rel.df()
finally:
    con.close()
```

### OS:

x86_64

### DuckDB Version:

0.5.2.dev1973

### DuckDB Client:

Python

### Full Name:

Eric Feldman

### Affiliation:

Explorium

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is probably related to materializing a very large dataframe - we currently first materialize the result as a DuckDB query result, then convert it to a Pandas DataFrame. You then have effectively three copies of the data in memory. The original dataframe, the DuckDB query result, and the output DataFrame.

We have plans to improve this in the future by removing the DuckDB query result and directly constructing the output DataFrame - but that is not there yet.

Thee memory limit does not help you in this situation since the memory consumption does not come from inside the DuckDB database engine. The result lives as a separate object - as do the two DataFrames.

**Comment by ericman93** [comment]
Will it act different using pyarrow?

**Comment by Mytherin** [comment]
In Python all of our result set materialization first goes to a DuckDB query result. You could of course load the query result into a DuckDB table instead using e.g. `CREATE TABLE result AS ...`.
