### ISSUE TITLE
DECIMAL field truncates on precision loss, rather than rounds

### ISSUE THREAD

**Issue by jardayn** [duckdb/duckdb#5288]
### What happens?

When I insert a DECIMAL or FLOAT of a higher precision than the column supports - PSQL/MySQL rounds it before saving.

DuckDB truncates. Which makes it an outlier.

To test in PSQL:

```
CREATE TABLE qwe (
	id serial PRIMARY KEY,
	dec decimal(10,3) NOT NULL,
	fl NUMERIC ( 10,3 ) NOT NULL
)

INSERT INTO qwe(dec,fl) VALUES (20.999999,5.99999999),(5.123123,5.123123123),

SELECT * FROM qwe
```

### To Reproduce

```
CREATE TABLE test(
dec DECIMAL(5,3)
)

INSERT INTO test VALUES (2.99999),(3.123), (8.8976553)

SELECT * FROM test
```

### OS:

linux

### DuckDB Version:

5.0.2

### DuckDB Client:

Python

### Full Name:

Igor

### Affiliation:

none.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
postgresql 15.0
```sql
mydb=# CREATE TABLE test(
mydb(# dec DECIMAL(5,3)
mydb(# );
CREATE TABLE
mydb=#
mydb=# INSERT INTO test VALUES (2.99999),(3.123), (8.8976553)
mydb-# ;
INSERT 0 3
mydb=# SELECT * FROM test;
  dec
-------
 3.000
 3.123
 8.898
(3 rows)
```

**Comment by Tishj** [comment]
The issue is that we already figure out how big the internal type should be, based on the width
And because of that we physically can't store more decimals than the internal type allows.

If the width is 1-4, the internal type is `int16_t`, which can only store up to 4 digits
so this example:
```
query I
select '1.23450000001'::DECIMAL(4,3)
----
1.235
```
while casting, currently we can only hold `1.234` and the others are ignored because the type physically cant store it
