### ISSUE TITLE
DuckDB hangs in Python when querying a RecordBatchReader returned by a previous DuckDB query

### ISSUE THREAD

**Issue by nph** [duckdb/duckdb#5397]
### What happens?
Running a query in the DuckDB python client, returning the results as an Arrow RecordBatchReader and then running a second query against the returned RecordBatchReader causes DuckDB to hang.

The size of the query data doesn't appear to be a factor - the second query on the returned RBR will hang when the first query is performed on a small Arrow table (see example below) or a reasonably large Arrow dataset (GBs). I've experimented a bit with the `chunk_size` argument to `fetch_record_batch` but so far have not been able to find a setting that works.

Note that the RecordBatchReader returned by DuckDB can be materialized as an Arrow Table (and then optionally converted back to an RBR using Arrow) and this object can be successfully queried by DuckDB. 

### To Reproduce
This hangs after the final statement:
```
import duckdb
import pyarrow as pa

con = duckdb.connect(database=':memory:')

# Create a simple Arrow table
arrow_table = pa.Table.from_pydict({'i':[1, 2, 3, 4], 'j':["one", "two", "three", "four"]})

# Query and return results as a RecordBatchReader
con.execute('SELECT * FROM arrow_table WHERE i < 3')
duckdb_rbr = con.fetch_record_batch()

# Now try to query the RecordBatchReader
# THIS HANGS...
con.execute('SELECT * FROM duckdb_rbr WHERE i > 1')
```

This works successfully:
```
import duckdb
import pyarrow as pa

con = duckdb.connect(database=':memory:')

# Create a simple Arrow table
arrow_table = pa.Table.from_pydict({'i':[1, 2, 3, 4], 'j':["one", "two", "three", "four"]})

# Query and return results as a RecordBatchReader
con.execute('SELECT * FROM arrow_table WHERE i < 3')
duckdb_rbr = con.fetch_record_batch()

# Create a new Arrow table from the DuckDB RBR and query the resulting table
arrow_table2 = pa.Table.from_batches(duckdb_rbr)
con.execute('SELECT * FROM arrow_table2 WHERE i > 1')
con.fetchall()
# [(2, 'two')]
```

### OS:
MacOS

### DuckDB Version:
0.6.0

### DuckDB Client:
Python

### Full Name:
Nick Hughes

### Affiliation:
Interval IQ

### Have you tried this on the latest `master` branch?
- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] I agree

**Comment by pdet** [comment]
Hi @nph 

The issue here is that the Record Batch Reader has a streaming query, so when you try to consume the query from the same connection, a result dependency in the connection is created which deadlocks. Also if you try to execute another query and then try to consume the reader, the reader gets borked.

I'm not yet entirely sure how to solve this, the options I can think of are:
1) I either have to block connections from executing new queries if their result is a stream or a record batch reader
2) Immediately materialize that query result
3) Throw an error if the result that the reader depends on gets invalidated before the reader is done.

As a workaround, you can use a different connection to consume the reader. e.g.,

``` python
import duckdb
import pyarrow as pa

con = duckdb.connect(database=':memory:')
con_2 = duckdb.connect(database=':memory:')

# Create a simple Arrow table
arrow_table = pa.Table.from_pydict({'i':[1, 2, 3, 4], 'j':["one", "two", "three", "four"]})

# Query and return results as a RecordBatchReader
con.execute('SELECT * FROM arrow_table WHERE i < 3')
duckdb_rbr = con.fetch_record_batch()

print(con_2.execute('SELECT * FROM duckdb_rbr WHERE i > 1').fetchall())
```

**Comment by nph** [comment]
Hi @pdet 

Thanks a lot for the quick response and the helpful explanation. Regarding the options you laid out, I think 1 and/or 3 are reasonable choices, whereas 2 could potentially be problematic for large datasets.

Unless there's an alternative solution it might be worth updating the docs to make a note of this issue - happy to submit a PR for that if it would be helpful?

Thanks for pointing out the workaround. I'm curious what the overhead is in creating a new connection to an in-memory DB? I'm currently working on an ML library that (amongst other things) samples time-series data segments from an Arrow dataset. I'm wondering how much overhead might be incurred by creating a new DuckDB connection for every sampling operation from the DB? Appreciate this is somewhat ill-defined but would be grateful for any advice on this.

Thanks!

**Comment by pdet** [comment]
Hi @nph,

most of the cost when creating a new connection is due to creating a new database instance.

You can create named memory connections, which will then share the same (cached) database instance, then it shouldn't have much of an increased cost on having multiple connections.

Thanks for the offer of updating the docs, but this is clearly a bug, as in we shouldn't just randomly deadlock or crash stuff. Many thanks for finding and reporting this as well!

**Comment by nph** [comment]
Thanks @pdet! Appreciate the info.
