### ISSUE TITLE
R: allocator check is triggered when connection is cleaned up in a finalizer on exit

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#5446]
### What happens?

When running the R code below in a clean session, the following error message appears:

```
Finalizing
Done finalizing
libc++abi: terminating with uncaught exception of type duckdb::InternalException: INTERNAL Error: Assertion triggered in file "/Users/kirill/git/R/duckdb/src/common/allocator.cpp" on line 201: allocation_count == 0
```

The messages about finalizing come from the R code, just to indicate that work is done.

Can we somehow avoid the message in this case?

### To Reproduce

1. Store the R code in a new file `alloc.R`
2. Run `R -q -f alloc.R`

```r
library(duckdb)

env <- new.env(parent = emptyenv())

con <- dbConnect(duckdb())

env$con <- con
reg.finalizer(env, onexit = TRUE, function(e) {
  message("Finalizing")
  dbDisconnect(env$con, shutdown = TRUE)
  message("Done finalizing")
})
```

### OS:

macOS

### DuckDB Version:

160ae452

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
This internal exception means that an allocator object was destroyed while there are still out-standing allocations from that allocator object. This is almost always a bug - because if those outstanding allocations are then attempted to be freed the code will trigger a use-after-free because freeing those resources requires using the allocator. Perhaps there is global state in the R client that is destroyed in the wrong order somehow?

**Comment by hannes** [comment]
This is caused by the altrep we use for strings that is used when querying the keywords. the keywords are stored in the connection, still as altrep, and the string heap in them is still alive by the time the database gets cleaned up.
