### ISSUE TITLE
Write amplification (300x) in copy (select * from read_csv_auto() order by 1) to 'file.parquet'

### ISSUE THREAD

**Issue by brendanyounger** [duckdb/duckdb#5490]
### What happens?

When importing a ~1GB csv file with an order by clause, duckdb ends up writing and reading >300GB to the file system. This seems excessive considering that the entire csv file could comfortably live in RAM.  The import process also takes well over 30 minutes.

### To Reproduce

Download https://download.cms.gov/nppes/NPPES_Data_Dissemination_November_2022.zip and extract the csv's inside.

```sql
LOAD parquet;
INSTALL parquet;
PRAGMA temp_directory='/tmp';
copy (select * 
from read_csv_auto('npidata_pfile_*.csv', HEADER=True, ALL_VARCHAR=True) 
order by \"NPI\") 
to 'npidata.parquet' (format 'parquet');
```

### OS:

Mac OS X 12.6, x64

### DuckDB Version:

v0.6.0

### DuckDB Client:

CLI

### Full Name:

Brendan Younger

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Maybe @lnkuiper can have a look?

**Comment by lnkuiper** [comment]
The CSV file in question is 8.5GB, not 1GB.

All columns are `VARCHAR`, and virtually all of the data in the CSV file are empty strings. In the CSV file, these take up two bytes per string, because they are written as `""`. There are 7,564,012 rows and 330 columns.

When reading the CSV, the strings are loaded into DuckDB as a `string_t`, which is 16 bytes. So, the size of the data in memory is 7,564,012 * 330 * 16 bytes = ~40GB.

To sort the data, DuckDB has to materialize the data in memory fully. To sort more data than fits in memory, we use an external merge sort. This requires writing data to disk and rereading it many times. Our implementation of this could be improved.

If you import the data from the CSV without sorting it, it still takes quite some time, but because there are so many strings, DuckDB is able to compress it very well. The table ends up taking up only ~1.6GB, which is great given the initial 8.5GB.

The column you are sorting by , `"NPI"` is a `VARCHAR`, but in reality this can be a `BIGINT`. Sorting by `BIGINT` will improve sorting performance, as comparing strings is more costly than integers.

Do you really need to sort the data? Or do you really need to sort all columns? I can recommend loading the CSV file into a table first, using a `CREATE TABLE AS`. Convert `NPI` to a `BIGINT`, and then select only the columns that you need, and sort them by `NPI`.

**Comment by brendanyounger** [comment]
Thank you for the explanation @lnkuiper 

It makes a lot more sense now that I know the empty columns are taking up that much space.
