### ISSUE TITLE
timestamptz?

### ISSUE THREAD

**Issue by r2evans** [duckdb/duckdb#561]
Is there a specific reason that TZ support is not provided?

I might be missing something, but in my experience, (1) it can be informative to have the TZ information, regardless of the ability to compensate for time zone differences; (2) too many programmers either don't know how to correct for TZ correct -- especially with DST -- or they don't even try due to ignorance or laziness. Many of the problems I've had (with client databases) have been resolved by identifying code that forgot how to do things like this.

I recognize sqlite's `DATETIME` is also without TZ, but that doesn't make it the best way to go.

I suggest a way forward:

- add support `TIMESTAMP WITHOUT TIME ZONE` and `TIMESTAMP WITH TIME ZONE`
- `TIMESTAMP` is just an alias to "without"

**Comment by Mytherin** [comment]
There is no reason besides we haven't gotten to it yet :) I think following PostgreSQL's implementation for timestamps with timezones is indeed a good idea. I have no objections to it.

**Comment by r2evans** [comment]
I'm all good for postgres, but my recommendation was based on the 2011 ANSI SQL "draft" (I don't have the official copy, just what's available for free download).

**Comment by Mytherin** [comment]
We don't have a direct parallel, but we mostly follow either what SQLite or what Postgres does. We tend to go with Postgres when it comes to features, and SQLite when it comes to leniency. Postgres is easiest for us to follow because we are using their parser, after all :)

I have taken a look at it and I think what Postgres does is very close to what you describe, and since Postgres tends to follow the SQL standard, I think it makes sense to follow them here.

**Comment by hawkfish** [comment]
I have grave concerns about using PG or the standard for TZ support. The last time I tried to use TZ support in PG it made no sense. The qualification kept disappearing and reappearing - and as far as I could tell this was expected behaviour. it made it impossible to add it to Tableau in a comprehensible manner.

**Comment by r2evans** [comment]
@hawkfish, interesting! While my use of postgres is not daily, I do use it regularly enough and haven't seen any of that behavior. Can you provide a small reprex that always or at least often produces that erroneous behavior? (I'm not trying to submit a bug report to postgres -- though that might be good -- I'm trying do route out your concerns to see if it is something that is avoidable or something that can otherwise be mitigated.)

**Comment by hawkfish** [comment]
Sadly I can't - it was several years ago. I don't have it installed on my laptop, but IIRC you start casting timestamp columns and looking at the types.

**Comment by r2evans** [comment]
Using postgres:11, I can do this:

```
psql (11.5 (Debian 11.5-3.pgdg90+1))
Type "help" for help.

postgres=# select current_timestamp;
       current_timestamp
-------------------------------
 2020-04-16 23:54:18.031456+00
(1 row)
```

and have been comfortable with that output for a while. (`current_timestamp` returns `timestamp with time zone` according to https://www.postgresql.org/docs/11/functions-datetime.html, table 9.30.)

I've not run into a situation where the `+00` varies in format or accuracy (only when the importing process did it incorrectly). (I have not tested with non-hour-aligned time zones, but [allegedly](https://www.postgresql.org/docs/11/datetime-input-rules.html) it will find them by their olson names or other unambiguous zone name, so the 2-digit hour on the output is likely not a limiting factor.)

Granted, I believe that PG always stores in UTC, so I do not expect to see something other than `+00` from queries. The important component was that the inserting application inserted what it though the appropriate time zone is (within pg's [parsing expectations](https://www.postgresql.org/docs/11/datetime-input-rules.html)).

It does have `at time zone`, so that works as well.

```
postgres=# select current_timestamp at time zone 'Canada/Newfoundland';
          timezone
----------------------------
 2020-04-16 21:40:04.973951
(1 row)

postgres=# select current_timestamp ; -- roughly a few seconds later, showing +30min offset from hourly
       current_timestamp
-------------------------------
 2020-04-17 00:10:10.006878+00
(1 row)
```

**Comment by hawkfish** [comment]
What I meant by the admittedly rather vague "disappearing and reappearing" was that a casting pipeline would alternately remove and add the TZ qualification, which made it pretty much useless for automated query generation where the generator might wrap calculations in casts for safety. This was v8, though, and it may have been a long fixed bug.

**Comment by hawkfish** [comment]
I think the big question with TZ support is: "What sort of analytic tasks are TZ queries supposed to enable?" For the most part, TZ support is a presentation layer issue, but knowing what the wall time was in the locale the record came from can be important (e.g., "Did the customer buy this product in the morning?") In that sense a TZ specification is actually a _calendar_ specification and the analytic queries can be phrased in terms of that calendar and its associated temporal bins and hierarchies.  (By calendar here I mean [a binning system for time](https://tc19.tableau.com/learn/sessions/time-pieces-temporal-analytics-jigsaw).)

**Comment by r2evans** [comment]
I think most of my anecdotes on why I feel I "need" TZ in a field are based on my mistakes and/or those of other programmers. Many "data-gathering sessions" I work with occur in various parts of the world, and for redundancy the feed processing can be done at various locations (in differing timezones). In a perfect world, all programmers would use proven libraries and always insert the correct TZ, but typically something somewhere uses local time, and the logs or data or whatever are now difficult to gather and correlate.

I certainly get the point (from you, from krlmlr, and perhaps Mytherin) that many feel that the perceived need for TZ in the database is borne from bad programming. A different way to look at it is to enforce a "proven library" to do the conversion, one that is common to all programmers: the database.

**Comment by hawkfish** [comment]
I don't think that there is _no_ need for it, but that as you say it is often just a data cleaning/import problem, and once the data is imported correctly, there are no remaining analytic tasks that require the original time zone. 

Still, I think there are analytic tasks that could use time zones, and the ones that come to mind are row level tasks (like record-level time of day queries) and global tasks (like sales reporting when a company is in a particular time zone).  So if we add TZ support, we should have these kinds of tasks in mind, both for performance and user comprehensibility.

**Comment by hawkfish** [comment]
Not a response, but another analytic use case I ran into recently is energy production and consumption.

**Comment by slotrans** [comment]
(sorry this is long, proper timezone handling is extremely important to me)

### Postgres
Postgres' timestamp types are very unfortunately named. That may be the fault of the standard, I'm not sure.

A helpful way to think of them is:
`TIMESTAMP`: local timestamp in an unknown/unspecified time zone
`TIMESTAMPTZ`: unambiguous/absolute timestamp

The problem with a plain `timestamp` like '2021-11-14 18:58:37' is that you don't actually know when that is, because I didn't give you enough information. If I tell you "in America/Denver" _then_ you have enough information, and are able to compare it to any other unambiguous timestamp. The problem with _that_ though is that the time zone was supplied through a side channel (I told it to you, wrote it on a napkin, etc), and isn't present in the data.

`timestamptz` fixes that by forcing us to supply enough information to produce an unambiguous instant. Note however that the time zone we supply _is not remembered_. When we ask Postgres for a string rendering of a `timestamptz`, it is shown to us in the current session timezone.

When I first started working with Postgres, I found these very confusing, and elected to use plain `timestamp` because I felt like `timestamptz` involved extra complication I didn't need. I was *completely* wrong. Systems built around plain `timestamp` are _missing_ critical information.

quick, possibly-helpful example:
```
postgres=# select current_timestamp ;
       current_timestamp
-------------------------------
 2021-11-14 19:05:47.436484-07

postgres=# select extract('epoch' from '2021-11-14 19:05:47.436484-07'::timestamptz) ;
     date_part
-------------------
 1636941947.436484

postgres=# select extract('epoch' from '2021-11-15 02:05:47.436484+00'::timestamptz) ;
     date_part
-------------------
 1636941947.436484

postgres=# select '2021-11-14 19:05:47.436484-07'::timestamptz = '2021-11-15 02:05:47.436484+00'::timestamptz ;
 ?column?
----------
 t
```


### Java
Java 8's date/time classes can make for a helpful comparison, as they are modeled extremely rigorously.

java.time.Instant holds the number of nanoseconds since the standard epoch.

java.time.LocalDateTime represents "a date-time without a time-zone". Converting a LocalDateTime to or from an Instant requires supplying a time zone, because of its inherent ambiguity.

java.time.OffsetDateTime represents "a date-time with an offset from UTC". OffsetDateTime can be converted to an Instant _without_ supplying a time zone, because it is unambiguous. (Converting the other way does require supplying a time zone, since that determines the offset.)


### Why is `timestamptz` necessary for analytics?
Time is a human concept, and humans generally care about *their local time*.

As software engineers, we're used to thinking like machines, and UTC is made for machines so it feels natural to us. But business users and analysts who don't themselves _live_ in UTC don't think in UTC and asking them to do so is silly. Where I live, for 6-7 hours each day it is a different calendar day here than it is in UTC, so any calendar-centric computation done with UTC timestamps will be egregiously incorrect.

So the common advice of "just use UTC" flat-out doesn't work in an analytical environment. If I were to try to use DuckDB for serious work, I would have to defy the manual and store only *localized* timestamps, rather than UTC. That would be a major pain for me, making sure everything was properly converted before ingesting, but it would be vitally necessary for the sanity of my users.


### Final thoughts
I would suggest DuckDB copy Postgres here. Helpfully, Redshift has already done that, and Snowflake works essentially the same as well (if you ignore `TIMESTAMP_LTZ` which offers a third behavior).

I believe Postgres leans on the [ICU](https://icu.unicode.org/) library for time zone handling... not sure if that's a dependency DuckDB wants to take on.

**Comment by hawkfish** [comment]
Thanks for the input @slotrans - this is a topic I've been noodling on for a while (see the link to my talk above), so here are some thoughts...

The important point that is very relevant this week (and maybe why you followed up!) is that "local timestamp" is not well defined. If you live where I do (Pacific Northwest) then last weekend was the switch back from daylight savings time. This means that there are _two_ instants that correspond to my local string representation `2021-11-14 02:30:00`. Next March, there will be a one hour gap. Neither of these is correct for temporal analytics.

The only way you can use regular timestamps without losing data or having holes is to assume that they are in a time zone without DST. There are a few of those in the US (Hawaii and Arizona), but if you have to make that assumption you might as well make it UTC. From a system design perspective, this means that all timestamps are really in UTC and should be thought of as instants.

One problem you identified is that when users insert timestamps, they implicitly use a calendar/time zone to specify them. This suggests that the correct way to handle inserts is to use the client's calendar/time zone to interpret the string `2021-11-14 02:30:00` as an instant. IIRC this is exactly what PG does, and we should consider it.

The other problem you mention is that the calendar binning functions (`DATE_PART` and friends) are all currently using the UTC calendar. What is really needed there is to make these functions TZ-aware by allowing an implicit or even explicit calendar specification. Again, I'm pretty sure this is what PG does, but it also requires a fair amount more complex code.

The argument for ICU is that time zones are a really hairy problem that no one should have to sort out. My favourite example is that in Jordan, the king decides every year when DST starts and ends - and sometimes he forgets!  Even the US has had ~5 different sets of rules over the past century, one in this century alone. So converting instants to and from local time requires a pile of code that only a time nerd could love. And that is who supports the ICU time module...

As for` TIMESTAMP WITH TIMEZONE`, the main use case for that is to add metadata on _where_ the time was recorded. For physical locations on the planet's surface (e.g., the output of a solar farm), this is redundant, but people are mobile, and if the time of day for individual instants is important to the analysis binning, you need to tag the timestamp/instance with the UTC offset. But if the analysis binning is uniform for the data, then tagging the data with a time zone is unnecessary.

**Comment by hawkfish** [comment]
The consensus is that we should do this via an extension, which is what we already do for collation.

**Comment by slotrans** [comment]
> As for `TIMESTAMP WITH TIMEZONE`, the main use case for that is to add metadata on where the time was recorded.

It's important to note that Postgres' `TIMESTAMP WITH TIME ZONE` type does not actually do this, nor does Redshift's. Snowflake's _does_, docs here: https://docs.snowflake.com/en/sql-reference/data-types-datetime.html#timestamp-ltz-timestamp-ntz-timestamp-tz Their 3rd type 'TIMESTAMP WITH LOCAL TIME ZONE` behaves like the above Postgres type. It seems Oracle now also has 3 types like Snowflake does, with the same name<->behavior mappings: https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlqr/Data-Types.html (My guess would be that Snowflake copied Oracle here.)

To elaborate, if I create a Postgres `timestamptz` column and input the value `2021-11-15 14:41:23.396889-07`, what is actually stored is the integer 1637012483396889 (or some equivalent, they may use an unconventional epoch internally). Neither my IANA zone id of `America/Denver` nor my (current) UTC offset of `-07:00` are stored. The internal representation is *always* UTC-based. Zones/offsets are only used to parse from, or serialize to, a string representation.

Given the choice between the two Postgres/Redshift types, I always choose `timestamp with time zone`. Given the choice between the 3 Snowflake/Oracle types, I never use the timezone-naive type (`timestamp_ntz`), but it's a tough choice between the other two. I find the behavior of "remembering" the stored timezone sometimes strange, as it makes the display potentially inconsistent within a single column, and the behavior of functions like `date_trunc` becomes non-intuitive. The advantage is that it does store strictly _more_ information, and in a more structured way than e.g. recording the zone/offset in a separate column.

--

Unrelated to the above, I also happened across another great explanation of the relevant issues in the Google Abseil docs https://abseil.io/docs/cpp/guides/time

**Comment by hawkfish** [comment]
Thanks for the link to Abseil. They have a richer type system (with implied truncation), but the basic concepts are the same except what they call a civil time is what I call a calendar binning (which is a bit more general and allows for things like Japanese imperial epochs.)

My read of Snowflake is that:
* `TIMESTAMP_NTZ` behaves like DuckDB's `TIMESTAMP` in that the implicit time zone/calendar/civil time is UTC (they may say there is no TZ but without a calendar the binning operations are not defined)
* `TIMESTAMP_LTZ` behaves like Postgres' `TIMESTAMP WITH TIME ZONE` in that it stores UTC but uses the connection's implied time zone/calendar/civil time setting for binning operations.
* `TIMESTAMP_TZ` attaches the location/culture metadata to the value, allowing that calendar to be used for binning operations on individual values. As I argued above, this has very limited utility (especially when two values are concerned as in `DATEDIFF`) but it is still a use case.

I think we could add support for the last two via an ICU extension. The first would be easier because no new storage layout is needed.

**Comment by akdor1154** [comment]
>     * `TIMESTAMP_TZ` attaches the location/culture metadata to the value, allowing that calendar to be used for binning operations on individual values. As I argued above, this has very limited utility (especially when two values are concerned as in `DATEDIFF`) but it is still a use case. 

Nearly - snowflake stores the utc offset  (+1100), not the geographic tz (aus/melbourne). This has implications for e.g. adding an interval that crosses a dst bound. I guess it makes the implementation simpler though.

**Comment by hawkfish** [comment]
The real problem with "local time" is that it can be ambiguous. What is the instant corresponding to `2021-11-14 02:30:00 America/Los_Angeles`? There are two of them, separated by an hour.

**Comment by r2evans** [comment]
I consider myself a little more-versed than the average programmer wrt the use of timezones, but I was surprised to realize that I have been missing the implication of storing all in UTC and then trying to truncate (floor/ceiling) by day. I primarily use SQL Server (not my choice) and use `DATETIMEOFFSET`, which stores the offset in the data *unambiguously*.

Good discussion.

**Comment by hawkfish** [comment]
@r2evans The problem is not usually _storing_ in UTC but rather in not specifying what calendar/time zone/binning should be used for date truncation. By storing the offset with the value, you provide that calendar information for each value, which works for single date functions (like truncation), but can run into problems with two date functions (like subtraction).

**Comment by r2evans** [comment]
That was my not-well-stated point, sorry for the ambiguity. What I should have said was that storing in UTC without the offset resolves one portion of the problem but not the other. If postgres does not store the offset, then truncation of a timestamp into a date is likely to have problems. I know one goal of duckdb is to mimic postgres dialects to a strong degree, this is one area where that behavior leaves something to be desired.

**Comment by hawkfish** [comment]
AFAICT, what PG sort of does is use the `TimeZone` setting to determine the calendar to use. If you have the data stored in UTC, would that solve your problem?  Of course, PG is not very helpful about making sure that times get inserted that way...

I'm really trying to understand what is most useful here, and its hard because casual users often don't understand time. But I also don't want to help them shoot themselves in the foot!

**Comment by r2evans** [comment]
Unfortunately, I believe that any method that does not store the offset will be broken in at least one use-case

```sql
select date_trunc('day',timestamptz '2021-11-18 22:31:35.842861 -0400') as day
#        day
# 2021-11-19
```

And while I'm not a proponent of everything-mssql, its analog to this is more intuitive:

```
select cast('2021-11-18 22:31:35.842861 -04:00' as Date) as day
#        day
# 2021-11-18
```

Granted, that may be a "complaint" with the assumptions within PG.

I believe that it makes sense for duckdb to be as compatible to a single dialect as possible, including replicating quirks like this. While I disagree with the query results, to say that it's mostly postgres-compatible and _not_ replicate this behavior could be counter-intuitive and frustrating.

With that, though, since it has been said that this would be implemented as an extension. Is it possible to load the extension with a particular option? That is, store the offset; when something like `date_trunc` is used, default to the postgres behavior; if some "pragma" or global option is set, though, one could enact alternate behavior (such as demonstrated in the t-sql variant above).

**Comment by hawkfish** [comment]
I have [written up a spec](https://github.com/duckdb/duckdb/discussions/2647) for Time Zone support that should follow PG pretty closely, with the caveat that it will require an extension.  The use case for embedding the origin of the value is the last section and still under consideration.

Under the proposal, the result in the first example you give will depend on the `TimeZone` setting. The string specifies an instant that is explicitly cast to a `TIMESTAMPTZ`; the `DATE_TRUNC` function (from an extension like `icu`) that binds to `TIMESTAMPTZ` will be invoked instead of the built in one (which can't bind to it) and the truncation will happen in that time zone. If the extension is not loaded, a "function not found" error will be generated.

**Comment by slotrans** [comment]
> select date_trunc('day',timestamptz '2021-11-18 22:31:35.842861 -0400') as day
>         day
>  2021-11-19

In Postgres, the behavior of `date_trunc` and the `date` cast are sensitive to the session timezone:

```
/* PG 12.8 */

postgres=# set timezone to 'America/Denver' ; --currently UTC-7
SET
postgres=# select date_trunc('day', val), val::date from (select '2021-11-18 22:31:35.842861 -0400'::timestamptz as val) x ;
       date_trunc       |    val     
------------------------+------------
 2021-11-18 00:00:00-07 | 2021-11-18

postgres=# set timezone to 'Canada/Atlantic' ; --currently UTC-4
SET
postgres=# select date_trunc('day', val), val::date from (select '2021-11-18 22:31:35.842861 -0400'::timestamptz as val) x ;
       date_trunc       |    val     
------------------------+------------
 2021-11-18 00:00:00-04 | 2021-11-18

postgres=# set timezone to 'UTC' ;
SET
postgres=# select date_trunc('day', val), val::date from (select '2021-11-18 22:31:35.842861 -0400'::timestamptz as val) x ;
       date_trunc       |    val     
------------------------+------------
 2021-11-19 00:00:00+00 | 2021-11-19

postgres=# set timezone to 'Europe/Athens' ; --currently UTC+2
SET
postgres=# select date_trunc('day', val), val::date from (select '2021-11-18 22:31:35.842861 -0400'::timestamptz as val) x ;
       date_trunc       |    val     
------------------------+------------
 2021-11-19 00:00:00+02 | 2021-11-19
```
This is because Postgres _always_ interprets `timestamptz` values in the session timezone. The values `2021-11-18 22:31:35.842861 -04` and `2021-11-19 02:31:35.842861 -00` are of course the same instant, but which _calendar day_ they occurred on is a matter of local perspective. In my view the output of `date` casts here is totally correct (since calendar dates are inherently local/naive), but the `date_trunc` output is slightly questionable, as each of the above timestamps represents a different instant.

This behavior is now basically intuitive to me, but I find that it drives analysts crazy.

As folks have pointed out, without a stored offset or TZ, it's impossible to get the "right" day from the perspective of the _event_ represented by the timestamp. The types that do that internally, like Snowflake's `TIMESTAMP_TZ`, can also produce odd behavior. For example, you could filter down to a 24-hour range, group by `date_trunc('hour', ...)` and see more than 24 values (I think? I don't have access to a Snowflake instance just now). You can get a consistent perspective by performing an explicit timezone conversion. In essence, such types prioritize localization over consistency. I tend to prefer consistency, so I generally favor using a type like Postgres' together with a separate column storing the event timezone. YMMV.

**Comment by hawkfish** [comment]
I am a bit puzzled by the truncation to `DATE` (instead of to `DATETZ`) because I would interpret that as removing the TTZ specification from the type and truncating the resulting instant (TTZ => T => D). It appears that PG is doing a TTZ => DTZ => D sequence for that cast. Which is good to know, I suppose, but another example of how this stuff is somewhat arbitrary.

I think you would have to see 25 values for "fall back" dates like `2021-11-14` in `America/Los_Angeles` because you would still be getting instants and there would be 25 of them.

**Comment by hawkfish** [comment]
> In Postgres, the behavior of `date_trunc` and the `date` cast are sensitive to the session timezone:

I think the confusion is that the `WITH TIME ZONE` types are badly named. What they actually mean is not "there is a time zone attached to this instant" but "bin this instant using the current time zone setting"...

**Comment by slotrans** [comment]
> I think the confusion is that the WITH TIME ZONE types are badly named. What they actually mean is not "there is a time zone attached to this instant" but "bin this instant using the current time zone setting"...

Correct, and agreed the names are very confusing.

**Comment by hawkfish** [comment]
As the trail of commits above indicates, I have been implementing time zones using the ICU extension. Functionality that is/has being added:
* A `TimeZone` setting that is validated, queryable and used for binning operations;
* Adding the Postgres `WITH TIME ZONE` types to the base DuckDB code. These types store instants/counts just like the non-TZ types, but they have no binning functions defined (only ordering and numerical arithmetic);
* Implementing the various binning functions for the `TIMESTAMPTZ` type (`DATEPART` and `DATETRUNC` so far; `DATEADD`, `DATESUB` and `AGE` are coming) that use the binning defined by the `TimeZone` setting.

Possible future work includes: 
* Adding binning for the other TZ types;
* `DATEPART(LIST<VARCHAR>, ...) => STRUCT<part:BIGINT,...>` to amortise the expense of computing parts;
* Time zone arguments to the binning functions (to enable row-specific binning);
* Non-Gregorian calendars (e.g., `SET CALENDAR='Japanese'`);
* Conversions (e.g., `to_char`, `to_timestamp`) (although those would require more ICU data than we currently embed.)

My question is: What are the remaining use cases that are important here? I have focussed on binning because that is what is needed for analytics, and it can also be used for presentation/formatting by the client. My read of the original issue is that it was a request for storing the TZ at the row level, but since the PG/SQL types don't actually do that, and since that problem can be solved in DuckDB by using a `STRUCT` type, what else is desired here?

**Comment by slotrans** [comment]
first, thank you for working on this!

The only other big item that comes to mind is some kind of operator or function for performing time zone conversions independent of the session time zone. In Postgres, this is the `at time zone` operator. In Snowflake, it's the `convert_timezone()` function.

I do think `to_char` support is essential, just in the very literal sense that I'm going to write `to_char` expressions against this type and expect them to work, and be very confused if they don't. In particular, `to_char(<some timestamptz value>, 'HH24')` is something I use all the time.

**Comment by hawkfish** [comment]
You are welcome - I'm a bit of a time nut, so this was fun.

> The only other big item that comes to mind is some kind of operator or function for performing time zone conversions independent of the session time zone. In Postgres, this is the `at time zone` operator. In Snowflake, it's the `convert_timezone()` function.

I have to say I'm not sure what these functions/operators actually do - which makes it hard to implement them. Timestamps without time zones in all these systems are instants, so saying they are "at a time zone" doesn't really mean anything. What it sounds like they are doing is "convert the instant to date parts using UTC and then create a new instant from those parts using the given TZ"? This is not a well-defined operation (consider a timestamp that represents a non-existent or duplicated DST time) but I suppose you could implement an ICU function to do that e.g., `convert_timezone(TIMESTAMP, VARCHAR) => TIMESTAMPTZ`?

>I do think `to_char` support is essential, just in the very literal sense that I'm going to write to_char expressions against this type and expect them to work, and be very confused if they don't. In particular, `to_char(<some timestamptz value>, 'HH24')` is something I use all the time.

Does `hour(TIMESTAMPTZ)::VARCHAR` not do what you want?

**Comment by slotrans** [comment]
> I have to say I'm not sure what these functions/operators actually do

As usual, it's confusing :)
https://www.postgresql.org/docs/14/functions-datetime.html#FUNCTIONS-DATETIME-ZONECONVERT

> timestamp without time zone AT TIME ZONE zone → timestamp with time zone
> Converts given time stamp without time zone to time stamp with time zone, assuming the given value is in the named time zone.
> timestamp '2001-02-16 20:38:40' at time zone 'America/Denver' → 2001-02-17 03:38:40+00

This form basically says "here's a _naive_ timestamp, and I am going to supply the missing time zone information, so that it can become an _aware_ timestamp". I don't generally use this form.

Equivalent operation from Java: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZonedDateTime.html#of(java.time.LocalDateTime,java.time.ZoneId)

> timestamp with time zone AT TIME ZONE zone → timestamp without time zone
>Converts given time stamp with time zone to time stamp without time zone, as the time would appear in that zone.
> timestamp with time zone '2001-02-16 20:38:40-05' at time zone 'America/Denver' → 2001-02-16 18:38:40

This form says "take this _aware_ timestamp, render it in the supplied time zone, _and then make it naive_". This is useful in that it gives you a local view of a `timestamptz` that isn't tied to the session time zone. A particularly useful thing to do with that is to see _multiple_ such views in one query, for example
```
select foo at time zone 'America/Los_Angeles' as PACIFIC
     , foo at time zone 'America/Denver' as MOUNTAIN
     , foo at time zone 'America/Chicago' as CENTRAL
     , foo at time zone 'America/New_York' as EASTERN
     , foo at time zone 'UTC' as UTC
  from (select date_trunc('second', current_timestamp) as foo) x
;
       pacific       |      mountain       |       central       |       eastern       |         utc
---------------------+---------------------+---------------------+---------------------+---------------------
 2021-12-04 20:23:50 | 2021-12-04 21:23:50 | 2021-12-04 22:23:50 | 2021-12-04 23:23:50 | 2021-12-05 04:23:50
```
Equivalent operation from Java: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalDateTime.html#ofInstant(java.time.Instant,java.time.ZoneId)

Snowflake's `convert_timezone()` is similar but does more.
https://docs.snowflake.com/en/sql-reference/functions/convert_timezone.html

The 3-argument version shifts a naive timestamp from one time zone to another, which the Postgres operator can't do.

I can't explain the 2-argument version very well without being able to test it, which I can't currently do.

> Does hour(TIMESTAMPTZ)::VARCHAR not do what you want?

`hour()` does work, though it doesn't giving leading zeros. I'm sure that can be accomplished, though.
I tend to reach for `to_char()` partly because Postgres doesn't have `hour()` etc and partly because it's very compactly expressive. Like if I wanted to go from "wall clock hours" to "wall clock hours for each day of the week" I just change `HH24` to `DAY HH24`.
I guess `to_char(foo, 'DAY HH24')` vs `printf('%s %02d', dayofweek(foo), hour(foo))` is six-of-one/half-a-dozen-of-the-other, I've just had the `to_char` format strings memorized for many years. Based on that, I'd walk back my earlier statement that it's "essential".

**Comment by hawkfish** [comment]
I think one of the things that is confusing here is your use of the words "naive timestamp" and "render". What you call a naive timestamp is actually an instant (a fixed number of microseconds from 1970-01-01 00:00:00 UTC), and what you call rendering is actually binning an instant using a particular calendar (Gregorian/time zone) and format string (ISO-8601 in this case). The example you give showing a single instant in multiple time zones is thus using multiple time zones to bin the value of an instant from a row. That is an interesting application, and my expectation on how to implement it eventually would be to have a `to_char` variant that takes a third time zone argument. I should mention that right now, the way DuckDB is formatting `TIMESTAMPTZ` is with a training "+00" so you can tell it apart from regular `TIMESTAMP` values.

For the zero padding, I had the rather horrible idea that you could create an `INTERVAL`, cast it to a `VARCHAR` and the extract the desired substring(!)

```sql
SELECT substr((interval (hour(ts)) hours)::varchar, 4, 2) FROM ...
```

The other problem I have seen mentioned in this discussion is a data cleaning problem. What has happened is that timestamp values have been inserted using a local time representation (either a formatted string or an offset count of µs) into a `TIMESTAMP` (i.e., instant) column and need to be converted to proper instants in order to apply multiple time zones operations (proper distances, etc.). One suggestion on how to deal with that problem now that we have time zone support is to create a second column containing the correct UTC offsets, cast the `TIMESTAMP` values to `VARCHAR`, concatenate the offset and then cast that to a new `TIMESTAMPTZ` column. Computing the offsets should be straightforward (check which range the value is in for that year) except for the one hour of DST overlap. For that you could leave the offset `NULL` temporarily and then use a single threaded (to preserve insertion order) windowing operation to find the first point where the instant goes backwards. With that marked, one can then write a second window calculation to fill down the correct offset.  Not pretty or fun, but at lest the data would be now be correct.

**Comment by slotrans** [comment]
"naive" and "aware" are standard terminology, AFAIK. A "naive" timestamp is local and does not represent an unambiguous instant. An "aware" timestamp has a time zone attached and is therefore absolute. The Python and Rust standard libraries, plus `pendulum`, `pandas`, and others, use these terms.

I've never seen/heard "bin" used as the verb here, but "render" is definitely a term of my own choosing. I use it because the _value_ remains the same, it is simply _shown_ (as text) in a particular time zone. It's analogous to the way that a scene can be rendered from different camera viewpoints, or HTML can be rendered to a text console or a bitmap display.

**Comment by hawkfish** [comment]
Ah, sorry, I had not seen that particular terminology (there are a lot of them out there). 

I use the term binning (admittedly my own coinage from analytics) to cover any way of taking UTC instants and mapping them into bins (years, hours, weeks, etc.). This includes calendars as well as time zones (e.g., the Japanese Imperial calendar has very strangely sized "era" bins and the Jewish calendar has 13 months in some years), so a larger term seems important (ICU attaches time zones to calendars, so it just calls them calendars). Once you have chosen a binning, you can then represent instants in some manner (usually a string, but also a `struct`). 

The thing I found strange about the rendering display in your example was that AFAICT the PG internal representation of the values is just an instant, so they must be converting them under the hood into "naive" values. This could be checked by taking a DST instant, using `AT TIME ZONE` to convert it and then casting it back to a regular timestamp to see if it round trips. I don't have PG installed right now, but I'd be interested in the answer.

I'm not trying to be excessively pedantic BTW, its just that in order to implement this stuff correctly, it has to be well defined. The reality is that in order to bin a time value using time zones and calendars, the existing libraries (like ICU) need UTC instants. Naive timestamps do not meet this criterion, so handling them correctly is rather fraught. Unfortunately they are quite common, and I want to make sure DuckDB can deal with them. "Dealing with them" really seems to mean "cleaning them on the fly", which as my DST example show is not simple and requires being able to infer the missing information from the physical layout of the data. Providing a means to clean the data correctly just once sounds like important functionality.

**Comment by hawkfish** [comment]
After some thought, I've decided I like that term "naive" - it is short and describes The Bad Thing. Thanks for bringing it to my attention! What it seems to mean internally is the inverse of the operation I described above: "convert the instant to date parts using a TZ and then create a new instant from those parts using UTC".

**Comment by hawkfish** [comment]
@r2evans I think we should be done with this now. A lot of things were discussed in this thread, but the original request was to support `TIMESTAMPTZ` and that should be available now, along with implementations of the *existing* binning functions in the ICU extension. If there is new functionality (e.g., `to_char`) we should create up new issues as the architectural work here should make it possible to implement smaller requests like that.

**Comment by r2evans** [comment]
This thread is a riveting lesson for non time-nuts/time-nerds. I think the direction is good, and I'm good with resolving this issue and, as needed, starting new issues for any helper functions. Thank you!
