### ISSUE TITLE
Internal error on GROUP BY ALL

### ISSUE THREAD

**Issue by bmschmidt** [duckdb/duckdb#5660]
### What happens?

Thanks again for this software.

I've noticed that a `GROUP BY ALL` with an UNLIST operation throws an unclear error ("InternalException: INTERNAL Error: Failed to bind column reference "x" [5.0] (bindings: [7.0])"), while manually passing the column names to group by produces the correct result.

Any subsequent queries throw the following error:
```
InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.
Original error: "INTERNAL Error: Failed to bind column reference "x" [5.0] (bindings: [7.0])"
```

### To Reproduce

Throws an error:

```python
import duckdb
con = duckdb.connect(":memory:")
con.execute("""CREATE TABLE foo AS SELECT 'a, b, c' AS "x", '1' AS y""")
con.execute("""SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY ALL""")
```

Works nicely:

```python
import duckdb
con = duckdb.connect(":memory:")
con.execute("""CREATE TABLE foo AS SELECT 'a, b, c' AS "x", '1' AS y""")
con.execute("""SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY x, y""")
```

### OS:

OS X, Apple M1 Pro

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Ben Schmidt

### Affiliation:

Nomic

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment]
0.6.1 CLI
```
D CREATE TABLE foo AS SELECT 'a, b, c' AS x, '1' AS y;
D
D SELECT y, UNLIST(string_split(x, ', ')) x, COUNT(*) FROM foo GROUP BY x,y;
┌─────────┬─────────┬──────────────┐
│    y    │    x    │ count_star() │
│ varchar │ varchar │    int64     │
├─────────┼─────────┼──────────────┤
│ 1       │ a       │            1 │
│ 1       │ b       │            1 │
│ 1       │ c       │            1 │
└─────────┴─────────┴──────────────┘
D SELECT y, UNLIST(string_split(x, ', ')) x, COUNT(*) FROM foo GROUP BY ALL;
Error: INTERNAL Error: Failed to bind column reference "x" [5.0] (bindings: [7.0])
```

**Comment by l1t1** [comment]
this is ok 
```
D CREATE TABLE foo AS SELECT 'a, b, c' AS x, '1' AS y;
D
D SELECT COUNT(*) FROM foo GROUP BY ALL;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│            1 │
└──────────────┘
```

**Comment by bmschmidt** [comment]
Interesting I assumed `GROUP BY ALL` should be supported because of its description [on the blog](https://duckdb.org/2022/05/04/friendlier-sql.html).

**Comment by hannes** [comment]
It should work, thanks for the issue report.

**Comment by hannes** [comment]
This also throws an internal error in our wasm shell, so clearly a bug.

**Comment by Tmonster** [comment]
Been having a lot of trouble with this bug and I've hit a wall. This is a summary of my findings so far.  I'm pretty sure the problem has something to do with the order of how you plan or bind unnest/aggregate/window functions. In plan_select_node.cpp operators are planned in the order of sample, where, aggregate, having, windows, qualify, unnest and 

if you plan unnest statements after the aggregate and window function you get the following. (This is current master functionality)

```
CREATE TABLE foo AS SELECT 'a, b, c' AS "x", '1' AS y;

-- SUCCEEDS 
D: SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY y, x;

-- FAILS with binding error
D: SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY ALL;
-- Error: INTERNAL Error: Failed to bind column reference "x" [5.0] (bindings: [7.0])

-- FAILS with the same binding error (aggregate over window) (https://github.com/duckdb/duckdb/issues/5703)
D: select unnest([5]) as r, sum(r) OVER ();   
-- Error: INTERNAL Error: Failed to bind column reference "x" [5.0] (bindings: [7.0])
```

If you plan unnest operators *after* aggregates and *before* window functions you get the following. This could fix https://github.com/duckdb/duckdb/issues/5703 but it doesn't pass all test cases. test_complex_macro.test has a failure.

```
CREATE TABLE foo AS SELECT 'a, b, c' AS "x", '1' AS y;

-- SUCCEEDS
D: select unnest([5]) as r, sum(r) OVER ();

-- SUCCEEDS
D: SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY y, x;

-- FAILS with binding error
D: SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY ALL;
-- Error: INTERNAL Error: Failed to bind column reference "x" [5.0] (bindings: [7.0])
```

If you plan unnest statements before aggregate functions and window functions (so unnest ➝ aggregate ➝ window) you get the following

```
CREATE TABLE foo AS SELECT 'a, b, c' AS "x", '1' AS y;

-- SUCCEEDS
D: select unnest([5]) as r, sum(r) OVER ();


-- FAILS with binding error
D: SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY y, x;
Error: INTERNAL Error: Failed to bind column reference "x" [1.1] (bindings: [7.0 7.1])

-- Succeeds
D: SELECT y, UNLIST(string_split("x", ', ')) x, COUNT(*) FROM foo GROUP BY ALL;
```

I think the order is rather delicate and changing it will results in more problems rather than solutions. I've spent some hours trying to figure out what's going on here but I keep running into dead ends. @Mytherin do you have any ideas off the top of your head?
