### ISSUE TITLE
Default entries are being created unexpectedly in `pg_catalog`

### ISSUE THREAD

**Issue by bleskes** [duckdb/duckdb#5668]
### What happens?

When running the statement `select * from t1,t2 where t1.i = t2.a;`, where table `t1` doesn't exist, I noticed that the catalog version is getting bumped (with some side effects in our extension code). Researching, it seems that the look up for `t1` creates the default entry for the `pg_catalog`.

Here are some screenshots of the relevant stack trace and state:
![image](https://user-images.githubusercontent.com/1006375/207059030-33aad83a-0e1d-420e-9ddc-8a120d3219d5.png)

![image](https://user-images.githubusercontent.com/1006375/207059112-68f92852-340e-496e-85b2-c1090ba7c776.png)

### To Reproduce

see above. Hopefully the stack traces are enough. Will work on an isolated repro if needed.

### OS:

MacOS

### DuckDB Version:

6.0.x

### DuckDB Client:

cpp embeded

### Full Name:

Boaz Leskes

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by omo** [comment]
Looking at this. I guess this can be a WAI.

These default entries are populated lazily and because pg_catalog schema is in the default search path, it is accessed and populated while a table name is being searched and the name does not exist in more prominent places (like "main"). 

Making pg_catalog lazy isn't very helpful because it has to be created anyway in many cases like this,
so it might be reasonable to populate it eagerly if it matters. But I'm not sure how it does matter.
Could you elaborate on the problem a bit more so that we can make a reasonable fix?

Thanks!
