### ISSUE TITLE
[NodeJS] Segfault when passing the file_search_path config

### ISSUE THREAD

**Issue by armanm** [duckdb/duckdb#5723]
### What happens?

It looks like the constructor for the `Database` class from the NodeJS client is unable to handle the `file_search_path` config when the code attempts to connect to a DB.

### expected behaviour

to receive an instance of the Database class

### actual behaviour

a segfault error and the whole of node process will crash

```
[1]    94447 segmentation fault  node
```

### To Reproduce

```js
new duckdb.Database(":memory:", {"file_search_path": "/Users/arman/Downloads"})
```

### OS:

Mac OS 13.0.1

### DuckDB Version:

0.6.1

### DuckDB Client:

NodeJS

### Full Name:

Arman Mirkazemi

### Affiliation:

Envato

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

I had a quick look at this and it seems to be caused by the node client crashing on unsupported configuration parameters in general. The `file_search_path` is not a valid global configuration parameter but has to be set at the connection level, e.g.:

```js
      db = new duckdb.Database(":memory:", () => {
        db.prepare("SET file_search_path='/Users/arman/Downloads'").run(done);
      });
```

This should definitely be fixed to not crash, but it will throw an error instead after being fixed.
