### ISSUE TITLE
read_csv_auto() reads a varchar column (starting with '0') as integer 

### ISSUE THREAD

**Issue by ericemc3** [duckdb/duckdb#5782]
### What happens?

My csv file contains a column with zip codes, some starting with a '0':
![image](https://user-images.githubusercontent.com/17407796/209432957-54e7ea06-a05e-4268-9a4f-528f9db2b33e.png)

read_csv_auto() convert that column as integer, i exepectd a varchar, the leading '0' is lost
![image](https://user-images.githubusercontent.com/17407796/209432994-63cbc91c-561d-412c-9f53-1fb90fc04d59.png)

### To Reproduce

SELECT * FROM read_csv_auto('test.csv');

[test.csv](https://github.com/duckdb/duckdb/files/10298425/test.csv)

### OS:

x64

### DuckDB Version:

0.6

### DuckDB Client:

DBeaver

### Full Name:

eric mauviere

### Affiliation:

icem7

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
You likely want to use `read_csv` and specify the columns and their types explicitly
https://duckdb.org/docs/data/csv

**Comment by ericemc3** [comment]
> You likely want to use `read_csv` and specify the columns and their types explicitly https://duckdb.org/docs/data/csv

Well, i know i could, but i love the simplicity of read_csv_auto(), which is also used as a default in many third parties tools (Observable, Tad...)

**Comment by Tishj** [comment]
Ah I see, but this requires context, there are definitely situations where this is the behavior you would want
and besides that you can fix it up yourself with something like `format` (if the length of the CODGEO column is a constant)

**Comment by ericemc3** [comment]
Thanks once again for your reactivity! I understand, but i don't know other contexts where it would be appropriate for a 09001 code value to be altered into a number such as 9001. 

With R for instance, readr::read_delim() reads properly such a file, without any particular specification.

**Comment by mskyttner** [comment]
I am too fond of the R package `readr` and its nice well-chosen defaults for parsing CSV and similar formats - especially its convenient type guessing for column types. 

While there are parameters such as ALL_VARCHAR and SAMPLE_SIZE available for use with duckdb's `read_csv_auto` (where the first one disables the type guessing entirely for all columns), it seems those options wouldn't help much in a use case such as this one, where one would like for strings starting with leading zeroes by default to be guessed to be varchar rather than numerical.

Another nice thing that `readr` allows for is to specify column types for a subset of the columns and a default for all the rest, making it less onerous in comparison with having to specify all the types for all the columns. Also, when required, the column type specification can be made in a compact way. For [example](https://readr.tidyverse.org/reference/read_delim.html): `read_csv('test.csv', col_types = 'c??')` reads the first column as characters and guesses the type for the next two columns.

**Comment by ericemc3** [comment]
Thank you very much @Mytherin!

**Comment by aborruso** [comment]
Hi @Mytherin what should i do to use it? Do I download the source and compile it?

Thank you

**Comment by Mause** [comment]
> Hi @Mytherin what should i do to use it? Do I download the source and compile it?
> 
> Thank you

You can download dev builds by following the links on this page: https://duckdb.org/docs/installation/

**Comment by aborruso** [comment]
> You can download dev builds by following the links on this page: https://duckdb.org/docs/installation/

Wow it works greatly. Thank you @Mause 

And thank you @Mytherin for your code job!
