### ISSUE TITLE
Node: `duckdb@next` does not appear to import on M1 / Node 17.2

### ISSUE THREAD

**Issue by hamilton** [duckdb/duckdb#5787]
### What happens?

On node, if I attempt to install via `npm install duckdb@next`, I'm not able to import the library. 
- I'm on an M1 / Monterey 12.6
- I'm using Node 17.2

### To Reproduce

1. run `npm install duckdb@next` (checked against `^0.6.2-dev895.0`)
2. attempt to import via `import duckdb from "duckdb"`
3. see the following error

```
node:internal/modules/cjs/loader:1179
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/path/to/duckdb/lib/binding/duckdb.node, 0x0001): symbol not found in flat namespace (__ZTIN6duckdb9ExceptionE)
```

### OS:

Mac 12.6 M1

### DuckDB Version:

0.6.2-dev895.0

### DuckDB Client:

Node

### Full Name:

Hamilton Ulmer

### Affiliation:

Rill Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
I reproduce against duckdb@0.6.2-dev895.0, but since there have been various changes to the node.js CI that led to fix various problems, and this appears to have been solved in that occasion.

Any recent npm version (e.g. both 0.7.1 and 0.7.2-dev333.0) seems to work as expected, so I think this can be closed.

Thanks for your report!
