### ISSUE TITLE
Race-conditions on `duckdb::BufferManager`

### ISSUE THREAD

**Issue by naazgull** [duckdb/duckdb#5818]
### What happens?

The logic around `duckdb::BufferManager::current_limit` member variable in `EvictBlocks` function has some issues w.r.t access serialization. Some of the issues relate to lack of ownership transfer of the reserved or freed buffer space to the thread that was able to reserve or free. This may lead to all threads being able to observe the temporary state that should be local to each thread.

### To Reproduce

Scenario 1
----------

Both _Thread1_  and _Thread2_ have entered the `duckdb::BufferManager::EvictBlocks` function with state `current_memory = 100, extra_memory = 20, memory_limit = 120` and the following is executed in sequence by each thread:

1. _Thread1_ executes `current_memory += extra_memory` leaving `current_memory = 120`.
2. _Thread2_ executes `current_memory += extra_memory` leaving `current_memory = 140`.
3. _Thread1_ executes `while (current_memory > memory_limit)` and enters the loop since `current_memory = 140 && memory_limit = 120`.
4. _Thread2_ executes `while (current_memory > memory_limit)` and enters the loop since `current_memory = 140 && memory_limit = 120`.
5. _Thread1_ executes `if (!queue->q.try_dequeue(node))` for which the condition evaluates to true.
6. _Thread2_ executes `if (!queue->q.try_dequeue(node))` for which the condition evaluates to true.
7. _Thread1_ executes `current_memory -= extra_memory`, leaving `current_memory = 120` and returning `false` (leading to an `OutOfMemoryException`).
8. _Thread2_ executes `current_memory -= extra_memory`, leaving `current_memory = 100` and returning `false` (leading to an `OutOfMemoryException`).

The expected behavior is for one of the threads to be able to allocate memory in the buffer.

Scenario 2
----------

Both _Thread1_  and _Thread2_ have entered the `duckdb::BufferManager::EvictBlocks` function with state `current_memory = 120, extra_memory = 20, memory_limit = 120` and the following is executed in sequence by each thread:

1. _Thread1_ executes `current_memory += extra_memory` leaving `current_memory = 140`.
2. _Thread1_ executes `while (current_memory > memory_limit)` and enters the loop since `current_memory = 140 && memory_limit = 120`.
3. _Thread1_ executes `if (!queue->q.try_dequeue(node))` and succeeds in poping a node.
4. _Thread1_ executes up until `*buffer = handle->UnloadAndTakeBlock()` and enters `duckdb::BlockHandle::UnloadAndTakeBlock`.
5. _Thread2_ executes `current_memory += extra_memory` leaving `current_memory = 160`.
6. _Thread2_ executes `while (current_memory > memory_limit)` and enters the loop since `current_memory = 160 && memory_limit = 120`.
7. _Thread1_ executes `buffer_manager.current_memory -= memory_usage` with `memory_usage = 40`, leaving `current_memory = 120`.
8. _Thread2_ executes `if (!queue->q.try_dequeue(node))` for which the condition evaluates to true.
9. _Thread2_ executes `current_memory -= extra_memory`, leaving `current_memory = 100` and returning `false` (leading to an `OutOfMemoryException`).

The expected behavior would be for _Thread2_ to also be able to allocate memory in the buffer. Some sort of signaling should be done so that _Thread2_ is able to understand that memory is being made available and it should wait to check if there is enough to proceed.

### OS:

Linux 5.15.0-48-generic #54~20.04.1-Ubuntu SMP x86_64 GNU/Linux

### DuckDB Version:

v..1-dev	662041e2b43283bfcfeed984af7c3eaa85fb4996

### DuckDB Client:

C++

### Full Name:

Pedro Figueiredo

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by naazgull** [comment]
When dealing with lock-free algorithms and/or structures, one should use local state and CAS operations to relay ownership transfer of the variable states. An example on how `EvictNode` could be written that way (it doesn't deal with **starvation**):

```c++
bool BufferManager::EvictBlocks(idx_t extra_memory, idx_t memory_limit, unique_ptr<FileBuffer> *buffer) {
	PurgeQueue();

	BufferEvictionNode node;
	while (true) {
		auto cur_mem = this->current_memory.load(std::memory_order_acquire);
		while (cur_mem + extra_memory > memory_limit) {
			// get a block to unpin from the queue
			if (!queue->q.try_dequeue(node)) {
				return false;
			}
			// get a reference to the underlying block pointer
			auto handle = node.TryGetBlockHandle();
			if (!handle) {
				continue;
			}
			// we might be able to free this block: grab the mutex and check if we can free it
			lock_guard<mutex> lock(handle->lock);
			if (!node.CanUnload(*handle)) {
				// something changed in the mean-time, bail out
				continue;
			}
			handle->Unload();
			cur_mem = this->current_memory.load(std::memory_order_acquire);
		}
		if (this->current_memory.compare_exchange_strong(cur_mem, cur_mem + extra_memory, std::memory_order_release)) {
			return true;
		}
        	std::this_thread::yield();
	}

	return true;
}

```

**Comment by Mytherin** [comment]
Thanks for the report!

While I can see the issues here - I am not sure if these are actually problems in practice. In general if *any* thread runs out of blocks to evict the entire query will be aborted anyway. Having both threads report an out-of-memory exception instead of only a single thread does not change the behavior of the system.

Did you run into any problems caused by the current implementation, or is this based only on theoretical analysis of the code? We could have a look at addressing this but considering the behavior of the system should not be affected I imagine it will be very hard to test for correctness of the fix.

**Comment by naazgull** [comment]
Thank you for the reply.

Comments below.



> Thanks for the report!
> 

Thank you for taking the time to look into it.

> While I can see the issues here - I am not sure if these are actually problems in practice. In general if _any_ thread runs out of blocks to evict the entire query will be aborted anyway. Having both threads report an out-of-memory exception instead of only a single thread does not change the behavior of the system.
> 

Unless I'm missing something and totally missread the code, it does impact system behavior since one thread may be processing one query and the other some other query (the buffer manager is per database, if I understood correctly). So, instead of failing for just one of the queries, it will fail for both while it shouldn't. Furthermore, while the scenario is described for only two threads, for simplicity, the race condition can be proven for N threads, each being associated with a different query and making fail N queries while in the normal case, could only fail one query, the one for the thread that reached the limit. In the worst case scenario, the system may have 0 bytes allocated, a number of parallel queries may arrive at the same time and lead the race-condition to be observed by all, leading to all queries to fail with out-of-memory exceptions while 0 bytes of memory have been allocated.

> Did you run into any problems caused by the current implementation, or is this based only on theoretical analysis of the code? 
>

Yes, we did ran into unexpected `OutOfMemory` exceptions and the analysis of those issues led to the reported findings.

> We could have a look at addressing this but considering the behavior of the system should not be affected I imagine it will be very hard to test for correctness of the fix.
>

Allow me to profoundly (and respectfully) disagree, IMHO, the algorithm should the correct and isn't, even if the lack of correction doesn't affect system behavior, which IMO, it does. Also, algorithm correctness can be proven theoretically and mathematically, independently of the implementation being correct or the need to test such implementation. In this case, we can prove theoretically and mathematically that the algorithm in question is incorrect.

Thank you for your time.

Regards,

**Comment by Mytherin** [comment]
> Unless I'm missing something and totally missread the code, it does impact system behavior since one thread may be processing one query and the other some other query (the buffer manager is per database, if I understood correctly). So, instead of failing for just one of the queries, it will fail for both while it shouldn't. Furthermore, while the scenario is described for only two threads, for simplicity, the race condition can be proven for N threads, each being associated with a different query and making fail N queries while in the normal case, could only fail one query, the one for the thread that reached the limit.

Yes, that is true, if there are multiple queries running concurrently this might be an issue. However, if multiple queries are running that close to the memory limit concurrently and you want to only abort one of them I do not think that fixing this will be sufficient to resolve the problem. The algorithm for what to do in case of an out-of-memory exception will need to be adapted to handle this situation. 

Let me give an example of how this can still go wrong even with this issue fixed:

```
Memory limit: 100
Allocation size: 1
Current memory: 99
```

Now let's say we allocate in two threads for two distinct queries, `Q1` and `Q2`:

```
Q1: allocate 1
Q2: allocate 1
Current memory: 101
```

Now in the current code we might trigger the race condition that you mentioned and abort both queries. However, assuming that we fix this race condition and only abort Q2, we face *another* race condition. Because what happens if, *before the resources of Q2 are freed up*, Q1 makes a second allocation:

```
Q1: allocate 1
Current memory: 100
-> abort Q1
```

Now there is still a race condition, and both queries might still get incorrectly aborted.

The correct way of fixing this issue is to rework how the out of memory handling works by making it query-aware, so that when we run out of memory we only abort a single query, wait for that queries' resources to be freed, and continue processing the others.

Reworking the out-of-memory handling in that way will also fix the race condition described here, in addition to the other race conditions, but it is of course a much more involved/difficult change to make.

> Yes, we did ran into unexpected OutOfMemory exceptions and the analysis of those issues led to the reported findings.

Have you tested that making these changes to the function resolves the `OutOfMemory` exceptions? I ask because, as mentioned before, shared memory management with multiple concurrent queries is notoriously difficult and I do not think that fixing this will be enough to resolve the issue completely.

> Allow me to profoundly (and respectfully) disagree, IMHO, the algorithm should be correct and isn't, even if the lack of correction doesn't affect system behavior, which IMO, it does. Also, algorithm correctness can be proven theoretically and mathematically, independently of the implementation being correct or the need to test such implementation. In this case, we can prove theoretically and mathematically that the algorithm in question is incorrect.

If fixing the algorithm does not affect system behavior the algorithm is not incorrect. In the single-query case the algorithm never affects system behavior. I do agree that currently the algorithm can affect system behavior in the concurrent multi-client case - however, as mentioned before, I believe the memory management will need to be adapted in a much more significant way to correctly deal with this case anyway.

I am not opposed to applying the changes you described if they resolve practical problems in your case - perhaps by making these race conditions less likely for now - but if there is no observable difference in system behavior I do not see the need to make these changes. Especially considering that lock-free algorithms are very error-prone, and this is making changes in a relatively sensitive part of the system.

**Comment by naazgull** [comment]
Thank you for taking the time to discuss this issue.

> Let me give an example of how this can still go wrong even with this issue fixed:

Sure, there may be other issues where the implementation falls short.

> If fixing the algorithm does not affect system behavior the algorithm is not incorrect.

**Comment by naazgull** [comment]
Thank you for taking the time to discuss this issue.

> Let me give an example of how this can still go wrong even with this issue fixed:

Sure, there may be other issues where the implementation falls short.

> If fixing the algorithm does not affect system behavior the algorithm is not incorrect. 

Let's just agree to disagree on this point since it's a philosophical discussion more than it is a practical one. 

> I am not opposed to applying the changes you described if they resolve practical problems in your case
