### ISSUE TITLE
`rel_project()` quotes uppercase column names

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#5900]
### What happens?

When projecting expressions that consist of a single alias to a column name that contains uppercase letters, the resulting relation has column names quoted. Is this expected?

I can work around, if needed, by setting an alias.

### To Reproduce

``` r
library(duckdb)
#> Loading required package: DBI

# df <- data.frame(b = 1)
df <- data.frame(B = 1)
df
#>   B
#> 1 1

con <- dbConnect(duckdb())

rel <- duckdb:::rel_from_df(con, df)

ref <- duckdb:::expr_reference(names(df))
# duckdb:::expr_set_alias(ref, names(df))

exprs <- list(ref)

proj <- duckdb:::rel_project(rel, exprs)
duckdb:::rapi_rel_to_df(proj)
#>   "B"
#> 1   1
```

<sup>Created on 2023-01-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

macOS aarch64

### DuckDB Version:

d3517c4a677700efe64be83ca51a5a76e805bc3f

### DuckDB Client:

R

### Full Name:

Kirill Müller

### Affiliation:

cynkra GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tmonster** [comment]
I know why the quotes show up. 

`ColumnRefExpression::ToString()` is called when creating projection, which calls  `KeywordHelper::WriteOptionallyQuoted()` and then `KeywordHelper::RequiresQuotes()`. `KeywordHelper::RequiresQuotes()` has an option allow_caps which defaults to false. I imagine false is needed for certain systems. @hannes do you know why this is? 

The fix is either to pass `allow_caps=true` from the `rel_project` in relational.cpp or to just make the `allow_caps` default to true.

**Comment by Mytherin** [comment]
I think we can just default `allow_caps` to true at this point - we used to need this to work around the Postgres parser lowercasing everything but that is not required for our own system anymore anyway.

**Comment by hannes** [comment]
So I'm a bit fuzzy why the `ToString` should quote in the first place
