### ISSUE TITLE
Excessive memory use in aggregations with order by clause

### ISSUE THREAD

**Issue by brendanyounger** [duckdb/duckdb#5920]
### What happens?

Using an `order by` clause in an aggregate leads to many 10's of GB of RAM usage rendering it unusable on Linux based cloud instances without extreme amounts of memory.

### To Reproduce

The following sequence uses 40GB of RAM on my test machine and takes well over a minute

```
create table t (a integer, b integer, c varchar);
insert into t select a.*, b.*, c.generate_series::varchar from generate_series(1, 500) as a join generate_series(1, 500) as b on true join generate_series(1, 50) as c on true;
select a, b, list(c order by c) from t group by 1, 2;
```

this query returns almost immediately and uses very little RAM (a few MBs).

```
select a, b, list(c) from t group by 1, 2;
```

Using `list_sort()` does not help as it causes a SEGFAULT (!).

```
select a, b, list_sort(list(c)) from t group by 1, 2;
Segmentation fault: 11
```

### OS:

x64 (OS X, but tested on Linux as well)

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

Brendan Younger

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! Perhaps @hawkfish can have a look at this issue?

> Using list_sort() does not help as it causes a SEGFAULT (!).

Have you tried this on the latest master? There was a recent fix for this (#5823) and it seems to work correctly for me.

**Comment by brendanyounger** [comment]
I can confirm that the list_sort() issue if fixed on the latest master (but not present on the automated builds for OSX from Github Actions).

**Comment by jmoy** [comment]
I continue to see this problem on current master (commit 73ea444b6b) with the STRING_AGG function. 

My dataset has about 11M rows with about 0.8M distinct groups. The query below takes around 11G of RAM and a minute of time to complete

````
CREATE TABLE HISTS AS 
    SELECT HH_ID, MEM_ID, STRING_AGG(EMPLOYMENT_STATUS ORDER BY WAVE_NO) 
    FROM '/home/jmoy/code/cphs/infilled_histories.parquet' 
    GROUP BY HH_ID,MEM_ID;
````

Removing the `ORDER BY` clause makes the query run instantaneously. 

The `EMPLOYMENT_STATUS` column has single-character values.

The source being a parquet file or not does not make a difference.

**Comment by hawkfish** [comment]
The way `ORDER BY` is implemented is to cache all the values for both the arguments and the ordering clause until `Finalize`, when the sort is performed and the aggregate computed. This means that at least two ~250KB buffer pages are allocated per group. If the number of groups is large, this will lead to the type of memory explosion you are seeing. We can have a look at adaptively reducing the allocation.

**Comment by hawkfish** [comment]
I think the simplest fix here is to just defer allocation of the `ColumnDataCollection`s until they overflow the two corresponding `DataChunk` members. That would buffer 2048 values very compactly, which would cover the common case here of building short strings.

**Comment by hawkfish** [comment]
Amusingly we were already doing this. The problem is that each (small) group buffers the sort key (4 bytes) and the strings (16 bytes) in a minimum chunk size of 2048 rows. 800K * 2048 * (4 + 16) = ~32GB.

The fix is to reduce the buffer size to 16 rows, grow it to 2048 and then start dumping them into `ColumnDataCollection`s. This will "only" consume 256M.

(It is worth mentioning here that ordered aggregation like this is going to be expensive because of the buffering, but the current implementation is certainly excessive!)

**Comment by Mytherin** [comment]
The `LIST` aggregate has a good buffering strategy (implemented by #4265). Perhaps this could be re-used for the ordered aggregates?

**Comment by hawkfish** [comment]
Interesting question about reusing the list aggregation. One thing that concerns me about it is that it seems to keep all the data in memory so it can't spool at scale? Another is that linked lists are typically much slower than resized vectors these days? Plus, ordered aggregates have to sink into sort buffers eventually, so there would be a bunch of copying from the LL to data chunks to sort states, and that seems slow too.

**Comment by Mytherin** [comment]
It's a linked list but it uses exponentially growing allocations, so you get batches of `4 -> 8 -> 16 -> 32 -> ..`. The difference between that and a vector is minimal as you are typically only dealing with a few batches.

I would say the actual sorting would dominate the cost of copying the data around most likely, no?

The spooling to disk is a fair point - but that is something we should solve for the `LIST` as well I think.

**Comment by hawkfish** [comment]
@brendanyounger Does the latest build work better?

**Comment by hawkfish** [comment]
Yes this would help a lot, but we need to architect operators to take advantage of this under parallelism etc. (And the timestamp use case is near and dear to my heart!)

**Comment by brendanyounger** [comment]
The issue does not appear to be fixed.  I tested with `v0.7.2-dev586 23ee8b036a` on OS X.

Specifically, `select a, b, list(c order by c) from t group by 1, 2;` still takes 15GB and close to a minute to process.

Both `select a, b, list_sort(list(c)) from t group by 1, 2;` and `select a, b, list(c) from t group by 1, 2;` use less than 2GB and complete in a few seconds.

**Comment by hawkfish** [comment]
My apologies - I seem to have committed Donald Knuth's sin of only proving it was a fix instead of testing it. I think there is a second problem with repartition the hash table and the `combine` operation chewing up memory unnecessarily.

**Comment by hawkfish** [comment]
Nope, it's just spending all its time allocating memory. Time to reuse the list concatenation code.

**Comment by hawkfish** [comment]
One thing that bears mentioning is that `list_sort(list(c))` is much simpler to implement than `list(c ORDER BY <expr>)` The former can only sort the list using the existing values and can pretty much sort the list in place one row at a time, but the latter can sort the list by _any_ ordered set of pre-aggregate expressions. The `ORDER BY` version has to store all the arguments _and_ the sort values for each aggregate row until finalize time, when it can sort and dispose of the intermediates. I can do a lot of things to reduce the memory footprint, but ultimately the `ORDER BY` version will use twice the memory because it can't assume that the values and the sort key are the same.

**Comment by hawkfish** [comment]
Yeah that occurred to me, but it would still be nice to improve the perf of the general case.

**Comment by Mytherin** [comment]
Definitely

**Comment by hawkfish** [comment]
Add the rewrite to `TransformFunction` (optimizer doesn't like converting aggregates to wrapped aggregates...) Benchmark went from 23.5s to 4.32s.

**Comment by hawkfish** [comment]
One small issue - how do we decide whether to use perfect aggregation? Is there a spot in the optimizer where we could do this?

**Comment by dannyfraser** [comment]
> jmoy

I've also had memory issues with `string_agg` in 0.7.1 when trying to order the aggregated list

**Comment by hawkfish** [comment]
I think I will take a second pass at this. The common case that everyone runs into is `AGG(x ORDER BY x)`, which we can accelerate two ways without cheesy rewrites like the one I added:

* Only make one copy of the data (since the data and the sort key are the same.) This will reduce memory consumption by 50%.
* Use @taniabogatsch's linked list library for smaller numbers of single keys. This will defer (or eliminate) the memory overhead of creating and growing single column `DataChunk`s for each state.

With these in place I think we should remove the rewrite.

**Comment by hawkfish** [comment]
Well I (finally) found the problem, Each ordered aggregate state had its own selection vector for scattering. Switching to using one SV per call to `Update` reduced the memory footprint 90% (17GB => 2GB) and reduced the `string_agg` benchmark runtime by another factor of 2.5 (15s => 6s).

**Comment by hawkfish** [comment]
* Sorting all the aggregate inputs for a chunk once instead of per aggregate in the chunk drops the run time by ⅓. 
* Increasing the number of threads that can process the aggregation finalization drops the run time for both approaches 

![image](https://user-images.githubusercontent.com/13156216/230222424-cc551c1c-b344-44e7-aa88-c437c450c168.png)

**Comment by hawkfish** [comment]
One takeaway here is that we do not allocate more threads for computing slow aggregates, which impacts both functions.

**Comment by hawkfish** [comment]
Just tried this on 1.1.4 and it runs on my MacBook in about 1.5s. Memory appears to peak at about 1.2 GB.
