### ISSUE TITLE
NodeJS client - Memory mode - S3 connection --> client does not automatically reconnect

### ISSUE THREAD

**Issue by dberardo-com** [duckdb/duckdb#5929]
### What happens?

Long running in-memory nodejs clients of duckdb that are fetching from S3 might experience network problems.

I have noticed that my remote duckdb client was not able to "find" any parquet data from S3, although a local development instance was. 

I thought the reason could be a network problem that cause a disconnection so i have just restarted the application. After restart, everything is working fine, and the query that was "not finding" files before, now can find them.

is it possible that the nodejs client does not automatically reconnects to S3 after network failures ? if so, how to add this behavior? 

### To Reproduce

TBH, very hard to reproduce . Is 

### OS:

k8s

### DuckDB Version:

0.6

### DuckDB Client:

nodejs

### Full Name:

check github profile

### Affiliation:

check github profile

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment]
Can you please fill out the missing parts of the issue template? Which "latest as of 18-12-2022" version are you referring to? The latest master or release build?

You also said to check your profile for affiliation, but neither your name nor your company are listed there


With regards to your issue, have you enabled object caching?

**Comment by dberardo-com** [comment]
> With regards to your issue, have you enabled object caching?

positive: 
`SET enable_object_cache=true;`

**Comment by tobilg** [comment]
@dberardo-com have you checked that your WebIdentity wasn't rotated? If you're running on EKS and WebIdentity, it might happed that they invalidate, and then subsequently you won't have access to S3 because of invalid/missing credentials. See https://medium.com/airwalk/how-a-pod-assumes-an-aws-identity-284fc6fda873

You can also inspect the token with jwt.io and determine if it's still valid.

**Comment by tobilg** [comment]
Well, I don't know how this works with MinIO... With S3, you'd have to specify the s3_access_key_id/s3_secret_access_key/s3_session_token (see https://duckdb.org/docs/extensions/httpfs). In EKS, the IAM permissions usually are provided via a service account role, and via the metadata service or webhook endpoint made available to the container you're running. I don't know about your setup, because you didn't explain that in your issue.

**Comment by dberardo-com** [comment]
currently i use access/key auth strategy, so no session token involved (at least not as a configuration). I cant say if auth is the problem, i have more a feeling that this could be a timeout with missing reconnection, in this sense i feel that the comment from @Mause  goes in the right direction.
But again, unfortunately the stdout log gives pretty much no useful information. 

if there is any other place where i could look for more verbose logs, i would give it a try
