### ISSUE TITLE
Support for UPSERT statements

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#61]
This is supported by both SQLite and PostgreSQL, so we probably should too

https://www.sqlite.org/lang_UPSERT.html

**Comment by ucicelos** [comment]
Just found DuckDB yesterday while searching for ways to increase SQLite3 performance and going back and forth between building TimescaleDB. Would love to have it "Upsert" implemented natively, but in the meanwhile wrote a function below to do that in python, the performance is still about 2-3x of SQLite upsert so I am not complaining. 

It's definitely clunky but might help some poor soul :) tbl_dict is a dictionary that holds DataFrames to inserted into DB and tablename is the key.

    def upsert_db_dict_bulk(self,tbl_dict,pk=None):
        ret_val='success'
        cxn = duckdb.connect(self.db_location)
        for tbl in tbl_dict:
            try:
                cur=cxn.cursor()
                try:
                    rcount=cxn.execute("SELECT count(*) as rcount FROM "+tbl).fetchdf()['rcount'].values[0]
                except:
                    rcount=0
                create_cols=[]
                for c in tbl_dict[tbl].columns:
                    create_cols.append(c + ' ' +self.df_duckdb[str(tbl_dict[tbl].dtypes[c])])
                if rcount==0:
                    if pk != None:
                        pkeys='PRIMARY KEY ('+','.join(pk)+')'
                        create_sql="create table " + tbl +" (" + ','.join(create_cols)+','+pkeys+")"
                    else:
                        create_sql="create table " + tbl +" (" + ','.join(create_cols)+")"
                    cur.execute(create_sql)

                #cur.executemany("insert into "+tbl+" ( "+','.join(list(tbl_dict[tbl].columns))+") values ("+','.join(['?' for i in list(tbl_dict[tbl].columns)])+")", (tbl_dict[tbl].values))

                cxn.register('test_df_view', tbl_dict[tbl])
                if pk != None:
                    key_constraints=[]
                    for k in pk:
                        key_constraints.append('tdv.'+k+ ' = '+tbl+'.'+k)
                        cxn.execute('insert into '+tbl+' SELECT tdv.* FROM test_df_view tdv left join ' + tbl + ' on ' + ' and '.join(key_constraints) + ' where '+tbl+'.'+pk[0] + ' is null')
                else:
                    cxn.execute('insert into '+tbl+' SELECT * FROM test_df_view')
                cxn.unregister('test_df_view')
                cxn.commit()
            except Exception as e:
                print(e)
                ret_val=str(e)
        cxn.commit()
        cxn.close()
        return ret_val

**Comment by shauryauppal** [comment]
I am not able to find upsert in documentation is this release?

**Comment by emmenlau** [comment]
In case that gets tackled, I just want to add a kind request here: PostgreSQLimplements `UPSERT` with the `INSERT ON CONFLICT` statement. I've found this quite problematic when used in cases where generic code should be written against the database, since the statement must repeat all non-conflicting types for the `UPDATE` in the `ON CONFLICT` case.

I would significantly prefer a true `UPSERT` functionality, so anything that allows to write "insert this new data into a row if a corresponding row does not exist, or overwrite the corresponding row if one exists" as easily as possible.

**Comment by Alex-Monahan** [comment]
Is there another open source database that implements this feature in a way that you particularly like? It always helps to have a good example! Thanks!

**Comment by emmenlau** [comment]
> Is there another open source database that implements this feature in a way that you particularly like? It always helps to have a good example! Thanks!

Admittedly, no, from the implementations that I've checked (PostgreSQL, SQLite and MySQL) the `UPSERT` is in my eyes always rather too "verbose". I can see some benefit in having the option of doing something different in the `ON CONFLICT` clause. But I'm always surprised that its *mandatory* to specify all non-conflicting entries again in the `ON CONFLICT` clause.

Considering from [here](https://www.techbeamers.com/mysql-upsert/) the following `ON DUPLICATE KEY UPDATE` example:
```sql
INSERT INTO BLOGPOSTs (postId, postTitle, postPublished)
VALUES (5, 'Python Tutorial', '2019-08-04')
ON DUPLICATE KEY UPDATE postId = 5, postTitle = 'Python Tutorial', postPublished = '2019-08-04';
```
I'm under the impression that a common use case is to repeat all values of the `INSERT` clause in the `UPDATE` clause again. This makes the code more verbose, more error-prone to write and less easy to machine-generate.

Having the option to not repeat the `INSERT` in the `UPDATE` would be preferable for me. Is that sensible? The syntax could be for example:
```sql
INSERT INTO BLOGPOSTs (postId, postTitle, postPublished)
VALUES (5, 'Python Tutorial', '2019-08-04')
ON DUPLICATE KEY UPDATE;
```
There may be good reasons to allow the more complex syntax too, for cases where a specific update behavior is needed.

I can see a specific benefit in comparison to PostgreSQL's `ON CONFLICT` syntax which seems particularly verbose in my eyes. With PostgreSQL, its required to identify the conflicting keys in the statement. This seems significantly more error-prone, i.e. when tables change. Furthermore its very hard to machine-generate a PostgreSQL `UPSERT` statement that would work on an arbitrary table.

**Comment by kuatroka** [comment]
So what is the current workaround? If I'm loading data from multiple dfs to a table, how do the rest of you make sure that the repetitive rows from different dfs  are not left duplicated in the table or no error is raised? Thanks

**Comment by kuatroka** [comment]
I'll play with the idea of removing duplicates from the df prior to writing it to the DB.

**Comment by emmenlau** [comment]
> I'll play with the idea of removing duplicates from the df prior to writing it to the DB.

That can work fine, but then you'll keep the values of the *earlier* occurrence, not the later. Is that what you want? For me, later inserts should overwrite earlier ones...

**Comment by kuatroka** [comment]
I deleted the post as I realised it didn't make much sense. Checking for the duplicates in the df prior to writing it to the DB, will not save me from checking for duplicates that might already be in the DB from the previous writes. In summary a proper `INSERT OR IGNORE` or `UPSERT` or `ON CONFLICT` SQL option is needed.

**Comment by Admolly** [comment]
I'd like to add my 2 cents to this discussion because we use DuckDB in production and faced this issue.

@kuatroka It's not really clear to me what exactly Option 1 accomplishes as it doesn't update any values at all.  Inserting the non-existent values is fine but no updates are being executed here.

Option 2 is currently what we use.  This is effective in the sense that it is correct and fast, but the one big problem with this is the fact that DuckDB still does not vacuum deletes.  Meaning that if you run some procedure where you are upserting values daily, the footprint of the table on disk will grow according to the number of rows being inserted AND the number of rows being updated.  This is a bit annoying as your database file grows faster than it really should.  I'm not clear if this is true or not, but it could also make other queries you perform on that table slower than need be.  I think for this option to be really the best option, you will need to address this in some way.

**Comment by dhirschfeld** [comment]
> Is there another open source database that implements this feature in a way that you particularly like? It always helps to have a good example! Thanks!

In case it helps, PG15 has implemented the `MERGE` statement:
* https://www.depesz.com/2022/03/31/waiting-for-postgresql-15-add-support-for-merge-sql-command/
