### ISSUE TITLE
Read Parquet + GCS Higher Memory Usage than expected.

### ISSUE THREAD

**Issue by leanderloew** [duckdb/duckdb#6130]
### What happens?

I have parquet files on GCS I query using duckdb with a query like this: 

```
SELECT
   order_col1,
   order_col2,
   filter_col,
   largeBinaryCol
FROM
  read_parquet('s3://test_bucket/data/*.parquet')
WHERE
  filter_col = a
ORDER BY
  order_col1,
  order_col2
```
My goal is to stream the data, the files are around 500 MB total compressed and 2 GB uncompressed (approx). 

I retrieve the data as follows: 

```
conn = duckdb.connect()
res = conn.execute(sql)
record_batch_reader = res.fetch_record_batch(2048)
for b in record_batch_reader:
   ....
```

Ideally, I want the data to be limited by the memory usage of 2048 rows. However, when I run tests using a bucket with 5k and 11k rows. I see that memory usage grows with the total size of the compressd data. Also, I noticed that we download the whole compressed data before returning the first batch of 2048 rows. 

Another thing I noticed is that the docs specify this query should return a pyarrow.ipc.RecordBatchStreamReader however when I check the actual type returned it is a pyarrow.ipc.RecordBatchReader.

### To Reproduce

See above.

### OS:

Linux / Docker

### DuckDB Version:

0.6.2.dev2063

### DuckDB Client:

Python

### Full Name:

Leander Löw

### Affiliation:

Connect Real

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue, this is a known problem with the python client currently, not so much related to parquet or S3/GCS reading.

We currently have to materialize the entire result set before being able to return the result, this will be fixed in a future version :)

**Comment by Mytherin** [comment]
In general you cannot really stream a query that contains an `ORDER BY`. The `ORDER BY` requires reading all of the data - otherwise the system cannot know what the first rows are supposed to be.

**Comment by leanderloew** [comment]
> In general you cannot really stream a query that contains an `ORDER BY`. The `ORDER BY` requires reading all of the data - otherwise the system cannot know what the first rows are supposed to be.

Makes sense, however, we have 99% of our data in the largeBinaryCol I thought it might be possible to only fully read the order cols to be able to efficiently stream the rest of the data.

**Comment by Mytherin** [comment]
That unfortunately doesn't really work well either. You would have to read in the data from the order columns and sort them to figure out which rows to read, and then do random access on the parquet files hosted on S3 to fetch the remaining data from the `largeBinaryCol`. That has a few problems. Firstly, random access is very costly, particularly over a network connection. Secondly, random access is not really supported by Parquet files. You need to read data one row-group at a time. If the data is spread over multiple row groups you would still be fetching significant chunks of your data to read the first few rows - and would need to read the same row groups many times over in order to have any sort of streaming effect. 

There could be possible configurations where such an algorithm makes sense but in the general case it would be significantly slower and would incur far more egress costs over just reading in the data all at once and sorting it.

**Comment by Mytherin** [comment]
Perhaps one interesting way in which this might be possible to do manually is using the `file_row_number`. For example, you can figure out which rows you want to read from which files:

```sql
SELECT
   order_col1,
   order_col2,
   filename,
   file_row_number
FROM
  read_parquet('s3://test_bucket/data/*.parquet', filename=True, file_row_number=true)
WHERE
  filter_col = a
ORDER BY
  order_col1,
  order_col2
```

Unfortunately we don't yet support an efficient pushdown of `file_row_number` that would then allow you to fetch only the remaining blobs - but that would be a potential path to getting this to work.

**Comment by leanderloew** [comment]
Thanks a lot for the detailed response! I also noticed that in the case of a WHERE clause, we don't download the data during executing the query but we load all associated files when we fetch any rows from it is that what @Tishj mentioned at the beginning? 

So, as it stands to retrieve any of the rows of a file stored in parquet format remotely the whole file has to be downloaded.
