### ISSUE TITLE
[regression in 0.7.0] duckdb-0.7.0 installs the 'duckdb' file back into the build directory

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#6255]
### What happens?

It installs the file ```/usr/ports/databases/duckdb/work/.build/duckdb```.

This file is probably supposed to be installed into bin/duckdb.

### To Reproduce

Regular cmake build/installation.

### OS:

FreeBSD 13.1

### DuckDB Version:

0.7.0

### DuckDB Client:

n/a

### Full Name:

Yuri

### Affiliation:

FreeBSD

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
I'm not entirely sure what the problem is that you're experiencing.
I'm assuming you're talking about building from source, and asking about where the duckdb CLI binary is located?

When building from source, using `make`, the build is written to `<current_directory>/build/${build_type}/`
Assuming your build_type is `release`, the CLI should be in `./build/debug/duckdb`

Please provide more information, currently this is not reproducable.

**Comment by yurivict** [comment]
cmake installs files into a stage directory.
In the stage directory the duckdb executable is supposed to be in: ```{stage-dir}/usr/local/bin/duckdb```. Instead of this, it is installed into ```{stage-dir}/usr/ports/databases/duckdb/work/.build/duckdb```.
