### ISSUE TITLE
Multi-dimensional index (KD-tree?)

### ISSUE THREAD

**Issue by Mytherin** [duckdb/duckdb#63]

**Comment by pdet** [comment]
We already support multidimensional indexes with the compound art keys. Do we still want a KD-Tree?

**Comment by bluezio** [comment]
@pdet the website says "We currently only support unidimensional indexes (of the following types)": does the website need to be updated? Just wondering about this, as I'm currently testing DuckDB for an approach that would benefit from multidimensional indices.

**Comment by hannesmuehleisen** [comment]
@bluezio there is a difference between 1) uni(one)dimensional index that supports compound (multiple columns form the key) and 2) multidimensional indices, which support efficient lookup along multiple dimensions at the same time, for example a KD-Tree. 
1) is supported, 2) currently not (this issue)

**Comment by pdet** [comment]
@hannesmuehleisen I think there is a misunderstanding on the "compound keys" term for ART indexes, which simply means that the keys are concatenated and indexed in the same tree. In the ART, the keys of multiple columns are indexed, are not only a covering index that boosts tuple rec.

e.g., if you index columns A, B. You will first index column A (with vertical and horizontal compression) with the following ART nodes indexing column B (again, with vertical and horizontal compression), reaching leaf nodes with tuples that are for both A and B.

The differences between the ART and the KD-Tree is how the lookup and range lookups are performed. In the KD-Tree you index blocks of data within a certain range, so I would expect that range queries would be faster (since in the art you need to traverse the tree itself), while the ART favors key-lookups.

The reason I suggested the art should be enough is that unless your query is covered by your index, you will do tuple reconstruction, so the advantage of a faster range query from the KD-Tree gets lost on that.

**Comment by Mytherin** [comment]
This is not on the road-map anymore, but might be re-added in the future. Feel free to comment here if there is interest in a KD-tree or similar multi-dimensional index structure.

**Comment by derhuerst** [comment]
Is multidimensional indices a feature that is required in order to define a `UNIQUE()` constraint on an `INTERVAL` column? (Consider this comment irrelevant if not.)

I just stumbled upon this limitation while porting [gtfs-via-postgres](https://github.com/public-transport/gtfs-via-postgres) to DuckDB.
