### ISSUE TITLE
pip install duckdb on termux failed

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#6329]
### What happens?

pip install duckdb on termux failed on many extension/jemalloc/…/xxxx.h at the step of build wheel

### To Reproduce

pip install duckdb
on termux shell

### OS:

Android

### DuckDB Version:

0.70

### DuckDB Client:

python

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for the error report!

Could you please post more of the error log?
I don't think this is enough context to be able to investigate this (besides attempting the install)

I expect we can discern a lot about the issue from the reported errors without having to resort to attempting the install :smile:

**Comment by 97Simei** [comment]
I also meet this problem when I use conan to cross-build from 'Macos:armv8' to 'Android:armv8'.

It gives me the error as :
```
![Screenshot 2023-02-17 at 12 04 01](https://user-images.githubusercontent.com/86485345/219631627-ef29ec82-3810-4a98-845b-1fa64244b84b.png)

```

**Comment by l1t1** [comment]
```
~ $ pip install duckdb --log log.log
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting duckdb
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3c/db/38898496a0f5a5dcebf32a0775f77554d3355b0f02219c2d1c4cce90e037/duckdb-0.7.0.tar.gz (10.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: duckdb
  error: subprocess-exited-with-error

  × Building wheel for duckdb (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for duckdb (pyproject.toml) ... error
  ERROR: Failed building wheel for duckdb
Failed to build duckdb
ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects
~ $ 
```

**Comment by l1t1** [comment]
[log.zip](https://github.com/duckdb/duckdb/files/10766642/log.zip)

**Comment by l1t1** [comment]
version 0.7.1 still has the question.

**Comment by abubelinha** [comment]
I know this is a closed issue, but I don't understand if it was closed because it was solved (by that time) or for antother reason.

@Mytherin @Tishj please, could you explain a bit?

duckdb CLI works well in termux. 
But pip installation of duckdb python package keeps failing in all Android python alternatives I know (termux and pydroid3). 

Other python packages like pandas are easily installed using pip.
It would be great to have duckdb available in our phones' python scripts. What should I do?

- Could you please reopen this issue?
- Should I open a new one?
- Is this closed because of some incompatibility, so it just can't be solved?
- Are we supposed to try the harder option mentioned in termux documentation, and install the package from sources?:
https://wiki.termux.com/wiki/Python

In that case, could someone explain the correct commands to use? I've never compiled anything myself.

Thanks a lot in advance
@abubelinha
