### ISSUE TITLE
Possible error in JoinOrderOptimizer::CreateJoinTree

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#638]
In src/optimizer/join_order_optimizer.cpp a comment conflicts with the code:
```
// cost is expected_cardinality plus the cost of the previous plans
idx_t cost = expected_cardinality;
```
The cost of a JoinNode is set to be its expected cardinality, rather than its expected cardinality plus the cost of its children. I changed it to:
```
idx_t cost = expected_cardinality + left->cost + right->cost;
```
And observed a speedup of ~22% on the IMDB Join Order Benchmark. With the 'corrected' cost, 67% of the 113 queries became faster.

Is this an error? Or does it have something to do with the lack of cardinality estimation?

**Comment by Mytherin** [comment]
At some point I think I fixed this, and the result indeed was that certain join orders got better, but others got worse. I think I reverted it because some queries we run a lot for testing got worse join orders which resulted in the tests taking a lot longer.

Either way, both are kind of a poor heuristic at the moment. We need to implement proper cardinality estimation (#75) to properly fix this.

**Comment by arjenpdevries** [comment]
If you plan not to change it, would be great to make code and comments consistent :-)

**Comment by Mytherin** [comment]
Indeed, good point ;) one of the standard traps: changing code without changing comments.
