### ISSUE TITLE
DBeaver (JDBC) not displaying view definition

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#6485]
### What happens?

DBeaver is not able to generate view definitions. 

### To Reproduce

Right clicking on a view in the left hand panel and generating the DDL does not show the view definition text. I receive the same error when I try to inspect the view itself, so DBeaver just isn't able to find the view definition in some way.

The view was generated with these statements:
```sql
create table testing as select 42 as test_col;

create view woot as select * from testing limit 1;
```

![image](https://user-images.githubusercontent.com/52226177/221599655-d1b41dd4-fceb-412e-a868-4216137072de.png)

![image](https://user-images.githubusercontent.com/52226177/221599671-c26104b8-e060-4a37-9599-3af93c94b6de.png)

### OS:

Windows 10

### DuckDB Version:

0.7.1

### DuckDB Client:

JDBC

### Full Name:

Alex Monahan

### Affiliation:

DuckDB Labs and Intel

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by chengjie0929** [comment]
I would like tad to be transformed into a duckdb proprietary database management tool based on the current functionality. Because dbeaver is too problematic for duckdb.

**Comment by chengjie0929** [comment]
What duckdb currently lacks is its own management tool, something similar to plsql developer.

**Comment by Mause** [comment]
I had a brief look into this issue the other day, and in short, dbeaver doesn't fetch a prerendered ddl string from the driver, instead it queries the driver for the columns, etc, and then depending on which dialect is selected in dbeaver, generates the ddl string using a string template. 

This would be fine if you could easily switch to the postgres dialect (instead of the generic one that DuckDB uses by default in dbeaver), but we're not yet compatible enough with postgres for that to work.

Depending on how much we want this feature, we may need to contribute a DuckDB dialect to dbeaver

**Comment by LonwoLonwo** [comment]
Hello @Mause 

Where can I find 

> prerendered ddl string from the driver

to check how we can read view definitions for DuckDB?

**Comment by Mause** [comment]
> Hello @Mause 
> 
> Where can I find 
> 
> > prerendered ddl string from the driver
> 
> to check how we can read view definitions for DuckDB?

```sql
select sql from duckdb_tables();
```

And similar queries for other things
