### ISSUE TITLE
Unexpected error when extracting entries from a map with nested keys

### ISSUE THREAD

**Issue by Teggy** [duckdb/duckdb#6541]
### What happens?

Building a map value with nested keys (lists or structs) works fine as indicated by the DuckDB documentation at  https://duckdb.org/docs/sql/data_types/map.

Extracting a value from such maps yields an unexpected error, however:

~~~
Error: Invalid type Error: Invalid Type [LIST]: Invalid type for List Vector Search
Error: Invalid type Error: Invalid Type [STRUCT]: Invalid type for List Vector Search
~~~

### To Reproduce

Map with list-typed keys:

~~~
SELECT map_extract(map([[0,1]], ['X']), [0,1]);
-- Error: Invalid type Error: Invalid Type [LIST]: Invalid type for List Vector Search
~~~

Map with struct-typed keys:
~~~
SELECT map_extract(map([(0,1)], ['X']), (0,1));
-- Error: Invalid type Error: Invalid Type [STRUCT]: Invalid type for List Vector Search
~~~

### OS:

macOS Ventura 13.2.1

### DuckDB Version:

v0.7.2-dev14 c817201fa8

### DuckDB Client:

CLI

### Full Name:

Torsten Grust

### Affiliation:

U Tübingen, Germany

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for making the issue, I started working on this 👍 

I did run into a bit of a hiccup, I wanted to use the ListPositionFunction to find the offset using the keys of the map, and then apply the offset to get the corresponding value.

But I was still thinking the MAP was a `STRUCT(LIST(K), LIST(V))` and it was recently changed to `LIST(STRUCT(K,V))` instead.
Which is a problem because ListPositionFunction takes a LIST(K).

Logically we can transform the input to something that ListPositionFunction does accept, at 0 cost.
But technically that's not possible currently.. debating whether to change the internals so it *is* possible at 0 cost
OR it's not worth it and I should just do a copy - or change the ListPositionFunction so it can also work on a `LIST(STRUCT(K,V))` using a Functor of some sorts

But rant aside - I think it should be a decently quick fix
