### ISSUE TITLE
httpfs fails to follow a 302 redirect

### ISSUE THREAD

**Issue by ttomasz** [duckdb/duckdb#6562]
### What happens?

When trying to query file: `https://api.dane.gov.pl/resources/41822,rejestr-biuro-rzeczy-znalezionych-miasto-przemysl-json/file` I get error:
```
>>> conn.execute("select * from read_json_auto('https://dane.gov.pl/pl/dataset/2861/resource/41822,rejestr-biuro-rzeczy-znalezionych-miasto-przemysl-json/file')")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.InvalidInputException: Invalid Input Error: Malformed JSON in file "https://dane.gov.pl/pl/dataset/2861/resource/41822,rejestr-biuro-rzeczy-znalezionych-miasto-przemysl-json/file", at byte 1 in object 2: unexpected character.
```

The URL redirects to: `https://przemysl.skycms.com.pl/open-data/9/1665396002_ams8nlw7CGHcawRU/json`

When I try that URL it seems to be able to read the file though if throws another error related to lack of Content-Length but that has been reported in #6388  is worked on in PR #6448 .

Similar issues were reported in #4964 and #5121 but may have been a different issue since they were closed.

### To Reproduce

```sql
select *
from read_json_auto('https://dane.gov.pl/pl/dataset/2861/resource/41822,rejestr-biuro-rzeczy-znalezionych-miasto-przemysl-json/file')
```

### OS:

Linux

### DuckDB Version:

0.7.2-dev16

### DuckDB Client:

Python

### Full Name:

Tomasz Taraś

### Affiliation:

DXC

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by RandomFractals** [comment]
I must be hitting the same issue with 304 redirect response when trying to load current Chicago traffic estimates.

Data Source: https://data.cityofchicago.org/Transportation/Chicago-Traffic-Tracker-Congestion-Estimates-by-Se/n4j6-wkkf

JSON Data Url: https://data.cityofchicago.org/resource/n4j6-wkkf.json

DuckDB Sql query:

```sql
select * from 'https://data.cityofchicago.org/resource/n4j6-wkkf.json';
```

Trying to query that public JSON data in Jupyter notebook with Python:

![image](https://user-images.githubusercontent.com/656833/226569693-74670369-e667-4b1b-8f15-d78c95be86ad.png)

Works just fine in a basic VSCode Restbook that handles redirects properly:

![image](https://user-images.githubusercontent.com/656833/226569872-3010bb9a-f42e-4376-a79c-7cceb09a462c.png)

**Comment by carlopi** [comment]
> https://api.dane.gov.pl/resources/41822,rejestr-biuro-rzeczy-znalezionych-miasto-przemysl-json/file

This URL do not use proper HTML redirects but emulates redirects via JavaScript events, and so it can only work in a Web browser, and it's out of the scope for DuckDB.

> select *
from read_json_auto('https://dane.gov.pl/pl/dataset/2861/resource/41822,rejestr-biuro-rzeczy-znalezionych-miasto-przemysl-json/file')

This works for me on latest master. Yey!

---

> select * from 'https://data.cityofchicago.org/resource/n4j6-wkkf.json';

Here the problem is different, and I confirm it does not work, but cause of failure is due to a 400 response by the server on HEAD request.
```bash
curl https://data.cityofchicago.org/resource/n4j6-wkkf.json -I
HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 08 May 2023 11:46:19 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Error-Code: invalid_request
X-Error-Message: HEAD is not supported
Cache-Control: private, no-cache, must-revalidate
Age: 0
X-Socrata-Region: aws-us-east-1-fedramp-prod
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Socrata-RequestId: cd74d38f0f0fbfe426b96dca14d5665f
```

Here potentially a full range download might be potentially attempted, potentially via opt-in by the user, but this case is currently not handled by DuckDB. (see https://github.com/duckdb/duckdb/issues/5041 or https://github.com/duckdb/duckdb/pull/6467)

---

Given the main issue is solved, and the second issue is not related and in-between "won't solve" and "duplicated", I think this can be now closed.

Thanks both!
