### ISSUE TITLE
Conflict target required when table has multiple primary key columns

### ISSUE THREAD

**Issue by tekumara** [duckdb/duckdb#6576]
### What happens?

`insert or replace` on a table with multiple primary keys requires a conflict_target. However the [docs](https://duckdb.org/docs/sql/statements/insert#on-conflict-clause) state it's optional and *all* keys will be targeted when there's no conflict_target:

> Optionally you can provide a conflict_target, which is a group of columns that an Index indexes on, or if left out, all UNIQUE or PRIMARY KEY constraint(s) on the table are targeted.

### To Reproduce

Without a conflict target,
```
D create table foo(a int, b int, c int, d int, primary key(a,b,c));
D insert or replace into foo values (1,2,3,4);
Error: Binder Error: Conflict target has to be provided for a DO UPDATE operation when the table has multiple UNIQUE/PRIMARY KEY constraints
```

Only works with a conflict target, eg:
```
D insert into foo values (1,2,3,4) on conflict(a,b,c) do update set d=4;
```

### OS:

macos

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

cli

### Full Name:

Oliver Mannion

### Affiliation:

Xero

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Hey thanks for raising the issue, we need to update the docs!

The reason this is not supported for DO UPDATE is because:
> Not supported because:
It's because one insert row could violate multiple different unique constraints,
with it being a different row for each of the constraints that's causing the violation,
and the upsert is only intended to update a single row.

[from here](https://sqlite.org/forum/info/45cf84d3e89d590d)
When there is only one unique/primary key constraint, we have opted to allow this because it doesn't cause this issue

**Comment by taniabogatsch** [comment]
Can be closed once we merge https://github.com/duckdb/duckdb-web/pull/791

**Comment by Alex-Monahan** [comment]
Closed by https://github.com/duckdb/duckdb-web/pull/791

**Comment by davetapley** [comment]
Just ran in to this and I'm not sure I agree with this statement for a table having a _single_ multi-column (composite) index (which is what @tekumara, the poster on sqlite.org, and myself all have):

> It's because one insert row could violate multiple different unique constraints,

For _multiple_ unique constraints I completely agree, but with a multi-column unique constraint there must be _exactly_ zero or one matching rows, surely?

Multiple rows might be matched by different columns which make up the composite, and again it would make sense that you couldn't update without a target if the constraints were separate, but for a composite it either matches all columns (and so you have exactly row to update) or it matches zero (and so you insert)?   🤔

**Comment by mattsta** [comment]
Just ran into this as well when converting a self-contained analytics platform from sqlite to duckdb (I'm converting a 100 GB sqlite management system because we're still too stubborn to just use a full database server).

The composite primary key upsert worked as expected on sqlite for years, but converting the interface to duckdb broke our simple `INSERT OR REPLACE` syntax because we have `PRIMARY KEY (name, timestamp)`.

A table with a single composite primary key is generating this error even though it's perfectly logical to just use "INSERT OR REPLACE" because the index is defined to be singular and unique. 🤷‍♂️

**Comment by taniabogatsch** [comment]
Hi @mattsta. We had another internal discussion, and we agreed that there should be no ambiguity conflict in the single-index scenario.
