### ISSUE TITLE
Error on R versions <= 3.6: 'R_user_dir' is not an exported object from 'namespace:tools'`

### ISSUE THREAD

**Issue by thisisnic** [duckdb/duckdb#6589]
### What happens?

The Arrow CI has a job which runs our tests on R 3.6.  Some of the tests in the R package which relate to passing data to DuckDB fail with the error message `'R_user_dir' is not an exported object from 'namespace:tools'`.

e.g. https://github.com/ursacomputing/crossbow/actions/runs/4338777892/jobs/7575753670#step:5:24251

The R function `tools::R_user_dir()` was introduced in tools version 4.0.0, so given the concordance between tools package version and R version, I'm guessing that what's happening here is that tools version 3.6 is being installed, and so the failure to find the function, which was introduced in #6355.

### To Reproduce

On R 3.6:
```
> library("DBI")
> con <- dbConnect(duckdb::duckdb(), dbdir = ":memory:")
Error: 'R_user_dir' is not an exported object from 'namespace:tools'
```

### OS:

Ubuntu

### DuckDB Version:

0.7.1-1

### DuckDB Client:

R

### Full Name:

Nic Crane

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment]
Indeed but CRAN specifically requested that we use `R_user_dir`. So not sure how to proceed here?

**Comment by thisisnic** [comment]
Thanks for the suggestion; I think we'll skip the tests on our CI on R < 4.0.0 for now and then that solves it for us most easily.

**Comment by rsund** [comment]
Technically it would be straightforward to condition not to use R_user_dir if R version is below 4.0. Is that really necessary is another question as the newest DuckDB versions will not be available (as pre-build binaries) for old R versions in CRAN or Runiverse, i.e. the problem will manifest only if recent DuckDB is "manually" compiled for an old R version. Setting the minimum R version needed by DuckDB to 4.0 would certainly change error from "function not found" to "too old R version", but maybe that is overreaction if dependency is just due to one function call in one place that would be easy to condition.

**Comment by eitsupi** [comment]
> Is that really necessary is another question as the newest DuckDB versions will not be available (as pre-build binaries) for old R versions in CRAN or Runiverse, i.e. the problem will manifest only if recent DuckDB is "manually" compiled for an old R version

I believe the Posit Public Package Manager (RSPM) still builds binaries for older versions of R.
https://packagemanager.rstudio.com/client/#/repos/2/packages/duckdb
https://packagemanager.rstudio.com/cran/__linux__/jammy/latest/src/contrib/duckdb_0.7.1-1.tar.gz?r_version=3.6

**Comment by rsund** [comment]
Probably the easiest thing to do for supporting older R versions would be to define an own (internal) function in DuckDB R package for the `R_user_dir()` by using [source from `backports` package](https://github.com/r-lib/backports/blob/main/R/R_user_dir.R) and use that instead of the function from `tools` as then the things would work in a similar way regardless of the R version without any conditioning. No idea, unfortunately, would that be against the explicit CRAN request.

I also noticed that the master branch `test_extensions.R` (under testhat) has `skip_on_cran()` commented out, but those tests should probably be skipped on CRAN as extensions most likely will not be available in the expected locations in a similar way as with DuckDB's own CIs. Unclear if that is manually fixed before sending to CRAN.
