### ISSUE TITLE
TIMESTAMP <=> TIMESTAMPTZ casts should reinterpret, not copy

### ISSUE THREAD

**Issue by hawkfish** [duckdb/duckdb#6604]
### What happens?

Casting between `TIMESTAMP` and `TIMESTAMP WITH TIME ZONE` copies data instead of just reinterpreting it.

### To Reproduce

From discussion #6599:

```sql
CREATE TABLE table_without_tz AS
SELECT row_number() OVER () % 5 AS KEY,
       row_number() OVER () AS value,
       timestamp_utc::timestamp AS timestamp_utc
FROM generate_series(NOW() - interval '1' MONTH, NOW(), interval '10 milliseconds') t(timestamp_utc);

SELECT min(timestamp_utc::timestamptz) FROM table_without_tz;
-- 3.83s

SELECT min(timestamp_utc) FROM table_without_tz;
-- About twice as fast
```

### OS:

OSX

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Richard Wesley

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Should be fixed now

**Comment by Mytherin** [comment]
Actually this is not yet fixed - it seems the issue does not come from the copy, but from the `CastFromNaive` and `CastToNaive` functions.

Here is a simpler example:

```sql

CREATE TABLE table_with_tz AS
SELECT row_number() OVER () % 5 AS KEY,
       timestamp_utc::timestamptz AS timestamp_utc
FROM generate_series(NOW() - interval '1' MONTH, NOW(), interval '100 milliseconds') t(timestamp_utc);

CREATE TABLE table_without_tz AS
SELECT row_number() OVER () % 5 AS KEY,
       timestamp_utc::timestamp AS timestamp_utc
FROM generate_series(NOW() - interval '1' MONTH, NOW(), interval '100 milliseconds') t(timestamp_utc);

SELECT min(timestamp_utc) FROM table_with_tz;
-- 0.008s
SELECT min(timestamp_utc::timestamp) FROM table_with_tz;
-- 0.43s

SELECT min(timestamp_utc) FROM table_without_tz;
-- 0.005s
SELECT min(timestamp_utc::timestamptz) FROM table_without_tz;
-- 0.39s

SELECT min(key) FROM table_with_tz;
-- 0.008s
SELECT min(key::DOUBLE) FROM table_with_tz;
-- 0.030s
```

Note how the cast from numerics normally does not have nearly as big of an impact.

It seems like the `CastTo/FromNaive` function are there only in case the user has changed the calendar. Could we perhaps optimize these functions so that they are a regular `Reinterpret` in the (likely very common) scenario where the user has not changed their calendar settings?
