### ISSUE TITLE
Selecting from a view in an attached database errors with references to tables that don't exist in current database

### ISSUE THREAD

**Issue by bhalatest** [duckdb/duckdb#6704]
### What happens?

Selecting from a  view  in an attached DB gives an error saying that underlying table doesn't exist.
Basically it is looking for the underlying objects of the view in the current database not the attached one.

Error:
ExampleExceptionFormatter: exception message was: Catalog Error: Table with name srctest does not exist!
Did you mean "src.srctest"? 

### To Reproduce

In a db say src.db create these

create table srctest (id varchar);
create view srcview as select * from srctest where id is not null;

In a diff db attch the src.db

attach 'c:/temp/src.db' as src;

select * from src.srctest; // This works

select * from src.srcview; //This gives the below error

Error:
ExampleExceptionFormatter: exception message was: Catalog Error: Table with name srctest does not exist!
Did you mean "src.srctest"? 

### OS:

windows

### DuckDB Version:

7.1

### DuckDB Client:

jdbc and Python

### Full Name:

Bhala Ghatate

### Affiliation:

Daman

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paul-iqmo** [comment]
This seems related to https://github.com/duckdb/duckdb/issues/6666. 

6666 is for indexes, and 6704 (this) is for views, but otherwise cases are identical.

**Comment by bhalatest** [comment]
I also tried a workaround where I created identical table in the :memory: db and also by trying to create a view in current db referencing the table in src db. Both didn't give desired result.
Thought process was that the select * from src.srcview may resolve to the table in current (:memory: db)
I know this would lead to name clashes esp when attaching multiple dbs etc but was trying to pinpoint where the issue might be.
Am thinking it is more than a simple name resolution fix for a general case. 
Haven't tried but if a views can refer to tables accross dbs then a cycles will also need to be resolved.

Tried the following two in  diff sessions
1. con.execute('create table srctest (id varchar);')
2. con.execute('create view srctest as select * from src.srctest;')

So as a workaround am just creating tables instead of views in src db. Duplication of data but it is a working db i.e. we use it for temp processing so not crtical for our application.

**Comment by Mytherin** [comment]
Thanks for the report!

The problem here is that the query of the view is stored as-is (`select * from srctest where id is not null`). When we attach a database in a different "position" - the meaning of the these tables changes. For example:

```sql
ATTACH 'attach.db' AS s1;
CREATE TABLE s1.table AS SELECT 42 i;
CREATE VIEW s1.view AS SELECT * FROM s1.table;
DETACH s1;
ATTACH 'attach.db' AS s2;
SELECT * FROM s2.table;
-- s1.table does not exist anymore - this is now called s2.table
-- Error: Catalog Error: Table with name table does not exist!
-- Did you mean "s2.table"?
```

Interestingly, SQLite seems to suffer from the same problem:

```sql
sqlite> ATTACH 'attach.db' AS s1;
sqlite> CREATE TABLE s1.tbl AS SELECT 42 i;
sqlite> CREATE VIEW s1.view AS SELECT * FROM s1.tbl;
sqlite> DETACH s1;
sqlite> ATTACH 'attach.db' AS s2;
Error: stepping, malformed database schema (view) - view view cannot reference objects in database s1 (11)
```

I think the correct solution here is to transform the query so that any tables that point to the current catalog are labeled as `[CATALOG_OF_VIEW]` or similar. When executing a view, we can then replace `[CATALOG_OF_VIEW]` with the current catalog name of the view.

That works when views are always *within* a database, but does not work when we have views *across* databases. For example, what about this:

```sql
D ATTACH 'attach.db' AS s1;
D ATTACH 'attach2.db' AS s2;
D CREATE TABLE s1.tbl(i INT);
D CREATE VIEW s2.view AS SELECT * FROM s1.tbl;
D DETACH s1;
D SELECT * FROM s2.view;
-- Error: Catalog Error: Table with name tbl does not exist!
-- Did you mean "system.information_schema.tables"?
```

SQLite solves this problem by prohibiting creating views that refer to tables outside of the catalog in which they are created. While that is possible - it also seems limiting as that means cross-database views can never be created.
