### ISSUE TITLE
Parent query columns mask subquery columns

### ISSUE THREAD

**Issue by kku1993** [duckdb/duckdb#6853]
### What happens?

When a subquery references a column that has the same identifier as a column in the parent query, it appears that the parent query's column is masking the subquery's.

For example, given 

```
SELECT
  1 as col
WHERE
  1 IN (SELECT col FROM t1)
```

The query behaves as if it's written like:

```
SELECT
  1 as col
WHERE
  1 IN (SELECT 1 as col FROM t1)
```

## SQL

```
WITH t1 AS (
  SELECT 1 as a
)

SELECT
  1 as col
WHERE
  1 IN (SELECT col FROM t1)
```

## Expected output

An error saying `col` is not found in `t1`

## Actual output

```
cat test2.sql | ./scripts/duckdb
┌───────┐
│  col  │
│ int32 │
├───────┤
│     1 │
└───────┘
```

### OS:

macOS 13.2.1, Apple M1 Pro

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

shell

### Full Name:

Kevin Ku

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

This is expected/intentional behavior. Using a column from the outer query inside the inner query turns it into a correlated subquery. This is standard SQL and works in all SQL systems. For example, in Postgres:

```sql
CREATE TABLE t1(i int);
CREATE TABLE t2(col int);
SELECT col FROM t2 WHERE 1 IN (SELECT col FROM t1);
 col 
-----
(0 rows)
```

The only difference is that DuckDB also allows using aliases in the `WHERE` clause, which most other systems do not allow. From the perspective of a correlated subquery I do not see this as an issue, however. The way I view correlated subqueries is that they are essentially function calls, where the correlated columns are the parameters. So for example, this:

```sql
SELECT
  1 as col
WHERE
  1 IN (SELECT col FROM t1)
```

Is equivalent to:

```sql
SELECT
  1 as col
WHERE
  in_subquery(1, col)
```

Since `col` is valid in the `WHERE` clause (as DuckDB supports using aliases in the WHERE clause) it should also be valid in a correlated subquery.

**Comment by kku1993** [comment]
Thanks for the explanation! The ability to use aliases in WHERE clause is nice :)

I did notice a bug with using aliases in subquery and WHERE clause when querying from CTEs, see repo below (I can also file a separate bug if that's preferred):

```
WITH t1 AS (
  SELECT 1 as a
),
t2 AS (
  SELECT 1 as b
)

SELECT b AS col FROM t2 WHERE 1 IN (SELECT col from t1)
```

Running the above gives me:

```
Error: near line 1: INTERNAL Error: Failed to bind column reference "b" [7.0] (bindings: [22.0])
```

Whereas running this is fine:

```
CREATE TABLE t1 (a int);
CREATE TABLE t2 (b int);
SELECT b AS col FROM t2 WHERE 1 IN (SELECT col from t1);
```
