### ISSUE TITLE
Optimizer - correlated subquery translation to join?

### ISSUE THREAD

**Issue by ak2k** [duckdb/duckdb#688]
Hi, while doing some benchmark comparisons with SQLite, I’m noticing that some subqueries that would benefit from the WHERE condition on the outer query don’t seem to be getting that applied automatically, which made made me wonder whether the engine yet supports the optimization of translating such subqueries to joins? 

Please let me know if my question is well enough expressed or if I should include an example query. Thank you!

**Comment by hannesmuehleisen** [comment]
It should always be translated. Can you give an example please?

**Comment by ak2k** [comment]
Thank you very much for confirming! In that case, I'll put together an example and revert.

**Comment by ak2k** [comment]
Hi, Attached is that example of the kind of query that SQLite seems to handle better for whatever reason. Rather than correlated subquery translation, perhaps this is an issue where filters aren't being pushed down to CTEs instead.

In the attached repro, the first query is the intended one, and the second query is a demonstration that if the predicate from the outer/main query were pushed down, the execution would be ~4X faster.

[repro_filter_pushdown.py.txt](https://github.com/cwida/duckdb/files/4864600/repro_filter_pushdown.py.txt)
[output.txt](https://github.com/cwida/duckdb/files/4864603/output.txt)

Thank you!

**Comment by ak2k** [comment]
Do we think there could be a chance that this potential non-pushdown with CTEs could be related to #746 or do they seem independent? https://github.com/cwida/duckdb/issues/746#issuecomment-656584741

**Comment by Mytherin** [comment]
Thanks for the example! I totally missed that you had updated it. Indeed the problem here seems to be related to filter pushdown, but I don't think it is related to #746. The issue in #746 seems more related to the Parquet reader itself, whereas this is a problem with the filter pushdown optimizer. I will take a look and see if I can fix it so the filter is correctly pushed down into the subquery.

**Comment by ak2k** [comment]
My pleasure! I'll be very interested in what you find.

**Comment by Mytherin** [comment]
After some investigation I can confirm that the issue is with this particular expression set not being pushed down into the subquery. The title of this issue is a bit ironic, given that the problem is that DuckDB does a rewrite to a join, while SQLite does not :) The join rewrite complicates the query plan to the point that the current filter pushdown optimizer does not correctly do the pushdown. I am looking into fixing this and extending the filter pushdown optimizer to properly handle this case.
