### ISSUE TITLE
Default table name for JSON files unintuitive.

### ISSUE THREAD

**Issue by cube2222** [duckdb/duckdb#6880]
### What happens?

This fails:
```bash
duckdb -c "SELECT books.summary FROM books.json LIMIT 10"
```

because it seems like DuckDB treats the `books.json` as the standard `database.table` form, meaning the table is aliased to `json` by default, leading to this being the correct form:
```bash
duckdb -c "SELECT json.summary FROM books.json LIMIT 10"
```
Which is really unintuitive.

I realize you can do `books.json as books` to make it work like I want, but I think making this the default would be much nicer.

### To Reproduce

Already posted above. Arbitrary json file.

### OS:

MacOS

### DuckDB Version:

0.7.1

### DuckDB Client:

CLI

### Full Name:

Jakub Martin

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
@cube2222 I am currently looking at this, and I don't think there's a way around this. What's happening is that the column name is set to `json`, not the table name. By default, tables do not have aliases unless you give them one. So, you can't do as you say
```
duckdb -c "SELECT books.summary FROM books.json as books LIMIT 10"
```
Because the resulting table is aliased with `books`, but the single column coming from this table is aliased to `json`. You would have to do:
```
duckdb -c "SELECT books.json.summary FROM books.json as books LIMIT 10"
```

Of course, the resulting column could be aliased too `books` instead, by stripping `.json` (and potentially, e.g., `.gz`), but the `read_json` table functions can also take more than one input file, by using a glob or a list of files. In this case, it is not clear what the resulting column should be called.

Also, `read_json_auto` (which you are implicitly using in your query) should unpack the top-level JSON object to it's individual fields, e.g., reading a file like this (`books.json`):
```json
{"id":42,"title":"Hitchhiker's Guide to the Galaxy","summary":"Thanks For All The Fish"}
```
Should result in a table with three columns, `id`, `title`, and `summary`.

Only if you set specific settings, or when the top-level JSON values are not objects, it should result in a column with name `json`.

**Comment by cube2222** [comment]
> Because the resulting table is aliased with books, but the single column coming from this table is aliased to json.

I don't think I understand @lnkuiper. I have the amazon review dataset json file (so suffice it to say there are many columns), and i.e.
```
duckdb -c "SELECT books.summary ROM books.json as books"
```
absolutely does work.

If I remove the table alias, the one that works is
```
duckdb -c "SELECT json.summary ROM books.json"
```
because
```
duckdb -c "SELECT books.summary ROM books.json"
```
results in 
```
~> duckdb -c "SELECT books.summary FROM books.json"
Error: Binder Error: Referenced table "books" not found!
Candidate tables: "json"
LINE 1: SELECT books.summary FROM books.json
```
which seems to indicate that the table referenced as `books.json` does get the default short name of `json`, and not `books` (which would be the intuitive one) nor `books.json` (as I think you indicated), as the following demonstrates:
```
> duckdb -c "SELECT books.json.summary FROM books.json"
Error: Binder Error: Referenced table "books" not found!
Candidate tables: "json"
LINE 1: SELECT books.json.summary FROM books.json
```
and for additional context, this one doesn't work either:
```
> duckdb -c 'SELECT "books.json".summary FROM books.json'
Error: Binder Error: Referenced table "books.json" not found!
Candidate tables: "json"
LINE 1: SELECT "books.json".summary FROM books.json
```

**Comment by lnkuiper** [comment]
@cube2222 Sorry for the misunderstanding! In some cases, the `read_json` table function can return a single column with name `json`. This isn't happening in your case. It is indeed the table name that is defaulted to `json`. I've pushed a fix in my branch, which will be in the next release.

Thanks again for the suggestion, this is a great addition. It will affect csv/parquet scans too.
