### ISSUE TITLE
DuckDB returns bogus values for numpy string scalars

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#6932]
### What happens?

DuckDB returns `None` values for DataFrame columns whose data are composed of numpy `str_` scalars.

Encountered in https://github.com/ibis-project/ibis/issues/5879.

### To Reproduce

```
In [18]: import duckdb, numpy as np, pandas as pd

In [19]: df = pd.DataFrame({"x": list(map(np.str_, range(3))), "y": list(range(3))})

In [20]: con.execute("select * from df").fetchall()
Out[20]: [(None, 0), (None, 1), (None, 2)]
```

I haven't tried this on `master`.

### OS:

NixOS

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
On master I can reproduce this 👍 

What is the expected behavior here? What is ` numpy.str_` scalar supposed to represent is what I'm wondering

**Comment by cpcloud** [comment]
Yep, they should be strings. They print like numbers due to the way pandas reprs the DataFrame. Perhaps `["a", "b", "c"]` is a better test case 😅

**Comment by cpcloud** [comment]
There's already a `UNICODE` enum variant in the codebase, but it's not handled anywhere in `vector_conversion.cpp`.

**Comment by paultiq** [comment]
Is this the same as https://github.com/duckdb/duckdb/issues/6845?

**Comment by Tishj** [comment]
I've identified the problem, and I'm writing a fix.
The problem is that this is an object column, so we analyze the objects to figure out the appropriate DuckDB type, which is VARCHAR.
Then when we scan an object column, there are 2 paths, one is converting the objects one by one, this is relatively slow.
The other is a fast path for if they are all strings, where we assume the objects are all `builtin.str` types, so we can directly access the buffers.

The decision which path is taken is made too naively currently:
```c++
	case PandasType::OBJECT: {
		//! We have determined the underlying logical type of this object column
		// Get the source pointer of the numpy array
		auto src_ptr = (PyObject **)numpy_col.data();
		if (out.GetType().id() != LogicalTypeId::VARCHAR) {
			return ScanPandasObjectColumn(bind_data, src_ptr, count, offset, out);
		}
```
In this case, even though it produces VARCHAR, it should still take the slow path because these aren't `builtin.str` objects
