### ISSUE TITLE
Compression Not Enabled for UUID / Validity

### ISSUE THREAD

**Issue by nicosuave** [duckdb/duckdb#7020]
### What happens?

More storage space utilized than anticipated for UUID / Validity types. See [related discussion from Discord](https://discord.com/channels/909674491309850675/1082335534799650959/1082360795779833927).

### To Reproduce

```sql
.open 'uuids.db'

create table five_million_uuids (
    id varchar(36) primary key,
    random_uuid uuid
);

insert into five_million_uuids (id, random_uuid)
select generated_uuid::varchar, generated_uuid
from (
  select uuid() as generated_uuid
  from generate_series(1, 5000000)
) as uuids;
     
select count(*) from five_million_uuids;

copy (select * from five_million_uuids) to 'uuids.parquet' (format parquet);

-- compare file size of parquet @ ./uuids.parquet against duckdb database @ ./uuids.db
```

### OS:

OS X

### DuckDB Version:

v0.7.1

### DuckDB Client:

CLI

### Full Name:

Nico Ritschel

### Affiliation:

Ant Money

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report! The issue here is actually the `PRIMARY KEY` index taking up extra space. Defining a `PRIMARY KEY` constraint [creates an additional index structure](https://duckdb.org/docs/sql/indexes), the `ART`, to enforce uniqueness of values. Parquet files do not support such index structures, and as such only contain the actual data.

Also note that while indeed we do not support compression on UUID columns currently, effectively compressing *randomly generated UUID values* is not possible. Compressing UUIDs would only be effective if they were stored in a sorted order or similarly clustered. Compression works by finding patterns in the data, and random data does not have any patterns, so compression is not effective in this scenario.

Here are the file sizes in the various configurations:

### UUID Column Only
```sql
create table five_million_uuids (
    random_uuid uuid
);

insert into five_million_uuids (random_uuid)
select generated_uuid
from (
  select uuid() as generated_uuid
  from generate_series(1, 5000000)
) as uuids;
     
select count(*) from five_million_uuids;

copy (select * from five_million_uuids) to 'uuid.parquet' (format parquet);
```

|     File     | Size |
|--------------|------|
| uuid.parquet | 76MB |
| uuid.db      | 82MB |

### UUID + VARCHAR

```sql
create table five_million_uuids (
    id varchar(36),
    random_uuid uuid
);

insert into five_million_uuids (id, random_uuid)
select generated_uuid::varchar, generated_uuid
from (
  select uuid() as generated_uuid
  from generate_series(1, 5000000)
) as uuids;
     
select count(*) from five_million_uuids;

copy (select * from five_million_uuids) to 'uuid.parquet' (format parquet);
```

|     File     | Size  |
|--------------|-------|
| uuid.parquet | 248MB |
| uuid.db      | 205MB |

### UUID + VARCHAR + Primary Key
###### Note this is not comparable because the DB file contains an extra index that is not present in the Parquet file.

|     File     | Size  |
|--------------|-------|
| uuid.parquet | 248MB |
| uuid.db      | 591MB |

#### Primary Key Space Usage

We do have an open issue on primary key space usage here #6667, and some ideas on how to reduce the space impact, but in general there will always be a significant storage overhead when storing an auxiliary index structure. An auxiliary index structure essentially creates a mapping of `[key -> row_number]` pairs. Particularly when data is unsorted this is hard to compress as effectively as the original data.

**Comment by orzom411** [comment]
An observation, parquet files and order by:

Given from the above example:

596,652,032 uuids.duckdb
260,470,958 uuids.parquet
244,053,613 uuids_order1.parquet

The latter created via:

`copy (select * from five_million_uuids order by 1) to 'uuids_order1.parquet' (format parquet);`

Compression, in case you were wondering as I was, gives us:

177,811,998 uuids_order1gz.parquet

Via:
copy (select * from five_million_uuids order by 1) to 'uuids_order1gz.parquet' (format parquet, compression gzip);
