### ISSUE TITLE
Unexpected result when take subquery as operand

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#7044]
### What happens?

consider the following program:

```
CREATE TABLE t0(c0 INT2);
CREATE TABLE t1(c0 BOOL);

INSERT INTO t1(c0) VALUES ((true));

INSERT INTO t0(c0) VALUES ((1));

SELECT (t1.rowid) AS c0 FROM t1 WHERE (('278898106'))>=((1));  -- 0

SELECT (t1.rowid) AS c0 FROM t1 WHERE (('278898106'))>=(SELECT t0.c0 AS c0 FROM t0, t1 WHERE t0.c0);  -- 0 rows
```

As there is only `1` in `t0`, so the second query is equivalent to the first one, but the second query has empty result.

I put the condition of second query to the output, like `SELECT (('278898106'))>=(SELECT t0.c0 AS c0 FROM t0, t1 WHERE t0.c0) FROM t1;`. This query triggers an error: `Error: near line 29: Conversion Error: Could not convert string '278898106' to INT16`.

### To Reproduce

I build DuckDB from the last commit version (https://github.com/duckdb/duckdb/commit/d8b4c8311f0ac97b5352d6b4ba2c6c45590ed1dd), and run the program with CLI.

### OS:

ubuntu 22.04

### DuckDB Version:

commit version d8b4c83

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
Interesting... was playing around with reproducing more minimally. The above case boils down to:
```
SELECT True where '32768' > 1; -- True
SELECT True where '32768' > (select 1); -- True
SELECT True where 32768 > 1::smallint; -- True

SELECT True where '32768' > (select 1::smallint) -- empty set
SELECT True where '32768' > 1::smallint; -- ConversionException: Conversion Error: Could not convert string '32768' to INT16
```

Why ConversionException? Because the original query had quotes around the numbers, making them varchars. 
Why 32768? Because 32767 is maxvalue for [smallint](https://duckdb.org/docs/sql/data_types/numeric.html)
Why smallint? Because INT2 == SMALLINT, which is the datatype of t0.c0. 

No idea why query 4 behaves differently than 5 though... I just thought this was an interesting peculiarity.
