### ISSUE TITLE
incorrect result with except operator

### ISSUE THREAD

**Issue by l0n3star** [duckdb/duckdb#7228]
### What happens?

I'm not getting the expected result when using except set operator on 2 tables.  I expect 1 row but get 31558.

### To Reproduce

I've attached [docs.tar.gz](https://github.com/duckdb/duckdb/files/11315113/docs.tar.gz) which has 2 files:  `lines1.json` and `lines2.json`.  `lines1.json` has 1 json object that `lines2.json` doesn't have, which is:

`{"with JSON":"there are no reserved field names","click":"to edit"}`

otherwise all other json objects are the same.  

### To reproduce the issue:

a.  `create table t1(j json);`
b.  `create table t2(j json);`
c.  `insert into t1 select * from read_ndjson_objects('lines1.json');`
d.  `insert into t2 select * from read_ndjson_objects('lines2.json');`
e.  following query should return 1 row:

```
select * from t1 
except 
select * from t2;
```

but instead I get 31558 rows.

### OS:

macOS 11.7.4 using docker, container has ubuntu 20.04.4 LTS

### DuckDB Version:

v0.7.2-dev2430 f429595834

### DuckDB Client:

CLI

### Full Name:

Hitesh Walia

### Affiliation:

Couchbase

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paultiq** [comment]
(I'm just another end-user here, but just my observations):

The JSON objects differ in order, but not value:
`{"geo":{"alt":1799,"lat":47.8383333,"lon":-90.3829444},"id":6849,"airportname":"Grand Marais Cook County Airport","city":"Grand Marais","icao":"KCKC","type":"airport","tz":"America/Chicago","country":"United States","faa":"GRM"}`
vs
`{"airportname":"Grand Marais Cook County Airport","city":"Grand Marais","id":6849,"type":"airport","tz":"America/Chicago","country":"United States","faa":"GRM","geo":{"alt":1799,"lat":47.8383333,"lon":-90.3829444},"icao":"KCKC"}`

Which is similar to this: 
```
with t1 as (select '{"id": 1, "test": 2}'::json as j),
	t2 as (select '{"test": 2, "id": 1}'::json as k)
  select j=k, j, k from t1, t2
```

** it's an interesting question because JSON is unordered (RFC 4627). 
** I tried to check in postgres but it doesn't support json equality checks: https://dbfiddle.uk/UJgxqtzT

**Comment by l0n3star** [comment]
As an aside, it works in snowflake:

```
select * from TRAVEL_DATA 
except 
select * from TRAVEL_DATA_2 ;
+----------------------------------------------------+                          
| SRC                                                |
|----------------------------------------------------|
| {                                                  |
|   "click": "to edit",                              |
|   "with JSON": "there are no reserved field names" |
| }                                                  |
+----------------------------------------------------+
```

**Comment by Mytherin** [comment]
Thanks for the report! JSON objects use string equality currently, so this is the expected result for any operation where a comparison between unordered JSON objects is performed.
