### ISSUE TITLE
Mismatched / non-existent struct key is ignored on INSERT

### ISSUE THREAD

**Issue by davetapley** [duckdb/duckdb#7303]
### What happens?

I had a bug with a typo in my `.sql`, which wasn't surfaced during my tests
because duckdb didn't complain about a mismatched key in a struct.

Not disastrous, but not a _great_ developer experience.

I'm _guessing_ it's because `struct` only cares about its arity and types (and not the key names), but [the docs](https://duckdb.org/docs/sql/data_types/struct) do imply it's a bit more strict:

> Each row in the STRUCT column must have the same keys.

### To Reproduce

Observe `ignoreme` is ignored:

```sql
CREATE TABLE
foo (
    bar struct(pip int)
);

INSERT INTO foo (bar) VALUES ({'ignoreme': 3});

SELECT * from foo;
```

```
┌─────────────────────┐
│         bar         │
│ struct(pip integer) │
├─────────────────────┤
│ {'pip': 3}          │
└─────────────────────┘
```

### OS:

Linux

### DuckDB Version:

v0.7.2-dev2699 199c0211c7

### DuckDB Client:

CLI

### Full Name:

Dave Tapley

### Affiliation:

JE Fuller

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Maxxen** [comment]
I don't think the docs are _techncially_ wrong here, a struct column does store entries with the same keys. I think that the reason why you can insert a struct with different key names because structs are castable to other structs as long as their "shape" is the same. It's actually more lenient than that, the members themselves can also differ in type as long as they are individually castable to the corresponding target member. E.g `INTEGER` is castable to both `DOUBLE` and `VARCHAR`:
```sql
CREATE TABLE t1 (s STRUCT(d DOUBLE, v VARCHAR)); 
INSERT INTO t1 VALUES ({i: 20, v: 'foobar'}), ({i: 20, v: 50});
```
```
┌─────────────────────────────┐
│              s              │
│ struct(d double, v varchar) │
├─────────────────────────────┤
│ {'d': 20.0, 'v': foobar}    │
│ {'d': 20.0, 'v': 50}        │
└─────────────────────────────┘
```

**Comment by Tishj** [comment]
I do agree that it makes sense to do a case-insensitive compare for the struct key names, I know for sure this will break some internal tests/logic but nothing major.

**Comment by Mytherin** [comment]
This is the same issue as #3884, as @Maxxen structs are implicitly castable to other structs even if names mismatch.

I'm not opposed to changing this - the main reason this is there is for compatibility with Postgres' `ROW` function, which allows creation of structs without names.

```sql
CREATE TABLE t1 (s STRUCT(d DOUBLE, v VARCHAR)); 
INSERT INTO t1 VALUES (ROW(0.5, 'hello'));
```

Row creates structs with names `v1`, `v2`, ... which then get auto-casted.

```sql
D SELECT ROW(0.5, 'hello');
┌─────────────────────────────────────┐
│       main.row(0.5, 'hello')        │
│ struct(v1 decimal(2,1), v2 varchar) │
├─────────────────────────────────────┤
│ {'v1': 0.5, 'v2': hello}            │
└─────────────────────────────────────┘
```

We could add support for unnamed structs which can be constructed with `ROW` and auto-casted to any struct, that would be a cleaner solution.

**Comment by Mytherin** [comment]
Yes agreed, let's try to include this in the next release

**Comment by maiadegraaf** [comment]
@taniabogatsch and I discussed a solution for this. In `struct_pack.cpp::StuctPackBind` we use an `if-else` to distinguish the `ROW` function, here we could set the return type to `UNNAMED_STRUCT` which we can later detect in `struct_cast.cpp:: StructToStructCast`.  This way we would be able to prevent implicit casts between mismatching keys, unless it is an `UNNAMED_STRUCT`. `UNNAMED_STRUCT` and `STRUCT` would otherwise have identical behavior.
