### ISSUE TITLE
Struct entry names are case-insensitive

### ISSUE THREAD

**Issue by mengyazhu96** [duckdb/duckdb#7450]
### What happens?

```
D select to_json({'material':'material','Material':'Material'});
Error: Binder Error: Duplicate struct entry name "Material"
```

I would expect this _not_ to error because the struct entry names are different capitalizations.

### To Reproduce

```
select to_json({'material':'material','Material':'Material'});
```

### OS:

macOS Ventura 13.3.1

### DuckDB Version:

0.7.1

### DuckDB Client:

DuckDB CLI

### Full Name:

Jessica Zhu

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Alex-Monahan** [comment]
Hello! I believe that is the currently expected behavior. It's possible that it could be changed or maybe a pragma flag could be added?
https://github.com/duckdb/duckdb/pull/2659

**Comment by mengyazhu96** [comment]
That's highly unintuitive to me, and it's also not in the [struct docs](https://duckdb.org/docs/sql/data_types/struct.html)! Postgres also treats JSONB keys as case-sensitive.

**Comment by Mytherin** [comment]
I agree that it should be documented - but it is intended behavior. Struct keys are identifiers, just like tables and columns, and identifiers are case insensitive as per the SQL standard. Treating struct keys as special identifiers that are suddenly case sensitive will cause more problems. You will then not be able to turn arbitrary structs into columns, for example.

JSON keys are not case insensitive in DuckDB either. Your example fails because of the struct construction - JSON is unrelated to this.

**Comment by lnkuiper** [comment]
Duplicate of #6722

**Comment by mengyazhu96** [comment]
Okay this is good to know! Thank you
