### ISSUE TITLE
Raw binary data

### ISSUE THREAD

**Issue by prashantharaonr** [duckdb/duckdb#751]
Is it possible to insert raw binary data like unsigned or signed int of 8/16/32/64 bit sizes? Is there a way to handle endianness interpretations and conversions?

**Comment by Mytherin** [comment]
Inserting data from raw binary files (I assume you mean a file containing e.g. only 4-byte integers?) is currently not yet supported. Happy to review a PR :)

One possibility of loading this would be to load the data right now would be to write a small C++ program and using the `Appender` class to add data to the system.

**Comment by prashantharaonr** [comment]
In the C++ program should I convert that into Int data and to the requires endianness and then append? If so it will be overhead for my use case as the conversion consumes lot of time. Actually the selects I do thereafter should also operate on the binary data types so that the conversion overhead can be avoided. 
I foresee this as a feature that can open up DuckDb usage in an embedded world.

**Comment by Mytherin** [comment]
I agree this would be a useful feature, and it should be rather simple to implement. I will take a look at implementing it when I have time. I also think we should have better support for user-defined table functions, that would simplify data loading from non-standard files.

**Comment by Mytherin** [comment]
Yes, that would should indeed work as such, but depending on how you are using DuckDB there might be better ways that are available right now.

* If you have your data stored in-memory and have access to the C or C++ API's, the `Appender` interface will be much easier to work with and will be faster as the data can be written to DuckDB directly without first having to write a file to disk. 
* If you have your data stored in e.g. a Pandas DataFrame or an R DataFrame we can directly read from those data structures and append.
* If you can convert your data to Parquet somehow, that will have similar performance as raw binary files.
* For other API's, prepared statements are also available that will avoid the to and from string conversion. Prepared statements will likely perform worse than batch binary file insertions because of the many round-trips to and from the database system, however.

Which API are you using and where are you getting your data from?

**Comment by emmenlau** [comment]
Thanks a lot @Mytherin , I'm slightly "shocked" how easy this seems to be in DuckDB!

Our use case is a C++ application and I'd be delighted to use a C++ API with as little overhead as possible. Our data is in-memory!

I will take a look at `Appender` and how it works. Basically, I'd be more than happy if I can dump such large blocks of binary, in-memory data to a new or existing table. If I understand correctly, this is exactly what `Appender` does?

**Comment by emmenlau** [comment]
> Which API are you using and where are you getting your data from?

Actually I've just discovered DuckDB today and started reading the docs :-) . I have not even started the installation. Your Linux build seems very straightforward so I'll definitely give it a go!

**Comment by Mytherin** [comment]
Yes, exactly. The documentation for the Appender can be found [here](https://duckdb.org/docs/data/appender).

**Comment by emmenlau** [comment]
This is awesome, exactly what we need....
