### ISSUE TITLE
`DuckDBPyRelation.close()` takes as long as the query itself

### ISSUE THREAD

**Issue by dsmilkov** [duckdb/duckdb#7566]
### What happens?

Closing a relational query (`query.close()`) takes as long as the execution of the query itself (`query.df()`).

### To Reproduce

```py
con = duckdb.connect(database=':memory:').cursor()
query = con.from_df(df)
query.filter(...)
query.limit(...)
query.df() # Takes 800ms.
query.close() # PROBLEM: Takes another 800ms.
con.close() # NO PROBLEM: Takes <1ms.
```

### OS:

Mac OS Ventura

### DuckDB Version:

0.7.1

### DuckDB Client:

0.7.1

### Full Name:

Daniel Smilkov

### Affiliation:

Lilac AI Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
What happens here is that `df` creates and consumes the result.
In `close` we check if there is a result, if there isn't we execute the relation.

I believe this is done because relations can also be made on plans that have side-effects, so we execute the relation for those side effects in case the relation was created but not explicitly consumed.

That's my suspicion, I'll verify it soon
