### ISSUE TITLE
summarize fails on blob columns

### ISSUE THREAD

**Issue by antonycourtney** [duckdb/duckdb#7902]
### What happens?

Attempt to run `summarize` on a query with Blob columns fails with a binder error.

### To Reproduce

The minimal repro is:

```sql
summarize select * from test_all_types();
```

This fails with the error:

```
Error: Binder Error: No function matches the given name and argument types 'approx_count_distinct(BLOB)'. [...]
```

Have verified that this occurs in both the native CLI and DuckDb WASM.

### OS:

MacOS

### DuckDB Version:

v0.8.0 e8e4cea5ec

### DuckDB Client:

CLI (DuckDb shell) and DuckDb WASM

### Full Name:

Antony Courtney

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by antonycourtney** [comment]
Also confirmed this is happening in the latest nightly build (`v0.8.1-dev416 9d5158ccd2`)

**Comment by carlopi** [comment]
Hi @antonycourtney, I can confirm this reproduce, reduced repro is `summarize select blob from test_all_types();`.

I am not sure of the rational here, since to some extent BLOBs and VARCHARs are 'the same' they should probably also behave the same here, and applying this patch does apparently solve the problem:
```git
--- a/src/core_functions/aggregate/distributive/approx_count.cpp
+++ b/src/core_functions/aggregate/distributive/approx_count.cpp
@@ -136,6 +136,7 @@ AggregateFunctionSet ApproxCountDistinctFun::GetFunctions() {
        approx_count.AddFunction(GetApproxCountDistinctFunction(LogicalType::FLOAT));
        approx_count.AddFunction(GetApproxCountDistinctFunction(LogicalType::DOUBLE));
        approx_count.AddFunction(GetApproxCountDistinctFunction(LogicalType::VARCHAR));
+       approx_count.AddFunction(GetApproxCountDistinctFunction(LogicalType::BLOB));
        approx_count.AddFunction(GetApproxCountDistinctFunction(LogicalType::TIMESTAMP));
        approx_count.AddFunction(GetApproxCountDistinctFunction(LogicalType::TIMESTAMP_TZ));
        return approx_count;
```

Once done that (+ adding the test case + testing that there are no unintended changes in behaviour) this could potentially be a PR, feel free to send it, but I have to stress I miss some context to be able to make an appropriate judgement.

Also note that even this line still has `summarize select * from test_all_types();` failing due to a separate issue who's repro is:
```
D summarize select date from test_all_types();
Error: Conversion Error: Type INT32 with value 5877642-06-25 (BC) can't be cast to the destination type INT64
```
(This looks like a completely separate problem tied potentially to the very wide date, feel free to open another issue)
