### ISSUE TITLE
Cannot match timestamp[us] type used in Delta (from pyspark)

### ISSUE THREAD

**Issue by watfordkcf** [duckdb/duckdb#7934]
### What happens?

I'm writing a query against a delta table with `timestamp[us] not null` time fields loaded as a PyArrow dataset. Using any timestamp related WHERE clause causes the following error:
```
duckdb.InvalidInputException: Invalid Input Error: arrow_scan: get_next failed(): NotImplemented: Function 'equal' has no kernel matching input types (timestamp[us], timestamp[ms, tz=UTC])
```

### To Reproduce

Very rough PySpark I used to create the incoming delta table:
```python
schema = StructType([
    StructField("collection_time", TimestampType(), nullable=False),
    ...
])

(
    DeltaTable.createIfNotExists(spark)
    .addColumns(schema)
    .tableName(table_name)
    .location(table_name)
    .execute()
)

(
    source_df.select([
        current_timestamp().alias("collection_time"),
        col("metrics.*")
    ])
    .format("delta")
    .mode("append")
    .save(table_name)
)
```
When loaded by deltatable and converted to a PyArrow dataset the table looks like so:
```
>>> dt = DeltaTable(path)
>>> ds = dt.to_pyarrow_dataset()
>>> duckdb.register('test', ds)
>>> ds.schema
collection_time: timestamp[us] not null
...
```
The first query that failed looks like so:
```sql
SELECT *
  FROM test
 WHERE collection_time BETWEEN '2023-06-12 00:00:00' AND '2023-06-13 00:00:00'
 ORDER BY collection_time ASC
```
I've tried casting as a timestamp:
```sql
SELECT *
  FROM test
 WHERE CAST(collection_time AS timestamp) BETWEEN '2023-06-12 00:00:00' AND '2023-06-13 00:00:00'
 ORDER BY collection_time ASC
```
I've tried making a timestamp:
```sql
SELECT *
  FROM test
 WHERE collection_time BETWEEN make_timestamp(2023, 6, 12, 0, 0, 0) AND make_timestamp(2023, 6, 13, 0, 0, 0)
 ORDER BY collection_time ASC
```
The only thing that consistently works (though I doubt partitions could be gleaned from this):
```sql
SELECT *
  FROM test
 WHERE epoch(collection_time) BETWEEN epoch('2023-06-12 00:00:00') AND epoch('2023-06-13 00:00:00')
 ORDER BY collection_time ASC
```
For the duckdb side:
```sh
$ pip list
Package         Version
--------------- -------
deltalake       0.10.0
duckdb          0.8.1
kafka-python    2.0.2
numpy           1.24.3
pandas          2.0.2
pip             23.1.2
pyarrow         12.0.0
python-dateutil 2.8.2
pytz            2023.3
setuptools      65.5.0
six             1.16.0
tzdata          2023.3
```

### OS:

arm64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Christopher Watford

### Affiliation:

christopher.watford@kcftech.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jwills** [comment]
Hey I'm running into a similar/related issue where I get back different `datetime` objects from the Python APIs when I do queries like `select now()`:

- the regular DBAPI returns a timezone-unaware `datetime` object (i.e., the `tzinfo` field is `None`),
- the Arrow APIs (e.g., `read_record_batch`) returns a timezone-aware `datetime` object with the `tzinfo` field set to `timezone.UTC`.

I suspect this commit changed the default value for the arrow conversion but it wasn't totally obvious how to change it back; maybe just a blank string for the TZ instead of "UTC" inside of `arrow_options.hpp`? https://github.com/duckdb/duckdb/commit/aa0165b2e171b6192eb1a490ff75a272455950b6#diff-55d9802bbadfc9ce4409c1fda317a5dbb36abfd918eead518a237d8f78d59584

**Comment by jwills** [comment]
(Note that this changed between 0.8.0 and 0.8.1), hence my suspicion of that commit)

**Comment by pdet** [comment]
> 
now() returns a timezone-aware timestamp
```
select now();
┌────────────────────────────┐
│           now()            │
│  timestamp with time zone  │
├────────────────────────────┤
│ 2023-06-21 09:12:44.399+00 │
└────────────────────────────┘
```

I believe the DBAPI must be updated to also return a tzinfo then.

**Comment by Tishj** [comment]
Sounds like an issue we fixed recently

**Comment by Tishj** [comment]
Since you haven't produced a reproduction example I'll spell out the issue we fixed:
Arrow supports us, ns, ms and s precisions for timestamp_tz, we only support us.

When we scan an Arrow schema, we turn this into a type we support, and the constant used in a filter gets cast to that type.

When a filter is produced and we're scanning a pyarrow object, we push the filter down into the scanner, converting our filter into a pyarrow filter - since we created the constant as a certain type, this is the type of the scalar we create in the filter.

That causes pyarrow to complain that it cant compare timestamp_tz(us) against timestamp_tz(other precision)
So we now create the pyarrow scalar from the original type - not the type we converted it into it.
