### ISSUE TITLE
Non-deterministic results when deterministic results are expected

### ISSUE THREAD

**Issue by ablack3** [duckdb/duckdb#8041]
### What happens?

I have a query that seems to produce unexpected results some of the time. I'm using the R API.

### To Reproduce

``` r
library(dplyr, warn.conflicts = F)

raw_data <- tibble::tribble(
  ~person_id,  ~start_date,    ~end_date,
  46,         "1991-11-29", "1991-11-29",
  46,         "1991-11-29", "2006-01-27",
  46,         "1994-12-16", "1994-12-16"
) %>% dplyr::mutate(dplyr::across(dplyr::matches("date"), as.Date))

con <- DBI::dbConnect(duckdb::duckdb())

DBI::dbWriteTable(con, "raw_data", raw_data)

test_query <- function(x) {
  result <- DBI::dbGetQuery(con, "
  with cteEndDates (person_id, end_date) AS
  (
    SELECT
        person_id,
        event_date as end_date
    FROM
    (
        SELECT
            person_id,
            event_date,
            SUM(event_type) OVER (PARTITION BY person_id ORDER BY event_date ROWS UNBOUNDED PRECEDING) AS interval_status
        FROM
        (
            SELECT
                person_id,
                start_date AS event_date,
                -1 AS event_type
            FROM raw_data

            UNION ALL

            SELECT
                person_id,
                end_date AS event_date,
                1 AS event_type
            FROM raw_data
        ) RAWDATA
    ) e
    WHERE interval_status = 0
  ),
  cteEnds (person_id, start_date, end_date) AS
  (
    SELECT
        c.person_id,
        c.start_date,
        MIN(e.end_date) AS end_date
    FROM raw_data c
    INNER JOIN cteEndDates e ON c.person_id = e.person_id
        AND e.end_date >= c.start_date
    GROUP BY
        c.person_id,
        c.start_date
  )
  select person_id, min(start_date) as start_date, end_date
  from cteEnds
  group by person_id, end_date
  ;") %>% dplyr::tibble()

  return(result)
}

# run the test 1000 times
results <- tibble(run = 1:1000, df = purrr::map(1:1000, test_query))

# summarize test results
summary <- results %>%
  count(df)

summary
#> # A tibble: 2 × 2
#>   df                   n
#>   <list>           <int>
#> 1 <tibble [2 × 3]>   207
#> 2 <tibble [1 × 3]>   793

summary$df[[1]]
#> # A tibble: 2 × 3
#>   person_id start_date end_date  
#>       <dbl> <date>     <date>    
#> 1        46 1991-11-29 1991-11-29
#> 2        46 1994-12-16 1994-12-16

summary$df[[2]]
#> # A tibble: 1 × 3
#>   person_id start_date end_date  
#>       <dbl> <date>     <date>    
#> 1        46 1991-11-29 2006-01-27

packageVersion("duckdb")
#> [1] '0.8.1'
```

<sup>Created on 2023-06-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### OS:

Mac OS 12.6

### DuckDB Version:

0.8.1

### DuckDB Client:

R

### Full Name:

Adam Black

### Affiliation:

Odysseus Data Services

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by chrisknoll** [comment]
Hi, I'll just chime in here because I don't think it's a bug in duckdb, logically, the results of the query can be non-deterministic:

this sql: `SUM(event_type) OVER (PARTITION BY person_id ORDER BY event_date ROWS UNBOUNDED PRECEDING) AS interval_status` could result in the following rows:

In one order:

|person_id|event_date|event_type|
|-|-|-|
|1}|01/01/2010|-1|
|1}|01/01/2010|-1|
|1}|01/01/2010|+1|
|1}|01/01/2010|+1|

In another order:

|person_id|event_date|event_type|
|-|-|-|
|1}|01/01/2010|-1|
|1}|01/01/2010|+1|
|1}|01/01/2010|-1|
|1}|01/01/2010|+1|

Adding the `SUM(event_type) OVER (PARTITION BY person_id ORDER BY event_date ROWS UNBOUNDED PRECEDING)`

From first order:
|person_id|event_date|event_type|sum()|
|-|-|-|-|
|1}|01/01/2010|-1|-1
|1}|01/01/2010|-1|-2
|1}|01/01/2010|+1|-1
|1}|01/01/2010|+1|0

From second order

|person_id|event_date|event_type|sum()|
|-|-|-|-|
|1}|01/01/2010|-1|-1
|1}|01/01/2010|+1|0
|1}|01/01/2010|-1|-1
|1}|01/01/2010|+1|0

So, in the usecase that spawned this issue, we need to sort on the event_type to make it determinstic:

```
SUM(event_type) OVER (PARTITION BY person_id ORDER BY event_date, event_type ROWS UNBOUNDED PRECEDING)
```

One reason why this might work consistently in other platforms is underlying indexes on the table may cause partitions to be sorted the same way by default, but the solution here is to be explicit.

**Comment by hawkfish** [comment]
Yes if there are duplicate values in the `OVER` ordering clause then the result is not well-defined. Is that the case?

**Comment by chrisknoll** [comment]
Yes.  The solution would be to add the necessary columps to have a determined result order.
