### ISSUE TITLE
Databases return `std::bad_alloc` when attempting to open

### ISSUE THREAD

**Issue by pcjentsch** [duckdb/duckdb#8065]
### What happens?

We are using duckdb databases to store and compute client data in production.

On rare occasions, we notice that they become corrupted and are unable to be read or connected to.

### To Reproduce

The duckdb CLI tool and the duckdb python library return the following error when we attempt to connect to one of these databases.

```

~> duckdb error_db.duckdb 
Error: unable to open database "error_db.duckdb": Invalid Error: std::bad_alloc

```

```

Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> duckdb.connect('error_db.duckdb')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError: std::bad_alloc

```

We can't reproduce what causes this, but I do have a DB file with this issue. I can't share the data publicly, but I have permission to share the database privately with a duckdb developer. 

We were wondering if you would have any insight on how this occurs, and how to recover databases that have this problem.

The submission form asks if I have tried to reproduce this on the latest master branch, but old databases cannot be opened with newer versions of duckdb.

Thank you!

### OS:

Linux 5.15.0-1037-aws x86_64

### DuckDB Version:

 v0.6.1

### DuckDB Client:

python, CLI

### Full Name:

Peter Jentsch

### Affiliation:

Liquid Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment]
Thanks for the report!

We are not currently fixing issues in older DuckDB versions. The storage has also evolved significantly in the last few releases, so it is very possible this issue has already been fixed in the latest version. As such, I don't think it is very productive to try and investigate the issue within an old database file directly.

If you could create a reproducible example that fails with 0.6.1 we would be happy to take a look and verify that the issue is fixed in the latest version (or fix it if it is not).

**Comment by Tishj** [comment]
> If you could create a reproducible example that fails with 0.6.1

I believe he meant 0.8.1 as that is currently the latest version, if that wasn't obvious :)
