### ISSUE TITLE
create index causes SIGBUS (Misaligned address error) on MacARM

### ISSUE THREAD

**Issue by karlseguin** [duckdb/duckdb#8066]
### What happens?

Crash when creating an index. Couldn't reproduce on Linux, but happens reliably on an m2.

Doesn't happen when in-memory. Doesn't happen if the column is an integer (does happen if its a timestamp or a date). Seems to only happen reliably with a row count > 215 000..but this seems inconsistent and might only be random

### To Reproduce

```
duckdb test.db
v0.8.1 6536a77232
Enter ".help" for usage hints.
D create table t as select now() as d from generate_series(1, 218165);
D create index i on t(d);
Job 1, 'duckdb test.db' terminated by signal SIGBUS (Misaligned address error)
```

### OS:

aarch64

### DuckDB Version:

0.8.1

### DuckDB Client:

-

### Full Name:

Karl Seguin

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by carlopi** [comment]
Hi @karlseguin!
Thanks for the bug report, I do reproduce also on latest master, apparently something to do with ART deallocations, moving on to @taniabogatsch!

**Comment by taniabogatsch** [comment]
I looked into this. It happens because we reach recursion-depth limits. With the ART being tree-based, we used recursive implementations of many functions for simplicity. This backfires here because all elements in the table have the same key. I am now changing many parts to iterative implementations, which fixes the issue. These changes should also improve performance, as they decrease the function-call overhead.
