### ISSUE TITLE
DuckDB access_mode Setting Not Taking Effect

### ISSUE THREAD

**Issue by ameijer** [duckdb/duckdb#8397]
### What happens?

Hi DuckDB Friends, 

Having a bit of trouble here getting settings to persist. We follow the documentation to set access_mode (and then check the setting to be sure it took), however, we are still able to write to the database. Check out the small SQL script that reproduces this I included in the section below. Perhaps we are not using this properly? 

cc @Sean-Holcomb @michaelmdresser

### To Reproduce

1. create the file `duck_access_test.sql` with the following contents: 
```
CREATE TABLE test (myNum int);
SET access_mode='read_only';

INSERT INTO test VALUES (1);
SELECT * FROM test;

SELECT current_setting('access_mode');
```

2. Execute this via `duckdb -c '.read duck_access_test.sql '`

We expect to have some sort of an error, or at least for the value to not persist in the table. However, the script seems to successfully insert the value. Here is the output we are seeing: 
```
┌───────┐
 │ myNum              │
 │ int32                 │
├───────┤
 │     1                    │
└───────┘
┌────────────────────────────────┐
 │ current_setting('access_mode')                                                             │
 │            varchar                                                                                           │
├────────────────────────────────┤
 │ read_only                                                                                                  │
└────────────────────────────────┘
```

### OS:

Mac OSX aarch64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

duckdb CLI

### Full Name:

Alex Meijer

### Affiliation:

Kubecost

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment]
Thanks for raising the issue, this does appear to not do what it's supposed to.
Maybe this got broken when we introduced attach database functionality

**Comment by Mytherin** [comment]
Thanks for the report!

Currently `access_mode` must be set while opening a database file. The setting takes effect upon opening of the file and cannot be changed after a database has already been opened. The issue here is actually that `SET access_mode='read_only';` does not throw an exception. `access_mode` is unique in that regard (all other settings can be changed at run-time) - so this should also be better documented.

How to open a read-only connection depends on the API used. For the CLI it is using the `-readonly` switch:

```sql
$ > duckdb file.db
D create table integers(i int);

$> duckdb -readonly file.db
D insert into integers values (42);
Error: Invalid Error: Cannot execute statement of type "INSERT" on database "x" which is attached in read-only mode!
```

Other APIs generally have a `key/value` dictionary that can be passed while connecting, e.g. in Python:

```py
import duckdb
duckdb.connect('file.db', config={'access_mode': 'read_only'})
```

Alternatively, the setting can also be set when attaching a new database using `ATTACH`:

```bash
$ > duckdb
D ATTACH 'file.db' (READ_ONLY);
D INSERT INTO file.integers VALUES (42);
Error: Invalid Error: Cannot execute statement of type "INSERT" on database "file" which is attached in read-only mode!
```

There is no current way of "downgrading" an already attached database (i.e. going from a read-write database to a read-only database).

**Comment by hannes** [comment]
Hey @ameijer could you please ping me at hannes@duckdblabs.com ? Thanks!

**Comment by ameijer** [comment]
thanks all, the suggestion from @Mytherin works well. @hannes , I emailed you just now.

**Comment by dufferzafar** [comment]
> @Mytherin Does access_mode setting work on in-memory databases as well? I think I saw this mentioned somewhere, but can't find it.

I guess i realised the answer after thinking about it a bit, since inmem dbs start empty, it won't make sense for access_mode setting on start either.
