### ISSUE TITLE
Unimplemented type for cast does not indicate offending column

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb#8485]
### What happens?

When an error like `Error: Conversion Error: Unimplemented type for cast` is thrown, the offending column is not indicated. In the spirit of friendlier SQL, would it be possible to include the column name or position of the error in some way?

### To Reproduce

```sql
select 
0.25::time as time_column, 
'woot'::int as int_column;
```
`Error: Conversion Error: Unimplemented type for cast (DECIMAL(3,2) -> TIME)`

### OS:

MacOS

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

Alex Monahan

### Affiliation:

MotherDuck and DuckDB Labs

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
Hmm that would be nice, but since this can happen anywhere in the pipeline, retracing what column the offending Vector belongs to can be tricky, and sometimes it could not even be part of a column at all and just be an intermediate result of an expression.

Curious to hear what Mark thinks, but I assume this would be non-trivial to implement

**Comment by Alex-Monahan** [comment]
Hmmm, true! Would a SQL query position indicator be any easier?

**Comment by szarnyasg** [comment]
We discussed this internally and decided to close it as it would be very complex to tackle.
