### ISSUE TITLE
IS NOT DISTINCT FROM produces conversion error when = does not

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb#8753]
### What happens?

``` sql
D create table foo as select * from values (4, null), (5, null) t(a, b);
D create table bar as select * from values (4, 'hi'), (6, null) t(a, b);
D select * from bar left join foo on bar.b = foo.b;
┌───────┬─────────┬───────┬───────┐
│   a   │    b    │   a   │   b   │
│ int32 │ varchar │ int32 │ int32 │
├───────┼─────────┼───────┼───────┤
│     4 │ hi      │       │       │
│     6 │         │       │       │
└───────┴─────────┴───────┴───────┘
D select * from bar left join foo on bar.b is not distinct from foo.b;
Error: Conversion Error: Could not convert string 'hi' to INT32
```

Note `foo.b` is being inferred as `INT32` here

I would expect both queries to run without an error (or possibly for both queries to error). Alternatively I'd expect this behavior difference to be documented on https://duckdb.org/docs/sql/expressions/comparison_operators.html

### To Reproduce

Run the above in a shell

### OS:

OS X

### DuckDB Version:

v0.8.2-dev2842

### DuckDB Client:

shell

### Full Name:

Carl Jackson

### Affiliation:

Watershed

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by zenazn** [comment]
possibly related:
```sql
D select * from bar left join foo on foo.b is not distinct from bar.b;
Error: Conversion Error: Could not convert string 'hi' to INT32
D select * from bar left join foo on foo.b is not distinct from bar.b or foo.b is null;
┌───────┬─────────┬───────┬───────┐
│   a   │    b    │   a   │   b   │
│ int32 │ varchar │ int32 │ int32 │
├───────┼─────────┼───────┼───────┤
│     4 │ hi      │     4 │       │
│     6 │         │     4 │       │
│     4 │ hi      │     5 │       │
│     6 │         │     5 │       │
└───────┴─────────┴───────┴───────┘
```

I would expect either both of these expressions to error, or neither to error

**Comment by Tmonster** [comment]
So this isn't a bug. There is an optimization happening when the hash join is executed that removes the error for the `=` case. In the `=` case, `NULL` is not considered a value that can be matched on. This means there are no values in the column `foo.b`, and the execution pipeline early outs, passing all values up to the next operator. 

In the `IS NOT DISTINCT FROM`, `NULL` is considered a value, so the casting takes place so the comparison can take place. This is why you only see the error in the `IS NOT DISTINCT FROM` case. If you add actual numeric values to `foo.b` you will see the error in that case as well. 

Duckdb's stance is that optimizations can remove errors, since keeping parity will limit optimization opportunities and will produce little benefit. Going to close this now, but if something is still unclear feel free to reopen the issue
