### ISSUE TITLE
feature idea: sqlite table reader

### ISSUE THREAD

**Issue by ak2k** [duckdb/duckdb#892]
Hi Guys, Thank you so much for all the exciting improvements to DuckDb in the past few months! So many cool additions!

What would you think of the idea of having a sqlite reader to go alongside the parquet and csv readers?

**Comment by hannesmuehleisen** [comment]
Ha we actually have been thinking about this ^^

**Comment by Alex-Monahan** [comment]
I bet there is a way to support an Attach use case with this type of method. Two birds with one stone! 
If the reader can use an existing SQLite connection, then the attach could be done in SQLite ahead of time, or if multiple SQLite databases can be accessed as separate tables in the same DuckDB query, that would work too!

**Comment by dforsber** [comment]
- After spending some time getting to know SQLite3 a bit better in the hopes of being able to have a row store (SQLite3) alongside column store (DuckDB), it would probably make more sense to write async IO capable sqlite3 db reader instead of sticking with the sqlite3 engine which is serial in what comes to disk IO. However, when thinking solely about row stores, it would probably make sense to start with some fresh format that suits nicely today's highly concurrent and async IO favoring environments (e.g. being able to easily cache full "index"/hash table metadata and use efficiently e.g. KV store backends)

- That said, it would be awesome to be able to do full (sub)query push down on SQL level for a virtual table as that brings up the possibility to integrate seamlessly with anything. Only the data format (e.g. Arrow) needs to be standardised and streaming would be a must requirement ;). 

This would rock the world as today these things happen with Presto/Spark and cloud native/proprietary solutions. On the other hand, if I may say, DuckDB already beats Presto/Spark in some sense. For DuckDB one of the remaining challenges is a matter of horizontal scalability (distribution), i.e. being able to distribute query execution in controlled but very dynamic manner (FaaS). I would be happy to discuss this further offline if needed.

Being able to run both **column** and **row** stores has the promise of being able to issue less IO requests to the data side from the query engine and also being able to fetch bigger blobs of data that are also useful for the query. This is especially important in environments where you have network level latency but concurrency and bandwidth are almost limitless (proportional to distribution).

What would it take to have a database format that stores the data both in column and row formats? Almost, like two databases combined together and executed under the same query planner. Reading from it would benefit of having the luxury of reading data from both stores at the same time.

**Comment by hannesmuehleisen** [comment]
This is going to be available soon
