### ISSUE TITLE
runs `SELECT COUNT(*) FROM (SELECT DISTINCT * FROM t)` on v0.9.0 slower than on v0.8.1

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#9121]
### What happens?

I try to reproduce the https://duckdb.org/2023/09/26/announcing-duckdb-090.html example.
I made a larger table, it contains 150M rows.
the size of that table is 12.6GB in v0.8.1, 15.3GB in v0.9.0
the query tooks 119.694s in  v0.8.1, 228.866s  in v0.9.0

### To Reproduce

```sql
set threads=1;
PRAGMA temp_directory='d:/tmp';
```
```sql
create table t15x10M_2 as
select i::int32 i,(i*15+j)::int32 "0","0"+1 "1","1"+1 "2","2"+1 "3","3"+1 "4","4"+1 "5","5"+1 "6","6"+1 "7","7"+1 "8",
"8"+1 "9","9"+1 "10","10"+1 "11","11"+1 "12","12"+1 "13","13"+1 "14"
from range(10000000)t(i),range(15)s(j);
PRAGMA database_size;
SELECT COUNT(*) FROM (SELECT DISTINCT * FROM t15x10M_2);
```

### OS:

windows7 x64

### DuckDB Version:

0.9.0

### DuckDB Client:

CLI

### Full Name:

lutao

### Affiliation:

study

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment]
btw, if table contains 30M rows,
```
create table t15x30M_2 as
select i::int32 i,(i*15)::int32 "0","0"+1 "1","1"+1 "2","2"+1 "3","3"+1 "4","4"+1 "5","5"+1 "6","6"+1 "7","7"+1 "8",
"8"+1 "9","9"+1 "10","10"+1 "11","11"+1 "12","12"+1 "13","13"+1 "14"
from range(30000000)t(i);
```
both of the size are 3GB, and run query `SELECT COUNT(*) FROM (SELECT DISTINCT * FROM t15x30M_2)`on v0.9.0 is faster than v0.8.1 ( 15s vs 20s )

**Comment by lnkuiper** [comment]
What's happening here is that while the data set fits in memory, an out-of-core hash aggregate is triggered because the data size is close to not fitting in memory anymore (if you have 16GB RAM). This is not necessary here, but we perform an out-of-core hash aggregate out of precaution.

Usually, the performance does not suffer much when switching to the out-of-core strategy, as we use partitioning anyway in a multi-thread scenario. However, when using single-threaded aggregation, we don't use partitioning at all. Because you've limited the threads to 1, you've hit an edge case that we will not optimize for, which is single-threaded out-of-core aggregation.

I expect that if you try measuring the difference in the performance of v0.8.1 vs. v0.9.0 with 4+ threads that v0.9.0 will almost always be faster.

**Comment by l1t1** [comment]
[test-thread.txt](https://github.com/duckdb/duckdb/files/12744875/test-thread.txt)

for 30M rows, 0.9.0 always faster than 0.8.1
for 150M rows, 0.9.0 is slower at most conditions

  | thread=1 | 2 | 4 | 8
-- | -- | -- | -- | --
30M |   |   |   |  
0.8.1 | 20 | 22 | 19 | 15
0.9.0 | 14 | 12 | 5 | 4
  |   |   |   |  
150M |   |   |   |  
0.8.1 | 106 | 123 | 121 | 130
0.9.0 | 188 | 148 | 118 | 149

**Comment by l1t1** [comment]
my host: 32GB mem and 24 theads(E5 2620v3 x 2)

**Comment by szarnyasg** [comment]
@l1t1 this benchmark result is in line with our expectations.

You can see that the new version is a lot faster on the 30M data set. On the 150M data set, the new version is slightly faster on 4 threads and it is only 15% slower on the 8 threads, which is a minor performance regression.

It is important to point out that there are a lot of interrelated tradeoffs involved when implementing these operators. Hence, a new operator can be generally a lot faster and scalable for most practical cases (like DuckDB's new out-of-core hash aggregate), and at the same time it can be somewhat slower on certain cases (certain data sets, architectures, number of threads, etc.). Please consider this before opening any further issues reporting performance regression.
