### ISSUE TITLE
Timezone changes to local timezone without adjusting timestamp

### ISSUE THREAD

**Issue by legout** [duckdb/duckdb#9381]
### What happens?

When using duckdb on an arrow table/dataset, polars/pandas dataframe, the timezone of a timestamp is replaced by the local timezone without adjusting the timestamp.

### To Reproduce

```python
import polars as pl
import duckdb
import datetime as dt

con = duckdb.connect()
end_date = dt.datetime(2023,10,16,10)

# create an arrow table with a timestamp[us, tz=UTC] column
datetime = pl.datetime_range(end_date-dt.timedelta(hours=4), end_date, interval="1h", time_zone="UTC", eager=True).to_frame().to_arrow()

print(datetime)
```
```shell
pyarrow.Table
datetime: timestamp[us, tz=UTC]
----
datetime: [[2023-10-16 06:00:00.000000,2023-10-16 07:00:00.000000,2023-10-16 08:00:00.000000,2023-10-16 09:00:00.000000,2023-10-16 10:00:00.000000]]
```
```python
# creating a duckdb relation from the arrow table and get back a new arrow table
print(con.from_arrow(datetime).arrow())
```
```shell
pyarrow.Table
datetime: timestamp[us, tz=Europe/Berlin]
----
datetime: [[2023-10-16 06:00:00.000000,2023-10-16 07:00:00.000000,2023-10-16 08:00:00.000000,2023-10-16 09:00:00.000000,2023-10-16 10:00:00.000000]]
```

### OS:

arm64 and x86_64

### DuckDB Version:

0.9.1

### DuckDB Client:

Python

### Full Name:

Volker Lorrmann

### Affiliation:

Siemens

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment]
The problem here is that unlike Arrow, DuckDB does not store the time zone in the column, so there is no way to round trip the TZ. If you insert an Arrow timestamp with time zone, DuckDB treats it as a SQL `TIMESTAMP WITH TIME ZONE`, but this type uses the `TIMEZONE` session setting (which in your case is probably `Europe/Berlin`) instead of attaching the TZ to the data. The only way to solve this is to set the session timezone with `SET TIMEZONE='UTC'`.

There may be an issue here that we should not set the TZ (or set it to UTC) when returning the instants in the column, as that is the TZ that corresponds to instants.

**Comment by legout** [comment]
Ok. Makes sense. Thanks for clarification.

**Comment by nph** [comment]
@hawkfish - I do think there is an issue here since correctness of the result set for Arrow timezone-aware timestamps seems to rely on the Arrow data timezone(s) happening to match the DuckDB session timezone (if I've understood the issue correctly)... Would it make sense for DuckDB to convert Arrow timestamp data to UTC during the query execution and then always return the result set as UTC?

BTW, I noticed that in DuckDB 0.8.1 @legout 's example code happens to produce the correct output. Did the session timezone default to UTC prior to DuckDB 0.9?

**Comment by hawkfish** [comment]
> @hawkfish - I do think there is an issue here since correctness of the result set for Arrow timezone-aware timestamps seems to rely on the Arrow data timezone(s) happening to match the DuckDB session timezone (if I've understood the issue correctly)... Would it make sense for DuckDB to convert Arrow timestamp data to UTC during the query execution and then always return the result set as UTC?

I think this is what we used to do and someone found this confusing. But given that Arrow seems to change the instant based on the TZ setting, we should probably revert it.

**Comment by nph** [comment]
Thanks - good to know.

**Comment by hawkfish** [comment]
Looping in @Tishj who IIRC made the change.

**Comment by hawkfish** [comment]
If I print out the table itself

```py
print(con.from_arrow(date time))
```

I get:
```
┌──────────────────────────┐
│         datetime         │
│ timestamp with time zone │
├──────────────────────────┤
│ 2023-10-16 08:00:00+02   │
│ 2023-10-16 09:00:00+02   │
│ 2023-10-16 10:00:00+02   │
│ 2023-10-16 11:00:00+02   │
│ 2023-10-16 12:00:00+02   │
└──────────────────────────┘
```

which is correct (those are the same instants in the original DF).

**Comment by hawkfish** [comment]
This is a display issue in Arrow or somewhere. If you print out individual values, then you get what you expect:

```py
print(field(0))
# pyarrow.Field<datetime: timestamp[us, tz=Europe/Berlin]>

print(datetime.column(0)[0])
# 2023-10-16 08:00:00+02:00
```

I suspect that when the entire array is printed, the TZ information is just not used because Arrow keeps the TZ as column metadata and so you just get the instants printed in GMT. But if you ask Arrow column for an individual value, it uses the TZ to format the instant.

**Comment by nph** [comment]
@hawkfish Thanks a lot for looking into this, I'll open an issue on the Arrow side.

**Comment by nph** [comment]
https://github.com/apache/arrow/issues/38629
