### ISSUE TITLE
Installing extension from custom repository that uses HTTPS fails

### ISSUE THREAD

**Issue by janjagusch** [duckdb/duckdb#9835]
### What happens?

DuckDB fails to install extensions from a custom extension repository that uses HTTPS. That's because it wrongly assumes any `url_template` that does not contain 'http://' is a local file path (ours starts with 'https://'). You get the `Failed to copy local extension` error in return.

https://github.com/duckdb/duckdb/blob/ce866cec9d80b6e8b91d890c90476a0c01322f11/src/main/extension/extension_install.cpp#L247-L256

Suggested solutions:
- Change the conditional to `if (!StringUtil::Contains(url_template, "http"))`.
- Introduce a `file://` protocol to explicitly declare an URI as local (would be breaking).

### To Reproduce

- Copy an extension, .e.g `json`,  onto a blob store that can be reached over HTTPS, e.g. `https://my-blob-store.example/duckdb_extensions`.
- Run `SET custom_extension_repository='https://my-blob-store.example/duckdb_extensions';` followed by `INSTALL json;`.
- You will get the `Failed to copy local extension` error.

### OS:

Linux

### DuckDB Version:

0.9.2

### DuckDB Client:

CLI

### Full Name:

Jan-Benedikt Jagusch

### Affiliation:

QuantCo

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment]
Install / load over HTTPS protocol is not properly supported in `v0.9.2`, and this is expected.

I have a PR up, https://github.com/duckdb/duckdb/pull/9818, to make so that allowing custom extension repositories via HTTPS protocol using the `httpfs` extension.

In the current iteration there is a requirement in place that httpfs extension has to be present on the system for this to be possible (either already loaded or it should be possible to INSTALL it ), and that extension is for now special cased (and we expect it to be loaded over http from the official extension repository or be made available to users and INSTALLed via `INSTALL https.duckdb_extension` once fetched with other means).

If you want to experiment with it, you can build from source, feedback is welcome.

**Comment by carlopi** [comment]
Actually, this is now solved properly, both:
```
SET custom_extension_repository='https://extensions.duckdb.org';
FORCE INSTALL spatial;
```
and
```
FORCE INSTALL spatial FROM 'https://extensions.duckdb.org';
```
work since 1.0.0.

Only caveat: you need to have HTTPFS installed on your machine, possibly through other means (= download with curl / python / browser / etc). HTTPFS will be then loaded automatically and allow fetching over `https://` (or even `s3://`).
