### ISSUE TITLE
COPY statement generating a S3 multipart upload error

### ISSUE THREAD

**Issue by tobilg** [duckdb/duckdb#9894]
### What happens?

When attempting to write Hive partitioned Parquet files to S3, I receive the follwoing error:

`Unexpected response while initializing S3 multipart upload`

This seems to be thrown here in the code: https://github.com/duckdb/duckdb/blob/main/extension/httpfs/s3fs.cpp#L299 I'm positive this isn't an IAM permissions issue, because I see data written to S3...

The IAM permissions I'm using are the same as https://github.com/tobilg/serverless-duckdb/blob/main/serverless.yml#L65-L88

### To Reproduce

Run a COPY table statement that writes Hive partitioned Parquet to S3.

### OS:

Amazon Linux 2

### DuckDB Version:

0.9.2

### DuckDB Client:

Node

### Full Name:

Tobi M.

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by OhmniD** [comment]
@tobilg I had this issue too, in my case it turned out it was permissions. The Lambda worked fine from my local machine with my user's creds, but as soon as I actually put it into AWS I got this error. 

What happened was the bucket I was writing to was encrypted with a customer managed KMS key, I'd added encrypt/decrypt permissions for `lambda.amazonaws.com` to the key's policy but it looks like I need to add it explicitly to the Lambda's execution role policy too. I'm still trying to narrow down what the exact permissions I need are, but adding `kms:*` allowed me to at least see the Lambda working and confirm the issue.

It might be worth relaxing the permissions on your execution role temporarily and having a poke about in CloudTrail to see if you've got something similar going on.
