### ISSUE TITLE
CSV Reader Casting exceptions

### ISSUE THREAD

**Issue by pdet** [duckdb/duckdb#998]
Should the auto-detect from the  csv reader throw casting exceptions?

**Comment by hannesmuehleisen** [comment]
Not clear to me what you mean. Is it throwing exceptions or is it not and you would like that?

**Comment by pdet** [comment]
Sorry, I should have been more clear.
Currently, it throws exceptions, I guess because it discovers data types by trying to cast the data. Since this is a discovery process and not a fundamental assumption about the data, I think it shouldn't throw exceptions.
(Also makes debugging exception breakpoints more annoying)

**Comment by hannesmuehleisen** [comment]
well an alternative would be to have a non-exception-throwing cast but if its just to improve debugging experience i am not if that is worth it. could be worse, could be python which always triggers some signal at startup ^^

**Comment by Mytherin** [comment]
In general I think avoiding exceptions for control flow is a good thing, they are very slow and I would prefer not to get into the Java situation of wrapping everything in try/catch, so removing the exceptions is a +1 from me. Exceptions should be reserved for exceptional situations after all :)

I think I already talked to Till about this before, but because the casting functions did not have a TryCast alternative when he made them he opted to use the throwing variant. We now have a non-throwing variant of the casts, so we could use those and remove the try/catch in the CSV reader.

**Comment by tdoehmen** [comment]
Yes, so there is one TryCastValue and TryCastVector function in the CSV reader within which Exceptions from the Casts are catched. However, the CSV Reader itself should always catch those. If it's not the case, this should be fixed, I think. 

Mark is right, we talked about it and I once started to adapt the builtin TryCast functions but there was some reason which made me switch back to the custom helper functions. I think there was no TryCast for Vectors, yet, and I wasn't sure how relevant this functionality would be for other, so I kept it local. In the course of the new date-type sniffing feature these local TryCastVector/Value functions also got extended with some more custom logic. Using the global TryCast would be cleaner but it would eventually just move the catch to a different place. The most elegant would be if the Casts themselves had a mode in which they don't raise Exceptions, but in order to prevent all Exceptions from being thrown, the logic of the Casts would have to be significantly adapted. Many casts rely on low level C++ libraries to perform parts of the conversion, which inevetably throw an exception when called with bad input.

**Comment by Mytherin** [comment]
> Yes, so there is one TryCastValue and TryCastVector function in the CSV reader within which Exceptions from the Casts are catched. However, the CSV Reader itself should always catch those. If it's not the case, this should be fixed, I think.

They are always caught, I think the problem here is that it's common to have e.g. "break on all exceptions" turned on in a debugger, which gets disrupted when using exceptions as control flow. The user normally never sees these exceptions.

> Mark is right, we talked about it and I once started to adapt the builtin TryCast functions but there was some reason which made me switch back to the custom helper functions. I think there was no TryCast for Vectors, yet, and I wasn't sure how relevant this functionality would be for other, so I kept it local. In the course of the new date-type sniffing feature these local TryCastVector/Value functions also got extended with some more custom logic. Using the global TryCast would be cleaner but it would eventually just move the catch to a different place. The most elegant would be if the Casts themselves had a mode in which they don't raise Exceptions, but in order to prevent all Exceptions from being thrown, the logic of the Casts would have to be significantly adapted. Many casts rely on low level C++ libraries to perform parts of the conversion, which inevetably throw an exception when called with bad input.

Indeed this redesign has to come from the low level casts upwards. I think this is not a huge problem though, as all our string casting functions (as far as I know) are custom-made, which means they can be easily adopted to not directly throw exceptions. It will just cost a bit of engineering effort. I can have a look at doing this :)

**Comment by Mytherin** [comment]
Going to have a go at this now.
